### ISSUE TITLE
REST API test shouldn't use hard coded ports

### ISSUE THREAD

**Issue by skrishnappa** [pravega/pravega#1014]
**Problem description**
We use the JerseyTest framework with the default port for running the REST server. We need to use a free port so that we can run unit tests in parallel.

**Problem location**
StreamMetaDataTests

**Suggestions for an improvement**
Use random ports

**Comment by fpj** [comment]
This is issue originally targeted `StreamMetaDataTests`, which I'm seeing does not have hardcoded ports any longer. Other test files reported by @tkaitchuck still do, though. `EndToEndTransactionOrderTest` is one of them. I'll close issue and check for other issues on hardcoded ports.
