### ISSUE TITLE
Prune dependency tree.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1035]
**Problem description**
Looking at our build.gradle, we have WAY too many dependencies. Virtually every target is pulling in way to large of a tree, but some of the worst offenders have become things like common which should not depend on anything, is now pulling in a whopping 396 dependencies!

**Problem location**
build.guava

**Suggestions for an improvement**
We can see the number of dependencies by running:
`./gradlew common:allDeps`
(or omit common to see it for all targets)
Perhaps We could add a test that output gets larger?

However in any event we need to go through the tree, and aggressively refactor things so as not to take on or impose this sort of dependency load on our customers.

**Comment by tkaitchuck** [comment]
Specifically this, is important for the client, as any dependency there affect the application linked to it. We should prioritize it.

**Comment by EronWright** [comment]
Can we nail down which dependencies will be shed on the client side?   I think that we should relocate any dependencies that remain after this exercise.

**Comment by fpj** [comment]
@tkaitchuck A run of:

```
./gradlew client:allDeps | grep '\-\-\-' | grep -v '(*)' | wc -l
```
Gives me: `376`. Is there any opportunity to reduce this further?

**Comment by andreipaduroiu** [comment]
I think removing Netty completely from the client will reduce it a lot. We may not use Netty for communication, but we still use it for ByteBufs (and maybe one or two other things).
