### ISSUE TITLE
Single node should support different independent variations for Tier1 and tier2 (in mem, in proc and external)

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1066]
**Problem description**
A single node implementation should allow independent variations for Tier1 and tier2 (in mem, in proc and external). Right now both tier1 and tier2 in mem/in proc implementations depend on the same flag.

**Problem location**
Single node implementation.

**Suggestions for an improvement**
This issue disables access to local in proc HDFS as in proc DL is not possible because of DL-192.

**Comment by tkaitchuck** [comment]
Closing in favor of #1290
