### ISSUE TITLE
Fast failover for reads

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#107]
Allow reads from a follower before recovery has completed. 

We could implement support for this with some changes and a bit of added memory overhead as follows:
In the readIndex we currently map the Segment and Offset to the data the data at that position in the segment.
We could replace that with two maps. One that mapps the Segment and Offset to the WriteEntry and Offset within the entry.
And a second that contains the WriteEntries.
The host that owns the container would need to keep both maps in memory (or RocksDB). 

To enable fast failover the host that would take over in the event of the death of the current owner could pro-actively maintain just the first map. Then when the first host fails, the consumers can issue their read request to the new owner. (Who may still be in the process of replay, and may not have the data yet to serve their read request.)
As there is no requirement that replay must take place in-order (Though there is a performance benefit.) so it is possible to read those leger entries that contain data that readers are asking for.

**Comment by andreipaduroiu** [comment]
This is included in #2314
