### ISSUE TITLE
Fast failover for writes

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#108]
Have a mechanism whereby appends can occur while recovery is still in progress. 

A Pravega node can begin accepting appends as soon as it can verify three things:
1. It is the owner of the relevant container.
2. The Segment exists
3. The segment has not been sealed.

The first two can be done very quickly, the third could be supplied by the controller without having to reconstruct the full state in the store. 

If we were to do this it would complicate the ReadIndex somewhat, as the data would be written before its offset is known.

**Comment by andreipaduroiu** [comment]
This is included in #2314
