### ISSUE TITLE
Spark Connector

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#111]
Implement a Spark connector using our producer and consumer APIs.

**Comment by claudiofahey** [comment]
See https://github.com/pravega/spark-connectors/pull/1.

**Comment by RaulGracia** [comment]
The initial version of the connector is at https://github.com/pravega/spark-connectors. For any further issues, we can work on that repository.

**Comment by cdmikechen** [comment]
@RaulGracia  Can not find this page. Has the project been cancelled?

**Comment by kant777** [comment]
Cannot find the page?

**Comment by fpj** [comment]
hi @kant777 , that's because it is a private repo. let me check whether we can make the current implementation available.
