### ISSUE TITLE
Auto Scaling feature is not observed on DC/OS

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#1111]
**Problem description**
When Pravega is deployed on DC/OS from universe, the auto scaling is not observed even though all scaling criteria is met for a stream. 

_This issue is already being debugged and this is for tracking purpose_

**Problem location**
Initial due diligence unveils that "Internal writer" is not created. The writer is supposed to send scaling requests to internal stream for controller to trigger scale action when scaling criteria is met. 

**Suggestions for an improvement**
Debug the root cause of internal write creator issue
Make sure that scaling happens in deployment environments

**Comment by shiveshr** [comment]
it has been observed and we have noticed the scale operation in the logs
