### ISSUE TITLE
Revisit Store exceptions

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1116]
**Problem description**
StoreExceptions have a type. Which makes type specific handling ugly whenever exception is thrown. 
Moving to a base class as StoreException and derived classes as Specific-StoreException will make handling the exception cleaner.

try {} catch(StoreException e) { if (e.type == X) do something else log and throw}
v/s
try {} catch (SpecificStoreException) {do something} catch(storeException){log and throw}

**Problem location**
StoreException and CheckpointStoreException and possibly other store exceptions 

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
In https://github.com/pravega/pravega/pull/1849/ we noticed that DataCorruptedException should really be a runtime. This is probably not the only case of this. We should review these and check if they should be runtime or not. Additionally if we do change an exception to runitem we should look where it is used and see if we can remove any uses of sneakyThrows like 1849 did.
