### ISSUE TITLE
Gradle task for Docs

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#1127]
**Problem description**
We have documents under docs/ folder in code repository on GitHub. However, I need to manually build them using mkdocs to generate html versions and upload to http://pravega,io/docs every time there is a change on source docs. 

**Problem location**
documentation

**Suggestions for an improvement**
We need to automate this task by adding gradle task that builds docs and uploads to https://pravega.io/docs **on demand**

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add gradle tasks to generate and upload docs in html format](https://trello.com/c/WV3cKT2i/21-add-gradle-tasks-to-generate-and-upload-docs-in-html-format)
