### ISSUE TITLE
Emit Events/Second stats for streams

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#1140]
**Problem description**
Pravega currently doesn't emit any stats on events per second.  This would be a useful stat for the UI team to render graphs for, especially when a dynamic stream has been setup with events/sec as the scaling trigger.

**Problem location**
Performance stats

**Suggestions for an improvement**
Add events/sec for stream stats

**Comment by jkhalack** [comment]
Pravega does report `segment_write_events` counter metrics now.
Events/second can be derived from the above counter.

**Comment by RaulGracia** [comment]
As @jkhalack said, this kind of metrics are already being reported.
