### ISSUE TITLE
Implement a shaded in-proc Pravega cluster

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#1142]
**Problem Description**
The work of #573 provides an in-process Pravega cluster (`LocalPravegaEmulator`) for use in client-side integration tests.   Dependency conflicts are likely to happen in such an environment, for example when writing Flink connector tests that use Flink's in-process cluster.

A solution to the conflict is to build a shaded JAR of the Pravega emulator that isolates most of Pravega's dependencies.   Ideally the library would leave only `io.pravega.*` unshaded.

**Suggested Fix**
I suggest the overall dependency tree be (as seen from the app perspective, with shaded deps elided):

```
flink-job
├─ flink-streaming-java (provided)
├─ pravega-connector (compile)
│  └─ pravega-client (compile)
└─ pravega-standalone (intTest)
   └─ pravega-client (compile)
```

To achieve the above, most of the shading work that is presently done in the connector should move to the client library.

**Comment by EronWright** [comment]
Some exposition on the rationale for my suggestion of moving shading (of Netty, etc) to the client library.

> When we apply shading to a library, our goal is to prevent a conflict with the application that uses the library by hiding its dependencies.  I’ll use Netty as an example of a dependency that we wish to hide.
> Hiding Netty has two aspects:  1. relocating the Netty classes in `io.pravega.shaded.netty`. 2. removing Netty as a listed dependency in the library’s POM.
> If we did (1) but not (2), shading would be ineffective because the application would still see Netty as a transitive dependency.
> Now consider the pravega connector.   Today it relocates all the dependencies _and removes the client library from its effective POM_.  If the client were still listed as a dependency of the connector, the app would again see Netty and other client dependencies (which we want to avoid)
> The ideal design would allow the connector to list the client as a dependency in the effective POM.  Likewise the standalone lib should list the client as a dependency.   To achieve this, _the client itself should take responsibility for shading its dependencies_.   No further shading would then be needed in the connector.

**Comment by EronWright** [comment]
Just to put the conflict in perspective, a process (e.g. integration test) that combines hadoop with the pravega client would face a crazy classpath:
```
hadoop (2.8.1):

|    |    \--- org.apache.curator:curator-framework:2.7.1
|    |         +--- org.apache.curator:curator-client:2.7.1
|    |         |    +--- org.slf4j:slf4j-api:1.7.6 -> 1.7.16
|    |         |    +--- org.apache.zookeeper:zookeeper:3.4.6 (*)
|    |         |    \--- com.google.guava:guava:16.0.1
|    |         +--- org.apache.zookeeper:zookeeper:3.4.6 (*)
|    |         \--- com.google.guava:guava:16.0.1


pravega-shared (master):
     |    \--- org.apache.curator:curator-recipes:4.0.0
     |         \--- org.apache.curator:curator-framework:4.0.0
     |              \--- org.apache.curator:curator-client:4.0.0
     |                   +--- org.apache.zookeeper:zookeeper:3.5.3-beta
     |                   |    +--- commons-cli:commons-cli:1.2
     |                   |    \--- io.netty:netty:3.10.5.Final
     |                   \--- com.google.guava:guava:20.0
     
```

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Shaded in-proc pravega cluster](https://trello.com/c/L41QWmHt/36-shaded-in-proc-pravega-cluster)

**Comment by andreipaduroiu** [comment]
I closed it inactivity for more than 1 year and no assignees that are actively working on the project.
