### ISSUE TITLE
Clean up metadata of completed transactions from stream metadata store in controller

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1164]
**Problem description**
Currently, metadata information about completed transactions is preserved permanently. This leads to accumulation of status information of completed transactions (aborted or committed). However, we need not store status information of completed transactions older than, say 1 hour. We need to periodically clean up status information about stale completed transactions from metadata store in controller.

**Problem location**
Controller transaction metadata store.

**Suggestions for an improvement**
We could employ one of the following mechanisms to clean up old completed transaction metadata.
1. Either use ZK nodes with fixed TTL to automatically clean up completed transaction metadata https://issues.apache.org/jira/browse/ZOOKEEPER-2169, or
2. Periodically scan list of completed transactions and delete stale entries.

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1164: Clean up metadata of completed transactions](https://trello.com/c/9IMpoeYT/37-1164-clean-up-metadata-of-completed-transactions)
