### ISSUE TITLE
Cross package code coverage.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1197]
**Problem description**
The code coverage tool works independently on each package running coverage using the tests in that package and measuring the code covered in that package. So any cross package coverage is lost. 

**Problem location**
Gradle.

**Suggestions for an improvement**
We can create a gradle target to perfrom a "JacocoMerge" across our packages to produce a unified report.

**Comment by tkaitchuck** [comment]
Perhaps we can do it like this:
https://discuss.gradle.org/t/merge-jacoco-coverage-reports-for-multiproject-setups/12100

**Comment by fpj** [comment]
@derekm Is there anything we can do about code coverage across packages?

**Comment by andreipaduroiu** [comment]
The question is: do we want it to work that way? We shouldn't rely on tests from a different package to "unit test" our components. All unit tests for a class should reside within that package.

If we change this behavior, the integration test package will likely cover the majority of our codebase, so developers will not be incentivized to write proper unit tests for their new/updated code. 

I know this was a "wish" a few years ago, but now, after working on this codebase, I do not want such a "feature" to be enabled.

**Comment by derekm** [comment]
@fpj @andreipaduroiu -- What if we could report integration test coverage separately? Codecov merges our separate unit test results, and that's what some of these "merge across packages/projects" docs read to be like.

If there's an issue/feature here, maybe it is being able to view the integration test coverage separate from and not merged with unit test coverage. I could see value in being able to view integration test coverage, as well as separating it from unit test coverage.

**Comment by andreipaduroiu** [comment]
@derekm If we could do that, it would be great. We can have a separate coverage report from integration tests, and make that optional - as long as we still gate the merge on the per-project unit test coverage.
