### ISSUE TITLE
Allow hyphens and periods in stream and group names.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1219]
**Problem description**
These do not need to be reserved symbols and are very useful for application developers.

**Problem location**
NameUtils, Examples, and Documentation

**Suggestions for an improvement**
Add the characters to the approved list and update the docs/examples.

**Comment by fpj** [comment]
We have allowed period and hyphen here: #1756 . Is it enough? One of the comments also refers to a slash.
