### ISSUE TITLE
Lock-free transaction management

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1222]
**Problem description**
Current transaction creation, ping, commit and abort operations are modeled as task framework tasks. These tasks acquire lock on the stream/transaction resource. However, we need not acquire lock for correctly executing these operations. Hence we need to move these operations out of task framework.

**Problem location**
Controller transaction tasks.

**Suggestions for an improvement**
Move transaction management operations out of task framework and execute them in the caller's context.

**Comment by fpj** [comment]
@bhargav-gulavani @shiveshr I don't like the API change that adds a `switchOver` boolean to the ping call. It is not intuitive and isn't very clear how it is supposed to be used. Can we find a way around it and not have this API change?
