### ISSUE TITLE
Classpath too long for windows using standalone script

### ISSUE THREAD

**Issue by chrisdail** [pravega/pravega#1239]
**Problem description**

The startup script for `standalone`, `controller`, and `segmentstore` have too many jars on the classpath. On windows this fails to start. This happens even in a very short directory.

```
C:\p\bin>pravega-standalone.bat
The input line is too long.
The syntax of the command is incorrect.
```

**Problem location**

The issue is with the application plugin for gradle that is used to generate the startup scripts. This is the same as https://issues.gradle.org/browse/GRADLE-2992.

**Suggestions for an improvement**

Couple of options to fix this:

- Look at the suggestions/workarounds on the gradle issue
- Switch to using the Java 6+ *.jar instead of naming individual jar files

**Comment by jasoncwik** [comment]
Confirmed that changing line 66 of `pravega-standalone.bat` to ```set CLASSPATH=%APP_HOME%\lib\*
``` works.  Note that it's *not* `lib\*.jar` but just `lib\*`

**Comment by chrisdail** [comment]
PR merged with the fix for this issue.

**Comment by jasoncwik** [comment]
Tested in master.  Looks good.
