### ISSUE TITLE
AutoScaleProcessor causes the Segment Store to depend on the Pravaga client

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1282]
**Problem description**
AutoScaleProcessor needs to write data related to rates that can be read by an external process. This is currently done by taking a dependency on the Pravega client and contracting the controller and other Pravega hosts and writing the data there. This creates a dependency cycle and introduces a cross instance communication/dependency. 

**Problem location**
[AutoScaleProcessor](https://github.com/pravega/pravega/blob/master/service/server/host/src/main/java/io/pravega/service/server/host/stat/AutoScaleProcessor.java#L124)

**Suggestions for an improvement**
Use a local segment rather than making RPCs. (IE: just call `StreamSegmentStore.append()`)
Alternately the data could be stored separately, is the Metadata log for example and an different API could be used to access it. (Though this is probably more complicated)

**Comment by shiveshr** [comment]
Duplicate of #610
