### ISSUE TITLE
SegmentStore: pluggable Cache, Tier1 and Tier2

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1290]
Cache, Tier1 and Tier2 are already defined by contracts (in `segmentstore:storage`), and have a proper implementation (in `segmentstore:storage:impl`).

We should allow a user to supply their own implementation of these components by:
1. Taking a dependency on `segmentstore:storage` and `segmentstore:contracts`
2. Implementing their adapter
3. Changing `config.props` to point the ServiceBuilder to load those implementations.
3.1 By default, this should just load the ones in `segmentstore:storage:impl`

**Comment by arvindkandhare** [comment]
We discussed this offline and here are the conclusions and work items:
1. Tier1 and cache need not be pluggable: right now we have only one implementation of each. There is no plan to extend it currently.
2. Tier2 implementations will be dynamically loaded using reflection. In memory implementation as well as HDFS will be bundled with the default binary tar package.
3. A new tar package will be created which will contain current implementation of custom bindings. 

(2) and (3) will ensure that we separate the default bindings and custom bindings. It will also ensure that  the custom bindings are already present in the docker container.

**Comment by EronWright** [comment]
One (obvious) suggestion as to how to reflectively load the tier2 implementation would be to use `ServiceLoader` ([ref](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html)).  An alternate implementation could then be discovered with a provider config file in its JAR.

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revisit the substitution of jsr311-api with javax.ws.rs-api](https://trello.com/c/jSYw92Cc/1-revisit-the-substitution-of-jsr311-api-with-javaxwsrs-api)

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revisit the substitution of jsr311-api with javax.ws.rs-api](https://trello.com/c/jSYw92Cc/1-revisit-the-substitution-of-jsr311-api-with-javaxwsrs-api)
