### ISSUE TITLE
Gauge type of metrics reports incorrect values

### ISSUE THREAD

**Issue by Abhijeet-Jadhav** [pravega/pravega#1298]
**Problem description**
The open transaction gauge metric doesn't decrease when the transaction is committed.

**Problem location**
Metrics framework.

**Suggestions for an improvement**
Report correct values for gauge metrics.

**Comment by fpj** [comment]
Is it the case that it never drops or is it the same problem as in #896 that we aren't updating it due to the absence of new requests?

**Comment by Abhijeet-Jadhav** [comment]
Its a different case, we aren't updating the guava cache when the guage value is updated. We are just inserting new values. In this case, the call on the line: https://github.com/pravega/pravega/blob/c1fab58882f279e1475a84b2c1e3df7e0e6b1172/controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java#L405 should decrease the open transaction count but since it is not a new gauge value it is not updated because of: https://github.com/pravega/pravega/blob/d378b26e24383ee86cc5131a03d90bcb16b98587/shared/metrics/src/main/java/io/pravega/shared/metrics/DynamicLoggerImpl.java#L120

**Comment by bayarsaikhan** [comment]
Has it been resolved?
