### ISSUE TITLE
Remove rat from `gradle check`

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1317]
**Problem description**
Apache rat is very slow, and is slowing down our build checks by adding another step. We should be able to configure checkstyle to do the header check: http://checkstyle.sourceforge.net/config_header.html
This way we can implement #1288 as part of the nightly build instead of on every CL.

**Problem location**
Gradle check

**Suggestions for an improvement**
Checkstyle can do the verification for our java files. Once we add that we can remove rat from `gradle check`

**Comment by tkaitchuck** [comment]
Checkstyle check already exits.

**Comment by fpj** [comment]
We have added checkstyle header check, but we still have rat as part of check. At least that's what I see when I run:

```
./gradlew check --dry-run
```

I'll close this issue for now, and please reopen if we the rat task being part of check is still a problem.
