### ISSUE TITLE
Include Controller REST API as part of Standalone

### ISSUE THREAD

**Issue by chrisdail** [pravega/pravega#1322]
**Problem description**

Standalone is a convenient way to get started with pravega. For simple non-production tests it is useful. Currently, this mode does not start the controller REST API. This means it is not possible to do basic REST API operations using standalone.

**Problem location**

Standalone startup

**Suggestions for an improvement**

Start the controller REST API as part of standalone.

**Comment by skrishnappa** [comment]
Duplicate of #832
