### ISSUE TITLE
Testing with fault injection

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1328]
**Problem description**
As part of our testing, we should have a way to inject faults so that we can confirm that our correctness guarantees are preserved in the presence of faults. There are a couple of options I can think of:

- Implement it as part of our framework for system tests
- Use some known tools, like Jepsen, Chaos Monkey and variants

**Problem location**
Testing, discussed in issue #1320. 

**Suggestions for an improvement**
Run tests with fault injection on a regular basis.

**Comment by andreipaduroiu** [comment]
Issue #338 is similar to this one, but for the SegmentStore. I'd be happy if we could develop a common solution so we don't have to duplicate efforts.

**Comment by dumblob** [comment]
Where could I find the results of these (hopefully regularly CI-run) Jepsen tests?

I am very much interested in the results.

Thanks!
