### ISSUE TITLE
SegmentStore Tier1 Async Writes

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1330]
**Problem**
Writes to Tier1 (BookKeeper) are synchronous, which limits our ability to make most use of BK's available throughput.

**Suggestions for improvement**
Allow async writes to BookKeeper, throttled up to a value.

**BookKeeperLog**
- External API stays the same. No need to change the `DurableDataLog` contract. Perhaps a few wording changes in the JavaDoc to explain concurrent behavior.
- No write throttling in here.
- Retries/error handling
    - Remove current retry logic. If used in async mode, it is responsible for writing out-of-order - and mostly useless.
- On write failure
    - Based on empirical research (not documented anywhere I see), a write failure causes a ledger to be closed, which causes all subsequent writes to that ledger to fail with LedgerClosedException.
    - When a write fails:
        - If fatal (Fencing exception), bail out; do not do anything, and report error on all pending writes
        - If non-fatal (Not enough bookies, not reachable): retry all writes in order.
        - If LedgerClosed: create a new ledger (be wary of fencing) and do the same as for non-fatal above.
        - Care must be taken when doing retries to verify that subsequent writes haven't actually completed (after a failed write) - however as explained above, this should not happen.
- Ledger Rollover Handling
    - Normal rollover: a new ledger is created and pointer atomically swapped with old ledger, then closed.
    - Failed write: there is no new ledger. This will need to be handled above (in retries)

**DurableLogConfig** (or wherever appropriate)
- Add setting: maxConcurrentDataLogWrites (=2/3/4/8/...)
    - If this is set to 1, it will essentially behave as it is today, writing synchronously.
   - This value will likely need to be tweaked based on deployment scenario and actual performance.

**OperationProcessor**
- Allow concurrent Tier1 writes. 
    - State/OperationMetadataUpdater: careful to commit only the stuff that has been written to Tier1, not everything
    - This may require chaining States/Updates together, and we'll need to ack/commit them as acks are coming in from Tier1
- Introduce a new component between the `OperationProcessor` and `DurableDataLog` (named `DataFrameProcessor`?)
    - This accepts sealed DataFrames, and processes them in order, by shipping them to Tier1(DurableDataLog).
    - It keeps a "counter" of how many active/concurrent such requests we have at any given time.
    - If this counter is below N (N=throttle limit), any new requests will go directly to Tier1
    - If this counter is at or above N, any new requests will be put in a queue. This queue will be processed, in order, as requests to Tier1 complete and free up capacity.
    - This reduces the overhead of queuing/dequeuing for most requests (since when we are below N, we go directly to Tier1) so it should not add any extra latency for most of these calls.

**Comment by andreipaduroiu** [comment]
**Pipelined Writes**
Idea: allow async writes with a max cap
BookKeeperConfig
- Add setting: maxConcurrentWrite (=2/3/4)

BookKeeperLog
- Write Throttling. Use eiher a Semaphore or some sort of BlockingQueue based off ArrayDeque.
    - Blocking Queue must allow processing the elements in order to enable parallel writes, but not dequeue them until actually processed.
    - append() must block synchronously when throttle reached its limit and release when space is available.
- Retries/error handling
    - Remove current retry logic. It is responsible for writing out-of-order - and mostly useless.
- On write failure
    - Based on empirical research (not documented anywhere I see), a write failure causes a ledger to be closed, which causes all subsequent writes to that ledger to fail with LedgerClosedException.
    - When a write fails:
        - If fatal (Fencing exception), bail out; do not do anything, and report error on all pending writes
        - If non-fatal (Not enough bookies, not reachable): retry all writes in order.
        - If LedgerClosed: create a new ledger (be wary of fencing) and do the same as for non-fatal above.
- Ledger Rollover Handling
    - Normal rollover: a new ledger is created and pointer atomically swapped with old ledger, then closed.
    - Failed write: there is no new ledger. This will need to be handled above (in retries)

OperationProcessor
- Allow concurrent Tier1 writes. Take advantage of the synchronous blocking in the `append` method in BookKeeperLog.
    - State/OperationMetadataUpdater: careful to commit only the stuff that has been written to Tier1, not everything
    - This may require chaining States/Updates together, and we'll need to ack/commit them as acks are coming in from Tier1

**Comment by tkaitchuck** [comment]
Sounds good.

**Comment by andreipaduroiu** [comment]
Perf measurements:
```
BASELINE: 2M appends, InMemory Tier1 with 0 latency.
0:00:21.508 [Reporter]: Ops = 2000001/2000000; Data (P/T/C/S): 190.7/190.7/190.7/190.7 MB; TPools (Q/T/S): Store = 5/0/20, Test = 1/1/50, ForkJoin = 0/0/1.
0:00:21.508 [Reporter]: Operation Summary
0:00:21.508 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:21.554 [Reporter]:             Append | 2000000 |     0 |     0 |     1 |     2 |     8
0:00:21.555 [Reporter]:               Seal |       1 |     5 |     5 |     5 |     5 |     5
0:00:21.585 [Reporter]:         End to End | 2000000 |     0 |     1 |     1 |     4 |    14
0:00:21.586 [Reporter]:       Catchup Read |   55483 |     0 |     0 |     0 |     0 |     1

OrderedItemProcessor(MaxCap=1, Synchronous): 2M appends of 100 bytes, InMemory Tier1 with 0 latency.
0:00:21.274 [Reporter]: Ops = 2000001/2000000; Data (P/T/C/S): 190.7/190.7/190.7/190.7 MB; TPools (Q/T/S): Store = 5/0/20, Test = 1/1/50, ForkJoin = 0/0/1.
0:00:21.274 [Reporter]: Operation Summary
0:00:21.274 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:21.315 [Reporter]:             Append | 2000000 |     0 |     0 |     1 |     2 |    10
0:00:21.315 [Reporter]:               Seal |       1 |     5 |     5 |     5 |     5 |     5
0:00:21.344 [Reporter]:         End to End | 2000000 |     0 |     1 |     1 |     3 |    18
0:00:21.345 [Reporter]:       Catchup Read |   55252 |     0 |     0 |     0 |     0 |     1


OrderedItemProcessor(MaxCap=1, Synchronous): 50K appends of 100 bytes, InMemory Tier1 with 100ms latency.
0:00:55.184 [Reporter]: Ops = 50001/50000; Data (P/T/C/S): 4.8/4.8/4.8/4.8 MB; TPools (Q/T/S): Store = 5/1/20, Test = 1/1/50, ForkJoin = 0/0/0.
0:00:55.184 [Reporter]: Operation Summary
0:00:55.184 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:55.194 [Reporter]:             Append |   50000 |   107 |   106 |   108 |   200 |   250
0:00:55.194 [Reporter]:               Seal |       1 |   107 |   107 |   107 |   107 |   107
0:00:55.197 [Reporter]:         End to End |   50000 |   110 |   109 |   113 |   205 |   275
0:00:55.197 [Reporter]:       Catchup Read |    1012 |     0 |     0 |     0 |     4 |     9


OrderedItemProcessor(MaxCap=1, Synchronous): 5K appends of 100KB, InMemory Tier1 with 100ms latency.
0:00:51.012 [Reporter]: Ops = 5001/5000; Data (P/T/C/S): 476.8/476.8/476.8/476.8 MB; TPools (Q/T/S): Store = 5/0/20, Test = 1/1/50, ForkJoin = 0/0/0.
0:00:51.012 [Reporter]: Operation Summary
0:00:51.012 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:51.019 [Reporter]:             Append |    5000 |   984 |  1024 |  1037 |  1063 |  1200
0:00:51.019 [Reporter]:               Seal |       1 |   932 |   932 |   932 |   932 |   932
0:00:51.021 [Reporter]:         End to End |    5000 |   987 |  1026 |  1040 |  1065 |  1202
0:00:51.021 [Reporter]:       Catchup Read |     965 |    10 |     5 |    22 |    46 |   102
```

**Comment by andreipaduroiu** [comment]
Perf measurements (with BookKeeper as Tier1)

```
BASELINE
No cache interference. In-memory Tier2. 1 Segment with 1 Container.

#1. Appends: 2M, Size=100, Producers=10000, No ledger rollover
0:00:24.367 [Reporter]: Ops = 2000001/2000000; Data (P/T/C/S): 190.7/190.7/190.7/190.7 MB; TPut: 8.5 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/1/80, ForkJoin = 0/0/1.
0:00:24.367 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:24.422 [Reporter]:             Append | 2000000 |   105 |    94 |   135 |   235 |   433


#2. Appends: 1M, Size=1K, Producers=10000, No ledger rollover
0:00:31.611 [Reporter]: Ops = 1000001/1000000; Data (P/T/C/S): 953.7/953.7/953.7/953.7 MB; TPut: 32.1 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/1/80, ForkJoin = 0/0/0.
0:00:31.611 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:31.653 [Reporter]:             Append | 1000000 |   288 |   240 |   488 |   587 |   645



#3. Appends: 100K, Size=10K, Producers=10000, No ledger rollover
0:00:26.602 [Reporter]: Ops = 100001/100000; Data (P/T/C/S): 953.7/953.7/953.7/953.7 MB; TPut: 38.5 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/1/80, ForkJoin = 0/0/1.
0:00:26.602 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:26.617 [Reporter]:             Append |  100000 |  2281 |  2384 |  2586 |  2772 |  2791


#4. Appends: 10K, Size=100K, Producers=10000, No ledger rollover
0:00:23.952 [Reporter]: Ops = 10001/10000; Data (P/T/C/S): 953.7/949.8/949.8/949.8 MB; TPut: 43.2 MB/s; TPools (Q/T/S): Store = 2/1/30, Test = 1/1/80, ForkJoin = 0/0/1.
0:00:23.952 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:23.960 [Reporter]:             Append |   10000 | 10623 | 10806 | 18119 | 20101 | 20213


#5. Appends: 1K, Size=1MB, Producers=1000, No ledger rollover
0:00:24.154 [Reporter]: Ops = 1001/1000; Data (P/T/C/S): 953.7/881.2/881.2/881.2 MB; TPut: 42.6 MB/s; TPools (Q/T/S): Store = 2/1/30, Test = 1/1/80, ForkJoin = 0/0/1.
0:00:24.154 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:24.158 [Reporter]:             Append |    1000 | 11662 | 11645 | 20653 | 21110 | 21168
```

**Comment by andreipaduroiu** [comment]
Test 1: 4 Parallel BK writes (No cache interference, In-memory Tier2, 1 Segment with 1 Container)

```
#1. Count=2M, Size=100, Producers=10000, No ledger rollover
0:00:17.907 [Reporter]: Ops = 2000001/2000000; Data (P/T/C/S): 190.7/190.7/190.7/190.7 MB; TPut: 12.0 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/1/80, ForkJoin = 0/0/1.
0:00:17.908 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:17.995 [Reporter]:             Append | 2000000 |    73 |    62 |   131 |   294 |   398

#2. Count=1M, Size=1K, Producers=10000, No ledger rollover
0:00:17.683 [Reporter]: Ops = 1000001/1000000; Data (P/T/C/S): 953.7/953.7/945.5/953.7 MB; TPut: 60.4 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/2/80, ForkJoin = 0/0/1.
0:00:17.683 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:17.776 [Reporter]:             Append | 1000000 |   147 |   106 |   335 |   476 |   636

#3. Count=100K, Size=10K, Producers=10000, No ledger rollover
0:00:15.905 [Reporter]: Ops = 100001/100000; Data (P/T/C/S): 953.7/953.7/953.7/953.7 MB; TPut: 68.0 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/1/80, ForkJoin = 0/0/1.
0:00:15.905 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:15.927 [Reporter]:             Append |  100000 |  1196 |  1248 |  1455 |  1634 |  1649

#4. Count=10K, Size=100K, Producers=10000, No ledger rollover
0:00:15.795 [Reporter]: Ops = 10001/10000; Data (P/T/C/S): 953.7/950.0/941.8/950.0 MB; TPut: 68.6 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/2/80, ForkJoin = 0/0/1.
0:00:15.795 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:15.802 [Reporter]:             Append |   10000 |  6769 |  6837 | 11038 | 11728 | 11773

#5. Count=1K, Size=1MB, Producers=1000, No ledger rollover
0:00:14.639 [Reporter]: Ops = 1001/1000; Data (P/T/C/S): 953.7/892.6/876.4/892.6 MB; TPut: 74.1 MB/s; TPools (Q/T/S): Store = 3/0/30, Test = 1/2/80, ForkJoin = 0/0/1.
0:00:14.639 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L90 |   L99 |  L999
0:00:14.642 [Reporter]:             Append |    1000 |  6025 |  6074 | 10506 | 11334 | 11407
```
