### ISSUE TITLE
Implement local file based Tier-2

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1336]
**Problem description**
Implement a Tier-2 based on Posix API. 
This will be useful in:
 1. Using NAS as Tier2.
 2. Using local file system as Tier2 in standalone deployment.

**Problem location**
Tier-2 implementation in segmentstore/storage/impl.
Sample deployment using docker-compose and swarm in docker/

**Suggestions for an improvement**
Implement a Tier2 based on Posix APIs.

**Comment by tkaitchuck** [comment]
I assume you mean java's File api not Posix. IE: We're not going to be writing native code.
