### ISSUE TITLE
Pravega Go Client

### ISSUE THREAD

**Issue by sggraham32** [pravega/pravega#1340]
**Problem description**
Many important middleware components are written in Go these days, especially agent-like components (for example the ElasticStack's *Beats ).

For the health of the Pravega eco-system, a Go client would make it easier to build connectors to these other middleware projects.

**Problem location**
Client

**Suggestions for an improvement**
Build a Go client to Pravega, equivalent in functionality to the Java client and with an idiomatic Go programming model.

**Comment by tkaitchuck** [comment]
I *really* don't think we should prioritize GO at the moment. 

The example you site of Beats; beats is used by ElasticStack to send data mostly to other services, which largely aren't written in Go. LogStash of example is written in Ruby but has its handlers for incoming data written in Java.

By [every](https://insights.stackoverflow.com/survey/2016#most-popular-technologies-per-occupation)[ metric](https://pypl.github.io/PYPL.html)  [I](https://www.tiobe.com/tiobe-index/)  [can](http://redmonk.com/sogrady/2016/02/19/language-rankings-1-16/) [find](https://trendyskills.com/) GO doesn't even break the top 10 in languages. Even within Google, it's largest promoter, it only represents a tiny tiny fraction of the code base and it isn't gaining any ground.

Perhaps more importantly GO really easily interfaces with C++, so we could just as easily write a C++ client and we could interoperate with with GO, C++, and dozen other languages.

**Comment by AmreeshTyagi** [comment]
Not sure about 2017, but now situation has changed. Go is the top notch language to build cloud native applications now a days.
I have worked with Java for 4-5 years but now working with golang since last 4 years & I find it equivalent in popularity.
 
Any plan to implement any client in golang.

**Comment by krishan-Rai** [comment]
Hi @AmreeshTyagi - You can find go and NodeJS client binding here - https://github.com/pravega/pravega-client-rust
