### ISSUE TITLE
Add event count metric for segments

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1346]
**Problem description**
Currently, there is no way to determine the event rate for a stream/segment.  We need this (along with the read/write byte rate), do determine how close/far we are to to the dynamic scaling trigger rate.

**Problem location**
Metrics

**Suggestions for an improvement**
We should add a counter for the number of events for each segment.  That way, we can calculate the rate of events for the segment and determine how close we are to the scaling trigger.

**Comment by bayarsaikhan** [comment]
we need to add 2 new dynamic metrics that are scoped per stream & segment. 

```
    public static final String SEGMENT_READ_EVENTS = "segment_read_events";            // Dynamic Counter
    public static final String SEGMENT_WRITE_EVENTS = "segment_write_events";          // Dynamic Counter
```

**Comment by andreipaduroiu** [comment]
I cannot add a counter for read events in the Segment Store since it can't figure that out. I can only record the incoming events which will have to be sum-aggregated in the reports.

**Comment by Abhijeet-Jadhav** [comment]
@bayarsaikhan @andreipaduroiu 
In order to be consistent with output/emitted names, the correct naming of above metrics should be, : 
```
public static final String SEGMENT_READ_EVENTS = "segmentstore.segment_read_events";            // Dynamic Counter
    public static final String SEGMENT_WRITE_EVENTS = "segmentstore.segment_write_events";          // Dynamic Counter
```
