### ISSUE TITLE
Add scaling events api to controller

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1347]
**Problem description**
We would like some information about scaling events to graph when the scaling events have occurred over time.

- [ ] Internal controller call to expose list of scale events (Issue #1360)
- [ ] Implement REST API call to return the list of scale events (Issue #1361)
- [ ] Document REST API call

**Problem location**
Controller REST API

**Suggestions for an improvement**
We'd like to add a new api to return the Scaling Event data for a stream.  

GET /v1/scopes/{scope}/streams/{stream}/scaling-events
- list all scaling events
- Should return a “scaling event” that describes the initial state of the stream when created.  Will be the only entry returned for static segment streams.

Return Types
{
    “scaling-events: [
        
    ]
}

Scaling Event
{
    “segments: [],
    “timestamp”: long
}

Segment
{
    “segment-number”: int,
    “key-start-inclusive: float,
    “key-end-exclusive: float
}

Query Parameters

from = datetime number/string.  Limit scaling events to this date time.  Should always include one scaling event before the “from” query parameter.  This is required to draw the initial state of the segment graph.

to = datetime number/string.  Limit scaling events to this date time.

Datetime inputs should be milliseconds from Jan 1 1970 or ISO date time string.

**Comment by Abhijeet-Jadhav** [comment]
@glounder need some clarification on requirements. Do you need an initial event for reference or do you need an event just before 'from' and 'to' timestamp?

**Comment by glounder** [comment]
For static scaling streams, I would expect to only ever get one scaling event, regardless of what the 'from' or 'to' parameters are.  It would describe how the segments are divided up (key start/end) so we can draw the chart accordingly.  

For dynamically scaling streams, we just need the event just before the 'from' timestamp.  This is so if we ask for all the events from "11:45 am", if first scaling event in that range happened at "11:51 am", we can still draw the first part of the chart because we have the event before "11:45 am" that happened at "11:41 am".

If in the above dynamic scaling example, the stream was only created at "11:43 am" and we ask for events from "11:45 am", I would still expect a scaling event that describes the key ranges when the stream was created at "11:43 am".

**Comment by shiveshr** [comment]
Already implemented so closing it.
