### ISSUE TITLE
Need Controller REST API Support in Single node mode

### ISSUE THREAD

**Issue by TonySpace** [pravega/pravega#1362]
**Problem description**
We will need controller REST API supported in single node mode, that would able to simplify our development work a lot. Currently that is disable.

**Problem location**
Single node deployment

**Suggestions for an improvement**

**Comment by bayarsaikhan** [comment]
Single node doesn't provide full functionality of what Pravega offers, and is designed lightweight and only for testing purpose. REST is not supported yet. I'd suggest to deploy simple Pravega cluster to get REST up and running?

**Comment by TonySpace** [comment]
Pravega REST provides important APIs like listSteams. It would be great to have single node to support controller REST API as well that would benefit the Pravega developer and its community.

**Comment by TonySpace** [comment]
I saw Abhijeet is working on a pull request to solve this problem, that's exactly what we need :)
https://github.com/pravega/pravega/pull/1353/files

**Comment by bayarsaikhan** [comment]
Cool. This can be closed with #1353

**Comment by RaulGracia** [comment]
Fixed via #1353.
