### ISSUE TITLE
Support dash and underscore as allowed character in stream name

### ISSUE THREAD

**Issue by TonySpace** [pravega/pravega#1363]
**Problem description**
Currently Pravega doesn't support special character as the stream name. Please consider add dash "-" and underscore "_" as allowed characters for stream name. 

**Problem location**
stream client

**Suggestions for an improvement**

**Comment by bayarsaikhan** [comment]
What is the use case? Why do you need those characters?

**Comment by TonySpace** [comment]
We'd like to keep multiple attributes into a steam name, by list all streams, and parsing the stream name, we can get the attributes we need, we will need "-" or "_" as the separation for different attributes. Or else, we would have to keep all these attributes somewhere like ZK, that would introduce another hop to get attributes back thus downgrade the performance.
