### ISSUE TITLE
Segment Metrics being recorded as Gauge and Counter

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1369]
**Problem description**
While working with the auto scaling, we observed that the segments_count, segment_merges and segment_splits are all being recorded with a Gauge and a Counter.

![screen shot 2017-05-31 at 8 35 58 am](https://cloud.githubusercontent.com/assets/9335655/26642168/208651f8-4603-11e7-8b39-13cf291feff5.png)

The actual data is being stored under:
segments_count.Counter
segment_merges.Gauge
segment_splits.Gauge

The expectation is that the data is stored under:
segments_count.Gauge
segment_merges.Counter
segment_splits.Counter

**Problem location**
Metrics

**Suggestions for an improvement**
Store metrics under:
segments_count.Gauge
segment_merges.Counter
segment_splits.Counter

Where Gauge has the current number of segment and the Counters are running totals of the number of splits/merges.

**Comment by jkhalack** [comment]
Right now it looks like `segments_count.Gauge` correctly represents the number of segments for streams with static scaling (when there is no scaling happens). 
However, it does not work properly for streams with dynamic scaling (where `segments_count.Gauge` stays at the initial number of segments).

On the other hand, `segments_count.Counter` currently starts being recorded when the first dynamic splitting event occurs. However, it's value does not make any sense.
I am seeing `segments_count.Counter=1` for the case of  2 active segments (3 segments total),
`segments_count.Counter=3` for 4 active  (5  total),
`segments_count.Counter=7` for 8 active  (15  total),
`segments_count.Counter=13` for 14 active  (29  total), and so on
(with `segments_count.Gauge=1` at all times). 
With the same stream with dynamic scaling, I see `segment_splits.Counter=0`at all times, while `segment_splits.Gauge` starts being recorded at the time of first splitting, and then it's value stays at 1 no matter what.

**Comment by jkhalack** [comment]
So it seems that one metric (`segments_count.Gauge`) is written when the stream is created, but the other one (`segments_count.Counter`) is updated when a splitting occurs.

**Comment by bayarsaikhan** [comment]
Thank @jkhalack segments_count.Counter should be the source of truth.
When stream is created, it is reported as GAUGE (https://github.com/pravega/pravega/blob/c1fab58882f279e1475a84b2c1e3df7e0e6b1172/controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java#L133) *bug is here* I guess. 

However when scaling happens, it is acted as COUNTER (https://github.com/pravega/pravega/blob/c1fab58882f279e1475a84b2c1e3df7e0e6b1172/controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java#L337)

It should be initialized with proper type. 

Please @Abhijeet-Jadhav have a look at it.
