### ISSUE TITLE
Renaming Metrics

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1370]
**Problem description**
The naming of the metrics are a little disorganized.  Also, we want to come up with a better way to name metrics so its easier to filter the metrics.

**Problem location**
Metrics

**Suggestions for an improvement**
1.  Prefix all metrics with "pravega".
2.  Remove "DYNAMIC" from metric names as its not required by anyone consuming the metrics.
3.  Adopt the following format for naming:

pravega.<source>.<metric_name>.<tags...>

So for example, metrics would look like:

pravega.store.segment_read_bytes.$scope.$stream.$segment
pravega.controller.segment_splits.$scope.$stream
pravega.controller.tier2_total_used

These changes would allow us to filter all pravega metrics to be stored in its own database.  Also, we can write templates that know the number of tags for each metric name.

**Comment by Abhijeet-Jadhav** [comment]
All 22 Metrics, renamed as:

SEGMENT_CREATE_LATENCY	pravega.store.segment_create_latency_ms
SEGMENT_READ_LATENCY     pravega.store.segment_read_latency_ms
SEGMENT_WRITE_LATENCY	pravega.store.segment_write_latency_ms
SEGMENT_READ_BYTES		pravega.store.segment_read_bytes.$scope.$stream.$segement
SEGMENT_WRITE_BYTES		pravega.store.segment_writes_bytes.$scope.$stream.$segement

HDFS_READ_LATENCY  		pravega.hdfs.hdfs_read_latency_ms
HDFS_WRITE_LATENCY		pravega.hdfs.hdfs_write_latency_ms
HDFS_READ_BYTES			pravega.hdfs.hdfs_read_bytes
HDFS_WRITE_BYTES		pravega.hdfs.hdfs_write_bytes

DURABLE_DATALOG_WRITE_LATENCY 	   pravega.durablelog.durable_datalog_write_latency
DURABLE_DATALOG_WRITE_BYTES	   pravega.durablelog.durable_datalog_write_bytes

CREATE_STREAM	pravega.controller.stream_created
SEAL_STREAM  	pravega.controller.stream_sealed
DELETE_STREAM	pravega.controller.stream_deleted

CREATE_TRANSACTION		pravega.controller.transactions_created.$scope.$stream
COMMIT_TRANSACTION  	pravega.controller.transactions_committed.$scope.$stream
ABORT_TRANSACTION   	pravega.controller.transactions_aborted.$scope.$stream
OPEN_TRANSACTIONS   	pravega.controller.transactions_opened.$scope.$stream
TIMEDOUT_TRANSACTION	pravega.controller.transactions_timedout.$scope.$stream

SEGMENTS_COUNT  	pravega.controller.segments_count.$scope.$stream
SEGMENTS_SPLITS 	        pravega.controller.segments_splits.$scope.$stream
SEGMENTS_MERGES 	pravega.controller.segments_merges.$scope.$stream

@glounder Any changes required ?

**Comment by glounder** [comment]
I wasn't sure by the 'hdfs' and 'durablelog' names, but if we consider those sources, similar to 'store' and 'controller', I'm ok with the names.

**Comment by Abhijeet-Jadhav** [comment]
Yes, 'hdfs' and 'durablelog' are similar to other sources. We can also include them in 'store' category and drop hdfs and durablelog . Should we do that ?
Also 'store' can be replaced by 'segmentstore' as suggested by @bayarsaikhan .

**Comment by bayarsaikhan** [comment]
Hey @glounder and @Abhijeet-Jadhav As we know Durablelog is Tier1 and HDFS is Tier 2. Since we will have multiple tier 2 support, I'd suggest to use naming that is standard. Assuming that customer will have choice to select any Tier 2 type, the platform need to draw the graphs and provide stats. 

*Current ones*
```
HDFS_READ_LATENCY          pravega.hdfs.hdfs_read_latency_ms
HDFS_WRITE_LATENCY         pravega.hdfs.hdfs_write_latency_ms
HDFS_READ_BYTES            pravega.hdfs.hdfs_read_bytes
HDFS_WRITE_BYTES           pravega.hdfs.hdfs_write_bytes

DURABLE_DATALOG_WRITE_LATENCY      pravega.durablelog.durable_datalog_write_latency
DURABLE_DATALOG_WRITE_BYTES        pravega.durablelog.durable_datalog_write_bytes
```

*Suggested Ones*
```
HDFS_READ_LATENCY          pravega.hdfs.tier2_read_latency_ms
NFS_READ_LATENCY           pravega.nfs.tier2_read_latency_ms
S3_READ_LATENCY            pravega.s3.tier2_read_latency_ms
etc..

TIER1_WRITE_LATENCY      pravega.durablelog.tier1_write_latency
TIER1_WRITE_BYTES        pravega.durablelog.tier1_write_bytes
etc..
```

Any thoughts?

**Comment by glounder** [comment]
If you want to show the same metrics in the UI consistently, regardless of the tier source, this is a good way to good.  The only thing you have to make sure is that you can get the same metrics from all three sources.

**Comment by Abhijeet-Jadhav** [comment]
@bayarsaikhan Done. PR https://github.com/pravega/pravega/pull/1417

**Comment by bayarsaikhan** [comment]
Thanks @Abhijeet-Jadhav !
