### ISSUE TITLE
Explore parallel build option in gradle to improve build times

### ISSUE THREAD

**Issue by skrishnappa** [pravega/pravega#1385]
**Problem description**
Validate the parallel builds feature in gradle to improve build times.
Also need to check feasibility of increasing gradle build parallelism by setting maxParallelForks to a larger value, currently its set to 1. 

**Problem location**
gradle.properties

**Suggestions for an improvement**
Verify if these settings improve build time.

**Comment by tkaitchuck** [comment]
There have been a number of issues around this starting with https://github.com/pravega/pravega/issues/625 .
We should try enabling it and perform multiple rounds of testing until we fix all the related issues.
