### ISSUE TITLE
Review and consolidate 'retries' across controller code base

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1393]
**Problem description**
There are different components which all do retries using 'Retry' class. However, they all duplicate the work they do at most places. Its better to consolidate so that we do not have code duplication all over the code base.

**Problem location**
Controller

**Suggestions for an improvement**
Create some helper class where we have default retry constants and predicates that different parts of code base can make use of.

**Comment by EronWright** [comment]
One thing to watch out for: 'attempts' versus 'retryAttempts', each of which has a different semantic.
