### ISSUE TITLE
Transaction commit exceptions on success not handled correctly.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1402]
**Problem description**
A transaction commit can encounter an error, however the error may not cause the commit to fail. In such a case Failed is returned to the client. If they retry the commit they will also see a failure due to https://github.com/pravega/pravega/issues/1401
which implies they have no way to tell if the transaction actually committed or failed.

**Problem location**
Client and controller

**Suggestions for an improvement**
We could delay the commit completion until we have the full status of the commit, then we can return definitively that it succeeded or failed.

**Comment by huide9** [comment]
should the controller has  recent transaction records (length could be time/size based), so no need a timer and keep client simple?

**Comment by shiveshr** [comment]
There is checkTransactionsStatus api that clients can use. 
Also commit is idempotent. Which checks the previous status.
