### ISSUE TITLE
Document REST API calls on pravega.io

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1406]
**Problem description**
We need to have the REST API calls documented on pravega.io.

**Problem location**
Documentation, Web site.

**Suggestions for an improvement**
Make REST API documentation available on pravega.io.

**Comment by skrishnappa** [comment]
@bayarsaikhan please check the attached zip file, it has 2 files (rest_apis.md and index.html). Please review and let me know which format you prefer and I will commit the same to github and you can link it to pravega.io. These are autogenerated documentation so any manual changes to it is not recommended. 

[swagger_doc.zip](https://github.com/pravega/pravega/files/1059940/swagger_doc.zip)

**Comment by bayarsaikhan** [comment]
@skrishnappa it is great! I believe we can use what swagger generated automatically. However, I believe we need a little more description per methods, just like we did for in our Javadocs. Currently, it is really short and has little context in most of the methods and return values.

**Comment by skrishnappa** [comment]
@bayarsaikhan I'll add more description to the APIs. Please confirm whether you want .md or .html format?
 I'll raise the PR accordingly.

**Comment by bayarsaikhan** [comment]
@skrishnappa md format would be better. so that I can compile them as part of current documentation format. Thank you!

**Comment by skrishnappa** [comment]
@bayarsaikhan please link this document to the pravega.io website.
