### ISSUE TITLE
Pluggable Tier2

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1425]
**Problem description**
As we add support for more options for Tier-2 storage, we should split it out into a separate module, so that to build and deploy pravega you don't need to pull in dependencies for all possible tier-2 implementations. After all it is quite likely that you only want one.

**Problem location**
Build

**Suggestions for an improvement**
The different implementations could be put into different Gradle targets to keep their dependencies and Jars separate.

**Comment by andreipaduroiu** [comment]
This is already described in #1290.

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revisit the substitution of jsr311-api with javax.ws.rs-api](https://trello.com/c/jSYw92Cc/1-revisit-the-substitution-of-jsr311-api-with-javaxwsrs-api)
