### ISSUE TITLE
Storing segment length controller side.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1436]
**Problem description**
To calculate the distance between a reader group's position and the end of a stream we currently need to make 2 RPCs to the controller and 1 to the service per segment for every segment between the reader position and the tail of the stream. The RPCs are to: 
a) Get the successors to find the next segment.
b) Get the address of the host that owns that segment
c) Request the length of the segment.
This is particularly wasteful as all but the current segments are sealed. Which means these lengths never change. 

**Suggestions for an improvement**
As seal requests go through the controller, it could get the length at the time a segment is sealed and store this information. This would allow us to compute the distance from any given point in the stream to the end only requesting the lengths of the open segments.

**Comment by tkaitchuck** [comment]
This highlights a larger issue: https://github.com/pravega/pravega/issues/1437

**Comment by shiveshr** [comment]
Controller stores sealed segment sizes for size based retention computation.
