### ISSUE TITLE
Revisit controller bootstrap sequence

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1438]
**Problem description**
Currently we open up RPC and REST service endpoints even before internal streams like commitStream and abortStream are created by controller. Although this allows clients to successfully invoke operations like createScope and listScope, transaction related operations that need handle to commit and abort stream writers fail with IllegalStateException. The transaction requests handler is initialized only after commitStream and abortStream writers are successfully created.

We could instead open up RPC/REST service only once all the internal components are successfully initialized. The new bootstrap sequence proposed is the following
1. Start host-container mapper.
2. Start creating internal streams. After completion, start the following concurrently.
    a. Controller Event Processors.
    b. RPC service.
    c. REST service.

**Problem location**
`ControllerServiceStarter.java`, `StreamTransactionTasks.java`

**Suggestions for an improvement**
A new bootstrap sequence, as suggested above.

**Comment by tkaitchuck** [comment]
I think this change could simplify the startup process quite a bit, especially as it relates to StreamTransactionMetadataTasks. And I find the idea of having IllegalStateExceptions regularly in the logs  under normal conditions problematic.

**Comment by maddisondavid** [comment]
I agree, it's common place to see several errors with the segment store trying to access information on startup from a controller that's not fully configured yet.

Somewhat related, I also opened #1491

**Comment by chrisdail** [comment]
I bumped the priority on this assuming this is the fix for 1491. 90% of the time our pravega installs are unable to even create streams so this is a blocker.
