### ISSUE TITLE
All events are not being read from _commitStream post SSS failover tests.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#1441]
**Problem description**
System Test :379
AutoScaleTest was invoked post MultiSegmentStore test and no scaling was observed for txns.(Test Info: Multiple transactions are created on a stream by multiple writers to test if scale is observed on the stream.)

It was observed that only one txn was was commited on SSS the remaining 400+ transactions were not commited .
```Log of a successful txn commit from SSS .
segmentstore_2017-06-15.06.log:2017-06-15 03:57:27,635 696371 [epollEventLoopGroup-3-6] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.CommitTransaction(type=COMMIT_TRANSACTION, requestId=1202, segment=testAutoScale1569107136/testTxnScaleUp/0, txid=fa3086ae-d8c9-4fc5-b265-b88e3592a18f
```

On the controller end it can be seen that transaction requests are sent to the _commitStream (i.e all the transactions are still in committing state). And the event processor read only 1 event from the commitStream.

Also from the SSS logs it was observed that no READ_SEGMENT was invoked for the stream `_commitStream` post the fa3086ae-d8c9-4fc5-b265-b88e3592a18f txn-id processing.

```
last read from commit stream is at:
segmentstore_2017-06-15.06.log:2017-06-15 03:57:27,702 696438 [epollEventLoopGroup-3-8] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=R
EAD_SEGMENT, segment=_system/_commitStream/1, offset=76396, suggestedLength=65536)

```

```
But we do have writes to commitStream post 03:57:27

E.g: 
2017-06-15 03:57:41,452 722284 [controllerpool-40] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 27e82bee-4b40-4501-839f-4a914b6d321b, state=COMMITTING, sending request to _commitStream
```

```
2017-06-15 03:57:41,458 722290 [epollEventLoopGroup-2-8] DEBUG i.p.c.n.i.ClientConnectionInboundHandler - 172.16.24.10 processing reply: WireCommands.DataAppended(type=DATA_APPENDED, writerId=5a73c731-a55e-404b-9df4-47df504f9446, eventNumber=32)
2017-06-15 03:57:41,459 722291 [controllerpool-63] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 27e82bee-4b40-4501-839f-4a914b6d321b, sent request to _commitStream

```
The test Started @ 03:57:24 and ended @04:01:48`

**Problem location**
SSS (as per current investigation, since the same test works when SSS failover test is not executed).

**Comment by shrids** [comment]
Additional findings from a new test run.
[SystemTest 398_findings.txt](https://github.com/pravega/pravega/files/1087327/SystemTest.398_findings.txt)

**Comment by andreipaduroiu** [comment]
The segment is `_system/_abortStream/1`
At `2017-06-19 16:04:05,280` the segment is recovered with a length of 0
No further appends are recorded for this  segment, hence its length is 0
At `2017-06-19 16:04:12,871`, a read request (offset 0, len = 64K) is issued for this segment. Since the segment is empty, the response is `FutureReadResult`
`2017-06-19 16:04:12,871 289295 [epollEventLoopGroup-3-4] TRACE i.p.s.s.r.StreamSegmentReadResult - ReadIndex[1-1].ReadResult[0]: Consumed = 0, MaxLength = 65536, Entry = (FutureReadResultEntry: Offset = 0, RequestedLength = 65536, HasData = false, Error = false, Cancelled = false).`

At `16:16:12`, we finally get an append for this segment
`2017-06-19 16:16:02,640 999064 [epollEventLoopGroup-3-4] DEBUG i.p.s.s.c.StreamSegmentContainer - SegmentContainer[1]: append [_system/_abortStream/1, 283]`
Followed shortly after by a completion of the previous future read:
```
2017-06-19 16:16:02,649 999073 [segment-store-19] DEBUG i.p.s.s.reading.ContainerReadIndex - ReadIndex[1]: triggerFutureReads (StreamSegmentIds = [1]).
2017-06-19 16:16:02,649 999073 [segment-store-19] DEBUG i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[1-1]: triggerFutureReads (Count = 282, Offset = 1, Sealed = false).
2017-06-19 16:16:02,649 999073 [segment-store-19] TRACE i.p.s.s.r.StreamSegmentReadIndex - ReadIndex[1-1]: triggerFutureReads (Offset = 0, Type = Cache).
```

So I don't see anything abnormal here...

**Comment by tkaitchuck** [comment]
The client is blocking on the read call because the first read attempt failed. We can see "Retransmitting a read request" at 16:04. This is causing the read call to be synchronous and blocking on a response from the re-transmitted read. The read is not completing because there is no data to be read until 16:16

**Comment by shrids** [comment]
Following response times can be observed from the logs below:

Response `SEGMENT_READ @ 16:06:49,139` corresponds to Request `READ_SEGMENT @ 15:59:44,069 ` for `_abortStream/0` Timetaken: `7min 5 secs`
Response `SEGMENT_READ @ 16:16:02,650` corresponds to Request `READ_SEGMENT @ 16:04:12,871` for `_abortStream/1` Timetaken:` 11 mins 50 secs`
```
grep "Processing request: WireCommands.ReadSegment(type=READ_SEGMENT" *.log |grep _abortStream
segmentstore_2017-06-19.00.log:2017-06-19 15:59:44,063 20487 [epollEventLoopGroup-3-8] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/1, offset=0, suggestedLength=65536)
segmentstore_2017-06-19.00.log:2017-06-19 15:59:44,069 20493 [epollEventLoopGroup-3-1] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/0, offset=0, suggestedLength=65536)
segmentstore_2017-06-19.36.log:2017-06-19 16:04:00,740 277164 [epollEventLoopGroup-3-6] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/1, offset=0, suggestedLength=65536)
segmentstore_2017-06-19.36.log:2017-06-19 16:04:00,848 277272 [epollEventLoopGroup-3-8] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/1, offset=0, suggestedLength=65536)
segmentstore_2017-06-19.36.log:2017-06-19 16:04:01,853 278277 [epollEventLoopGroup-3-2] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/1, offset=0, suggestedLength=65536)
segmentstore_2017-06-19.36.log:2017-06-19 16:04:12,871 289295 [epollEventLoopGroup-3-4] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/1, offset=0, suggestedLength=65536)
segmentstore_2017-06-19.55.log:2017-06-19 16:16:02,652 999076 [epollEventLoopGroup-3-4] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/1, offset=283, suggestedLength=65536)
segmentstore_2017-06-19.55.log:2017-06-19 16:16:02,728 999152 [epollEventLoopGroup-3-1] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: WireCommands.ReadSegment(type=READ_SEGMENT, segment=_system/_abortStream/0, offset=291, suggestedLength=65536)
```

```
root@devBoxUbuntu-01:~/Documents/tmp/systemTest-398/logs/sss# grep "Encoding message to send over the wire WireCommands.SegmentRead(type=SEGMENT_READ" *.log |grep _abortStream
segmentstore_2017-06-19.43.log:2017-06-19 16:06:49,139 445563 [epollEventLoopGroup-3-1] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.SegmentRead(type=SEGMENT_READ, segment=_system/_abortStream/0, offset=0, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=291 cap=291])
segmentstore_2017-06-19.55.log:2017-06-19 16:16:02,650 999074 [epollEventLoopGroup-3-4] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire WireCommands.SegmentRead(type=SEGMENT_READ, segment=_system/_abortStream/1, offset=0, atTail=false, endOfSegment=false, data=java.nio.HeapByteBuffer[pos=0 lim=283 cap=283])
```
From the logs SSS takes about 7 to 11 mins to respond to a READ_SEGMENT request post failover

**Comment by shrids** [comment]
The above inference is incorrect because "a read segment command can come in and not get a response for a long time if there is no data. But when data comes in the server should repond with a segment_read"
The following behavior of SSS is correct.
1) READ_SEGMENT @ 15:59:44,069 for _abortStream/0 
2) READ_SEGMENT @ 16:04:12,871 for _abortStream/1
3) Append @  16:06:49,127 to _abortStream/0 
4) Response SEGMENT_READ @ 16:06:49,139 for _abortStream/0
5) Append @ 16:16:02,640 to _abortStream/1
6) Response SEGMENT_READ @ 16:16:02,650 for _abortStream/1

Hence the issue is not with SSS but just with the reader as mentioned in @tkaitchuck 's comment above.

**Comment by tkaitchuck** [comment]
So that leaves us with just two issues:
1. Following a failover ongoing requests to Reader.readNextEvent() do not honor the provided timeout. I've filed https://github.com/pravega/pravega/issues/1477 for this.
2. The test is for some reason very sensitive to this and the writing thread is oddly delayed for several minutes (but no prevented entirely) from writing to the stream.

@shrids Can you shed some more light on the second point?

**Comment by shrids** [comment]
From the logs do not see any delay in the writes to _abortStream.
The writes to _abortStream happens @ 16:06:49 .

**Controller Logs**:
```
2017-06-19 16:06:49,343 449430 [controllerpool-14] DEBUG i.p.c.t.S.StreamTransactionMetadataTasks - Transaction 6380c023-9f08-4119-bad4-d355f7ebe2ad, state=ABORTING, sending request to _abortStream
2017-06-19 16:06:49,346 449433 [epollEventLoopGroup-2-1] TRACE i.p.s.protocol.netty.CommandEncoder - Encoding message to send over the wire Append(segment=_system/_abortStream/0, writerId=a2739131-1a58-42e1-9b93-d63d74d02ee6, eventNumber=1, eventCount=1, data=UnpooledHeapByteBuf(ridx: 0, widx: 283, cap: 283/283), expectedLength=null)
```

**SSS Logs:**
`segmentstore_2017-06-19.43.log:2017-06-19 16:06:49,127 445551 [epollEventLoopGroup-3-3] DEBUG i.p.s.s.h.h.ServerConnectionInboundHandler - Processing request: Append(segment=_system/_abortStream/0, writerId=a2739131-1a58-42e1-9b93-d63d74d02ee6, eventNumber=1, eventCount=1, data=CompositeByteBuf(ridx: 0, widx: 291, cap: 291, components=1), expectedLength=null)`

**Test Logs:**
```
2017-06-19 16:06:49,149 8104 [Time-limited test] INFO  i.p.t.system.ControllerFailoverTest - Trying to abort transaction 6380c023-9f08-4119-bad4-d355f7ebe2ad, by sending request to controller at tcp://172.16.24.6:9092
2017-06-19 16:06:49,150 8105 [Time-limited test] TRACE i.p.c.stream.impl.ControllerImpl - ENTER abortTransaction@2348598552035 
```

**Comment by shrids** [comment]
Closing this issue as it is being tracked by #1477
