### ISSUE TITLE
New feature request - Having offset available when write event

### ISSUE THREAD

**Issue by TonySpace** [pravega/pravega#1453]
**Problem description**
Currently, we publish events to a Pravega stream, we do not know its offset for each event, that works well for IoT use case. While Pravega search is little bit different, because we persist Lucene index files into Pravega stream. From reader side, when we try to reach to a given file (suppose each file is written in an event), we do not want iterate all the events to find that given file, offset is needed for us to skip un-relevant events. 
The limitation is when writing an event into a stream, how to get the offset. And from reader side, how to use offset to retrieve an event.  

**Problem location**
Pravega client

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
Does RevisionedStreamClient:
https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/state/RevisionedStreamClient.java
Fit your needs or is there something additional you are looking for?
