### ISSUE TITLE
Support server affinity in the controller client

### ISSUE THREAD

**Issue by skrishnappa** [pravega/pravega#1485]
**Problem description**
The current controller client uses a round robin policy to send requests to multiple controller server instances. There are certain session based operations (#863 ) which will perform better if the client sends requests to the same server instance it initially connected with (enabling server affinity). 

**Problem location**
ControllerImpl

**Suggestions for an improvement**
Client should failover to other controller server instances only on failures.

**Comment by tkaitchuck** [comment]
Are we still planning to add this?

**Comment by shiveshr** [comment]
Closing this because with rolling txn we should get rid of pings altogether.
