### ISSUE TITLE
Performance should be comparable to Kafka when tuned for equivalent reliability/scale

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#15]
To be competitive with existing messaging infrastructures today (like Kafka), we should be able to provide write and read latency (tail and catch up reads) which are comparable or preferably better. 

TBD: Exact numbers, end-to-end versus broker latency...etc

**Comment by pmullaney** [comment]
Was this closed because the comparison was done? Link?

**Comment by shafqatevo** [comment]
Was any benchmark comparisons done between Pravega and Kafka for the same messaging use case?
