### ISSUE TITLE
Make Tier-2 plugable at compile time

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1503]
**Problem description**
Right now the code builds all Tier-2 connectors and pulls in all the dependencies for every possible Tier-2 implementation. This results in additional code being loaded into the process.

**Problem location**
build.gradle

**Suggestions for an improvement**
We should find a way to isolate the build so that we can produce targets for each Tier-2 impl and we can only ship the appropriate bundle for the deployment.

**Comment by andreipaduroiu** [comment]
See #1290 . That covers this as well.
