### ISSUE TITLE
Avoid exposing version from transaction related APIs of StreamMetadataStore

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1504]
**Problem description**
Currently, `pingTxn` and `sealTxn` APIs of `StreamMetadataStore` take version of transaction node in the underlying store as an input parameter. `sealTxn` API uses `version` parameter to conditionally abort the transaction, and `pingTxn` API updates transaction node, thus updating its version and fencing off any other controller process tracking timeout for that transaction. The callers assume several properties of this version (1) It is a positive integer, (2) On creation of a node, its version is 0, (3) Each update increments it by 1. This exposes underlying store's behavior to higher layers, thus constraining the types of compatible stores. We should instead a new `ownerId` parameter to server the purpose that `version` serves today.

**Problem location**
Transaction APIs in `StreamMetadataStore`.

**Suggestions for an improvement**
We should instead a new `ownerId` parameter to server the purpose that `version` serves today.

**Comment by tkaitchuck** [comment]
Is this still an issue?
