### ISSUE TITLE
Storage interface definition is passing a reference buffer a raw byte array across threads to be filled and returned.

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1508]
**Problem description**
Storage interface passes byte arrays across threads to fill.
```
public CompletableFuture<Integer> read(SegmentHandle handle, long offset, byte[] buffer, int bufferOffset, int
```
This is a pattern used across storage implementation.

**Problem location**
Storage interface definition and its different implementations.

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
So ... why is this a problem?

**Comment by arvindkandhare** [comment]
This was from a comment from @tkaitchuck on the code review 1395. I think he will be able to thow more light on this.
