### ISSUE TITLE
Segment Splits are being reported as Merges in Metrics

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1512]
**Problem description**
Currently, we have a Pravega Scaling test that looks like its scaling, but the splits are being reported as merges.

**Problem location**
We are using build 0.1.0-1470.e5e9896 that includes the changes from https://github.com/pravega/pravega/pull/1447.

**Suggestions for an improvement**
Looking at the code, it assumes the order of scaleMetadataList.  We might to make sure that list is sorted chronologically.  

Also, in the loops to calculate the total spits in merges, it overwrites the value on each loop.  Is that expected or should it be adding to the total on each iteration?

**Comment by fpj** [comment]
Sounds like a bug.
