### ISSUE TITLE
Refactor cluster abstraction in common

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1529]
**Problem description**
We have a `Cluster` interface and implementation in `common/` that is used primarily by the controller to manage a Pravega cluster. This cluster abstraction is currently a dependency of the segment store as well because each server makes a call to this interface to register against the zk-backed metadata store.

In this abstraction, there are really two parts: one call to register nodes and another set to manage the abstract cluster. We should consider separating out these calls.

A second issue is that this cluster abstraction does not really belong in common, so we should consider moving it out of there.  

**Problem location**
Controller, `Cluster` interface and implementation.

**Suggestions for an improvement**
Split the cluster abstraction and implementation into two parts:
- One part used for cluster management that belongs in the `controller` package
- A second part used by any node to register against the cluster that arguably belongs in `shared/controller-api`. Such a call to register is in some sense part of the controller API because if we were to use an RPC to register rather than shared-memory via zookeeper, then the RPC call would go there.

**Comment by shiveshr** [comment]
This is done. So closing the issue
