### ISSUE TITLE
Scaling didn't start for 2 hours

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1530]
**Problem description**
While running our scale test, scaling didn't start for 2 hours.  This happened earlier this morning, so its possible the logs didn't capture the input.  Segment Store and Controller logs attached.

[Logs](https://github.com/pravega/pravega/files/1122911/Archive.zip)

0.1.0-1475.c0b1b6f

Test started at 9:32 ADT and scaling started around 12:14 ADT

**Problem location**

**Suggestions for an improvement**

**Comment by glounder** [comment]
We tested this again on another cluster and the scaling started after 20 minutes, so this might be an intermittent problem.

**Comment by shiveshr** [comment]
it is partially related to #1531. Dns name resolution did not happen correctly for controller and name resolution was retried after a long delay. 

We need to investigate what happened after the name resolution happened eventually but eventStreamWriter was still not set up.

**Comment by skrishnappa** [comment]
@glounder we are not able to conclude using the existing info level logs. Is it possible to check this on a setup with debug logging enabled. We could try enabling debug logs only for gRPC to narrow down the issue. We need to updated the logback (logback.xml) configuration for the segmentstore and controller with the following:

**Comment by chrisdail** [comment]
We have not seen this issue in a long time. Going to close it.
