### ISSUE TITLE
Controller client should attempt controller URI resolution frequently

### ISSUE THREAD

**Issue by skrishnappa** [pravega/pravega#1531]
**Problem description**
The current controller gRPC client implementation attempts to resolve the controller URI only every 30 minutes. We have seen this to cause the controller client to be unusable for 30 minutes if the initial resolution fails. We should attempt to resolve the controller URI more frequently to handle the following issues
* Temporary DNS resolution failures (could be due to network connectivity or DNS propagation delays too)
* Controller IP address changes (hence the DNS update should be picked up sooner than later)

**Problem location**
ControllerImpl.java

**Suggestions for an improvement**
Increase frequency of controller URI resolution

**Comment by shiveshr** [comment]
should it not do resolution everytime there is a connection failure? Timing should not be a consideration IMO
