### ISSUE TITLE
Refactor Segment Container Management

### ISSUE THREAD

**Issue by skrishnappa** [pravega/pravega#154]
The current implementation of segment container ownership management (https://github.com/emccode/pravega/wiki/Managing-Segment-Containers) does not address the following requriements:
1. Need to ensure (in all scenarios) that a container is stopped before starting it on another container
  -- We should not assume fencing logic being implemented in Tier I and Tier II storage
2. The current implementation is only for host level failure handling. Need to handle the following container level failures too
  -- Starting container could fail
  -- Stopping a container could fail
  -- A running container could fail/abort
3. Architectural consistency
  -- We do not want Pravega service calling into external storage for ownership information. We can the controller to actively call into the pravega service to keep the flow consistent with the other features design
4. Rebalance segment container based on load
  -- In a heterogenous cluster enviroment distributing containers equal on all hosts may not be optimal

We need to review and validate each of the above requirements and come up with an overall architecture to address them.

**Comment by andreipaduroiu** [comment]
I believe this has already been sufficiently implemented that no further work is required.
