### ISSUE TITLE
Lock not getting transferred from a dead controller instance to the active controller instance

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#1542]
**Problem description**
Lock is not getting transferred from a dead controller instance to the active controller instance. This is observed when multiControllerSystem test is the first test to run.

When multiController test was run there were no SSS so stream internal creation had not completed, and it was killed before the task could fail... (i.e. the number number of controllers post the test is 0)
This task is not transferred to new controller instance(created by the subsequent test ) and this new controller instance, in its own attempts to create stream keeps failing with lock failed as another controller is holding on the lock..

The reason lock is not transferring is because of a cyclic dependency -- 
1. controllerClusterListener waits on transactionMetadataTasks to become ready. 
2. transactionMetadataTasks waits on internal streams to be created. 
3. internal stream creation is stuck because task sweeper has not run and transferred locks from a failed controller
4. task sweeper starts sweeping after controllerClusterListener is ready

Logs: System test Run 433

``` 
2017-07-06 10:15:21,821 42879 [controllerpool-44] WARN  i.p.c.s.e.ControllerEventProcessors - Error creating event processor stream _requeststream
java.util.concurrent.CompletionException: io.pravega.controller.store.task.LockFailedException: Failed locking resource _system/_requeststream.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
```

**Problem location**
Controller startup...

**Comment by shrids** [comment]
[logs_ctrl.tar.gz](https://github.com/pravega/pravega/files/1127673/logs_ctrl.tar.gz)

**Comment by Prabha-Veerubhotla** [comment]
Facing the same  while running MultiReaderWriterFailoverTest :

[controller logs.zip](https://github.com/pravega/pravega/files/1128040/controller.logs.zip)
