### ISSUE TITLE
System tests should run against deployments with filesystem (and extended s3) as tier2 storage

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1572]
**Problem description**
Currently we run our system tests with HDFS as tier-2. There should be an option to run these against filesystem (and extended s3) as tier2 storage.

**Problem location**
System tests.

**Suggestions for an improvement**
There should be a way to use common shared NFS/extended S3 deployments and run system tests pointing to these.

**Comment by arvindkandhare** [comment]
The branches `issue-1572-systemtestsforecs` and `issue-1572-systemtestsforisilon` have the hard coded changes for running these. 
TBD: Update the system test code so that the `TIER2_STORAGE` as well as rest of the tier-2 specific configurations can be taken as parameters to `startSystemTests`.

**Comment by andreipaduroiu** [comment]
Isn't this done? I see this in the sys test UI.
