### ISSUE TITLE
spurious failure in SynchronousStreamSegmentStoreTests with OperationProcessor not running error

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1578]
**Problem description**

io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStoreTests > testEndToEnd FAILED
    java.util.concurrent.CompletionException: io.pravega.segmentstore.server.IllegalContainerStateException: OperationProcessor is not running.
        Caused by:
        io.pravega.segmentstore.server.IllegalContainerStateException: OperationProcessor is not running.

**Problem location**
SynchronousStreamSegmentStoreTests
https://travis-ci.org/pravega/pravega/builds/252978529

**Suggestions for an improvement**
None.

**Comment by Prabha-Veerubhotla** [comment]
io.pravega.segmentstore.server.mocks.SynchronousStreamSegmentStoreTests > testEndToEnd FAILED
    java.util.concurrent.CompletionException: io.pravega.segmentstore.contracts.ContainerNotFoundException: [Container 1] Container Id does not exist..
        Caused by:
        io.pravega.segmentstore.contracts.ContainerNotFoundException: [Container 1] Container Id does not exist..
