### ISSUE TITLE
Txns can be left in committing or aborting because of failure before posting event in the stream

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1645]
**Problem description**
Txn commit and abort have following sequence:
1. Add txn to current host's index
2. Seal txn (this sets the state of txn to committing or aborting)
3. write event to corresponding stream

If client calls commit and we have a failure between (2) and (3) then txn state is left dangling to committing.
Unless client calls commit again, this txn is never committed as event was never posted in EP.. 
it can also not be aborted with timeout. So txn will be left dangling. 

**Problem location**
StreamTxnMetadataTasks.java

**Suggestions for an improvement**
Fix the issue without breaking any txn commit guarantees.

**Comment by bhargav-gulavani** [comment]
If the controller process fails, e.g., crash, after step 2, then, during recovery, for each orphaned transaction in committing (resp. aborting) state, we write a commitEvent (resp. abortEvent), to the commit stream (resp. abort stream).

**Comment by shiveshr** [comment]
@bhargav-gulavani if its a crash, we have a recovery path. but for any other exceptional case, we may be left dangling for the lack of event being posted in the stream

**Comment by bhargav-gulavani** [comment]
If `sealTxn` succeeds, which other exceptional cases could arise? Note that, we attempt adding an event to the appropriate stream repeatedly until success. 

As an optimization, after `sealTxn` succeeds, we could add an event to an in-memory structure - an operation that cannot fail, and return to the client immediately. In the background, we could move the event from in-memory structure to the appropriate stream.
