### ISSUE TITLE
StreamSegmentContainerRegistry.getContainer should throw WrongHost 

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1647]
**Problem description**
In `AppendProcessor.handleException`, we expect `WrongHostException` to be thrown when the server does't have the container, e.g., when the container ownership has changed. It is instead throwing `ContainerNotFoundException`.

**Problem location**
Segment store.

**Suggestions for an improvement**
Throw `WrongHostException` instead of `ContainerNotFoundException` in the container registry or change the exception expected in `AppendProcessor`.

**Comment by andreipaduroiu** [comment]
I can't throw this because I don't know what the correct host is. Check out the constructor of that exception.

**Comment by fpj** [comment]
@andreipaduroiu I'm not seeing it thrown anywhere, do we ever throw it? should we consider getting rid of it and just using `ContainerNotFoundException`?

**Comment by andreipaduroiu** [comment]
I would use `ContainerNotFoundException`, but I looked at where `WrongHostException` is checked, and it looks like it wants to send the "correct host name" back onto the wire. I can switch over to ContainerNotFoundException with no problems, but I don't know what to put there.

**Comment by andreipaduroiu** [comment]
Looks like this is being fixed in #1658

**Comment by andreipaduroiu** [comment]
Fixed with #1658
