### ISSUE TITLE
StreamSegmentStore should validate Tier2 configuration and abort in the startup

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1650]
**Problem description**
In case of invalid configuration for Tier-2, StreamSegmentStore should not continue startup.

**Problem location**
`HDFSStorage`, `FileSystemStorage` and `ExtendedS3Storage`

**Suggestions for an improvement**
The storage should check validity during startup and abort early.

**Comment by andreipaduroiu** [comment]
This was fixed long ago.
