### ISSUE TITLE
Possible out-of-order writes in SegmentStore

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1659]
**Problem description**
1. We have a Segment that is brand new or hasn't been used in a while (inactive)
2. We have two concurrent calls to `append` to that Segment, A1 and A2, with A2 arriving just after A1
3. Since the segment is inactive, the SegmentContainer needs to load an existing/assign a new segment id, which is an operation that may take a while (Tier2 read or Tier1 write). This is triggered by the receipt of the A1 request, and A2 will "tag along" waiting on the existing assignment to complete (no double-completions).
4. If A2 arrives before the id is assigned, then it is very possible that A2 will be queued into the OperationProcessor before A1 (the correct order is the opposite). This is because we are now at the mercy of the Java thread scheduler and CompletableFuture dependent execution, which will not necessarily respect the order we want.

**Problem location**
StreamSegmentContainer and StreamSegmentMapper.

**Suggestions for an improvement**
StreamSegmentMapper.getOrAssignSegmentId will take an explicit callback. The callbacks will be then executed in order in which they were received - by code that we write, not JVM scheduler or whatever.

**Comment by tkaitchuck** [comment]
Clients should not be impacted by this because AppendProcessor only allows one write outstanding against the store per connection at a time.
