### ISSUE TITLE
Health status check for controller and segment store

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1665]
**Problem description**
It would be useful to have a quick way to determine whether our components are up and healthy. One way is to have a simple text protocol that sends short commands and receives text responses. The zookeeper 4lw is an example of such protocol.

This feature would be useful not only to determine whether the components of a cluster are healthy quickly, but also to determine when system tests can run.

**Problem location**
Controller and segment store.

**Suggestions for an improvement**
Add either a simple text protocol or use a REST call to do it.

- [ ] Controller
- [ ] Segment store

**Comment by andreipaduroiu** [comment]
My thoughts on this:
- We should have a REST API that outputs either JSON or XML (both human and machine readable
- Have 2 endpoints
    - Summary: A quick one, that just outputs OK or NOTOK (or whatever we choose). This should not do any extensive queries and would likely just be used by a readiness probe.
    - Details: More details, which may involve a bit more extensive queries. For the Segment Store, for example, this would include information about all registered Containers, their status, active segments, etc.


We should decide the amount of information that goes into each of these. Things to consider including:
- Thread pool(s)
- Cache
- IO activity
- ?

**Comment by derekm** [comment]
I'm a big fan of MicroProfile Health, which supports Liveness and Readiness tests out of the box and will support Wellness tests (that enabled a DEGRADED status which doesn't fail the check) in upcoming versions of the spec.

MicroProfile Health assumes the presence of CDI, but otherwise it is very convenient and easy to work with.

**Comment by derekm** [comment]
Also, the IETF is specifying a draft RFC for health checks here: https://github.com/inadarei/rfc-healthcheck

I'm working in both the RFC and MicroProfile communities to achieve more agreement between the two specs.

**Comment by pbelgundi** [comment]
This health-check should be used by pravega-operator to decide if a controller / SSS pod should serve requests or not. The health-checks implemented by controller and SSS are just place holders and do only a basic port check.
Filed this on p-operator, which can be taken up once these checks are implemented on SSS and Controller : https://github.com/pravega/pravega-operator/issues/357

**Comment by pbelgundi** [comment]
This has been implemented  as fixes for following issues: 
Issue 6219: Health checks for Segment Store.
Issue 6144: Health checks for Controller.
