### ISSUE TITLE
Pass Tier2 credentials securely to streamsegmentstore

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1666]
**Problem description**
The creds for accessing an extendedS3 bucket/access to NFS share through filesystem is currently supplied through config/env variables. It needs to be passed through a secure mechanism.

**Problem location**
`ExtendedS3StorageConfig` and `entrypoint.sh`.

**Suggestions for an improvement**
Use a commonly used mechanism to pass the creds securely. We should still keep the option of sending these through config.

**Comment by sachin-j-joshi** [comment]
This is now done via k8s secret passed to segment store by Pravega operator.
https://github.com/pravega/pravega/wiki/Using-ECS-as-Tier-2#step-2-create-secret
