### ISSUE TITLE
Implement leader election with state synchronizer

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1671]
**Problem description**
State synchronizer provides the ability of keeping state synchronized across replicas using conditional updates. Leader election is one possible use case for the state synchronizer.

One option is to have a listener to subscribe to leadership changes and track the changes via the state synchronizer. The state consists of membership and leadership. Heartbeating could happen either via state synchronizer or via direct communication (e.g., TCP).

**Problem location**
Not a problem, it is an addition

**Suggestions for an improvement**
Implement a leader election recipe.

**Comment by tkaitchuck** [comment]
Done in https://github.com/pravega/pravega-leaderElection
