### ISSUE TITLE
Test that txn commit is idempotent controller-side

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1676]
**Problem description**
Pull request #1675 fixed the problem that the execution of txn commit controller-side was not idempotent. We need to add test cases (unit or integration) to verify the correctness of txn processing in the presence of crashes. We should not rely on system tests for such basic testing.

**Problem location**
Controller, testing.

**Suggestions for an improvement**
Write test cases.

**Comment by shiveshr** [comment]
We have unit tests covering this.
