### ISSUE TITLE
Fail outstanding writes when stream is sealed.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1684]
**Problem description**
When a Stream is sealed the client currently has no way to differentiate this from merely a segment within the stream being sealed. So it continues to retry and leaves futures for events previously written uncompleted and unfailed.

**Problem location**
Client - Controller interaction.

**Suggestions for an improvement**
We should add a means to alert the client to the fact the stream is sealed when it is fetching new segments.

**Comment by shiveshr** [comment]
An empty list of successors should be returned by controller for segments from the last epoch before sealing of stream completes. 

This should be an unambiguous response indicating a "sealed stream" if the original segment is sealed and has no successors. 

I suppose we can handle this scenario solely on client without requiring any changes to controller-client interaction.

**Comment by shiveshr** [comment]
For a sealed stream, controller returns {} empty map as successors for last set of segments (from the last epoch before the stream was sealed).
For all other cases, controller returns correct successor segment list. 
So empty successor segments is an unambiguous response for clients to determine if a stream was sealed.

**Comment by fpj** [comment]
I'm in general not in favor of implicit behavior, so I'd rather have a change to the protocol to indicate that the stream is sealed. Is that acceptable or should we go with the implicit behavior option? What do you people think?

**Comment by tkaitchuck** [comment]
This looks similar to https://github.com/pravega/pravega/issues/2613
which change the refresh code in segmentSelector to the following:
```
    public List<PendingEvent> refreshSegmentEventWritersUponSealed(Segment sealedSegment, Consumer<Segment>
            segmentSealedCallback) {
        StreamSegmentsWithPredecessors successors = Futures.getAndHandleExceptions(
                controller.getSuccessors(sealedSegment), t -> {
                    log.error("Error while fetching successors for segment: {}", sealedSegment, t);
                    return null;
                });

        if (successors == null) {
            // Stream is deleted, complete all pending writes exceptionally.
            log.error("Stream is deleted, all pending writes will be completed exceptionally");
            removeAllWriters().forEach(event -> event.getAckFuture()
                    .completeExceptionally(new NoSuchSegmentException(sealedSegment.toString())));
            return Collections.emptyList();
        } else {
            return updateSegmentsUponSealed(successors, sealedSegment, segmentSealedCallback);
        }
    }
```
It looks like we are handling the generic error case as a truncated segment. Perhaps we should narrow that, and add a case to handle empty. 
I do agree that is makes sense to add the flag to the wireprotocol. It would be backwards compatible, and strictly make things more clear.
