### ISSUE TITLE
Minor fixes to Pravega.io

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1690]
**Problem description**
1. Instead of having two bullets `Prerequisites (Manual install)` and `Installation (Manual install)` under `running Pravega`, these should go under `Manual install` and should have two sub-bullets.
2. On page `Running in the cloud (AWS)` , `Region us-east-1` and `Region us-west-1:` should not have different headings/should not come up in the table of contents.

**Problem location**
pravega.io website.

**Suggestions for an improvement**

**Comment by askewj** [comment]
Fixed in https://github.com/pravega/pravega/pull/1736
