### ISSUE TITLE
Ack appends before adding to ReadIndex

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1702]
**Problem description**
High-level view of how appends are processed in the Segmentstore:
1. Append is received
2. Append is batched with others and sent async to Tier1
3. Tier1 ack comes back
4. Metadata for all appends in batch gets committed to the main metadata
5. All appends in batch get added to ReadIndex (and thus to Rocks) and then to in-memory log.
6. All appends in batch are acked back to the caller.

In some cases it may take up to 1ms for step 5 above to complete. In addition, it is also done under a lock that is used extensively throughout the `OperationProcessor`, and both the ReadIndex-add and the MemLog-add have their own set of locks.

**Problem location**
`OperationProcessor` and `MemoryStateUpdater`.

**Suggestions for an improvement**
Swap steps 5 and 6 (see **Problem Description** above). Complete the Operation future before we add to the read index (but always after persisting to Tier1). This still acks to the caller after durably persisting to Tier1, thus we are in no danger of breaking the exactly-once guarantee. Plus it will be done outside of the `OperationProcessor` lock.

However, there is a concern about swapping 5 and 6. It is possible, in some rare cases, that the caller will want to read the data once they got an ack. But I do not believe that it will be an issue:
1. It will take a lot longer than 1ms for a signal to go back to the caller, the caller figuring it out, then the caller issuing some random read, and that read reaching the same SegmentStore instance.
2. Due to our API limitations, the caller cannot issue random reads anyway until they do a tail read. The tail read will not be triggered until the operations are added to the ReadIndex, so no worries there.

**Comment by andreipaduroiu** [comment]
Here is a comparison of before-and-after using the SelfTester (**DISCLAIMER:** This is a specific test run on my dev machine with limited resources with the purpose of showing potential improvements brought by this feature; do not use this as a proxy for Pravega Performance)

5M appends of 100 bytes, 100 producers x 100 burst, 1 Container, 1 Segment, 1 Bookie, SegmentStoreDirect, No reads.

Before:
```

**Comment by tkaitchuck** [comment]
Reading might be an issue, but it would really be an issue if when we called getInfo on the stream it returned the pre-append length. But I assume that is taken care of in step 4.

**Comment by andreipaduroiu** [comment]
**DISCLAIMER**:  These numbers should by no means be used to judge the Segment Store's performance. This benchmark was obtained on my local dev machine using a test that's designed to push as much data as possible. Its goal was to compare various configurations and see how they affect throughput and latency.

Compare against [this](https://github.com/pravega/pravega/issues/1420#issuecomment-337320095)

```
#1. Count=2M, Size=100, Producers=10000, No ledger rollover
-Dtarget=SegmentStore -Dreads=false -Ds=1 -Dws=100 -Do=2000000 -Dp=10000
0:00:14.591 [Reporter]: Ops = 2004000/2000000; Data: 191.1 MB; TPut: 17.3/18.8 MB/s; TPools (Q/T/S): Store = 4/1/30, Test = 0/1/80, ForkJoin = 0/0/0.
0:00:14.591 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:14.592 [Reporter]:             Append | 2003999 |    48 |    38 |    61 |    95 |   182 |   209

#2. Count=1M, Size=1K, Producers=10000, No ledger rollover
-Dtarget=SegmentStore -Dreads=false -Ds=1 -Dws=1000 -Do=1000000 -Dp=10000
0:00:13.144 [Reporter]: Ops = 1008270/1000000; Data: 961.6 MB; TPut: 104.4/100.1 MB/s; TPools (Q/T/S): Store = 5/1/30, Test = 0/1/80, ForkJoin = 0/0/0.
0:00:13.144 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:13.145 [Reporter]:             Append | 1008269 |    91 |    76 |   110 |   151 |   379 |   442

#3. Count=100K, Size=10K, Producers=10000, No ledger rollover
-Dtarget=SegmentStore -Dreads=false -Ds=1 -Dws=10000 -Do=100000 -Dp=10000
0:00:09.780 [Reporter]: Ops = 110001/100000; Data: 1049.0 MB; TPut: 190.7/147.4 MB/s; TPools (Q/T/S): Store = 5/2/30, Test = 0/1/80, ForkJoin = 0/0/0.
0:00:09.780 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:09.781 [Reporter]:             Append |  110000 |   642 |   649 |   781 |   912 |  1008 |  1074

#4. Count=10K, Size=100K, Producers=10000, No ledger rollover
-Dtarget=SegmentStore -Dreads=false -Ds=1 -Dws=100000 -Do=10000 -Dp=10000
0:00:13.013 [Reporter]: Ops = 11001/10000; Data: 1049.0 MB; TPut: 1458.1/154.4 MB/s; TPools (Q/T/S): Store = 6/1/30, Test = 0/1/80, ForkJoin = 0/0/0.
0:00:13.014 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:13.016 [Reporter]:             Append |   11000 |  5192 |  5475 |  5945 |  6155 |  6336 |  6376

#5. Count=1K, Size=1MB, Producers=1000, No ledger rollover
-Dtarget=SegmentStore -Dreads=false -Ds=1 -Dws=1000000 -Do=1000 -Dp=1000
0:00:08.784 [Reporter]: Ops = 1101/1000; Data: 1049.0 MB; TPut: 2046.8/165.5 MB/s; TPools (Q/T/S): Store = 5/2/30, Test = 0/1/80, ForkJoin = 0/0/0.
0:00:08.784 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:08.785 [Reporter]:             Append |    1100 |  5274 |  5742 |  5897 |  6007 |  6324 |  6368
```

**Comment by andreipaduroiu** [comment]
@tkaitchuck 
> Reading might be an issue, but it would really be an issue if when we called getInfo on the stream it returned the pre-append length. But I assume that is taken care of in step 4.

This issue is there now as well and is not getting better or worse with this change. There is no global lock that is acquired when updating all in-memory state, so the metadata gets updated first and then the read index. The effect of the scenario you're describing will be that a FutureRead will be returned which will be completed very quickly. We are talking about a few milliseconds at best and you'd have to issue the reads like "getInfo, then read the last few bytes based on that info", which is not how tail reads are supposed to be done (they are done via FutureReads, which are unaffected by this change).

**Comment by andreipaduroiu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ack operations earlier in SegmentStore commit path](https://trello.com/c/gSEmUfYM/29-ack-operations-earlier-in-segmentstore-commit-path)

**Comment by andreipaduroiu** [comment]
**DISCLAIMER:** These numbers should by no means be used to judge the Segment Store's performance. This benchmark was obtained on my local dev machine using a test that's designed to push as much data as possible. Its goal was to compare various configurations and see how they affect throughput and latency.

**Benchmark**
**Test 1: Producers=10000, Producer Burst=1, Write Size=100, Operation Count=2M**
`./gradlew test:integration:selftest -Dtarget=SegmentStore -Dreads=false -Dmetrics=false -Dbkc=1 -Dc=1 -Ds=1 -Dsc=1 -Do=2000000 -Dp=10000 -Dpp=1 -Dws=100`

**BASELINE:**
```
0:00:15.654 [Reporter]: 2009964/2000000; Ops = 155807/170976; Data: 191.7 MB; TPut: 14.9/16.3 MB/s; TPools (Q/T/S): S = 4/1/30, T = 0/1/80, FJ = 0/0/0.
0:00:15.654 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:15.655 [Reporter]:             Append | 2009963 |    57 |    47 |    71 |   109 |   188 |   225
```

**ACK EARLY:**
```
0:00:13.816 [Reporter]: 2006371/2000000; Ops = 64/193717; Data: 191.3 MB; TPut: 0.0/18.5 MB/s; TPools (Q/T/S): S = 4/1/30, T = 0/1/80, FJ = 0/0/0.
0:00:13.816 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:13.816 [Reporter]:             Append | 2006370 |    49 |    37 |    63 |    99 |   188 |   228
```

**Test 2: Producers=100000, Producer Burst=100, Write Size=100, Operation Count=5M.**
`./gradlew test:integration:selftest -Dtarget=SegmentStore -Dreads=false -Dmetrics=false -Dbkc=1 -Dc=1 -Ds=1 -Dsc=1 -Do=5000000 -Dp=1000 -Dpp=100 -Dws=100`

**BASELINE:**
```
0:00:26.764 [Reporter]: 5095383/5000000; Ops = 361050/230408; Data: 485.9 MB; TPut: 34.4/22.0 MB/s; TPools (Q/T/S): S = 5/1/30, T = 0/1/80, FJ = 0/0/0.
0:00:26.764 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:26.765 [Reporter]:             Append | 5095382 |   430 |   426 |   509 |   616 |  1037 |  1231
```

**ACK EARLY:**
```
0:00:16.339 [Reporter]: 5099842/5000000; Ops = 834502/506111; Data: 486.4 MB; TPut: 79.6/48.3 MB/s; TPools (Q/T/S): S = 5/2/30, T = 0/1/80, FJ = 0/0/0.
0:00:16.340 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:16.341 [Reporter]:             Append | 5099841 |   175 |   106 |   135 |   314 |  1481 |  1530
```
