### ISSUE TITLE
Need a way to see the used storage space of a stream

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#1715]
**Problem description**
There is no way to see how much data is currently stored in a stream.

**Problem location**
REST API

**Suggestions for an improvement**
Add some sort of currently used storage space information to the REST API when retrieving streams.  Getting the used storage space at a scope level as well would be a bonus.

As another bonus, it might be useful to see this as a metric as well, but isn't as important to just seeing the current used storage space.

**Comment by shiveshr** [comment]
This can be done via a controller api. Controller stores sizes for sealed segments for a stream. And for active segments, it can query segment store to get the current offsets. 
This way we can compute the size of the stream overall.
