### ISSUE TITLE
Possible OOM when BookKeeper is backed up

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1716]
**Problem description**
1. Every write we send to BookKeeper is encoded in a `DataFrame`, which always wraps a 1MB byte array, regardless of whether we want to write 1 byte or 1 MB (that's because we don't know at the beginning of the allocation how much we'll end up needing). As a recap, the `OperationProcessor` serializes all operations into DataFrames, but we never know how many more ops are waiting or how long they are, so we can't estimate how much we'll need.
2. We queue up a number of such writes to BK in each container. In busy times, this can be as high as 10 * degree of parallelism.
3. After the write to BK completes, we release the buffer (and the GC will eventually reclaim it) 
4. Since we may have multiple SegmentContainers per host, we may end up having a lot of 1MB buffers around, which may exceed the maximum heap size, causing OOMs.

**Problem location**
SegmentStore->SegmentContainer-> sub-components

**Suggestions for an improvement**
A few ideas:
1. Use a buffer pool and block (async) when full, until one is available. Release when done.
2. Instead of allocating a singe 1MB block, allocate progressively (maybe 10KB blocks) and stitch them together if needing more. Stitching does not require copying every time. Then combine into a single byte array when writing to BookKeeper - since BK's API only accepts byte arrays.
3. Keep allocating 1MB buffers, but reuse those end-portions that have not been filled yet. So, a 1MB buffer may hold multiple DataFrames, but once we reach the end of that buffer, a frame may not be split across multiple buffers. As such, no copying of data is required, ever.

**Comment by arvindkandhare** [comment]
This issue may be root cause for the OOM observed in #1714. Still keeping that issue separate from this till we confidently conclude this is the case.

**Comment by tkaitchuck** [comment]
If we are going to go the Pool route. I suggest we simply use the pool already implemented in Netty as we depend on the library anyway.
