### ISSUE TITLE
Multiple controllers send differing segment count/splits/merges metrics on the same stream

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#1761]
**Problem description**

On clusters with two Pravega controller instances, if two controllers are reporting `segments_count`, `segment_splits`, and `segment_merges` metrics on the same stream, the numbers being reported differ between the controllers.

One of two controllers would report stale metrics as of the moment when the stream was created (initial number of segments for `segments_count`, and zeros for `segment_splits` and `segment_merges`).
The second controller reports the actual number of active segments in `segments_count`, but much bigger numbers than the actual metrics for `segment_splits` and `segment_merges` would have to be.

###### Example:
One controller is reporting 
```
53e392ef-27ad-4b8b-be0b-198a14b7b7b1-0004.pravega_controller__b9051a32-5ff8-4083-a343-702f4ae1a34a.66cd021c-23da-46eb-88a3-d64166d5c1ab.pravega.controller.segments_count.hulk.smallScale.Gauge:1|g
```
The other controller is reporting
```
53e392ef-27ad-4b8b-be0b-198a14b7b7b1-0004.pravega_controller__9ea16bb9-05b6-424e-9066-e799a51b9134.5810a308-b5f6-4adf-ac65-b6a680cb7fbb.pravega.controller.segments_count.hulk.hulk.smallScale.Gauge:15|g
```
*(the correct number of active segments is 15, as confirmed by `scaling-events` API)*

###### Another example:
One controller is reporting 
```
c41e8d11-b058-4bf1-883a-829185d8134d-0004.pravega_controller__b5eed754-a70a-4200-8299-1c570b57902b.67f3abd2-4365-45bf-9bc9-3b9184b5330c.pravega.controller.segment_splits.hulk.smallScale.Counter:0|g
```
The other controller is reporting
```
c41e8d11-b058-4bf1-883a-829185d8134d-0004.pravega_controller__2a23b6bb-cca4-4543-a432-991d8fa62b6d.48d93a29-27f7-4257-9711-c4c5f1fa1c09.pravega.controller.segment_splits.hulk.smallScale.Counter:2453|g
``` 
*(the correct number would be below 400, as the total number of ever created segments is less than 400 for the stream)*

If only one of the two controllers is reporting the metrics for a given stream, then all the three metrics are reported correctly.

**Problem location**
Pravega controller - multiple instances

**Suggestions for an improvement**
Multiple controllers should report identical metrics;
they should report correct counters for `segment_splits` and `segment_merges`.

**Comment by shiveshr** [comment]
Fixing this may require some rework of how we manage metrics and distribute work across controller instances. 
It has manifested with create and scale operations but could happen with other metrics too if different update operation of same type are performed across different controller instances.

**Comment by jkhalack** [comment]
This should probably be closed as the same information is now available through `scaling-events` API (https://github.com/pravega/pravega/pull/2244).

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiple controllers send differing segment count/splits/merges metrics on the same stream](https://trello.com/c/XMwv7Tzk/58-multiple-controllers-send-differing-segment-count-splits-merges-metrics-on-the-same-stream)

**Comment by shiveshr** [comment]
@kevinhan88 @jkhalack i see several merges happen against this issue. can we close this ?

**Comment by jkhalack** [comment]
@shiveshr #3195 is still open.

**Comment by kevinhan88** [comment]
@shiveshr - we changed the active segments from counter to gauge as active segments is already an aggregated value. This change should have solved some confusions on the metrics dashboard. 
But the original problem has not been nailed down. I've tried one implementation as https://github.com/pravega/pravega/pull/3995/commits/99242ef1d5d5c7db41178e06826297e7be0b893c but it turned out too heavy for a metric.

Then I started a thread in pravega-engineering channel to discuss a different approach to report active segments. The basic idea is, instead controller report aggregated active segments, each individual segmentstore could report "1" whenever it's reading/writing a segment. The metrics backend will do the aggregation in order to get the total of active segments.
This is slightly different to the strict definition of "active segments", but is probably what operations really want.

I just assign the issue to myself, in order to continue the discussion and the implementation.

**Comment by kevinhan88** [comment]
I left comments in #3195, just copy it here for convenience:

This situation of this issue:
1. #3995 has partially solved the problem.
2. It's been proven this approach is not practical - controller report active segments - not only the operation to aggregate active segments is too expensive for a metric, but also the synchronization of the aggregation among multiple controller is too expensive for a metric. This is the main reason why this PR got stuck for such a long time, and it's unlikely this PR will be merged in future.
3. I've talked with Andrei briefly and also mentioned it to the team a couple of times - instead we can let segmentstore to report the number of segments being read/written, and let the metrics dashboard to aggregate the total number of CURRENTLY being accessed segments. This dynamic number plus the real 'activeSegments' retrieved from API will give the whole picture to operation, in a lightweight way.

We can close this PR but leave #1761 open. I'll bring up another round of discussion for the approach above. If an agreement can be reached, then a new PR will be created.
