### ISSUE TITLE
Use assertThrows in NameUtilsTest

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1762]
**Problem description**
In the unit tests here:

https://github.com/pravega/pravega/blob/master/shared/src/test/java/io/pravega/shared/NameUtilsTest.java

We are using a try-catch block to spot expected exceptions. We should instead use `assertThrows` to be consistent with how we are doing in other tests:

https://github.com/pravega/pravega/blob/master/test/testcommon/src/main/java/io/pravega/test/common/AssertExtensions.java

**Problem location**
`NameUtilsTest`.

**Suggestions for an improvement**
Use `assertThrows`.

**Comment by ZhengyangChang** [comment]
There are some other test case using try-catch block that assert failure on unexpected exceptions. 
Since the test case will fail on exception automatically, is it better to remove the try-catch blocks for consistency?
