### ISSUE TITLE
Controller Metrics for Containers

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1768]
**Problem description**
It would be nice to have some Container-specific metrics that can aid us in figuring out where containers are living (which hosts). Ideally this would be something that can help us answer these questions:
- Where is container X located? (which host)
- How many containers on host Y?
- How many failovers per container per time unit?
- Possibly others.

**Problem location**
Controller.

**Suggestions for an improvement**
Add metrics or some other queryable interface

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pravega Metrics are being reported as Histograms](https://trello.com/c/OEk8u3Vu/33-new-pravega-metrics-are-being-reported-as-histograms)

**Comment by RaulGracia** [comment]
Closed via #3117.
