### ISSUE TITLE
Revisit the thread pool size in failover tests

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1784]
**Problem description**
As per the comment of @andreipaduroiu:

https://github.com/pravega/pravega/pull/1766#discussion_r134785098

it seems unnecessary to have a thread per reader/writer as we are setting the thread pool to have in the failover system tests. This issue is to revisit it and make sure we us the minimum viable.

**Problem location**
System tests.

**Suggestions for an improvement**
Analysis of the minimum thread pool size for those tests.

**Comment by shrids** [comment]
Closing this as per comment https://github.com/pravega/pravega/pull/1766#discussion_r135440210
