### ISSUE TITLE
Rolling Transactions

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#179]
Allow support for scaling streams that perpetually have transactions open by making scale up staged:
1. Create the new segments.
2. New transactions start on the new segments but cannot commit yet.
3. Wait for old transactions to complete or timeout.
4. Close old segments.
5. Allow transactions on new segments to commit.

Because we don't want to have commit return an error we need to create a new state for a transaction where it is waiting to be committed (But guaranteed to eventually succeed)

**Comment by shiveshr** [comment]
Subtasks
#2324 Restructure background processing of commitTxn and scale (Controller)
#2325 Transaction discovery across epochs (Controller)
#2439 Generalize transaction segments to be first class segments (Segment Store)
#2442 Allow transactions against old epochs to be active (Controller)
#2469 Client changes
#2511 Update Controller to handle new segment naming scheme
