### ISSUE TITLE
System test to exercise creation, deletion, and sealing of scopes and streams

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1850]
**Problem description**
We need to exercise regularly the creation, deletion, and sealing of scopes and streams. 

**Problem location**
Tests.

**Suggestions for an improvement**
Add a system test to do it.

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [System test to exercise creation, deletion, and sealing of scopes and streams](https://trello.com/c/YJNsoIfT/44-system-test-to-exercise-creation-deletion-and-sealing-of-scopes-and-streams)
