### ISSUE TITLE
Implement event processing in Event processors using visitor pattern

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1874]
**Problem description**
Visitor pattern is a more clean and elegant way of expressing processing ability of an event and creates a neat abstraction. 
So move all event processor processing to be performed as visitor pattern. 

**Problem location**
Controller Event processor

**Suggestions for an improvement**
Use visitor pattern.

**Comment by andreipaduroiu** [comment]
Isn't this the same as #1815 ?

**Comment by shrids** [comment]
Closed with PR: #1915
