### ISSUE TITLE
Implement concat merge operator for RocksDB

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1884]
**Problem description**
After #1607 is completed. We should write a RocksDB merge operator so that we can append to the existing entries for a segment without having to write new ones. This should reduce the number of keys we need to keep track of, and reduce the Java heap use.

**Problem location**
RocksDBCache

**Suggestions for an improvement**
If we implement concatenate, when an append comes in and we already have data for the preceding offset, it can simply be concatenated onto it.

**Comment by andreipaduroiu** [comment]
This would involve writing native C/C++ code and integrating it into our build process. This is a cumbersome process with little perceived benefits. So far we have experienced no performance problems with RocksDB, so I doubt this will improve anything by much.
