### ISSUE TITLE
Log the config at startup

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1885]
**Problem description**
There are several config parameters, it would be useful for debugging if these were printed in the log on startup.

**Problem location**
Client, Server, and Controller.

**Suggestions for an improvement**
When a component is initialized with a config, we should log it at info level.

**Comment by andreipaduroiu** [comment]
The SegmentStore already does this. It logs non-default config values (retrieved via config file, system props or env vars) as a `debug` log event.

See `ServiceStarter.java:main()`

**Comment by shrids** [comment]
Controller does this @ https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/util/Config.java#L65 as a `debug` log event.
