### ISSUE TITLE
Create a build target for specialized serializes

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1887]
**Problem description**
Currently we only provide JavaSerializer and ByteArraySerizlizer because we don't want force a dependency on our user's applications. We should however support other formats, as well as wrapping serializes that do things like compression. 

**Problem location**
Client build

**Suggestions for an improvement**
We should create a new set of gradel build targets and maven artifacts for specialized serializers that rely on external dependencies.

**Comment by EronWright** [comment]
A few alternative solutions:
1. define all the serializers in a single module with _optional dependencies_ ([ref](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html), [ref](https://blog.gradle.org/introducing-compile-only-dependencies)).  In that way, the application must re-declare the dependencies that it actually intends to use.
2. create a module for each serializer (`pravega-client-avro`, `pravega-client-protobuf`, etc).

**Comment by tkaitchuck** [comment]
Yes, number 2 is the suggestion. 
With regards to 1339, no we aren't going to do that. So if in your above example an app declared a dependency on pravega-client-avro you would have an indirect dependency on avro, and we would not hide that fact.

**Comment by fpj** [comment]
(from a conversation with @tkaitchuck)

With respect to repository, should we have it in the pravega repository or in a separate serializers repository (e.g., `pravega/serializers`).

**Comment by tkaitchuck** [comment]
Yes. If we had a pravega/serializers package it could have it's own gradle build with a separate target for each different serializer a user might want to use. So each would have it's own artifact. This would allow applications to depend on just those serializers they want without pulling any unwanted dependencies into their application.

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support other serializers (e.g., JSON, Avro)](https://trello.com/c/jCWinp31/17-support-other-serializers-eg-json-avro)
