### ISSUE TITLE
Move reading from an event pointer to it's own interface

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1890]
**Problem description**
Right now `EventStreamReader.read(EventPointer pointer)` uses an existing reader to fetch a previously read event from a stream. However given that it does not have to come from the same reader that read the event, or even the same readerGroup, this placement is arbitrary. Instead there should be a different top level API to read events out of order.

**Problem location**
EventStreamReader

**Suggestions for an improvement**
Create a new class that supports reading events from a stream via EventPointers.

**Comment by tkaitchuck** [comment]
We could also have an API to take a list of pointers. This way they could be sorted and the read somewhat optimized.

**Comment by stephen-lazarionok** [comment]
Can this issue be assigned to me?
