### ISSUE TITLE
Provide a hint to the segment store that a particular read should warm the cache

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1891]
**Problem description**
For some API calls, including #1890, it would be useful to tell the Segment Store that the read is coming in order and should ensure that subsequent reads are already "warmed up".

**Problem location**
SegmentStore

**Suggestions for an improvement**
One idea would be for the `ReadRequest` wire command to carry an int field which tells the Segment Store how much data to pre-cache as a result of executing the current read. This is optional, and should be set to 0 if random reads are expected.
- Random reads are generally for Table Segments or when we do arbitrary-location stream reads (i.e., by an external Event Pointer database).

**Comment by tkaitchuck** [comment]
Another use for this api would be for #1886

**Comment by andreipaduroiu** [comment]
This could be done by adding a `ReadOptions` argument to the `StreamSegmentStore.read` call which has (to begin with) a property named `cacheResult==true|false`. This would be propagated down and would cause no cache inserts or extra reads beyond the specified max length.

**Comment by tkaitchuck** [comment]
Closing in favor of #6177
