### ISSUE TITLE
How to handle ReinitializationRequiredException

### ISSUE THREAD

**Issue by florianschmidt1994** [pravega/pravega#1894]
**Problem description**
Calls to `eventStreamReader.readNextEvent` require handling a `ReinitializationRequiredException`, but it is not clear how to handle this exception correctly. The examples either:

- print a Stacktrace and ignore it
- add an Exception to the method signature

From that it is not clear how to actually handle such a required reinitialization

**Problem location**
pravega-samples, pravega-client, flink-connectors

**Suggestions for an improvement**
Add documentation / samples on why this exception occurs and how to best handle it

**Comment by tkaitchuck** [comment]
For what it's worth, the answer is to close the reader and re-create it.
