### ISSUE TITLE
Intermittent build failures in `BookKeeperLogTests > testAppendTransientZooKeeperFailure`

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#1900]
**Problem description**
io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests > testAppendTransientZooKeeperFailure FAILED
    java.lang.AssertionError: Unexpected sequence number. expected:<51539607561> but was:<55834574848>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at 

**Problem location**
Unittests for `BookKeeperLogTests > testAppendTransientZooKeeperFailure`
**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
Preliminary debugging indicates that writes to BookKeeper are completed with RC 0 (success) from BK, however, upon re-reading the Log, some entries are missing. 

How to repro: run the test `testAppendTransientZooKeeperFailure` in a loop, making sure `tearDown/setup` is invoked at the end. After a few iterations (could be as many as 50), the failure will happen.

**Comment by andreipaduroiu** [comment]
This is due to opening ledgers with no recovery during reads. That is done for a good reason (so that it doesn't fence itself). The fix for this is to figure out how to properly recover ledgers upon reading without interfering with the current (write) operation of the log.
