### ISSUE TITLE
Faq : Is Pravega similar to Kafka ? Needs refinement

### ISSUE THREAD

**Issue by derek45** [pravega/pravega#1903]
Description:
Is Pravega similiar to systems such as Kafka and Kinesis?  
Answer to this question is kind of confusing. Doesn't answer precisely.

Location:
Wiki: FAQ 

Answer needs to be refined , so that it addresses the question and doesn't confuse further.

**Comment by shafqatevo** [comment]
The answer is still incomplete and confusing. In general, more clarity is required for people looking to use Pravega as a replacement for Kafka for use cases like messaging, event sourcing, etc.
