### ISSUE TITLE
Test failure testAppendTransientZooKeeperFailure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1904]
**Problem description**
We have observed a couple of failures of this test case:

```
io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests.testAppendTransientZooKeeperFailure
```

I´m attaching the corresponding logs.

[testAppendTransientZooKeeperFailure.txt](https://github.com/pravega/pravega/files/1315697/testAppendTransientZooKeeperFailure.txt)

**Problem location**
BookKeeperLog failure tests.

**Suggestions for an improvement**
Debug.

**Comment by andreipaduroiu** [comment]
Duplicate of #1900.
