### ISSUE TITLE
Stream termination

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1916]
**Problem description**
Say we want to process all the data of a sealed stream and notify the readers that the data has been entirely read. If the stream is sealed, then the last segments of the stream are sealed and they have no successors. This feature is useful to process the stream data with a batch job.

The previous description assumes a sealed stream, but it might be possible in a follow-up extension to relax this assumption and consider, for example, a subset containing only sealed segments, essentially discarding only the open segments.

**Problem location**
Stream reader, client.

**Suggestions for an improvement**
Enable a notification via the reader API that indicates the end of the stream, initially, for a sealed stream. To make sure that all segments are entirely read in the presence of reader crashes, we need agreement on the end of each segment across all segments. We need to implement coordination using the state synchronizer.

**Comment by tkaitchuck** [comment]
The most minimal way to do this is to modify our existing API to allow a reader to return some special marker or exception when the end of a stream is reached. The reader would know it reached this point when a bit is set in the ReaderGroupState and all the segments are exhausted. To set the bit we would need to modify the reply to getSuccessors on the controller to indicate if a segment is at the end of a stream an hence has no successors.

**Comment by fpj** [comment]
@tkaitchuck Ok, and internally, we will need to implement a barrier-like abstraction where each reader joins the barrier upon hitting the end of all its assigned segments and crosses the barrier once all readers have joined the barrier. Upon joining the termination barrier, a reader adds itself to a set in the `ReaderGroupState` and termination is declared once the set contains the id of all readers. Also, I'm assuming that a reader declares that it has reached the end of its assigned segments once it tries to get successors for them and getting nothing from the controller.

does it sound right?

**Comment by shrids** [comment]
@tkaitchuck @fpj My current understanding is as follows, is it right ?

The `ReaderGroupStateManager `does the following on receiving a `SegmentSealed `.
a. Invoke getSuccessors(segmentCompleted ) on controller.
b. Update the ReaderGroupState :
    i) remove segmentCompleted from `assigned` mapping.
    ii) Update futureSegments with the newer successors.

Now, in case of  a sealed stream on reaching the end of stream the readers receive a `SegmentSealed `and the readers perform `Step a` mentioned above. The controller returns an empty list. After executing `step b `the `ReaderGroupState.assignedSegments `will be empty for the readers and the `ReaderGroupState.futuresegments `will also be empty.

Hence to detect that a stream has terminated the above two conditions  (assignedSegments is empty) and (futureSegments is empty) are enough to indicate that the stream has terminated.

**Comment by tkaitchuck** [comment]
That condition is sufficient to determine that all streams the reader group is subscribed to have terminated.
