### ISSUE TITLE
Remove transaction pinging from the API

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1919]
**Problem description**
Transaction pinging shouldn't be a top level api that applications need to code to. If we want keep alive for a transaction it should be performed internal to the client library. 

**Problem location**
EventStreamWriter.beginTransaction()

**Suggestions for an improvement**
Remove the parameter, and bring the logic into the implementation.

- [x] Remove the API call (PR #1922)
- [ ] Add internal client logic for pinging (Issue #863 )

**Comment by shiveshr** [comment]
once we implement rolling transaction, we will not have require short duration bounds on timeouts. This will make transaction pings irrelevant and can be rid of.
