### ISSUE TITLE
Stream concatenation

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1927]
**Problem description**
We need an API call and the internal machinery to enable the concatenation of two streams. For example, say that I have a stream A with one segment S1 and another stream B with segment S2. If I request that A and B are merged via a call to:

```
concatStreams(String source, String target)
```

such as `concatStreams("B", "A");`, then the result should be a new stream such that:

- S2 is sealed
- The head of the new stream becomes the head of S2
- The head of S1 becomes the first offset after the last offset of S2

It is to be decided whether we want the the new concatenated stream to be a stream with a new name or to be called `A`, the name of the target. It feels like keeping the name of the target is a better idea.

One of the use cases for this is compaction. With stream concatenation, we can do the following:
- Read the data of a given stream `C` from head to a specific position `p` (this is the portion of the stream that we want to compact)
- Write the compacted data to a new stream `C'`
- Trim `C` up to `p` and merge `C'` back onto `C`

Ideally, the last step is "atomic" so that we don't make it complex on the application side to cope with crashes. We could have, for example, a controller task that trims and merges.

**Problem location**
Client, Controller.

**Suggestions for an improvement**
Implement concatenation.

**Comment by tkaitchuck** [comment]
Combined with truncation this could be fairly powerful. It would allow for taking a cutpoint and replacing the data before that point with a different set of segments. My intuition would be that we don't want to make this into a new stream, but rather as a metadata operation on and existing one. IE: Insert the following sealed segments into the head of this stream. Sortof the reverse of a transaction which puts new ones at the tail.
