### ISSUE TITLE
Typo in WireCommands

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1934]
**Problem description**
There is a typo in `WireCommands`:

```
public static final int OLDEST_COMPATABLE_VERSION = 1;
```

**Problem location**
`io.pravega.shared.protocol.netty.WireCommands` 

**Suggestions for an improvement**
Replace it with:

```
public static final int OLDEST_COMPATIBLE_VERSION = 1;
```

**Comment by tkaitchuck** [comment]
This has been fixed
