### ISSUE TITLE
Compact event pointers.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1941]
**Problem description**
Currently due to Java serialization Event pointers are large. These could be written as a much smaller, and human readable string of the format:
`scope/stream/segmentNumber:offset`
This would be much smaller than they are now, would make sense in logs, and are easily compressible. 

**Problem location**
EventPointerImpl

**Suggestions for an improvement**
Use the externalizable interface to manually serialize them.

**Comment by fpj** [comment]
Resolved.
