### ISSUE TITLE
PDP 22: Apache BookKeeper for Tier 2

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1949]
**Problem description**
Pravega Design Proposal to add Apache BookKeeper as an option for Tier 2.

See https://github.com/pravega/pravega/wiki/PDP-22:-BK-based-Storage-(Tier-2)-for-Pravega

**Problem location**
Segment store, Tier 2.

**Suggestions for an improvement**
See the PDP for detail.

**Comment by andreipaduroiu** [comment]
> Shall we improve the existing BookkeeperLog to implement a generic storage OR implement a different storage ledger for tier-2 purpose.

**Comment by andreipaduroiu** [comment]
> We need to build an algorithm to map offset to entry-id.

**Comment by arvindkandhare** [comment]
> I would strongly prefer keeping them separate. BookKeeperLog is (and should be) optimized for DurableDataLog and writing to a log. Storage has vastly different requirements and access patterns.

Thanks for the inputs. I am leaning in the same direction as well. Will wait for a couple of days for other inputs on this and then close having independent implementation as a plan.

**Comment by tkaitchuck** [comment]
In terms of tracking offsets, we could use EntryId as the offset. It is already a long, and BK supports using it to position reads.

**Comment by eolivelli** [comment]
I am very interested in this feature, as it will allow to deploy Pravega without HDFS or NFS.
I have already Bookies but I am using Kafka for "event streams"; Using BK as Storage for Pravega will make me able to switch from using Kafka to Pravega, and dropping the Kafka servers in favor of more "light" Pravega daemons.

Maybe I can give some help on this topic.
I am recently working at a project which will use BookKeeper as Binary Large Object Storage, so I am working on improvements on BK in that direction (see https://cwiki.apache.org/confluence/display/BOOKKEEPER/BP-14+Relax+durability)

Some ideas:
Using createLedgerAdv will let you have full control about entryIds and even on ledgerIds. But there are a few constrains:
- you cannot create gaps in the sequence of entry ids
- the write for entry id X won't be acknowledged until every entry from 0 to X-1 has been acknowledged even if your are sending entries in sparse order

We have also to take into account that an entry as maximum size (by default 1MB) so every chunk must be split into smaller chunks.
if you can pre-calculate the size of the chunk (and this is the case), you can pre-allocate the range of entry ids which will cover the chunk, so you can store as coordinates of the chunk the triple (ledgerid,first_entry_id,last_entry_id)

BookKeeper 4.6 will give the ability to more control when data is fsynch'd to disk and this feature will open the usage of BookKeeper to receive streams of data with better performances.

b.q. Where is the best place to store metadata ? in ZooKeeper ?

Hope that helps

**Comment by arvindkandhare** [comment]
@eolivelli thanks a lot for the inputs. 
Will incorporate the `createLedgerAdv` in the PDP. I think that works well for us.

About control when data is flushed to disk: I see that it can be really useful. For large writes we can write multiple 1 MB chunks and then flush these in one go. Looking forward to using the feature when it becomes available.

**Comment by fpj** [comment]
> Truncate (optional currently) This can be a metadata operation.

The only way I see to implement this is to roll the ledger and delete the old, disposed ledgers. Of course, we can re-write ledgers, but it isn't clear that it is desirable.

**Comment by eolivelli** [comment]
@arvindkandhare  I can't find "truncate" in https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/Storage.java , https://github.com/pravega/pravega/blob/master/segmentstore/storage/src/main/java/io/pravega/segmentstore/storage/ReadOnlyStorage.java 

could you point me to the truncate operation ?

**Comment by eolivelli** [comment]
Any news on this topic?

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BK based Tier-2 implementation](https://trello.com/c/Uj3hUjhP/18-bk-based-tier-2-implementation)

**Comment by eolivelli** [comment]
@andreipaduroiu why are you closing this issue, has the feature been delivered?
