### ISSUE TITLE
General solution for versioned, binary deserialization

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1956]
**Problem description**
We need a more general solution that can simplify the deserialization of binary data when multiple versions are involved. This solution should provide a way for the data to be both backwards compatible and forward compatible.
    - **Backward compatible**. Data written with code at Version X can be read by code at version Y > X.
    - **Forward compatible**. Data written with code at Version X can be read by code at version Y < X.
        - Forward compatibility is needed if we need to roll back an upgrade or during rolling upgrades.

**Other options considered**
1. Existing binary serialization (like the one we have in the SegmentStore). 
    - It has a version number that it writes out at the beginning of each serialization and based on that it chooses a deserializer.
    - This is pretty rudimentary, but it is not forward compatible. The only way to do forward compatibility with this scheme is to re-write the data in multiple formats, resulting in a lot of data duplication.
2. XML or JSON. 
    - These are both good candidates since they have structured name-value pairs. 
    - However, they are very verbose and introduce a lot of overhead, both in terms of data and in terms of processing.
3. JavaSerializer
    - This can produce a binary serialization, however there is very little (if any) support for versioning. We also do not have control over how or what parts of the data are serialized.

**Suggestions for an improvement**
Currently, a change in serialization version gives us the freedom to drop, add, replace and rearrange fields as needed. It's as simple as writing a new set of code that knows how to read each version. But this is a dead end when it comes to forward compatibility.

I propose using the concept of **Versions** and **Revisions**. 
- Versions start at 0, and are incremented when needed (see below)
- A version has multiple revisions, starting at 0 and incremented when needed.
- Data formats are compatible within a version but not compatible (in either direction) for different versions (so data with version 1 will not be able to be read with a deserializer that can only read version 2)
- Data formats are both backwards and forward compatible within a version (between different revisions).
- Within each Version
    - Revision 0 defines the base (initial format) for that version.
    - Revision R+1 is an incremental change to Revision R. It does not replace it. 
    - Once a particular Version-Revision has been published as part of a Pravega release, its data format is set in stone. It cannot be modified.
    - Code that is compatible with Revision X will write data in all revisions (incrementally) Y <= X. Data is not duplicated for each revision, rather it is written incrementally.
    - Code that is compatible with Revision X will read all data up to revision X and skip over any data for revision Y > X. This ensures forward compatibility.
- Lifecycle
    - When we accumulate enough revisions to make the code messy (or for any other reason), we can introduce a new Version, which would start with a clean slate.
    - Revisions can be introduced on the fly, without any additional prerequisite work.
    - Versions need to be planned out. First we need a release which supports reading the version, and only in the next release we'll be able to write at that version.
    - This only describes the overall framework. We will need additional guidelines for developers as to how to retire a field, change its type or add a new field. That will be treated separately from this.  

**Example**:
- The notation below for Versions & Revisions is `V.R` (1.0: Version 1, Revision 0, 1.3: Version 1, Revision 3, etc.)
- Suppose we have 1.0, 1.1, 1.2, 1.3, 2.0 and 2.1. 
    - We have made 3 revisions to Version 1. 
    - At revision 1.3, we decided that we made enough changes to warrant a new version. So we introduce a new format (Version2) and read support for it. It contains the same information as in revision 1.3, but in a new format.
    - Initial deployment: 1.0 (base format
    - Upgrade 1: Revision 1.1
        - 1.0 and 1.1 run concurrently
        - New code reads 1.0 & 1.1 and writes 1.1
        - Old code reads and writes 1.0.
    - Upgrade 2: Revision 1.2  
        - 1.0, 1.1 and 1.2 run concurrently
        - New code reads 1.0 -> 1.2 and writes 1.0->1.2, old code reads and writes 1.0 -> 1.1
    - Upgrade 3: Revisions 1.3 & 2.0 
        - 1.0 -> 1.3 run concurrently
        - New code reads 1.0 -> 1.3 & 2.0 and writes 1.0->1.3
        - Old code reads and writes 1.2.
    - Upgrade 4: Revision 2.1       
        - 1.x/2.0 and 2.1 run concurrently. 
        - New code reads reads 1.x, 2.0, 2.1 and writes 2.0->2.1
        - Old code reads 1.3 & 2.0 and writes 1.3
    - Subsequent upgrade: we remove support for version 1 altogether.

**Benefits**:
- Compact, version tolerant, binary serialization
- We don't have to proactively (i.e., 6-12 months ahead) introduce serialization support for a new field. We increment a revision and add the field.
- We can cleanup the code periodically. This is done by incrementing the Version, which does require some long-term planning (6-12 months or otherwise a few releases)

**Binary Format**:
- `SerializerVersion|Version|RevisionCount|Revision1|Revision2|...|RevisionN`
    - `|` is not part of the format; it's for illustration purposes only.
    - SerializerVersion (1 byte): Internal to the Serializer code; this allows us to change the actual binary data layout.
    - Version (1 byte): Caller-supplied data version (1 or 2 in the example above)
    - RevisionCount (1 byte): How many revisions are serialized in this serialization
    - RevisionX: data for each revision, in order. 0<=X<RevisionCount. Format: `RevisionId|Data`
        - RevisionId (1 byte): id of the revision.
        - Data: caller-serialized data for this revision.
- Example
    - `0|0|2|0|a=1,b=2|1|c=3`
        - SerializerVersion: 0, DataVersion: 0, 2 Revisions, Revision 0: "a=1,b=2", Revision 1: "c=3"
        - This is the result of a revision increment where we added a new field `c`
        - Code that only knows about 0.0 will read `a=1,b=2`.
        - Code that knows about 0.1 will read `a=1,b=2,c=3`.
    - `0|1|1|0|a=1,b=2,c=3`
        - SerializerVersion: 0, DataVersion: 1, 1 Revision, Revision 0: "a=1,b=2,c=3"
        - Code that doesn't know about this Version will not work.
        - Code that does know about it will be able to read `a=1,b=2,c=3`

**Comment by fpj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design binary serialization](https://trello.com/c/TiEN01jT/5-design-binary-serialization)

**Comment by andreipaduroiu** [comment]
Sample usage (this is based on a prototype I put together - it does not include the actual code that makes this possible; it's just how we'd use it in practice):

```java
private static final MySerializer s = new MySerializer();
private static final MyDeserializer d = new MyDeserializer(MyClass::builder);
public static void main(String[] args) {
    val mc1 = new MyClass("myname", (long) Integer.MAX_VALUE + 123, 456);
    @Cleanup
     stream = new ByteArrayOutputStream();
    s.serialize(mc1, stream);
    val mc2 = d.deserialize(new ByteArrayInputStream(stream.toByteArray()))
}

    //Data class - we use Lombok's @Builder and we force that builder to implement our special interface "ClassBuilder", which defines the build() method - this is needed for deserialization.
    @Data
    @Builder
    private static class MyClass {
        private final String name;
        private final long id;
        private final long tick;

        static class MyClassBuilder implements ClassBuilder<MyClass> {
        }
    }

// Serializer class. Extend from the base "Serializer", define your current DataVersion, and attach your revision-based serializers.
 private static class MySerializer extends Serializer<MyClass> {
        @Override
        protected final byte version() {
            return 0;
        }
        @Override
        protected void initialize() {
            revision(0, this::serialize0);
            revision(1, this::serialize1);
            revision(2, this::serialize2);
        }
        // Revision 0 has an Int Id and a String Name.
        private void serialize0(MyClass object, DataOutputStream stream) throws IOException {
            stream.writeInt((int) object.getId());
            stream.writeUTF(object.getName());
        }
        // In Revision 1 we change Id to Long. Notice how we do not touch Revision 0 - that stays put for older code to use.
        private void serialize1(MyClass object, DataOutputStream stream) throws IOException {
            stream.writeLong(object.getId());
        }
        // In Revision 2 we add a Long Tick to the format. Notice how we do not re-write the other fields.
        private void serialize2(MyClass object, DataOutputStream stream) throws IOException {
            stream.writeLong(object.getTick());
        }
    }

// Deserializer: we need a Builder (from Lombok, or custom-made)
private static class MyDeserializer extends Deserializer<MyClass, MyClass.MyClassBuilder> {
        MyDeserializer() {
            super(MyClass::builder);
        }
        // This is the Deserializer for code that knows about 0.x and 1.0. Previous code would not have 1.0 or higher revisions for Version 0.
        @Override
        protected void initialize() {
            version(0).revision(0, this::version0Revision0)
                      .revision(1, this::version0Revision1)
                      .revision(2, this::version0Revision2);
            version(1).revision(0, this::version1Revision0);
        }
        // 0.0 is the base. Int Id, String Name. Note how we keep reading an Int from the Stream so we can advance its position.
        private void version0Revision0(DataInputStream s, MyClass.MyClassBuilder b) throws IOException {
            b.id(s.readInt()); 
            b.name(s.readUTF());
        }
        // 0.1 : we re-read the Id because now it's a Long.
        private void version0Revision1(DataInputStream s, MyClass.MyClassBuilder b) throws IOException {
            b.id(s.readLong());
        }
        // 0.2: we added Long Tick.
        private void version0Revision2(DataInputStream s, MyClass.MyClassBuilder b) throws IOException {
            b.tick(s.readLong());
        }
        // 1.0: Clean slate; entirely new format.
        private void version1Revision0(DataInputStream s, MyClass.MyClassBuilder b) throws IOException {
            b.id(s.readLong());
            b.name(s.readUTF());
            b.tick(s.readLong());
        }
    }
```

**Comment by tkaitchuck** [comment]
There is a problem with nesting. I had the following 
```
    @Data
    @Builder
    private static class MyOtherClass {
        private final String name;
        private final MyClass myClass;

        static class MyOtherClassBuilder implements ClassBuilder<MyOtherClass> {
        }
    }
```
It would not be possible to deserialize it correctly. While in the serializer for MyOtherClass it could invoke the serializer for MyClass it does not record the length. So when deserializing MyOtherClass could invoke the deserializers for 0.0 and 0.1 but it there was data for 0.2 it can't skip over it, because it doesn't know how long it is. So the deserialization of MyOtherClass cannot proceed.

**Comment by andreipaduroiu** [comment]
@tkaitchuck Ah good point. So both `MyOtherClass` and `MyClass` have their own builders and serializers and deserializers. When we serialize/deserialize an instance of `MyOtherClass`, we serialize MyClass on the same OutputStream we serialize it and deserialize it as well.

Ex:

Serializing
```
private void serialize0(MyOtherClass object, DataOutputStream stream) throws IOException {
            myOtherClassSerializer.serialize(object.myClass, stream);
            stream.writeUTF(object.getSomeValue());
        }
```
Deserializing:
```
private void version0Revision0(DataInputStream s, MyOtherClassClass.MyOtherClassBuilder b) throws IOException {
            b.myOtherClass(myOtherClassDeserializer.deserialize(s));
            b.someOtherValue(s.readUTF());
        }
```

**Comment by andreipaduroiu** [comment]
@tkaitchuck I took your feedback into consideration. I've updated the format to include length and based on where we serialize it will either require it or auto-calculate it.

I've also added support for collections and maps.

**Comment by shiveshr** [comment]
Couple of questions/observations:
`Revisions` 
Question: Can we skip revisions and serialize say 0.1 followed by 0.3 skipping 0.2 in the process? 
If we dont foresee such scenarios, then revision putting revision numbers in serialized blobs seems redundant. We may just need to maintain highest revision number and that will suffice to tell the reader how many fields it can parse. 
This is because as long as we are only adding new fields and never removing/replacing fields across revisions, the revision is implicit and the serialized blob forward and backward compatible. 

Secondly, instead of writing boiler plate ObjectFormat classes per Serializable object we may use annotations to the same effect whereby reducing boilerplate code further.

Say something like:
`
    public class MySerializableClass implements MySerializable {
        @serialize(revision = 1, type = i32, default=Integer.MIN)
        private final int segmentNumber;
        @serialize(revision = 1, type = i64)
        private final long startTime;
        @serialize(revision = 1, type = floating)
        private final double routingKeyStart;
        @serialize(revision = 1, type = floating)
        private final double routingKeyEnd;
        @serialize(revision = 2, type = MyClass.class)   
        private final MyClass myClass; // Note: only classes that extend our MySerializable are allowed here.  
        @serialize(revision = 2, objType = MyClass.class, collection = true)
        private final List<MyClass> listOf;
        @serialize(revision = 3, map = true, keyType = string, valueType = string)
        private final Map<String, String> mapOf;

	@Override
	public int getVersion() {
              return 0;
	}

	@Override
	public int getRevision() {
	    return 3;
        }
}
`

**Comment by andreipaduroiu** [comment]
> Question: Can we skip some revisions in between and serialize say 0.1 followed by 0.3 skipping 0.2 in the process? Your scheme seems to allow for that but do we foresee needing that abiilty?

Revisions are meant to be incremental. In order to get to 5, you need to process 0, 1, 2, 3, 4 in order. I don't see any benefit in skipping them. However, when you deserialize, you can choose not to process the data for a particular revision which means it will be skipped over. But when you write, you need to write all of them in sequence so previous versions of the code can still read that data.


> putting revision numbers and revision count in serialized blobs seems redundant.

I agree. Since they're encoded sequentially, we can skip that 1 byte that represents the revision ID. Since 1 byte doesn't have that much of an effect on the overall size, I have a slight preference towards keeping it as it helps double-check the data integrity (i.e., when we finish a revision, we expect to read a number whose value is equal to the previous revision + 1.

> This is because as long as we are only adding new fields and never removing/replacing fields across revisions, the revision is implicit and the serialized blob forward and backward compatible.

We can add, remove or replace fields. However, when we establish the format for a particular revision, we will always have to follow that format as long as we encode that revision. That's because old code still needs to read that. So if you remove a field, you will need to back-fill some valid value in your old revision, and similarly if you change the data type for a field. Eventually when enough such changes are accumulated, we can start fresh with a new Version, which will have its own format.


> Annotations

Yes I thought about that. It only works with POJOs. It doesn't work if I need to do a custom serialization/deserialization with only a part of an object, such as its internal state, or if my object has a base type and various other derived classes which need to be instantiated - both of these cases exist in the Segment Store code. Also I won't be able to serialize the same POJO in different formats (suppose if I want to include it in different locations).

I agree that using annotations will remove the need for all the boilerplate code for the simple POJO cases and we should explore it. The goal is to defer as much of the work to the constructor of the `VersionedSerializer` and not introduce any extra overhead in the `serialize/deserialize` methods. 

Let me think about this option and whether I can add something with this PR or do it as follow-up. @fpj  I'd welcome your input on this.

**Comment by shiveshr** [comment]
> Annotations. It only works with POJOs. It doesn't work if I need to do a custom serialization/deserialization with only a part of an object, such as its internal state

If the internal state is encapsulated in a serializable class, then that can be independently serialized and deserialized. And the deserialized value can be assigned to whatever uber object we want to partially update. 
I suppose even with ObjectSerializer model we will need to declare specific classes that define how to do partial serialization and deserializations for certain fields. 
So maybe I don't completely understand how that problem manifests if we do annotation based serializations.

> if my object has a base type and various other derived classes which need to be instantiated  
I think this problem of inheritance is tricky one.. Especially in terms of versions and revisions..  the base class and derived classes may have their own versions and revisions which makes it tricky for how to handle it. 
I suppose in the scheme that is proposed here, in the Serializer for the derived class we will have to explicitly decide which fields from base class should be included in which version of derived class. right?

But you are right, annotations will suffer with inheritance.. we will need some way in which in the derived class we are able to describe which parent fields to take while serializing and what should their revision translate to.
