### ISSUE TITLE
Out-of-box JSON serializer

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#1958]
**Problem description**
Provide an out-of-box JSON serializer based on Jackson databinding.

**Suggested Improvements**
The produced message should be compatible with the `JsonRowDeserializationSchema` in the Flink connector.  Ordinary JSON byestrings produced by `ObjectMapper` should be fine, e.g. `{"x":42, "y":"foo"}`.  Regarding character encoding, a suggestion: let Jackson use its defaults via `ObjectMapper::writeValueAsBytes(obj)`.

Suggestion: declare the jackson dependency as 'optional' thus forcing the app to supply the jackson library.

**Comment by tkaitchuck** [comment]
This is done in https://github.com/pravega/pravega-serializer
