### ISSUE TITLE
Update the code of conduct scope

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1973]
**Problem description**
We take our code of conduct very seriously. As such, we would like to expand the scope of the code to include situations in which any form of inappropriate behavior, even outside the immediate scope of the project, can cause damage to members of its community. For example, any sort of harassment when the connection between the people involved was established in the context of the project.

Expanding the scope does not imply changes to how we react to reports. We still reserve the right to assess any submitted reports under the guidelines of the code, maintaining the privacy of any information either submitted as part of the report or conveyed during conversations with the reporter.

**Problem location**
Code of conduct.

**Suggestions for an improvement**
Here is a suggestion of a sentence to add to the scope:

`This code additionally applies to situations of inappropriate conduct when the project is perceived as having enabled such a situation. For example, when it can be established that the people involved in an incident have met through the project communication media.`

**Comment by tkaitchuck** [comment]
LGTM
