### ISSUE TITLE
APIs to get Stream Cut

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1994]
**Problem description**
We want to be able to obtain stream cuts from both writer and reader. A stream cut from a reader group corresponds to the current segment offsets of the group, whereas one obtained from the ~~reader~~ writer is generated by the controller and corresponds to the end of the segments, independent of how much they have been read by any group.

This task has two subtasks:
- [ ] Stream cut reader side
- [ ] Stream cut writer side

**Problem location**
Client.

**Suggestions for an improvement**
Implement the corresponding API calls.

**Comment by EronWright** [comment]
For the writer side, I would like to obtain a stream cut corresponding to a Flink checkpoint and its corresponding transaction end positions.     Each Flink checkpoint has a corresponding checkpoint-id and corresponds to a set of transactions.    Can we somehow construct a stream cut corresponding to that checkpoint?

**Comment by shengkaisun** [comment]
Hi @fpj / @EronWright, it makes lots of sense to support stream cut from reader side to support batch processing. But I'm not very clear why we need it for writer side. Could you provide more details?

**Comment by tkaitchuck** [comment]
This has been added to the streamManager
