### ISSUE TITLE
Clarify semantics of `retryAttempts` on `EventWriterConfig`

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2000]
**Problem description**
There's a mismatch between 'retries' and 'attempts' in various places.   Certain config objects - `EventWriterConfig`, `ControllerImplConfig` - provide `retryAttempts` which implies the number of retries (and could reasonably be zero to disable retries).   The configured value is ultimately passed to `io.pravega.common.util.Retry` class which works in terms of `attempts` (which implies the number of attempts and must be at least one).

**Suggestions for an improvement**
Change the config API to use 'attempts' or add one to the value when configuring the underlying `Retry` object.

**Comment by tkaitchuck** [comment]
Yes, attempts includes the initial attempt. This is the semantic that is intended in both places.

**Comment by EronWright** [comment]
`retryAttempts` is hilariously confusing.
