### ISSUE TITLE
Stream truncation integration test

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2011]
**Problem description**
Add more integration tests for truncation. 
At least these two:
 1. get a valid stream cut with offset > 0.
 validate truncation within a segment
2. have an existing reader reading from non truncated segment and then truncate the segment.
 verify that reader gets appropriate response and handles it successfully. 
3. have an existing reader reading from a segment that gets deleted while reader is reading from it. 

**Problem location**
test/integration/test/EndToEndTruncationTest

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
https://trello.com/c/wtV1GOMU/15-implement-system-test-for-truncation
