### ISSUE TITLE
Pravega Security: Encryption: security certificate creation and distribution during Pravega deployment

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2033]
**Problem description**
To enable server auth for TLS, certificates need to be created and distributed along with Pravega deployment. These can be generated from a self-signed root cert OR can be generated from a root cert obtained from a CA.
Pravega deployments need to ensure that there is a way to achieve this.

This issue is part of #1669.

**Problem location**

**Suggestions for an improvement**

**Comment by EronWright** [comment]
This sounds like the sort of thing that a Kubernetes Pravega operator would do.   It is unclear what is being proposed here specifically.

**Comment by arvindkandhare** [comment]
@EronWright This is a mechanism/documentation for distribution of Pravega certs in all the possible ways Pravega can be deployed. One of these can be via Pravega operator. Here are the multiple ways Pravega can be deployed: http://pravega.io/docs/latest/deployment/deployment/

**Comment by ravisharda** [comment]
@fpj what's your opinion on this? Could we close this issue?

**Comment by fpj** [comment]
I don't understand how we are going distribute certificates, specially in the presence of changes to the cluster. Pravega is designed to be elastic: we can add controller instances and segment stores on the fly. As we do it in production, what's the strategy for updating certificates?

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2033 - Cert creation and distribution](https://trello.com/c/bJ7MP8qs/7-2033-cert-creation-and-distribution)
