### ISSUE TITLE
Add min run instructions to Pravega's dockerhub page

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#2069]
**Problem description**
There are no minimal run instructions on the dockerhub page of pravega.  

**Problem location**
dockerhub pravega page

**Suggestions for an improvement**
Add minimum instructions to run pravega using the docker image in the dockerhub description area.

**Comment by Prabha-Veerubhotla** [comment]
Updated the docker hub page, waiting for @arvindkandhare  to review.
