### ISSUE TITLE
Implement remote distributed test execution using System Test Framework

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2074]
**Problem description**
 ` REMOTE_DISTRIBUTED`  mode of test execution should  be implemented.
This execution is about running tests on a remote cluster in a distributed environment.

**Problem location**
System Test framework

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
We can execute the system test framework in remote clusters (Kubernetes, Docker Swarm, etc.).
