### ISSUE TITLE
Estimate segment store memory allocation for deployment

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2093]
**Problem description**
We are observing a few scenarios, in particular when running for a few days, in which the segment store starts to crash on out of memory.

We need an estimate of how much memory to allocate to a server and to make sure that the amount of memory used does not grow without bounds. 

**Problem location**
Segment store.

**Suggestions for an improvement**
I suggest we do the following:
- Document what parts of the segment store are using substantial amounts of memory (heap and off-heap)
- Estimate how they grow with the number of segments and segment data.
- Make sure nothing really grows without bounds.

**Comment by shengkaisun** [comment]
Looks like this bug should be fixed already, correct? @fpj
