### ISSUE TITLE
Sample code on pravega.io is not correct

### ISSUE THREAD

**Issue by wangzhizheng** [pravega/pravega#2106]
**Problem description**
Sample code at http://pravega.io/docs/basic-reader-and-writer/
still shows that AckFuture  is used.
but io.pravega.client.stream.AckFuture is removed at  #1356 

**Problem location**
 http://pravega.io/docs/basic-reader-and-writer/

**Suggestions for an improvement**
we should correct the sample code on pravega.io
 http://pravega.io/docs/basic-reader-and-writer/

**Comment by fpj** [comment]
Not an issue any longer.
