### ISSUE TITLE
Upgrade rocksdb to 5.8.6 (re: JVM crash on Windows)

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2118]
**Problem description**
Pravega (as of 96cefe97c6846470fa25cce226bdfe2a6d92a04b) crashes on Windows 10 due to an issue with rocksdbjni 5.8.0.  Problem is resolved by upgrading to 5.8.6.

**Suggestions for an improvement**
Upgrade to rocksdbjni 5.8.6.  Re-test pravega standalone to verify that it starts completely.

**Comment by fpj** [comment]
hey @EronWright, thanks for reporting this issue. a couple of points:

1- do we know the precise cause of the crash and how it was solved in 5.8.6? it might be worth checking the release notes so that we understand it better.
2- could you submit a PR, please?

**Comment by EronWright** [comment]
@fpj the release notes ([here](https://github.com/facebook/rocksdb/releases)) mention an alloc issue which could be the cause.

> 5.8.6 (11/20/2017)
> 
> Bug Fixes
> 
> Fixed aligned_alloc issues with Windows.

>
