### ISSUE TITLE
Pravega Security: Pravega should allow custom implementations of `PravegaAuthHandler` to be loaded dynamically 

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2125]
**Problem description**
Pravega can allow multiple instances of auth*n implementation to co-exist at the same time. 
It should be possible to load these implementation from jars stored in a known path dynamically during controller startup.

**Problem location**
Pravega controller startup.

**Suggestions for an improvement**

**Comment by shengkaisun** [comment]
Is it also done, @arvindkandhare ?

**Comment by arvindkandhare** [comment]
@shengkaisun This is under code review. It will be done once we merge #2175

**Comment by EronWright** [comment]
I think this is done.
