### ISSUE TITLE
Spurious exceptions related to segment sealed.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2150]
**Problem description**
The connection is not dropped in response to segment being sealed so the server will continue to generate errors as more appends arrive. Example:
```
2017-12-01 01:42:12,706 190233879 [segment-store-17] INFO  i.p.s.s.h.handler.AppendProcessor - Segment 'hulk/smallScale/929' is sealed and 5d04bead-7127-42dc-9166-559708ba0050 cannot perform operation 'appending data'
2017-12-01 01:42:12,706 190233879 [epollEventLoopGroup-3-2] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.lang.IllegalStateException: Data from unexpected connection: 5d04bead-7127-42dc-9166-559708ba0050.
```
There may be a larger issue here related to why the client does not handle this case properly...

**Problem location**
AppendProcessor

**Suggestions for an improvement**
Look into server-client interaction upon segment seal. Perhaps there is something wrong. 
Make logs more useful. 
See if there is a broader issue in the client-server interaction or if there is some underlying issue triggering the exception loop.

**Comment by tkaitchuck** [comment]
This is just log spam. We can avoid the processing by having the server close the connection after sending segment sealed

**Comment by TonySpace** [comment]
Longevity test failed. Flavio suggest that might share the same root cause of this issue.  Detail stack is on pravega-integration channel. 

```
2018-03-14 22:05:09,614 114163076 [epollEventLoopGroup-3-15] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
java.lang.IllegalStateException: Data from unexpected connection: c446310e-5ef2-4dd4-9b04-5b0437c49e38.
    at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
    at io.pravega.segmentstore.server.host.handler.AppendProcessor.append(AppendProcessor.java:380)

1 CommentClick to expand inline (43 lines)

**Comment by andreipaduroiu** [comment]
@tkaitchuck Is this still an issue? Last comment was almost 2 years ago.

**Comment by RaulGracia** [comment]
I think that the message is still present, but I don't think that it is specific of a flaky test, so maybe we can remote that label.

**Comment by shrids** [comment]
**Summary:**
The log line 

```
 Data from unexpected connection: Segment=testScope/testStream1/0.#epoch.0, WriterId=dc6722f7-6460-4109-8c64-ecdaaabdaf02.
```
is just log spam.

**Why does it happen:**
One common example where this can happen is during a segment sealing scenario. The `AppendProcessor` on the segment store on receiving an `Append `from the client invokes an append on the underlying StreamSegmentStore. In case the segment is sealed the AppendProcessor sends a `WireCommands.SegmentIsSealed` back to the client. As part of handling of segment sealed the `AppendProcessor` removes the `WriterState` for this id. 

On the client’s end `Append` requests are sent to the SegmentStore and on receiving `WireCommands.SegmentIsSealed` from the client tries to resend the inflight events in a thread pool  `ScalingRetransmission-*`. This implies that multiple appends can be transmitted before the Segmentstore responds with `SegmentIsSealed`. 

With the above two points in context, we see that the later `Appends` that are received by the Segmentstore would lead to “Data from unexpected connection:” log msg. 

Log snippet: [debug-log-unexpected.zip](https://github.com/pravega/pravega/files/6209508/debug-log-unexpected.zip)
