### ISSUE TITLE
Reader should throw upon data truncation

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2151]
**Problem description**
It is an open question as to how a reader should react if the segment is reading from is truncated deleting data is was reading. 
It could silently advance to the next valid data and continue working. However this seems inappropriate in some cases. Especially if the reader backed up explicitly to read old data. 
It could fail, but this is problematic for applications that have simply fallen behind. In that case they don't even have a good point to resume from and would like to jump forward.

**Comment by tkaitchuck** [comment]
After some discussion, It seems like the best thing to do would be to throw a checked exception that the user is free to ignore and keep reading (which will have the effect of skipping forward).

**Comment by fpj** [comment]
This issue is related to #2017
