### ISSUE TITLE
Publish Pravega snapshots

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2155]
**Problem description**
As we work towards the next release, we improve and fix bugs in Pravega. Making snapshot artifacts out of those changes available enables users to try them out and uncover problems early.  

**Problem location**
Publish, Maven Central, build.

**Suggestions for an improvement**
Publish snapshot artifacts to Maven Central either upon successful merge builds or after successful nightly builds. We can publish snapshots to Sonatype OSSRH:

http://central.sonatype.org/pages/ossrh-guide.html
https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/

**Comment by EronWright** [comment]
One of the motivations is to make the versioning between sample, connector, and client more explicit. 
 With that in mind, here's some info on how to link to a specific snapshot build as opposed to the latest snapshot.  Note that transitive links should also work as expected.

When you publish a snapshot to sonatype, a timestamp-based version number is automatically ascribed.  A client may link to that specific build by using that version number ([more info](http://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-pom-syntax.html#pom-relationships-sect-snapshot-versions)).  Note that older builds are retained but am unsure about policy specifics.   

See [this gist](https://gist.github.com/EronWright/c03fef714c23b5dea59abc022137d945) for an example of a Gradle build script demonstrating this idea, for an arbitrarily-selected library called `org.zenframework.easy-services` in Sonatype's snapshot repository.  Here's the dependency output (note the overrides):
```
compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- org.zenframework.easy-services:easy-services-js:1.0.0-SNAPSHOT -> 1.0.0-20170814.105643-1
     +--- org.zenframework.easy-services:easy-services-config:1.0.0-SNAPSHOT -> 1.0.0-20170814.105639-1
     |    \--- org.slf4j:slf4j-api:[1.7,) -> 1.8.0-beta0
     +--- org.zenframework.easy-services:easy-services-resource:1.0.0-SNAPSHOT -> 1.0.0-20170814.105616-1
     |    +--- org.zenframework.easy-services:easy-services-config:1.0.0-SNAPSHOT -> 1.0.0-20170814.105639-1 (*)
     |    +--- org.zenframework.easy-services:easy-services-util:1.0.0-SNAPSHOT -> 1.0.0-20170814.105626-1
     |    |    +--- commons-lang:commons-lang:2.6
     |    |    +--- commons-io:commons-io:2.5
     |    |    \--- org.slf4j:slf4j-api:[1.7,) -> 1.8.0-beta0
     |    \--- org.slf4j:slf4j-api:[1.7,) -> 1.8.0-beta0
     +--- org.zenframework.easy-services:easy-services-util:1.0.0-SNAPSHOT -> 1.0.0-20170814.105626-1 (*)
     +--- org.apache.commons:commons-pool2:2.4.2
     \--- org.slf4j:slf4j-api:[1.7,) -> 1.8.0-beta0
```

**Comment by EronWright** [comment]
To elaborate on the motivations (as I understand them):
1. Make it possible to use binary dependencies between the `pravega-samples`, `flink-connectors`, and `pravega` repositories.
2. Enable travis on samples and connectors, without requiring a pre-build step of building Pravega.
3. Improve stability of samples and connectors with explicit versioning, without requiring a release of Pravega.

**Comment by EronWright** [comment]
@vijikarthi is there more to do here, or may this be closed?

**Comment by RaulGracia** [comment]
Snapshots are being published in: https://oss.jfrog.org/artifactory/jfrog-dependencies/io/pravega/
I'm in favor of closing the issue and re-open if there is anything else missing.
