### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#217]
If a user is writing to or reading from multiple streams, there is no requirement for these to go over separate connections. As the number of streams grows this becomes more and more important.
For this reason we should implement connection pooling so that redundant connections to the same host are not needed.

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 217: Connection pooling Design document](https://trello.com/c/BtKprslb/131-issue-217-connection-pooling-design-document)

**Comment by shrids** [comment]
SubTasks:
- [ ] Implement the WireCommand Changes and modify the server and client logic to handle extra fields to enable connection pooling. (In Progress)
- [ ] Implement Connection pool for Netty Channels.
- [ ] Enable connection pooling for connections between the client process and Segment store.
