### ISSUE TITLE
PingImpl warning

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2172]
**Problem description**
I'm observing this warning when running standalone:
```
WARNING: A provider io.pravega.controller.server.rest.resources.PingImpl registered in SERVER 
runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to 
constraint configuration problems the provider io.pravega.controller.server.rest.resources.PingImpl will 
be ignored.
```

We seem to be missing some implementation.

**Problem location**
REST server, controller.

**Suggestions for an improvement**
Implement missing interface implementation.

**Comment by shrids** [comment]
Looks similar to `https://github.com/jersey/jersey/issues/3700` on 2.26 version of jersey (we are using this version), will investigate further...
