### ISSUE TITLE
Add `serialVersionUID` to `ReaderGroupConfig` 

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2177]
**Problem description**
`ReaderGroupConfig` should have `serialVersionUID`.    Consider auditing other serializable classes for similar issue, especially those related to state synchronizer (also: `Sequence`).

**Suggestions for an improvement**
I believe the latest auto-generated value for that class is `-7435346079857745183` .

**Comment by tkaitchuck** [comment]
This has been added.
