### ISSUE TITLE
Evaluate options for rebalancing readers in readergroups on internal streams used in controller

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2183]
**Problem description**
Controller performs concurrent asynchronous processing of requests posted in internal streams.
Here, we apply a trick to linearize all requests for a single "key" using an in-memory queue. The key used is scoped stream name. 
So this ensures that we guarantee in-order processing of requests for a given stream. But at the same time we do not block work for unrelated streams. 

Controller also maintains a reader-position checkpoint that keeps track of highest position object such that all events till this position are processed completely. 
For example, say we have events 1...100.
We have completed processing of 2 till 99. 1 and 100 are still being processed. 
In such case, the checkpoint will be null. The moment 1's processing completes, the checkpoint will move to position object corresponding to 99. 

Also note: all processing is idempotent. 
So this works well if a controller fails and reader's segments are reassigned, the new reader will resume reading on the segments using the checkpointed position object. Which may mean reprocessing some events, but ordering guarantee is maintained. 

However, if new controller instances are added, we cannot automatically rebalance segments to new readers. 
The rebalancing in readergroup, otherwise relies on automatic checkpointing. However, auto-checkpoint is not useful in scenario of asynchronous processing as there is no way we can determine conclusively which events are processed and which are currently being processed when a rebalance happens. 

If we were to rebalance segments if new readers are added, then auto-checkpointing will erroneously assume the position on the segment to be much further than actual because auto-checkpoint takes position corresponding to last processed event for its checkpoint. But as described above, in asynchronous processing, the checkpoint computation is custom to controller's logic. 

This introduces two broad problems:
1. Since processing of event read by origin segment owner `reader` was scheduled asyncrhonously, we can have two different controller instances processing events from the same segment. 
This can break ordering guarantees for proessing events for a key (/scopedStreamName). 

2. New reader starts to process events from a future checkpoint. If original owner controller fails during rebalance, the processing for some events may not have completed while auto-checkpoints checkpoint may point to a future checkpoint and new reader would be processing event from the higher position. 

**Problem location**
Controller event processor + auto-checkpoint + rebalance

**Suggestions for an improvement**
We should have a mechanism to explicitly bring reader-offline after completing all ongoing processing before we allow rebalancing of segments owned by the reader. 
Automatic checkpoint does not suffice for this purpose and we should come up with a new scheme that handles such cases.

**Comment by tkaitchuck** [comment]
See also: https://github.com/pravega/pravega/issues/2218
