### ISSUE TITLE
Controller should delete all active transactions prior to deleting a Stream

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2189]
**Problem description**
We need to make sure all transactions for a Stream are either committed or aborted prior to deleting the Stream, otherwise they will be left dangling and look like garbage in Tier2.

The SegmentStore can delete either a Segment or a Transaction, but due to limitations in the Tier2 API (lack of a `list` command), it cannot detect all transactions for a Segment. Since it does not keep any sort of mapping of Segment -> Txn (the relationship is determined by the naming of the Txn segment), it cannot do the cleanup at that level.

**Problem location**
Controller.

**Suggestions for an improvement**
Abort/Commit transactions prior to deleting a Stream.

**Comment by fpj** [comment]
@andreipaduroiu there is one thing I don't understand tangentially related to the issue here. will transaction segments of **closed** txns (committed or aborted) induce delete calls to tier 2 when we try to delete the stream?

**Comment by andreipaduroiu** [comment]
If the transaction segment exists in Tier2 it will be deleted.
If the transaction segment does not exist in Tier2 it will not be deleted and you'd get a SegmentNotExistsException.
If the transaction has been closed but that change hasn't made it to Tier2, then this will delete it from Tier2 and the StorageWriter will figure that out.
