### ISSUE TITLE
DeleteSegment request responds with unexpected "Segment Already Exists"

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2190]
**Problem description**
We observed that DeleteSegment request to segmentstore during deleteStream workflow responded with "Segment Already Exists" response, which is unexpected and causes delete stream workflow's failure with a non-retryable exception. 

**Problem location**
PravegaRequestProcessor.DeleteSegment 

**Suggestions for an improvement**
Valid expected responses for deleteSegment should be : SegmentDeleted, NoSuchSegment or WrongHost.

**Comment by andreipaduroiu** [comment]
According to the logs this is due to Tier2 Storage implementations not being thread-safe and Delete bypassing StorageWriter. This can be fixed (theoretically) by making `RollingStorage` thread-safe per Segment.
