### ISSUE TITLE
Idempotence of segment truncation

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2203]
**Problem description**
It is not entirely clear from the javadocs of `StreamSegmentStore`what the expected behavior is in the presence of calls to truncate a segment at an offset that has already been truncated. 

**Problem location**
SegmentStore

**Suggestions for an improvement**
Improve javavadoc in `StreamSegmentStore` and write test cases if needed. If there are already test cases covering the behavior, then please point to them here.

**Comment by fpj** [comment]
From the javadocs, I don't think that `truncateStreamSegment` is idempotent, although I'm not sure:

```
/**
     * Truncates a StreamSegment at a given offset.
     *
     * @param streamSegmentName The name of the StreamSegment to truncate.
     * @param offset            The offset at which to truncate. This must be at least equal to the existing truncation
     *                          offset and no larger than the StreamSegment's length. After the operation is complete,
     *                          no offsets below this one will be accessible anymore.
     * @param timeout           Timeout for the operation.
     * @return A CompletableFuture that, when completed normally, will indicate the operation completed. If the operation
     * failed, the future will be failed with the causing exception.
     */
    CompletableFuture<Void> truncateStreamSegment(String streamSegmentName, long offset, Duration timeout);
```

Specifically, it says that the offset must be at least as large as the current truncation offset. I'm assuming that in the case the offset is smaller, it is going to error the request. Based on recent changes, I'm assuming this is going to be `BadOffsetException`, but it is not entirely clear.
