### ISSUE TITLE
Javadoc Standards

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2214]
We need to establish a common set of rules governing the JavaDoc in our codebase. This will be added as a new section in the [Contributing wiki page](https://github.com/pravega/pravega/wiki/Contributing).

I will be taking comments until January 5, 2018 5PM PST.
Proposed text (use comments below to comment, and I will update the text accordingly):

----
# JavaDoc Guidelines
The base for these is the [Oracle JavaDoc Conventions](http://www.oracle.com/technetwork/articles/java/index-137868.html). The items below supersede that document.

JavaDoc scopes (from highest to lowest):
- **Scope 1.** All client-visible APIs (contracts and classes we expect the users to consume in order to make use of Pravega) and all publicly visible code in `common` (which we treat as stuff we'd like to have in the JRE but is not there).
- **Scope 2.** Inter-application contracts and APIs (i.e., SegmentStore contracts used by Client or Controller and Controller contracts used by SegmentStore or Client).
- **Scope 3.** Intra-application contracts used by various components in that application that are not exposed outside.
- **Scope 4.** Individual components and types (classes, interfaces and enums) within an application. This includes "package-private" types, public nested types, as well as any non-private method, field or constructor.
- **Scope 5.** Non-public nested types and private methods. Essentially everything else.

Refer to the scopes above for each type of JavaDoc listed below. Please note that these are minimum requirements - it is always encouraged to be more detailed with JavaDoc for a particular type of component.

- **Types** (**Classes**, **Interfaces** and **Enums**)
    - Scopes 1-4 types should have a description explaining the purpose of the type.
    - Scope 1 Classes: should include a small code example of how to use.
    - Scope 1-4 enums should have a description on each enum value explaining its meaning.
    - Javadoc required for Scopes 1-4 and recommended for Scope 5.
- **Constructor**
    - Default text for a constructor should be `Creates a new instance of the <class-name> class.`. If the constructor does something unusual, it should be described here.
    - Javadoc required for Scopes 1-4.
- **Methods**
    - Should include descriptive text (not just reiterating method name). Scope 1 requires sample usage, where appropriate.
    - `@params` tag for every argument and generic type
    - `@throws` tag for every checked exception. Runtime exceptions are not required, however if those exceptions are used in an unusual way, it is highly recommended documenting that here.
        - If declaring a common exception (i.e., `@throws StreamingException`, then list possible sub-exceptions under this tag and under what conditions they arise).
        - If the method returns a type extending from `Future` (i.e., executes asynchronously), do not include exceptions that the returned future can be failed with (see below how to document this). Only include exceptions that are thrown synchronously.
    - `@returns` tag required for all non-getter methods.
        - If the method returns a type extending from `Future` list all possible exceptions the returned future may fail here. Do not include them in the `@throws` tag.
    - If a method overrides a method from a super class or interface it is not necessary to add Javadoc to it as long as it has the `@Override` annotation.
    - Javadoc required for Scopes 1-4 and recommended for Scope 5.

Other miscellaneous things of importance:
- In addition, any check imposed by checkstyle or the Javadoc Compiler that results in a warning or error should be fixed rather than suppressed. 
- For Lombok auto-generated getters and setters (done via `@Data`, `@Getter` or `@Setter` annotations) the Javadoc should be set on the field itself. There is no need to add the `@return` or `@param` docs as they will be auto-generated.

## Example:
This example is for Javadoc illustration purposes only; the methods have been left empty on purpose and no guarantees are made as to the correctness of the code or the design of the class.
```
/**
 * Represents an asynchronous processor for general items.
 *
 * @param <ItemT> Type of items to process.
 */
public class ItemProcessor<ItemT> implements AutoCloseable {
    /**
     * Defines how many items we can have in the queue at any given time.
     */
    public static final int MAX_QUEUE_SIZE = 1000;
    private final Queue<ItemT> queue;
    private final Executor executor;
    private final Consumer<ItemT> itemProcessor;

    /**
     * Keeps track of how many items have been completed since the creation of this ItemProcessor.
     */
    @Getter
    private int completedItemCount;

    /**
     * Creates a new instance of the ItemProcessor class.
     *
     * @param itemProcessor A Consumer that will be invoked on each item to process.
     * @param executor      An Executor to use for background operations.
     */
    public ItemProcessor(Consumer<ItemT> itemProcessor, Executor executor) {
    }

    @Override
    public void close() {
    }

    /**
     * Gets a value indicating the number of items in the queue.
     */
    public int getQueueSize() {
    }

    /**
     * Queues the given item for processing.
     *
     * @param item    The item to process.
     * @param timeout A timeout for the operation. The item will not be processed if the timeout elapsed prior to this 
     *                timeout expiring.
     * @return A CompletableFuture that, when completed, will indicate the item has been processed. If an exception occurred,
     * it will be completed with the causing exception. Notable exceptions:
     * * {@link java.util.concurrent.TimeoutException} If the given timeout expired prior to processing the item.
     * * {@link io.pravega.common.ObjectClosedException} If this instance of ItemProcessor has been closed prior to processing
     * the item.
     */
    public CompletableFuture<Void> process(ItemT item, Duration timeout) {
    }

    private void executeNextItem() {
    }
    
    private class QueueItem{
        QueueItem(ItemT item, CompletableFuture<Void> result){
        }
        private final ItemT item;
        private final CompletableFuture<Void> result;
    }
}
```

**Comment by fpj** [comment]
+1, looks good.

**Comment by tkaitchuck** [comment]
Under Scope 1, I would change it from "all code in common" to "all visible code in common". IE: Private methods that happen to be in common should still be excluded

**Comment by tkaitchuck** [comment]
I think we should add a section on dealing with Lombok and Javadocs. There the text to go in the Javadoc can be added in a Javadoc above the parameter declaration, but the @return and @parm are not needed and will be auto-generated.
```
@Data
public class SegmentInfo {

    /**
     * Which segment these properties relate to.
     */
    private final Segment segment;
    
    /**
     * The offset at which data is available. In the event the stream has never been truncated this
     * is 0. However if all data below a certain offset has been truncated, that offset will be
     * provide here. (Offsets are left absolute even if data is truncated so that positions in the
     * segment can be refered to consistantly)
     */
    private final long startingOffset;
    
    /**
     * The offset at which new data would be written if it were to be added. This is equal to the
     * total length of all data written to the segment.
     */
    private final long writeOffset;
    
    /**
     * If the segment is sealed and can no longer be written to.
     */
    private final boolean isSealed;
    
    /**
     * The last time the segment was written to.
     */
    private final long lastModifiedTime;

}
```

**Comment by tkaitchuck** [comment]
Additionally, any check imposed by checkstyle or the Javadoc compiler that results in a warning or error should be fixed rather than suppressed.

**Comment by andreipaduroiu** [comment]
> Under Scope 1, I would change it from "all code in common" to "all visible code in common". IE: Private methods that happen to be in common should still be excluded

Fixed.

**Comment by andreipaduroiu** [comment]
> Additionally, any check imposed by checkstyle or the Javadoc compiler that results in a warning or error should be fixed rather than suppressed.

Fixed.

**Comment by andreipaduroiu** [comment]
> I think we should add a section on dealing with Lombok and Javadocs

Fixed.

**Comment by tkaitchuck** [comment]
Under "Types" it says "Required for Scopes 1-4. Recommended for Scope 5." 
It's not clear what this refers to. What is required? Is this meant to be a sub-bullet of the one above?

**Comment by tkaitchuck** [comment]
Can you add a Lombok getter to the example just to show it?
Otherwise looks good.

**Comment by shrids** [comment]
+1, went through it, looks good.

- The example was helpful to understand the doc standards.
   >     public int getQueueSize() { the java doc should have a @return right?

**Comment by Prabha-Veerubhotla** [comment]
> Level 1 requires sample usage, where appropriate.

is this scope 1 ?

**Comment by andreipaduroiu** [comment]
> Level 1 requires sample usage, where appropriate.
> is this scope 1 ?

Yes. Fixed.

**Comment by andreipaduroiu** [comment]
> Under "Types" it says "Required for Scopes 1-4. Recommended for Scope 5."
> It's not clear what this refers to. What is required? A Javadoc?

Yes. Javadoc. I clarified the ambiguity.

**Comment by andreipaduroiu** [comment]
> Can you add a Lombok getter to the example just to show it?
Done

**Comment by andreipaduroiu** [comment]
Thank you all for the feedback provided. I have updated our [Contribution Guidelines](https://github.com/pravega/pravega/wiki/Contributing#javadoc) with the contents proposed in this issue.
