### ISSUE TITLE
endOffset in the batch API is confusing

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2215]
**Problem description**
In the BatchClient, endOffset is passed as a way to limit how far the iterator will go. It is defined exclusively. This can be confusing given it's name.

**Problem location**
BatchClient.readSegment()

**Suggestions for an improvement**
The parameter should simply be removed. The iterator returned can provide its current offset to the caller. So an application wanting to limit how far it reads need not supply the offset at the time of the creation of the iterator, it can simply compare against the result of `getOffset()`.

**Comment by fpj** [comment]
`SegmentInfo` is also missing a Javadoc block altogether. I'm not sure if you want to sort this out in the same issue or in a separate one.
