### ISSUE TITLE
Create integration test for the BatchClient

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2217]
**Problem description**
Right now the BatchClient interface is not covered by any tests. (The impl is)

**Problem location**
Integration tests

**Suggestions for an improvement**
We should add an integration test to cover this code.

**Comment by fpj** [comment]
Do you mean a system test? Basically, a test case in `test/integration` or a test case `test/system`?

**Comment by tkaitchuck** [comment]
I mean a test case in `test/integration`

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue#2217](https://trello.com/c/cXGoVL57/8-issue2217)
