### ISSUE TITLE
BatchClient -> BatchReader

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2219]
**Problem description**
For consistency, should we rename `BatchClient` to `BatchReader`? I'm not sure why we haven't called it `BatchReader` in the first place.

**Problem location**
Reader, batch API.

**Suggestions for an improvement**
Rename API (note that it is a breaking change, so better do it sooner rather than later).

**Comment by tkaitchuck** [comment]
As of https://github.com/pravega/pravega/pull/3126 it is now `BatchClientFactory`
