### ISSUE TITLE
Pravega Security: Strategy to secure data at rest in tier-1

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2224]
**Problem description**
Apache bookkeeper does not encrypt data at rest. Decide a strategy to secure this data.

This issue is part of #1669.
**Problem location**
Tier-1.

**Suggestions for an improvement**
Ensure that this data is secure.

**Comment by andreipaduroiu** [comment]
I thought Bookkeeper has the ability to supply some sort of password when opening ledgers (supplied by the BK client when being initialized). @fpj would you know if this is good enough?

**Comment by shengkaisun** [comment]
This is a new feature. Can add the feature label @arvindkandhare ?

**Comment by arvindkandhare** [comment]
@shengkaisun added a `feature` label. Thanks.
