### ISSUE TITLE
Pravega Security: Retrieve security related parameters through systemProperties rather than changing the API

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2225]
**Problem description**
According to current proposal in PDP, https://github.com/pravega/pravega/wiki/PDP-23:-Pravega-security----encryption-and-Role-Based-Access-Control#4-client-api-changes the security parameters are input as paramters to the API. 
 
These parameters need to be moved to systemProperties so that there is no change in the API.

**Problem location**
Security related changes in `ClientFactory` and `StreamManager`.

**Suggestions for an improvement**
Retrieve these parameters from systemProperties.

**Comment by EronWright** [comment]
This issue could use some clarification @arvindkandhare

**Comment by arvindkandhare** [comment]
This issue is good to be closed. We achieved both the goals:
1. Accept security parameters through properties/config
2. No change in the API (we changed just the `ClientConfig` object.)

**Comment by ravisharda** [comment]
Closing as this issue appears to already have been addressed.
