### ISSUE TITLE
Segment Store Admin Tools

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2228]
**Problem description**
We need a set of tools that help us do:
1. General debugging of production issues with the Segment Store. 
    - This is different from debugging a problem discovered in the code; it has more to do with getting a particular user back up and running after they got stuck without having to wipe away the entire cluster.
2. Admin commands that are not available via the general API (i.e, clear Tier1 for a container, cleanup orphan BK ledgers, etc).

Initial desires:
- Debug causes of Segment Container recovery failures
- Fix Segment Container recovery failures by altering the data already written to Tier1 (which is usually the most common cause of recovery failures).
- Issue #1165 
- Issue #2261 (commands for BookKeeper)
- Issue #2262 (commands for Segment Containers)

**Problem location**
Segment Store Tools.

**Suggestions for an improvement**
This is a sample set of commands to begin with. Depending on details, we may choose to split them onto several PRs or adjust the syntax to better suit us.
- `config <key1=value1> ...` - sets or updates the configuration to use for subsequent commands. 
    - Key here refers to the keys in the config file (i.e. `pravegaservice.listeningPort`) so essentially this would be in lieu of an actual config file. 
    - Most of the uses for this would be to set the ZK address so that subsequent commands can connect appropriately.
- `bookkeeper list` - list all BK Logs (no details)
- `bookkeeper details <log-id>`: output info about a log (metadata + bk ledgers)
- `bookkeeper delete <log-id>`: delete a log's contents
- `bookkeeper cleanup`: delete orphan ledgers
- `container set-status <container-id> <online|offline>`: 
    - `online`: can be used by SegmentStore but cannot debug
    - `offline`: SegmentStore cannot load it, but it can be debugged.
- `container recover <container-id> <verbosity>`: do a dummy recovery of the Container, without processing anything or otherwise affecting the state of the data in Tier1 (still have a ContainerMetadata, InMemLog and a ReadIndex, but no actual cache storage)
    - verbosity: `DataFrame|OperationSummary|OperationDetail` (from just reading frames without extracting operations to just listing operations to actually validating operations)
- `container replace-op <seq-no> <TBD>`: replace an operation with given SeqNo with another. TBD how to load up the new operation contents.
- `container delete-op <seq-no>`: variation of `replace-op`, but it replaces an op with a no-op
- `container add-op <after-seq-no> <TBD>`: insert an operation immediately after the operation with existing SeqNo.

**Comment by fpj** [comment]
This is a great initiative, I really like the direction. A couple of things that I'd like to get clarity on:

1- *Running the tool*. Our source code is of course open, so anyone is able to fetch a copy and build. Our primary way of distributing Pravega is via maven artifacts that users include as dependencies in their projects. Maven dependencies are not a good way to distribute such admin tools, we would need to distribute some form of binary that an admin can fetch and use. The overall question is how we expect users to actually run this tool.
2- *Concrete scenarios*. I'm sure the suggested commands are not accidental and they come from your perceived way of dealing with segment store problems. I think the design should be driven to some extent by use cases, though. Even if we don't do it all up front, we need to understand what scenarios we are covering and what commands (and sequences of) we expect users to run each case.

**Comment by fpj** [comment]
It might be worth writing a PDP so that we have a reference document about how to write admin tools for pravega (or extend an admin tool in the case we agree to have a single tool).

**Comment by andreipaduroiu** [comment]
> Running the tool.

I'm planning on making this a command line tool that can be started either as a Gradle target or via the standard way of invoking Java apps. I can see this either being deployed with Pravega and someone would ssh into the machine and run it locally or run it remotely (assuming the cluster can be reached from the local machine). Additionally, for complicated debugging scenarios, I can imagine a developer needing to run this from their IDE so they can step through the process and inspect various things that would otherwise not be available via a regular stack trace.

For read-only scenarios, there should be no (data corruption) concerns running this either locally or remotely. However, when it comes to making changes, a remote tool will need to have the exact same code version of Pravega that is running on the cluster, otherwise we risk making the situation worse (imagine serializing something with a future version that is not yet supported on the cluster version).

> Concrete scenarios
Hard to imagine now. I suspect that we (devs) will need to get our feet wet in the beginning so we can observe some patterns. The tool, as proposed right now, is general enough to fix a variety of things. However, consider the data corruption that we detected internally last week. In order to fix that, I would have had to download 800KB of raw bytes to my machine, change 2 bytes in there, then replace that operation with the new sequence of bytes. Such a case would be far beyond what a sys admin would be doing.

I can imagine debugging working like this
1. A problem is reported and some logs are generated
2. A sys admin will look at the logs to pinpoint the problem. 
3. If this is an environment issue (connections, disks full, etc), that can be fixed right away with no further issues.
4. If this is a blocking data corruption issue, the sys admin can run the read-only commands above (list BK ledgers, run a dummy recovery, etc) and see where it blows up.
5. Depending on the case (and this is where a lot of unknowns currently exist), this may either be fixed by the sys admin (see sub-section below) or escalated to a dev for actual fix
5.1 Over time, as we gain more experience with this, we may write recipes or write additional tools to self-heal the data, but at this point we'd just be guessing.
