### ISSUE TITLE
Clean up unused writer ids

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2240]
**Problem description**
A new writer creates a new writer id when it is instantiated. The writer id is important to make sure we avoid duplicates by storing as part of the segment metadata a mapping of the id to the last event successfully appended.

In the case that we continuously create writers of a stream over time, the number of writer ids associated to a segment can grow in an unbounded manner. It isn't clear how to decide whether a writer id can be discarded or not, mainly because discarding an id prematurely can potentially lead to duplicates. We should investigate what mechanisms we can use and guarantees we can offer. 

**Problem location**
Event writers.

**Suggestions for an improvement**
Determine how to clean up unused ids.

**Comment by tkaitchuck** [comment]
This is done via configuration on the stream. `StreamConfiguration.timestampAggregationTimeout`
