### ISSUE TITLE
Sporadic build failure in FileSystemIntegrationTest.testEndToEnd

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2249]
**Problem description**
```
Error Message

org.junit.runners.model.TestTimedOutException: test timed out after 300 seconds

Stacktrace

org.junit.runners.model.TestTimedOutException: test timed out after 300 seconds
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
```

**Problem location**
FileSystemIntegrationTest.testEndToEnd

**Suggestions for an improvement**
Fix the issue

**Comment by fpj** [comment]
@RaulGracia have we observed this test case failing recently?

**Comment by RaulGracia** [comment]
@fpj I haven't seen this one recently, but on December 12th I observed the following failure:  `io.pravega.segmentstore.server.host.FileSystemIntegrationTest.testEndToEndWithFencing`. Given that `FileSystemIntegrationTest` and `HDFSIntegrationTest` belong to the same family of tests, and `HDFSIntegrationTest.testEndToEnd` fails sometimes, it is expected that we observe this failure again.

**Comment by sachin-j-joshi** [comment]
@RaulGracia @shiveshr Is this still an issue?

**Comment by sachin-j-joshi** [comment]
@RaulGracia @shiveshr Is this still an issue?

I am not able to repro this test locally. I tried by continuously running the test in loop until it failed.
Even after more than 1000 invocations and more than 2 hrs I am not able to make it fail.

![image](https://user-images.githubusercontent.com/44757683/57032162-893f4100-6bfe-11e9-8950-f836e2065873.png)

Alternatively, running this test in constrained environment (low cpu/memory or but often low disk) results in bookie failure (unable to provision enough healthy bookies). This is a genuine "error" in a sense that the test can not be run without healthy bookie. This is not a tier-2 issue.

Not sure at this point if it is okay to close this for now.

**Comment by RaulGracia** [comment]
Thanks for looking into this @sachin-j-joshi. This issue is quite old, if it cannot be reproduced at this point we can close it are re-open it if necessary.
