### ISSUE TITLE
Disable auto-checkpointing for readers used in controller's event processor

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2254]
**Problem description**
Auto-checkpointing and rebalancing do not work for controller's asynchronous processing of events. 
Sincce auto-checkpointing is enabled by default, we should disable it explicitly. 

**Problem location**
EventProcessorGroupImpl.java

**Suggestions for an improvement**
Disable auto-checkpointing.

**Comment by fpj** [comment]
This is related, if not a duplicate, of issue #2183 .

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue 007 under review](https://trello.com/c/9UPQSk21/5-issue-007-under-review)

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [testing new board. how do we pull GitHub issues here?](https://trello.com/c/0jOAWClM/1-testing-new-board-how-do-we-pull-github-issues-here)
