### ISSUE TITLE
Ensure cleanup of state synchronizer in ReaderGroupImpl

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2257]
**Problem description**
Some methods within `ReaderGroupImpl` create a temporary state synchronizer without a definite cleanup.  For example:
```
    @Override
    public Set<String> getStreamNames() {
        @Cleanup
        StateSynchronizer<ReaderGroupState> synchronizer = createSynchronizer();
        synchronizer.fetchUpdates();
        return synchronizer.getState().getStreamNames();
    }
```

This might address some connection leaks that are under investigation.

**Problem location**
`ReaderGroupImpl`

**Comment by tkaitchuck** [comment]
This was fixed in https://github.com/pravega/pravega/pull/2383
