### ISSUE TITLE
Revisit timeouts in Pravega Service

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#226]
The Pravega Service takes in/supplies timeout parameters for the following operations
- External APIs (append, read, get, seal, merge, etc) - called in from the clients via the Wire Protocol.
- Tier1 operations (append, truncate, read)
- Tier2 operations (write, read, get, etc.)

Decide what to do with these timeouts
- Option 1: Wire the timeouts through (for External APIs), and respect them. 
    - That is, if an operation is not completed during the given timeout, it should be auto-canceled. 
    - For Tier 1: write may get a variable timeout based on the operations enqueued, the others can have predefined timeouts
    - For Tier 2: have predefined timeouts, which are configurable.
- Option 2: Implement them and use hard-coded values (in which case, what is an appropriate value for each)
- Option 3: Get rid of them and don't use timeouts at all (judge on a case-by-case basis)
- **Option 4 (My preference)**: Get rid of them and replace with `CancellationToken`. 
    - The external APIs would require such a token to be passed by the caller (who is the sole timekeeper). 
    - The caller will cancel this token if its timeout expired. Internally this token is passed around to each sub-call or subcomponent, which will have to respect it. 
    - For internal-only calls, a similar approach can be used.
    - The token would have these methods: 
        - register(Callback/Future): registers a Callback to invoke or Future to cancel. Care must be taken for such callbacks/futures to be unregistered (TBD) when they are no longer needed, to prevent memory leaks.
        - requestCancellation(): attempt to cancel the operation. All registered callbacks will be invoked and all registered Futures will be canceled.
        - isCancellationRequested(): whether requestCancellation() has been invoked.

My preference would be Option 4. Looking for input via comments below or let me know if I should open a PDP for it.

**Comment by fpj** [comment]
I like the idea of a `CancellationToken` better than timeouts. My understanding is that these timeouts are not honored at all today and the request processors do not rely on them. Consequently, such a change would be initially localized on the segment store API and internals to honor the cancellation.

**Comment by andreipaduroiu** [comment]
@fpj Yes that is correct. None of the timeouts (except for very, very few - maybe less than 3) actually honor timeouts, but all are internally set timeouts (via config). Every external timeout is virtually ignored and just pollute the code.

I would love it if we could get rid of all the timeouts (and most `TimeoutTimer`s) . This is a lot of cleanup "legwork" and should not affect any functionality at all. However the benefit is a nicer looking API and code. 

As for priority, we can squeeze this as a 1-2 day task after we solve the main problems with release 0.4 or 0.5.
