### ISSUE TITLE
Segment Store Admin Tools for BookKeeper

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2261]
**Problem description**
Implement admin tools commands for BookKeeper.
- `bookkeeper list` - list all BK Logs (no details)
- `bookkeeper details <log-id>`: output info about a log (metadata + bk ledgers)
- `bookkeeper delete <log-id>`: delete a log's contents
- `bookkeeper cleanup`: delete orphan ledgers

**Problem location**
Segment Store Admin Tools.

**Suggestions for an improvement**
Implement new commands.

**Comment by fpj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Segment Store Admin Tools: recovery ledger](https://trello.com/c/jmXLTNZH/6-segment-store-admin-tools-recovery-ledger)
