### ISSUE TITLE
Segment Store Admin Tools for Container Recovery

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2262]
**Problem description**
Implement admin tools commands for Segment Containers recovery:
- `bk enable <container-id>`: enable the BookKeeperLog backing the given Container Id (Container will eventually enter online mode)
- `bk disable <container-id>`: disable the BookKeeperLog backing the given Container Id (Container goes in offline mode).
- `container recover <container-id>`: do a dummy recovery of the Container, without processing anything or otherwise affecting the state of the data in Tier1 (still have a ContainerMetadata, InMemLog and a ReadIndex, but no actual cache storage)

**Problem location**
Segment Store & Segment Store Admin Tools.

**Suggestions for an improvement**
Implement commands.

**Comment by fpj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Segment Store Admin Tools: recovery ledger](https://trello.com/c/jmXLTNZH/6-segment-store-admin-tools-recovery-ledger)
