### ISSUE TITLE
Download and Replace BookKeeperLog Entries

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2281]
**Problem description**
In order to make the admin tools useful, we need a way to be able to repair the data in Tier1. Two things would be ideal to get done:
- The ability to download a (range of) BookKeeperLog Ledger Entries.
- The ability to delete (ignore) or replace a (range of) BookKeeperLog Ledger Entries with another

This would help the container get unstuck in case the recovery failed with a DataCorruptionException due to bad data in the log.

**Problem location**
Segment Store.

**Suggestions for an improvement**
Add the ability to point to a special BK Ledger from `BookKeeperLog` - name it "Repair Ledger". The admin tools can populate this ledger with various entries that contain the replaced/added/deleted operations/data frames.

Admin tools to implement:
- `bk ledger get <ledger-id> <ledger-entries> <target-path>`
- `bk ledger delete <ledger-id> <ledger-entries>`
- `bk ledger replace <ledger-id> <ledger-entry-id> <source-path>`

It would be nice if we didn't need to have "target-path" in these and we could just manipulate this in memory. TBD.

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Stream retention system test](https://trello.com/c/NjeCjqlR/13-add-stream-retention-system-test)
