### ISSUE TITLE
Ability to enable reads/writes to/from Streams across all data-centers

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#23]
Pravega should have the ability to handle geo-replicated Streams with reads and writes enabled on all replicated sites. We refer to this configuration as Active-Active ( Contrasts to an Active-Passive configuration where Streams are actively written to from only one Primary site. Others are read-only.

This req is part of #21 

Note: Active-Passive should be included in EAP2 releases, not Active-Active.

**Comment by tkaitchuck** [comment]
Closing in favor of #21
