### ISSUE TITLE
Pravega Security: Explore explicitly requesting `delegationToken` instead of piggybacking on the returns from controller

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2344]
**Problem description**
The current implementation in the PR returns the delegationtoken along with the relevant returns 
from controller. This is as per this section of PDP: https://github.com/pravega/pravega/wiki/PDP-23:-Pravega-security----encryption-and-Role-Based-Access-Control#3-authorization.

We need to explore options where the client explicitly requests the token instead of piggybacking on the returns from the controller.

**Problem location**
Client to controller interface.

**Suggestions for an improvement**

**Comment by ravisharda** [comment]
Closing this issue after a prolonged period of inactivity.
