### ISSUE TITLE
Provide `StreamManager::scopeExists` operation

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2358]
**Problem description**
It would be handy to be able to check whether a scope exists.

**Problem location**
`io.pravega.client.admin.StreamManager`

**Suggestions for an improvement**
Consider introducing a `getScope` in Controller, even if scopes have no associated information at this time.   This would facilitate an existence check, and prepare for future features such as scope labels/tags.

**Comment by medvedevigorek** [comment]
Covered by #4751
