### ISSUE TITLE
Make Pravega compile on Windows

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2365]
**Problem description**
To enhance developer productivity and adoption, it would be nice if we could do Pravega development on Windows.

**Problem location**
All.

**Suggestions for an improvement**
`gradlew check` should work on a Windows machine.

**Comment by EronWright** [comment]
I observe that the docker tasks don't work on Windows (because it assumes `/usr/bin/docker` or something).   Should be fixed to fully support building on Windows.

**Comment by andreipaduroiu** [comment]
@EronWright You can create a new issue for that. Docker tasks are not part of the compilation process (`gradlew check`).
