### ISSUE TITLE
Pravega Security: Use JKS based trust/key stores instead of using cert and key files

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2376]
**Problem description**
Currently Pravega clients use cert and key based certificates to interact with controller and segmentstore. This was mainly because there was no obvious way to use standard (JKS based) way to use the certificates.
This URL provides a solution:
https://groups.google.com/forum/#!topic/grpc-io/cRPysB5AcMU 

Using this we can move the controller to use JKS based solution. The segmentstore also can move to using JKS.

**Problem location**
Network code for client, controller and segmentstore.

**Suggestions for an improvement**
Implement JKS based security.

**Comment by ravisharda** [comment]
The rationale for moving to Java JKS keystore is not clear. There was, in fact, an ask to do the opposite for the one place we use a JKS file - the Controller REST API - [here](https://github.com/pravega/pravega/issues/3652) (see deferred items in the issue description). Also, Java has deprecated `JKS` format in favor of `PKCS12` (`.p12` or .pfx`), so I suppose that the ask is really for moving to `PKCS12`. I'll close this issue until the need for moving to Java keystore surfaces again.
