### ISSUE TITLE
Pravega Security: Standardize the use of the HTTP Authorization header

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2384]
**Problem description**
The auth framework uses the HTTP `Authorization` header to transmit credentials from client to controller.   Also provided is a built-in auth implementation based on a password file.  It is reasonable to expect that the format of the `Authorization` header would follow the HTTP Basic Authentication standard ([RFC 7617](https://tools.ietf.org/html/rfc7617)) in the 'password' handler case, and follow [RFC 7235](https://tools.ietf.org/html/rfc7235) in general.   Such standardization would allow ordinary HTTP clients (e.g. `curl`) to authenticate with the controller.

There is also an encoding issue with certain passwords (e.g. those containing commas).

Here's what the authorization header looks like today:
```
Authorization: handler:Pravega-Default,userName:Aladdin,password:open sesame
```

Here's the suggested format:
```
Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
```

**Suggestions for an improvement**
Let us define the value of the `Authorization` header as the _credentials_, as per RFC 7617.  The credentials may be parsed into a _scheme_ and a _token_.

1. Select a handler based on the scheme.
2. Change the built-in password handler to register as the handler for `Basic` scheme and to use base64 encoding as per the spec.
3. Rework the `AuthHandler` interface to work with a single value (the token) rather than with a map.

To comment on how the Nautilus handler would work, I suggest it handle the `Bearer` scheme and treat the token as a signed JWT token.

**Comment by arvindkandhare** [comment]
This point needs to be discussed and closed on before we move on to implementing this: https://github.com/pravega/pravega/pull/2385#pullrequestreview-106368324

**Comment by fpj** [comment]
I agree it is important to follow standard practices and the propose change looks good overall. Two points I don't understand:

- There is sample in the description, but I don't fully understand what it is that is broken or not ideal today.
- What are the contention points for doing this? It feels like a needed change.

**Comment by EronWright** [comment]
The thrust of this PR is to be less prescriptive about the `Authorization` header format, so that a) the password handler may use the well-known `Basic` encoding, and b) an OAuth handler may use the well-known `Bearer` encoding.   The main benefit is to enable ordinary HTTP clients to use the controller REST API, for example:
- `curl`
- [Apache HttpClient's `UsernamePasswordCredentials`](http://www.baeldung.com/httpclient-4-basic-authentication)
- [Keycloak's OAuth request helper](https://github.com/keycloak/keycloak/blob/3.4.3.Final/adapters/oidc/spring-security/src/main/java/org/keycloak/adapters/springsecurity/client/KeycloakClientRequestFactory.java#L54).
