### ISSUE TITLE
Too many `segment_read_bytes` metrics updates on sealed segments

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2390]
**Problem description**
`segment_read_bytes` metrics are being sent for every single existing segment known to Pravega (even if the segment is sealed and no reads have been happening for days or weeks). 
As the number of segments only grows with time, the number of metrics grows too. 
In a testing environment with a **single** stream that experiences active scaling, we get 5000 segments after three days of starting a test, so 5000 metrics are being sent every 10 seconds on non-active segments. This overwhelms dcos-metrics package and leads to the loss of other metrics,  so the metrics from the active segments are not being sent further and are not being processed.

**Problem location**
Segmentstore metrics

**Suggestions for an improvement**
Send the `segment_read_bytes` metrics only when there are active reads happening from the segment.

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Too many updates of `segment_read_byte metrics` on sealed segments.](https://trello.com/c/Pm2u6nwn/27-too-many-updates-of-segmentreadbyte-metrics-on-sealed-segments)
