### ISSUE TITLE
RetryHelperTest.testLoopWithDelay relies on system clock.

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2392]
**Problem description**
`RetryHelperTest.testLoopWithDelay` fails occasionally with:
```
io.pravega.controller.util.RetryHelperTest > testLoopWithDelay FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.pravega.controller.util.RetryHelperTest.testLoopWithDelay(RetryHelperTest.java:123)
```
**Problem location**
RetryHelperTest.testLoopWithDelay

**Suggestions for an improvement**
One or more of these may work:
1.Do not use System clock, but some counter
2. Use System.nanoTime, since it has higher precision.
3. Delay more than 1 second and when comparing, add some buffer (i.e., compare with 0.9 seconds)

**Comment by shiveshr** [comment]
> 1.Do not use System clock, but some counter
The Retry class uses System clock for rescheduling the delay. 

> 2. Use System.nanoTime, since it has higher precision.
This will work. But I think along with this we should also add "greater than or equal to" comparison. 

> 3. Delay more than 1 second and when comparing, add some buffer (i.e., compare with 0.9 seconds)
This will not be correct check.
