### ISSUE TITLE
Pravega Security: Support auth handler configuration

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2396]
**Problem description**
One possible way to configure an auth plugin is to load configuration files from the classpath.   Another would be to support arbitrary name-value pairs in Pravega's `SecurityConfig`.

**Suggestions for an improvement**
Consider adding a `pluginconf` directory to the classpath.   Ideally the conf would be easily injectable by Kubernetes via a `ConfigMap` [(ref)](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume).

Note that the current solution of using a wildcard (e.g. `pluginlib/*`) does not allow for a loose config file AFAIK.  During some prototyping, I was forced to do the following:
`CLASSPATH=$APP_HOME/pluginlib/*:$APP_HOME/pluginlib`

**Comment by arvindkandhare** [comment]
@EronWright can you confirm whether the config is picked up once #2452 is merged?

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Security and grpc fixes/enhancements.](https://trello.com/c/RARjbNat/31-security-and-grpc-fixes-enhancements)
