### ISSUE TITLE
SelfTest tool reads not working

### ISSUE THREAD

**Issue by ack72tdp** [pravega/pravega#2421]
**Problem description**
Sleftest tool reads functionality is broken.

**Problem location**
SelfTest reads

**Suggestions for an improvement**
Perhaps due to recent changes in  pravega read code path, it appears that selftest tool may need re-compile or fix references.

**Comment by andreipaduroiu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing issues to support perf testing](https://trello.com/c/T2hnw40H/29-fixing-issues-to-support-perf-testing)
