### ISSUE TITLE
Configure default repoUri for mkdocs

### ISSUE THREAD

**Issue by vijikarthi** [pravega/pravega#2423]
**Problem description**
Flink connector project is making use of Pravega dependency as a git sub-module snapped at a specific commit version. The introduction of `mkdocs` plugin in Pravega is causing build issue in `flink-connector` project since the plugin is not able to resolve the project repo URI 

https://github.com/pravega/pravega/blob/master/build.gradle#L27

**Problem location**

The plugin appears to break when applied to a project that is checked out as a git sub-module (as is the case for Pravega in the connector repository).   This is due to a slight variation in how the `.git` directory works.

**Suggestions for an improvement**
The `mkdocs` plugin breaks when attempting to discover the origin uri of the source repository for which documentation is being generated.  This appears to be for informational purposes only.  By default the plugin inspects the git remotes to find `origin`, i.e. `https://github.com/pravega/pravega.git`.

A simple workaround is to explicitly configure the repo uri so that the faulty discovery logic isn't exercised.   Update `mkdocs.gradle` ([ref](https://github.com/pravega/pravega/blob/master/gradle/mkdocs.gradle#L17)) to include a  `repoUri` block that points to the Pravega source repository.  e.g. 
```
mkdocs {
    sourcesDir = "$rootDir/documentation/src"
    buildDir = "$rootDir/documentation/generated"
    updateSiteUrl = false
    publish {
            repoUri = "https://github.com/pravega/pravega.git"
    }
}
```

The underlying plugin code may be seen [here ](https://github.com/xvik/gradle-mkdocs-plugin/blob/master/src/main/groovy/ru/vyarus/gradle/plugin/mkdocs/MkdocsPlugin.groovy#L61) and [here](https://github.com/xvik/gradle-mkdocs-plugin/blob/master/src/main/groovy/ru/vyarus/gradle/plugin/mkdocs/MkdocsPlugin.groovy#L153).

**Comment by Prabha-Veerubhotla** [comment]
https://github.com/pravega/pravega/pull/2424

**Comment by vijikarthi** [comment]
My understanding is that `repo_url` is used by the plugin to provide a link to the project repository from the documentation site (pages).
