### ISSUE TITLE
SegmentRange.getScopeName() returns the scoped named of the stream.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2425]
**Problem description**
SegmentRange.getScopeName() should return the scope name.

**Problem location**
SegmentRangeImpl

**Suggestions for an improvement**
Return scope name instead of the scopedName of the stream.

**Comment by EronWright** [comment]
Just a comment, the phrase "scoped name" is a bit confusing to me because "scoped" often means "in the context of".  I think a better phrase would be "fully-qualified".   A fully-qualified stream name would be "scope1/stream1", versus an unqualified name of "stream1".
