### ISSUE TITLE
Generalize transaction segments to be first class segments

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2439]
**Problem description**
Generalize transaction segments to be first class segments such that:
1. Remove the notion of parent segment. From the POV of the Segment Store, Transaction segments are the same as regular segments. 
2. Any segment can be merged in any other segment, as long as they are both mapped to the same SegmentContainer and the source segment is not truncated. 
3. For this, implement segment naming scheme as described in [PDP24](https://github.com/pravega/pravega/wiki/PDP-24:-Rolling-Transaction)

NOTE: this relaxes some constraints in the Segment Store, making it more flexible from the POV of mergers. This also relaxes some constraint verifications, which will now be the sole responsibility of the Controller. For example, since transactions are no longer tied to a segment, it is up to the controller to guarantee that transactions will be on the same Container as the segment they will ultimately be merged into.

**Problem location**
Segment Container

**Suggestions for an improvement**
Implement this ability as precursor for rolling transactions.

**Comment by andreipaduroiu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rolling Txn: Segment Store Stuff](https://trello.com/c/h2I4VJtZ/28-rolling-txn-segment-store-stuff)
