### ISSUE TITLE
Server-Client exception correlation

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2451]
**Problem description**
Many times we get a failure server-side (Segment Store or Controller), record a stack trace or error message in the server-side logs, and another error/stack trace in the client. Most of the times we know about an error from the client logs, however the information logged there has no correlation or otherwise any information about what went wrong on the server side.

**Problem location**
Client, Controller, Segment Store.

**Suggestions for an improvement**
Server-side, Both of these should be done:
- Generate a UUID with every exception that bubbles up to the Wire Protocol (or gRPC layer in Controller). Log this with the exception and stack trace, and send it back to the Client.
- Capture the stack trace (including causes, suppressed exceptions, etc) and send it back to the Client.

Client-side:
- Record whatever extra information came back from the server in the client logs.

The UUID will help us do a quick correlation (a simple `grep` command) will quickly pinpoint the location in the server logs where the fault originated. We get the UUID from the client logs and search in the server logs.

The stack trace, although a bit redundant since we also have the UUID, may help speed diagnosing the problem, since we can quickly see where the fault originates from, server-side.

**Comment by RaulGracia** [comment]
Closed via #2901.
