### ISSUE TITLE
Improvements to the project documentation

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#2461]
**Problem description**
There is a set of minor issues that may improve the documentation of the project (especially for first time readers).

**Problem location**
Doc.

**Suggestions for an improvement**
I attach a review with the specific comments on the documentation.
[Pravega docs review.txt](https://github.com/pravega/pravega/files/1902722/Pravega.docs.review.txt)

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [improve pravega.io docs and fix broken links](https://trello.com/c/6BAdlYct/48-improve-pravegaio-docs-and-fix-broken-links)
