### ISSUE TITLE
Implement hashcode() and equals() method for SegmentRange

### ISSUE THREAD

**Issue by vijikarthi** [pravega/pravega#2463]
**Problem description**
There are situations where `SegmentRange` implementation could be used in Collections (composite reference inside some container class) and requires the objects to be comparable. Since the current implementation does not override equals/hashcode methods, any classes that is making use of SegmentRange is forced to implement the equals/hashcode methods which might create a problem if and when the SegmentRange code evolves.  

**Problem location**
`SegmentRange` implementation class

**Comment by shrids** [comment]
Closing this as the latest SegmentRangeImpl has equals and hashcode implemented.
ref: https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/batch/impl/SegmentRangeImpl.java#L29
