### ISSUE TITLE
PDP 24: Rolling Transaction Segment Store changes

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2468]
**Problem description**
To support the scheme described in PDP 24, we need following support from segment store:

A segment should have a primary id and a secondary id to uniquely identify the segment. 
Primary id will be used to identify segment container mapping while primary+secondaryId(optional) has to be unique for a segment. 
- Update all segment store apis to  take segmentId of the above form (segmentId = scope+stream+primary+secondaryId). 
-  CreateSegment Api to take primary and secondary id for a segment
```CreateSegment(String scope, String stream, int segmentPrimaryId, UUID segmentSecondaryId, isTransaction = false)```

- CreateTransaction Api should be decoupled from parent segment. Basically replace it with createSegment where we simply tell segment store that its a transactional segment. 
Important: transaction segment will have no parent. So a transaction can be created irrespective of state or presence of any potential sibling segment (that share same primary id). 
```CreateSegment(String scope, String stream, int segmentPrimaryId, UUID segmentSecondaryId, isTransaction = true)```

**Problem location**
Segment Store

**Suggestions for an improvement**
Implement new segment id scheme.

**Comment by andreipaduroiu** [comment]
Let's track this in #2439.
