### ISSUE TITLE
Standardize the Pravega URI schemes

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2477]
**Problem description**
When configuring a client to connect to Pravega, one uses an URI with a scheme that indicates whether to make an SSL connection and whether to employ discovery.   For some of those scenarios we use `tcp://` and `tls://`, which I believe is a problem.   It would never be possible to register those schemes with IANA, and is against the recommendations of [RFC-7595](https://tools.ietf.org/html/rfc7595#section-3.8) (_Guidelines and Registration Procedures for URI Schemes_):

> Schemes SHOULD NOT use names that are either very general purpose or
   associated in the community with some other application or protocol.
   Schemes also SHOULD NOT use names that are overly general or
   grandiose in scope (e.g., that allude to their "universal" or
   "standard" nature).

To reduce the number of schemes in play, could discovery always be employed or configured in another way?  Is there a true need to bypass discovery in some cases? 

**Suggestions for an improvement**
- Use only `pravega://` and `pravegas://` for the gRPC endpoint.
- Update samples accordingly.

**Comment by EronWright** [comment]
@fpj would you mind giving this some consideration, because it will be more difficult to change later.

**Comment by fpj** [comment]
We already use `pravega://` and `pravegas://`, see here:

https://github.com/pravega/pravega/blob/e514e780d1cbdb9f502eb17a782cafcb859d0b09/client/src/main/java/io/pravega/client/stream/impl/ControllerResolverFactory.java#L55

I'm not sure why you say that they are not recommended schemes as `tcp://`, for example, as I understand it, maps to a grpc resolver plugin.

**Comment by EronWright** [comment]
My point is about the fact that there's `tcp://` *and* `pravega://` to consider.

**Comment by ravisharda** [comment]
Closing this issue after a prolonged period of inactivity.
