### ISSUE TITLE
Explore on upgrading bookkeeper version to 4.6.2

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2480]
**Problem description**
The latest stable version released by apache bookkeeper is `4.6.2`. 
We need to check if we can upgrade from `4.5.0` ( our current version) to `4.6.2`

**Problem location**
Bookkeeper version 

**Suggestions for an improvement**
Make sure all the integration tests, system tests pass and deployment is stable.

**Comment by andreipaduroiu** [comment]
I think we should skip over this and go straight to 4.7, which is the latest.
