### ISSUE TITLE
Intermittent failure in NullPointerException in MetricsProviderTest.testGauge on travis

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2496]
**Problem description**
```
io.pravega.shared.metrics.MetricsProviderTest > testGauge FAILED
    java.lang.NullPointerException
        at io.pravega.shared.metrics.MetricsProviderTest.testGauge(MetricsProviderTest.java:113)
```

**Problem location**
`io.pravega.shared.metrics.MetricsProviderTest.testGauge`

**Suggestions for an improvement**
Try to repro and fix this issue.

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Intermittent failure of MetricsProviderTest.testGauge on travis](https://trello.com/c/liRtb5eD/35-intermittent-failure-of-metricsprovidertesttestgauge-on-travis)
