### ISSUE TITLE
Fix standalone distribution to include a conf directory

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2497]
**Problem description**
The distribution output from the `standalone` project doesn't produce a usable distribution.   An error occurs due to a missing configuration file:
```
λ gradlew installDist
λ cd standalone\build\install\pravega-standalone
λ bin\pravega-standalone.bat
...
java.io.FileNotFoundException: C:\pravega\standalone\build\install\pravega-standalone\bin\..\conf\standalone-config.properties (The system cannot find the path specified)
```

**Problem location**
`build.gradle`

**Suggestions for an improvement**
add a default configuration to `standalone/src/main/dist/conf/`:
- `standalone-config.properties`
- `logback.xml`

**Comment by EronWright** [comment]
@arvindkandhare this is follow-up from the earlier PR

**Comment by arvindkandhare** [comment]
Thanks. Will take this up.

**Comment by arvindkandhare** [comment]
Please note that `./gradlew installdist` installs the standalone bins in `.\build\install\` and that's the way to access all the distributions. You are looking at a wrong place `standalone\build\install\pravega-standalone`. Though all the individuals components have their own `installdist` they do not create complete runnable solution.
Do let me know whether this solution works for you. If you need specifically `./gradlew :standalone:installdist` to work, we can fix  that.

**Comment by EronWright** [comment]
While it is certainly a best practice for each project's distribution output to be well-formed and fully functional, using the top-level distribution would be fine.   I would have thought that the top-level distribution was simply a composite of the various project's distribution output.

**Comment by fpj** [comment]
My understanding from the discussion is that the issue is resolved. Please reopen if this is still an issue.
