### ISSUE TITLE
Add Kubernetes deployment option

### ISSUE THREAD

**Issue by elgalu** [pravega/pravega#2498]
**Suggestions for an improvement**
Would be nice to have Kubernetes as a deployment option inside this repository at https://github.com/pravega/pravega/tree/master/deployment

I'm pretty sure someone in the community has done this already. Perhaps @EronWright ?

It should be linked at: https://github.com/pravega/pravega/blob/master/documentation/src/docs/deployment/deployment.md#installation

**Comment by fpj** [comment]
@elgalu thanks for poking us on this, you are absolutely right that we should provide the option.
