### ISSUE TITLE
Segment store should let tier2 implementation know the size of the cluster

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2501]
**Problem description**
This issue came out of discussions from #2401.
According to this comment: https://github.com/pravega/pravega/pull/2401#discussion_r184076411
it will be easy to limit the number of loops if segmentstore could send the size of cluster to tier-2 and update it every time it changes.

**Problem location**
segmentstore - tier-2 mapping.

**Suggestions for an improvement**
Add API to `SyncStorage` interface to set and update the cluster size.

**Comment by andreipaduroiu** [comment]
This seems like a one-off solution to fix one particular problem in one particular Tier2 implementation. There is no reason the Tier2 adapter should be aware of any details above its "paygrade". The "size of the cluster" is definitely one of them. Also, what is the size of the cluster? Number of segment store instances, number of containers? The former can change every other minute, and the latter really does not need to be injected into the Tier2 adapters. 

I suggest we find another solution to the problem that triggered this "issue".

**Comment by arvindkandhare** [comment]
Yes. The assessment makes sense. I agree with the observations. Let's discuss this further and figure out the best way to fix this issue.

> This seems like a one-off solution to fix one particular problem in one particular Tier2 implementation. There is no reason the Tier2 adapter should be aware of any details above its "paygrade". The "size of the cluster" is definitely one of them. Also, what is the size of the cluster? Number of segment store instances, number of containers? The former can change every other minute, and the latter really does not need to be injected into the Tier2 adapters.
> 
> I suggest we find another solution to the problem that triggered this "issue".

**Comment by arvindkandhare** [comment]
As discussed in the earlier pull requests, the correct owner will get the ower ship after this loop goes on for a number equal to the numbers of segmentstores in the race. The upper bound for this is the number of segmentstores in the deployment. 
It is a major change in the segmentstore to pass this value. Also these details are not necessary for a tier-2 stoarge to know.
I think a compromise can be where we keep the number of retries high enough that the number of segmentstores in a deployment never passes this number. It can be either a very high integer (e.g. 50000 or can be `MAX_INT`). @andreipaduroiu @fpj do let me know how this sunds.

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Security and grpc fixes/enhancements.](https://trello.com/c/RARjbNat/31-security-and-grpc-fixes-enhancements)

**Comment by fpj** [comment]
> The correct owner will get the ownership after this loop goes on for a number equal to the numbers of segmentstores in the race. The upper bound for this is the number of segmentstores in the deployment.

That's what I have understood from the discussion around the pull request we merged to fix the fencing issue for HDFS.

> It is a major change in the segmentstore to pass this value. Also these details are not necessary for a tier-2 storage to know.

It depends, if the strategy depends on the size of the cluster, then we need the size of the cluster.

> I think a compromise can be where we keep the number of retries high enough that the number of segmentstores in a deployment never passes this number. It can be either a very high integer (e.g. 50000 or can be MAX_INT). @andreipaduroiu @fpj do let me know how this sounds.

Guessing a very large value that covers all possible scenarios ever opens up to cases in which we can be looping for a long time, and that is clearly undesirable from an availability angle. I'd rather be precise about the condition we use to end the loop, releasing or taking ownership.

**Comment by arvindkandhare** [comment]
As discussed earlier, this loop will never to more than number of segmentstores in race. I agree that it is ideal to get either this number or the higher bound for this (total number of segmentstore in the deployment).
Let's see the scenario when this race will happen. It needs reassignment of the container to multiple segmentstores. This will happen only when a large number of segmentstore are going up and down. In this scenario there is always an availability issue. This loop will not add more complexity to the availability.
So this fix is a good compromise which achieves the same goal without requiring a major change in the tier2 interface.

**Comment by arvindkandhare** [comment]
Here is a reference to the discussion thread that is important in closing this. It was agreed that each host looping till its epoch is enough to ensure that the race is resolved and there is no possibility of segmentstore looping for a large count: https://github.com/pravega/pravega/pull/2525#discussion_r186039912
