### ISSUE TITLE
Too many transaction metrics

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2526]
**Problem description**
We are running a `smallTx` test that creates about one transaction per second (half of them committed, another half aborted), and we are noticing that all clusters that run this test would have big gaps in the metrics charts.
Turns out, there are about 8,000 transaction metrics being emitted every ten seconds (while there would be only 10 transactions happening every 10 seconds).
As a result, DCOS metrics component is not able to process everything, and the useful metrics are not coming through.

The excess transaction metrics are of the kind: `pravega.segmentstore.segment_write_bytes.hulk.smallTx.0#transaction.019c5af8a04b4028829514f291a48044.Counter:7351`(repeated for 10 time beats) or `pravega.segmentstore.segment_write_events.hulk.smallTx.0#transaction.001bd9271b6242c0947bd57e25c14fd0.Counter:10` (repeated for 7 time beats).

**Problem location**
Segmentstore metrics

**Suggestions for an improvement**
Reduce the number of transaction metrics.
Please consider either including the corresponding numbers into the general `segment_write_bytes` and `segment_write_events` metrics on the stream segment, or having separate transactional metrics based on stream segment only, without any UUID fields.

**Comment by shengkaisun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Too many transaction metrics](https://trello.com/c/q6LXlVDn/36-too-many-transaction-metrics)

**Comment by Prabha-Veerubhotla** [comment]
https://github.com/pravega/pravega/issues/2570
