### ISSUE TITLE
Read/writes cease after a scaling event on the stream

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2528]
**Problem description**
When trying to write and read from a stream with the scaling triggered by event rate, we are observing all the reads and writes cease after the initial segment has experienced two to four scaling rounds (right after a major scaling round). We have multiple writers and readers on the stream, and all of them report as healthy. However, no writes happen anymore (the readers are tail readers, so there is nothing to read for them).
There are no visible major errors in pravega logs around the time of the failure.
After the failure, the stream would scale down to one segment, in accordance with no writes happening to it.

We are using this [commit](https://github.com/pravega/pravega/commit/10f7a4559aea762232c01e831071f4723d68a91a) of Pravega.

![stopped_writes](https://user-images.githubusercontent.com/25368596/39446826-2aaee1a0-4c96-11e8-97a9-c4f3f344a6e4.png)

**Problem location**
Client?

**Suggestions for an improvement**
The writers should not stop writing to a stream.

**Comment by shiveshr** [comment]
can you please share client and controller logs. Want to confirm if successor segments are being processed correctly.

**Comment by jkhalack** [comment]
Would these files work? 
[stdout.controller-0.log](https://github.com/pravega/pravega/files/1963670/stdout.controller-0.log)
[stdout.controller-1.log](https://github.com/pravega/pravega/files/1963671/stdout.controller-1.log)
[controller_server_2018-04-30.4.log](https://github.com/pravega/pravega/files/1963674/controller_server_2018-04-30.4.log)

**Comment by jkhalack** [comment]
Example of another run.
You can see that the writes stopped right after a scaling event (here segments 13 and 14 merged into into segment 15 after 10:15:30 chart time, that is 13:15:30 logs time 
![stopped_scaling](https://user-images.githubusercontent.com/25368596/39474368-0b18c9d4-4d2a-11e8-8b76-88c0a3c11be4.png)

There is another peculiarity: the reported writes go down with every scaling (the writers are expected to write at a constant rate with our test):
![writer_metrics_down](https://user-images.githubusercontent.com/25368596/39474663-70b0c8e0-4d2b-11e8-8e89-1f7215dea034.png)

The controller logs (there are two controllers in the cluster):
[stdout_2.controller-0.log](https://github.com/pravega/pravega/files/1963895/stdout_2.controller-0.log)
[stdout_2.controller-1.log](https://github.com/pravega/pravega/files/1963896/stdout_2.controller-1.log)

And the client log:
[controller_server_2018-05-01.6.log](https://github.com/pravega/pravega/files/1963903/controller_server_2018-05-01.6.log)

**Comment by shiveshr** [comment]
@jkhalack controller logs have nothing interesting in them. Its all business as usual.. 
last relevant logs suggest writers found segment 5 to be sealed and requested for the successor (11, 12).
I see getUri being requested for 11, 12 and there are no error logs.. 
so probably as @tkaitchuck suggests, writers may not be able to write to 11 and 12 despite getting the correct URI.

I also tried running a set up locally against latest build but could not reproduce the problem.

**Comment by jkhalack** [comment]
Here is a client thread dump from another cluster that stopped writes a few hours ago. 
Please, let me know if you need fresh logs.

[thread_dump.log](https://github.com/pravega/pravega/files/1967445/thread_dump.log)

**Comment by tkaitchuck** [comment]
I think that is all the logs I need.
Can you tell me, in that run: how many **EventStreamWriter**s are instantiated?

**Comment by jkhalack** [comment]
There should be 3 writers on `smallScale` stream (also the last cluster for the thread dump has one writer on `smallTx` stream).

**Comment by jkhalack** [comment]
https://github.com/pravega/pravega/pull/2548 has not fixed our issue.
