### ISSUE TITLE
Revision Client cannot be closed

### ISSUE THREAD

**Issue by BenWang91** [pravega/pravega#2547]
**Problem description**
After RevisionedStreamClient.close() is called, the connections between client and controller, segmentstore are still established. They should be closed.

**Comment by BenWang91** [comment]
I can easily reproduce this by 
public class TestReproduce {

	private static final String ENDPOINT = "tcp://10.240.124.145:9091";
	private static final String SCOPE = "TestScope" + UUID.randomUUID().toString().split("-")[0];
	private static final String STREAM = "TestScope" + UUID.randomUUID().toString().split("-")[0];

	@Test
	public void test() throws Exception {
		URI controller = new URI(ENDPOINT);
		StreamManager streamManager = StreamManager.create(controller);
		streamManager.createScope(SCOPE);
		StreamConfiguration streamConfig = StreamConfiguration.builder()
				.scalingPolicy(ScalingPolicy.fixed(1))
				.build();
		streamManager.createStream(SCOPE, STREAM, streamConfig);
		ClientFactory clientFactory = ClientFactory.withScope(SCOPE, controller);
		RevisionedStreamClient<String> client =
				clientFactory.createRevisionedStreamClient(STREAM, new JavaSerializer<>(),
						SynchronizerConfig.builder().build());
		client.close();
		while (true) {

		}
	}
}

Then check the netstat on client side. We can find out that connections are still established.

**Comment by shrids** [comment]
Modifying the above code to include close for streamManager and clientFactory closes all additional sockets which are open.
```
        client.close(); // already present in the code.
        clientFactory.close(); //newly added
        streamManager.close(); //newly added.
```

**Comment by shrids** [comment]
We need to modify the above code to include close for streamManager and clientFactory closes all additional sockets which are open.
```
        client.close(); // already present in the code.
        clientFactory.close(); //newly added
        streamManager.close(); //newly added.
```
Currently clientFactory.close() does not close the controller client which is created internally `ClientFactory.withScope(SCOPE, controllerURI)` , 
will raise a PR to fix this issue.
