### ISSUE TITLE
Cleanup serializable use on client.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#256]
We use serializable on the client for:
Revision, Position, EventPointer, TransactionId, and others.
We should standardize on a pattern. This may include `asString()` and `fromString()` on the interface.

**Comment by giorgio-v** [comment]
A quick grep for `Serializable` reveals the following classes. Assuming that not all of these need to implement `Externalizable`, could you please complete the list sketched in the summary?
- `client/src/main/java/io/pravega/client/segment/impl/Segment.java`
- `client/src/main/java/io/pravega/client/state/SynchronizerConfig.java`
- `client/src/main/java/io/pravega/client/state/impl/RevisionImpl.java`
- `client/src/main/java/io/pravega/client/state/impl/UpdateOrInitSerializer.java`
- `client/src/main/java/io/pravega/client/stream/Checkpoint.java`
- `client/src/main/java/io/pravega/client/stream/EventPointer.java`
- `client/src/main/java/io/pravega/client/stream/EventWriterConfig.java`
- `client/src/main/java/io/pravega/client/stream/Position.java`
- `client/src/main/java/io/pravega/client/stream/ReaderConfig.java`
- `client/src/main/java/io/pravega/client/stream/ReaderGroupConfig.java`
- `client/src/main/java/io/pravega/client/stream/RetentionPolicy.java`
- `client/src/main/java/io/pravega/client/stream/ScalingPolicy.java`
- `client/src/main/java/io/pravega/client/stream/Sequence.java`
- `client/src/main/java/io/pravega/client/stream/Stream.java`
- `client/src/main/java/io/pravega/client/stream/StreamConfiguration.java`
- `client/src/main/java/io/pravega/client/stream/impl/ByteArraySerializer.java`
- `client/src/main/java/io/pravega/client/stream/impl/ControllerImplConfig.java`
- `client/src/main/java/io/pravega/client/stream/impl/JavaSerializer.java`
- `client/src/main/java/io/pravega/client/stream/impl/ReaderGroupState.java`
- `client/src/main/java/io/pravega/client/stream/impl/SegmentWithRange.java`
- `client/src/main/java/io/pravega/client/stream/impl/StreamCut.java`
- `client/src/test/java/io/pravega/client/state/examples/MembershipSynchronizer.java`
- `client/src/test/java/io/pravega/client/state/examples/SetSynchronizer.java`
- `client/src/test/java/io/pravega/client/state/impl/SynchronizerTest.java`
- `client/src/test/java/io/pravega/client/stream/impl/JavaSerializerTest.java`
- `common/src/main/java/io/pravega/common/cluster/Host.java`
- `controller/src/main/java/io/pravega/controller/store/checkpoint/ZKCheckpointStore.java`
- `controller/src/main/java/io/pravega/controller/store/host/ZKHostStore.java`
- `controller/src/main/java/io/pravega/controller/store/task/LockData.java`
- `controller/src/main/java/io/pravega/controller/task/Stream/StreamMetadataTasks.java`
- `controller/src/main/java/io/pravega/controller/task/Stream/TestTasks.java`
- `controller/src/main/java/io/pravega/controller/task/TaskBase.java`
- `controller/src/main/java/io/pravega/controller/task/TaskData.java`
- `controller/src/test/java/io/pravega/controller/task/TaskTest.java`
- `shared/controller-api/src/main/java/io/pravega/shared/controller/event/ControllerEvent.java`
- `test/integration/src/test/java/io/pravega/test/integration/StateSynchronizerTest.java`
- `test/integration/src/test/java/io/pravega/test/integration/TransactionTest.java`
- `test/system/src/test/java/io/pravega/test/system/MultiSegmentStoreTest.java`
- `test/system/src/test/java/io/pravega/test/system/PravegaTest.java`

**Comment by tkaitchuck** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use custom serialization with versions on client](https://trello.com/c/7EydTLbn/7-use-custom-serialization-with-versions-on-client)

**Comment by EronWright** [comment]
Please continue to implement `java.io.Serializable` on all client-side config classes and interfaces.

The rationale is that Pravega config objects, e.g. `Stream`, may reasonably be field values of user classes that are serializable.   For example, the `FlinkPravegaReader` contains Pravega config objects and is serializable for Flink's purposes.

**Comment by tkaitchuck** [comment]
Resolved in https://github.com/pravega/pravega/pull/2514
