### ISSUE TITLE
REST api - TLS connection was non-properly terminated

### ISSUE THREAD

**Issue by hldnova** [pravega/pravega#2566]
**Problem description**
How to reproduce (with pravega master as of 5/9/2018).

Enable TLS in standalone-config.properties
```
singlenode.certFile=../config/cert.pem
singlenode.keyFile=../config/key.pem
singlenode.enableTls=true
```

Start with standalone pravega with 
```
gradlew startstandalone
```

Run the curl command below:
```
curl -v https://localhost:9091/v1/scopes
```
eventual the curl command times out with the following output
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9091 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
```

However,  request to http continues to work, e.g., `curl http://localhost:9091/v1/scopes` would still list the scopes.

**Problem location**

**Suggestions for an improvement**

**Comment by ravisharda** [comment]
After fixing the startup issue mentioned in issue #3228, I encountered a different error (listed below) than the one mentioned above when invoking the REST endpoint /v1/scopes using ``curl -v http://localhost:9091/v1/scopes``. Pull request [3235](https://github.com/pravega/pravega/pull/3235) made for #3228 also resolves this issue.

```
...@ubuntu:~$ curl -v https://localhost:9091/v1/scopes
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9091 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9091 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9091 

```

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2566 - REST API TLS termination](https://trello.com/c/2t6wIklm/6-2566-rest-api-tls-termination)
