### ISSUE TITLE
StreamCuts generated from ReaderGroups can have missing ranges

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2572]
**Problem description**
Take the following example:
epoch 0: S0 [0.0, 0.5), S1 [0.5, 1.0)
epoch 1: S2 [0.0, 0.6) , S3 [0.6, 1.0)

Readers in reader group may have read S1 completely while they may still be reading S0. 
In such cases, readers can continue reading from S3, while S2 will wait until S0 has been read completely. 

If a streamcut is generated at this point, then the stream cut will contain `(S0/offset, S3/offset)`. 
Which essentially means the key range covered in the StreamCut will be [0.0, 0.5), [0.6, 1.0). 

Such a stream cut will have a missing range of [0.5, 0.6). And it becomes hard to determine casual precedence wrt the stream cut for the missing range.
Hence it makes the stream cut inconsistent with the definition which states: 
```
 * A set of segment/offset pairs for a single stream that represent a consistent position in the
 * stream. (IE: Segment 1 and 2 will not both appear in the set if 2 succeeds 1, and if 0 appears
 * and is responsible for keyspace 0-0.5 then other segments covering the range 0.5-1.0 will also be
 * included.)
```
Note: what makes it harder here is that we do not have a segment that matches the missing keyspace. 
And current implementation of Stream Cut does not allow such partial range to be captured.
The missing range is implicit and readergroup can handle this cleanly. 
However, validation checks on partial streamcuts (those missing intermediate ranges) become harder. 

Also, with current implementation of streamcut which does not provide entire range, operations like apply streamcut on head of stream will yield segments without encompassing complete keyspace. 
**Problem location**
StreamCut

**Suggestions for an improvement**
Improve streamcut implementation such that we are explicitly capturing the entire keyspace.

**Comment by tkaitchuck** [comment]
I still need to think more about the larger issue being raised here. But:
>In such cases, readers can continue reading from S3, while S2 will wait until S0 has been read completely.
That is not actually the way they work at the moment. (Not that we can generate splits like this ATM anyway) but if we did the client as-is would wait until s0 was finished to start on either of them. (Although that is not by any special design)

**Comment by shrids** [comment]
With the above example, we cannot have a StreamCut of the pattern `(S0/offset, S3/offset)`. i.e S3 will be part of the unassigned segments only when both S0 and S1 have been completed. i.e. the StreamCut can be either 
`(S0/off, S1/off)` or `(S2/off, S3/off)`. (both of them cover the entire key range).

In case of a stream
```
epoch 0: S0[0.0, 0.5), S1[0.5. 1.0)
epoch 1: S0[0.0, 0.5), S2[0.5, 0,75), S3 [0.75, 1.0)
epoch 2 : S0[0.0, 0.5), S4([0.5, 1.0)
epoch 3 : S5[0.0, 1.0)
```
We could have a StreamCut which contains just `(S0/off)` which has a missing range, since the reader finished reading S1, S2, S3, S4.
