### ISSUE TITLE
Explore on enhancing the display of code blocks on pravega.io site

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2579]
**Problem description**
The code samples with in the pravega documentation on `www.pravega.io` are not up to the mark.
Needs to be improved using some of  the `markdown` features to display code blocks. 

**Problem location**
http://www.pravega.io/

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
I have updated the code under [this issue](https://github.com/pravega/pravega-samples/issues/73). Once the PR is reviewed, maybe it will be easier to update the documentation and keep consistent both sources.

**Comment by Prabha-Veerubhotla** [comment]
sure @RaulGracia .

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve format of code snippets in pravega.io docs](https://trello.com/c/ltMvtjJ4/39-improve-format-of-code-snippets-in-pravegaio-docs)

**Comment by Prabha-Veerubhotla** [comment]
After offline discussion with @RaulGracia, sending out the PR.
