### ISSUE TITLE
Writers stop writing one by one (threads locked)

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2614]
**Problem description**
We are running a scaling test (3 writers), scaling policy based on events rate, 20 routing keys, and the Pravega version from the following commit: https://github.com/pravega/pravega/commit/6a4bc6847ca64b73f63a11fac804d89da1628ab8
Often we see writers stop writing like in the following segment write heat map:
![writers_die](https://user-images.githubusercontent.com/25368596/40386006-e9ce8fb4-5dde-11e8-896d-6a137ab819f1.png)

It looks like the first writer (see the bottom part of the heat chart) stops writing in the middle of a segment,  without any scaling event happening to the segment. Later on, the rest of the writers stop writing. If a thread dump is performed after all the writes have stopped, a few locked threads are seen present.

The thread dump:
[Thread_dump_for__smallScale__client.txt](https://github.com/pravega/pravega/files/2028315/Thread_dump_for__smallScale__client.txt)

Controller-server log for the client (the first writer would stop writing around 11:20 log time):
[controller-server_smallScale_vision_.log](https://github.com/pravega/pravega/files/2028371/controller-server_smallScale_vision_.log)

**Problem location**
Client

**Suggestions for an improvement**
The writers should not stop writing

**Comment by tkaitchuck** [comment]
If possible can this be run on this branch?
https://github.com/pravega/pravega/compare/master...tkaitchuck:logging?expand=1

**Comment by tkaitchuck** [comment]
What is interesting is that the first writer stops at 11:22 which is when ScalingRetransmition-hulk/smallScale-2 is running, but that thread is gone by the time of the thread dump and has been replaced with ScalingRetransmition-hulk/smallScale-3 which did not start until after 11:30 when the other two segments stopped. So while from the thread dump it looks simple like the flush() call in ScalingRetransmition-hulk/smallScale-3 is holding up everything, the blocking actually started before that happened. It couldn't have caused it. The only way I can make sense as to what happened is to infer that the writer on one segment was blocked at 11:22 somehow... and that only later when that 3'rd split occurred did all the segments get blocked.
