### ISSUE TITLE
Non-determinism in RevisionDataOutputStreamTests

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2626]
**Problem description**
In RevisionDataOutputStreamTests it called String.getBytes() and assumed the result would be the same length across machines. This is not the case because the default charset varies.

**Problem location**
RevisionDataOutputStreamTests

**Suggestions for an improvement**
Fix the charset, and generalize the code to calculate the length correctly regardless.

**Comment by andreipaduroiu** [comment]
This was fixed with #2627
