### ISSUE TITLE
Wrong (too low) segment_read_bytes metrics

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2659]
**Problem description**
For streams with one reader group of tail reader the calculated read byte rates are always lower than write byte rates. 
Looking at the `segment_read_bytes` counter emitted by the segment stores (top chart), we can see that it is much lower than the `segment_write_bytes` counter (bottom_chart):
![tiny_read_bytes](https://user-images.githubusercontent.com/25368596/40940486-58c10fd4-681e-11e8-8e4d-66bf636dde90.png)
![tiny_write_bytes](https://user-images.githubusercontent.com/25368596/40940588-aa90ac70-681e-11e8-814f-eef3b0548ac4.png)

These two charts are for a stream with one segment and a fixed number of segments.
The reader clients report that they read the same amount of bytes as was written by writer clients (and reported by `segment_write_bytes` metrics counter). 
The problem is only with `segment_read_bytes`  metrics.

**Problem location**
Segment store, `segment_read_bytes` metrics

**Suggestions for an improvement**
Segment stores should report correct `segment_read_bytes` metrics

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wrong segment_read_bytes metrics](https://trello.com/c/r8TyFsw8/47-wrong-segmentreadbytes-metrics)
