### ISSUE TITLE
Publish Pravega 0.3.0 snapshot binary distribution

### ISSUE THREAD

**Issue by hldnova** [pravega/pravega#2666]
**Problem description**
To develop and test latest pravega client applications, e.g., flink or hadoop connectors, it is more convenient to just down the binary then compiling pravega locally. 

**Problem location**

**Suggestions for an improvement**
Ideally, the pravega **Getting Started** guide (http://pravega.io/docs/latest/getting-started/) should be updated. Some of the pravega/flink connector samples have been updated to require latest pravega and they may have links to Pravega getting started guide that is no longer compatible.

**Comment by vijikarthi** [comment]
For publishing the `standalone` binaries, we could add these lines to the `standalone` project configuration and it will take care of publishing the compressed artifacts to repository.

```
    distributions {
        main {
            contents {
                duplicatesStrategy = "exclude"
                from("../dist/conf") {
                    into "conf"
                }
                from("../config") {
                    into "conf"
                }
            }
        }
    }

    def standaloneBinaryArchive = artifacts.add('archives', file("$project.buildDir/distributions/pravega-standalone-${version}.tgz")) {
        builtBy('assembleDist')
    }

    tasks.withType(Tar){
        compression = Compression.GZIP
    }

    artifacts {
        archives standaloneBinaryArchive
    }
```
