### ISSUE TITLE
Etcd/Consul support

### ISSUE THREAD

**Issue by thedrow** [pravega/pravega#2687]
**Problem description**
ZooKeeper is a software many, many sysadmins and DevOps engineers prefer to avoid.
Whether justified or not, ZooKeeper is the reason why people recommend avoiding Kafka until it is absolutely necessary.

**Problem location**
Service Coordination.

**Suggestions for an improvement**
Add alternative backends for Etcd and/or Consul which will allow users to deploy less intimidating software.

**Comment by fpj** [comment]
Thanks for the feedback, @thedrow. We will keep it in mind for the future, and otherwise, feel free to contribute such implementations in the case you are interested.
