### ISSUE TITLE
Revisit header marshalling in PravegaInterceptor

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2711]
**Problem description**
I'd like to propose that we revisit the logic here:

https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L52

The three potential problems I see with this line of code are the following:
1- It is indistinctly adding ASCII headers to `paramMap`, independent of whether we need it for authentication. Perhaps we are not using ASCII headers for anything else today, but if we decide to change it in the future, then we might have a bug here.
2- It is unclear what needs to happen in the presence of an `IllegalArgumentException`. Currently, we simply log it and move on, but I wonder if this can even be a security vulnerability. If the argument is illegal for a header that is supposedly used for authentication, then we seem to be allowing it to proceed. If the header is to be used for authentication, then the right course of action is to not allow it to proceed in the case of an illegal argument.
3- The log message is printing the stack trace, and I'm not sure how helpful that is. This is on the controller side, so I assume it will be seen by an operator. I'd think that we need a log message that is more specific about what has gone wrong. We should perhaps print some information about the specific header that failed to parse. 

**Problem location**
`PravegaInterceptor`, Controller.

**Suggestions for an improvement**

**Comment by EronWright** [comment]
Related: #2384

**Comment by ravisharda** [comment]
@fpj, the issues mentioned above in the problem description do not seem to apply anymore to the latest code. They seem to have been fixed already. Could you please recheck and close the issue if you concur?

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2711 - Header Marshalling](https://trello.com/c/DHoR0mWt/3-2711-header-marshalling)

**Comment by fpj** [comment]
By the time this issue was reported, the code looked like this:

https://github.com/pravega/pravega/blob/b9e01566ee45fd40d12f7375976340469a84b517/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L52

And now it has changed to this:
https://github.com/pravega/pravega/blob/9a734d273a51fed757db327a8a67c8b373cc4da3/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L52

It does not seem to be applicable any longer.
