### ISSUE TITLE
Decouple TLS configs

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2731]
**Problem description**
In a realistic TLS-enabled deployment of Pravega into a containerized environment, the keystores and truststores to be used vary by endpoint.   For example, client-to-controller vs client-to-segmentstore.

The controller likely has a well-known FQDN and a certificate provided by the environment's CA.   Clients should typically use their system truststore to validate the controller's certificate.

The segmentstore likely has a self-signed certificate, since its FQDN is not known upfront, and the set of segmentstores varies elastically.  Clients should typically use a constrained truststore to validate the segmentstore certificate.

**Suggestions for an improvement**
1. Decouple the configuration of the various truststores.
2. Make it easy to have a different keystore for each segmentstore.

**Comment by arvindkandhare** [comment]
Ideally a client is talking to a Pravega deployment and not to a controller OR a segmentstore. This way specifying separate certs for controller and segmentstore looks like we are exposing Pravega internal design to the users.
I think we can support JKS (through #2376). Once we do this the deployment can be done more flexibly where user can deploy and manage controller and segmentstore certs the same way.

**Comment by arvindkandhare** [comment]
As discussed earlier, internal design of Pravega should not be exposed to the end user/admin. Closing this issue in favor of #2730. I think this is the right way to go.
