### ISSUE TITLE
Javascript Connector for NodeJS

### ISSUE THREAD

**Issue by eruiz** [pravega/pravega#2733]
**New Feature**
A Javascript connector to be able to connect to Pravega from Javascript based engines like NodeJS.

**Comment by fpj** [comment]
Thanks for the suggestion, @eruiz . We will look into it.

**Comment by AmreeshTyagi** [comment]
I still don't see any nodejs connector for this. 
Is there any alternative connector to connect to pravega from Nodejs or some other streaming tools has arrived to replace pravega?
