### ISSUE TITLE
EventStreamReader/Orderer avoid selecting segments for read that are sealed.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2739]
**Problem description**
We observe that when there is data available in a stream some segments are not read in a very long time. 
This is because they are preceded by a sealed segment. The seal has been 'encountered' in that segmentInputStreamImpl received the flag indicating it, and hence will no longer issue requests to fetch more data from the server. 
However the Orderer will not select this segment to read from because it has nothing in memory. (Which it can't have because there is no data left on the segment as it has all been read.)

Orderer round robins across the segments checking each in turn. If there are any segments with data, then those are selected. If there are none, it blocks on the segment for which the request was issued first in the rotation order. If it is called repeatedly, it will drain the contents of all of the segments in memory. On the following call, it will iterate over all of the segments and eventually block on the next segment after the one to have last returned it data. So if the segments are ordered such that all of the active segments are followed by either another active segment or an idle segment, and not a sealed segment then it will keep picking among the same set, never selecting one of the sealed segments.

**Problem location**
Orderer and SegemntInputStreamImpl

**Suggestions for an improvement**
SegmentInputStreamImpl.canReadWithoutBlocking() should return true if encounteredSegmentSealed

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1164: Clean up metadata of completed transactions](https://trello.com/c/9IMpoeYT/37-1164-clean-up-metadata-of-completed-transactions)
