### ISSUE TITLE
Segment_read_bytes metrics not always triggered at the first read from segment

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2740]
**Problem description**
For streams with autoscaling, the read byte rate we calculate from `segment_read_bytes` sometimes would go significantly below the write rate. At the same time our app shows that all written events have been read (there would be one writer group and one TAIL reader group on the stream, and the app shows number of writer group events equals to number of reader group events).
![write_read_rates](https://user-images.githubusercontent.com/25368596/42110517-bd9a2e7a-7bb7-11e8-8a28-57b0fb30d86c.png)

When checking on individual segment metrics (`segment_read_bytes` counter reported by pravega segment stores) in chronograf (we use TICK stack to collect and manage the metrics), it can be seen that for some of the segments the counter is not being reported until a few minutes into segment existence. The following image shows the `segment_read_bytes` counter in a  different color for each segments:
![read_segments](https://user-images.githubusercontent.com/25368596/42110558-ee07d738-7bb7-11e8-8a30-1e00ba79e451.png)

Picking out the segment number for one these peculiar `segment_read_bytes` counter curves, and comparing `segment_write_bytes` (also reported by the segment stores) to `segment_read_bytes` metrics for the same segment number (see the chart below for segment 194), it is possible to see that the write counter starts some time before the read counter. 
When the read counter starts being reported, it coincides with the write counter.
![segment_194](https://user-images.githubusercontent.com/25368596/42110646-5570b4da-7bb8-11e8-8fd2-0783c7bae696.png)

Since numbers reported by the client app for reads and writes are being practically equal at all times, it looks like the segment read metrics are simply not being reported for some period of time.

Also we can be sure that it is not all reads happening at once a few minutes into segment existence. Such a delay would be reported by our test app as a reader lag (the actual reader lag reported for the above stream was within one second, not the minutes observed with the read metrics).

And I don't think it is the case of metrics not being passed through a busy DCOS metrics module. In the latter case we would rather observe the _write_ metrics missing ('w' stands after 'r" in the alphabet), or at least all of the _read_ metrics missing, which is not the case.
We are only observing missing read metrics for some certain segments, and only for some period after the segment has been created.

The issue is being observed with Pravega v0.3.

**Problem location**
Segmentstore metrics

**Suggestions for an improvement**
`segment_read_bytes` metrics should be reported for every time period there are reads from the segment

**Comment by Prabha-Veerubhotla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [segment_read_bytes metric issue](https://trello.com/c/ETF26icw/34-segmentreadbytes-metric-issue)

**Comment by kevinhan88** [comment]
Julia Khalack, who opened this issue, updated that the issue seems no longer exists with Pravega 0.4 on PKS cluster.
Checked the source code already, didn't find issue could cause the original issue reported, the issue might be deployment specific. Close the issue for now.

<img width="533" alt="issue2740" src="https://user-images.githubusercontent.com/24516773/48749240-e3d77880-ec2e-11e8-9aa7-d9ef3c10dd03.PNG">
