### ISSUE TITLE
Cache delegation token in client interactions with segmentstore

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2741]
**Problem description**
As mentioned in https://github.com/pravega/pravega/pull/2732#discussion_r199099473

As enhancement we could  cache the `delegationToken` in `groupState` since a `delegationToken` is on per Stream level basis. 

The advantages of caching include:
- No additional controller api call to fetch token for every segmentTruncationExcecption received by Reader on its managed segments.
- No additional controller api call to fetch token for every segment acquired by the reader, when a new instance of `SegmentInputStream` is created inside `EventStreamReaderImpl.acquireSegmentsIfNeeded()`.
- Reuse the `delegationToken` returned by `controller.getSuccessors()` api.

**Problem location**
delegation toke handling in the client.

**Suggestions for an improvement**
Add caching to the token.

**Comment by tkaitchuck** [comment]
I don't think this is a good idea from a security POV. We don't want the delegation token being written down somewhere that we then have to worry about securing.

**Comment by arvindkandhare** [comment]
@tkaitchuck I agree to this point. Will close this issue and "won't fix" if there are no further comments.
