### ISSUE TITLE
Revisit the substitution of jsr311-api with javax.ws.rs-api

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2744]
**Problem description**
In PR #2724, we added a substitution to fix the issue with `bin/standalone` described in #2718. Although the fix works with the current code base, there is the concern that this solution might not be ideal long term.

**Problem location**
Gradle build.

**Suggestions for an improvement**
We need to revisit issue #2718 and the given solution to determine whether there is something else we should be doing instead.

**Comment by EronWright** [comment]
If I recall correctly, the issue stems from a major conflict between HDFS dependencies and with the controller's dependencies, notably in the standalone mode.   I think the best solution is to assemble a shaded HDFS library with all its dependencies relocated.   Other tier-2 backends may require similar treatment.

**Comment by fpj** [comment]
@EronWright 

> If I recall correctly, the issue stems from a major conflict between HDFS dependencies and with the controller's dependencies, notably in the standalone mode.

Yes, that's right.

> I think the best solution is to assemble a shaded HDFS library with all its dependencies relocated. Other tier-2 backends may require similar treatment.

Thanks for the recommendation. Could you elaborate on what needs to be executed precisely according to your suggestion? I'm wondering in particular whether it overlaps with this: wotk

https://github.com/pravega/pravega/pull/2437

**Comment by EronWright** [comment]
The idea is to assemble a plugin-JAR containing `io.pravega.segmentstore.storage.impl.hdfs.*` as per 2437, with the Hadoop client and its dependencies shaded into it.    Most dependencies must be relocated as `io.pravega.shaded...` so as to not conflict with other Pravega dependencies.    Apply this technique for all tier-2 plugins.

Flink actually uses this technique; check out the voodoo here:
https://github.com/apache/flink/tree/master/flink-shaded-hadoop

**Comment by EronWright** [comment]
One aspect to be careful about is Hadoop's own plugin system, HCFS.   We mustn't break HCFS support when we relocate various Hadoop dependencies.    For example, relocating `org.apache.hadoop.*` would probably not work.
