### ISSUE TITLE
Provide Management CLI

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#2764]
**Problem description**
Pravega does not currently provide a CLI to allow easy configuration of a Pravega instance from the command line.  Such a tool should be provided which would communicate with the Pravega controller allow interrogation and management direct from the command line.

Further analysis would be required to determine a specification on exactly what features the CLI would provide.

**Comment by RaulGracia** [comment]
We have created the first version for such a tool at: https://github.com/pravega/pravega-tools/tree/master/pravega-cli. Please, for any improvement or suggestion, please create an issue in the `pravega-tools` repo.
