### ISSUE TITLE
Create `security@pravega.io` email and update `index.md`

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2765]
**Problem description**
We need a separate mechanism to discuss Pravega security related issues and updates.

**Problem location**
`documentation/src/docs/index.md`.

**Suggestions for an improvement**
Setup the account and update the documentation.

**Comment by sowensnc** [comment]
Who do we want receive emails intended for security@pravega.io?

**Comment by arvindkandhare** [comment]
> Who do we want receive emails intended for security@pravega.io?

I do not have any specific preference. I think it can be same audience as other `*@pravega.io` recipients. This will just ensure that security issues come to a different alias and can be treated with different level of urgency.

**Comment by sowensnc** [comment]
Okay. I've configured the mail exchange records for the pravega.io domain. I can have the various email address point to email lists.

**Comment by arvindkandhare** [comment]
@sowensnc can you point me to a procedure for verifying this? Once verified, I will close the issue.

**Comment by sowensnc** [comment]
Are you looking to verify the ability to send emails to security@pravega.io?

**Comment by arvindkandhare** [comment]
Yes. I am looking at a verification that an email sent to security@pravega.io goes to a list of emails internally. I am ok with you just confirming that this works. Once done, I'll close this issue.

**Comment by arvindkandhare** [comment]
The email id is created and verified. @sowensnc thanks!. Closing the issue.
