### ISSUE TITLE
Improve Pravega simple test system test case

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#2782]
**Problem description**
Currently, we are not validating the write and read count after the test explicitly.
Following the pattern used in other failover tests and the common methods in `AbstractFailoverTests`,
add two atomic variables for write, read count and make sure writes and reads are equal at the end of tests.
Also, update the code to match with the system tests wherever required and makes sense,  which we have introduced recently.

**Problem location**
https://github.com/pravega/pravega/blob/master/test/system/src/test/java/io/pravega/test/system/PravegaTest.java

**Suggestions for an improvement**
*  Add more logs whenever required.
*  add `tearDown()` method, and close the relevant.
*  Make sure readers are close before reader group is deleted. ( by checking `onlineReaders==0`). This might be redundant, need @shrids 's advice here.
*  Use `stream manager` for creating scope and stream.
*  Use the methods in `AbstractFailoverTests` wherever it is relevant

**Comment by shrids** [comment]
Closed as part of PR #3135
