### ISSUE TITLE
Add ids to trace requests across processes.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2803]
**Problem description**
When debugging an issue we need to coordinate issues across the client, the controler, and the server. However doing this while looking at logs is sometimes difficult. It would be helpful if we could add an identifier in the logs to provide context that would be consistent across processes. 

**Problem location**
Everywhere.

**Suggestions for an improvement**
We could add a field 'logId' to each message in the wire protocol and make sure this is passed along the full request chain so that all logs contain the ID.

**Comment by EronWright** [comment]
Sounds similar to a "request id" as often seen in REST APIs, or a "trace id" as per OpenTracing, or the older Mapped Diagnostic Context as seen in log4j.   Are you mainly interested in correlation across processes or across threads?  In any case, this is a good idea.

http://opentracing.io/documentation/
https://logback.qos.ch/manual/mdc.html
http://logging.apache.org/log4j/2.x/manual/thread-context.html
https://github.com/mercari/go-grpc-interceptor/tree/master/xrequestid

**Comment by RaulGracia** [comment]
Thanks for the inputs @tkaitchuck and @EronWright. But it would be great to have a little bit more of feedback on this issue. Currently, most commands in `WireCommands` already contain a `requestId` that is generated at the client side (Client, Controller Client) and is preserved in the server side (Segment Store), so we can correlate a request across logs.

But I understand that your goal is to have a `global request tag` for the lifecycle of a request and its _possibly derived requests_, right?. For instance, let's imagine that a client creates a new Stream. In this case, the workflow would be:
1. Create a unique `global request tag` at the client side for the `createStrem` request.
2. Pass this `global request tag` along with the request to the Controller (via gRPC call).
3. Use this `global request tag` in the Controller when it sends `create segment` requests to the segment store.
4. Add `global request tag` field in `WireCommnds.CreateSegment`
5. Use the `global request tag` for logging at the segment store and any possible client reply.

This would clearly help us to see the system activity related with a client request. However, it looks like doing this may involve significant changes in calls/APIs that may break compatibility at some point. Is this correct? Is the previous example in line with the goal of this issue?

**Comment by RaulGracia** [comment]
[PDP-31](https://github.com/pravega/pravega/wiki/PDP-31:-End-to-end-Request-Tags) available to foster the discussion on this issue.
