### ISSUE TITLE
OutOfMemoryError thrown from the UncaughtExceptionHandler on longevity run after 2d21hrs

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#2818]
**Problem description**
Longevity run failed with writers and readers bytes are not increasing after 2d21hrs.

Experiments has been executed in a virtualized platform. The cluster contains 5 nodes (CentOS 7 VMs) that run the different Pravega services in containers (Mesos): 1 Master node and 5 slaves (running 1 Pravega Controller instance, 3 Segment Store server and other services, such as Bookkeeper and Zookeeper). Continuous small read / write workload (4 reader and 4 writer) were exhibiting with a total throughput of 30 kbps (```small```), The workload was longevity-oriented, so all the experiments results were obtained after at least 48 hours of execution. 

From Longevity Log getting too many exception on one of the slave system (slave-4) and segment store associated.

```
2018-08-02 03:18:00,567 214164004 [epollEventLoopGroup-2-1] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection 172.16.27.24
   2018-08-02 03:19:46,059 214269496 [epollEventLoopGroup-5-12] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection 172.16.27.24
```

From Pravega Log, it seems there are ledger failure and DurableLog recovery failure had been observed with Critical failure for SegmentContainer Container Id = 0.

```
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:18:06,313 402954484 [core-24] ERROR o.a.b.meta.AbstractZkLedgerManager - Could not read metadata for ledger: 8
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:18:06,314 402954485 [core-24] ERROR i.p.s.server.logs.DurableLog - DurableLog[0] Recovery FAILED.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:18:09,159 402957330 [core-24] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 0, State = FAILED. {}
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:20:27,679 403095850 [core-16] ERROR i.p.s.server.logs.DurableLog - DurableLog[12] Recovery FAILED.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:22:41,111 403229282 [core-25] ERROR i.p.s.server.logs.DurableLog - DurableLog[13] Recovery FAILED.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:22:41,120 403229291 [BookKeeperClientWorker-orderedsafeexecutor-5-0] ERROR o.a.bookkeeper.client.LedgerHandle - Error update ledger metadata for ledger 110 : -9
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:22:41,122 403229293 [BookKeeperClientWorker-orderedsafeexecutor-1-0] ERROR o.a.bookkeeper.client.LedgerHandle - Error writing ledger config -9 of ledger 22
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:22:41,123 403229294 [core-25] ERROR i.p.s.s.s.StreamSegmentContainerRegistry - Critical failure for SegmentContainer Container Id = 13, State = FAILED. {}
```
From Segment store Logs there were java.lang.OutOfMemoryError 
(attached segment store log from assertion time line)

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "BookieClientTimer-0"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "core-20"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main-SendThread(zookeeper.pravega.l4lb.thisdcos.directory:31886)"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "core-9"
```

**Problem location**
Segment store out of memory

**Suggestions for an improvement**
Memory usage optimization / In case of multi instance deployment, it is fine if segments get restarted but a hanging instance like this is not acceptable  - as discussed with Arvind.

[segment_store_stdout.txt](https://github.com/pravega/pravega/files/2267537/segment_store_stdout.txt)
[logs-1533181170634-vindicator.zip](https://github.com/pravega/pravega/files/2267575/logs-1533181170634-vindicator.zip)

**Comment by ybasetty** [comment]
@andreipaduroiu is there a reason this issue was closed?

**Comment by andreipaduroiu** [comment]
This was due to incorrect test setup. In memory was used for tier2

**Comment by sumit-bm** [comment]
@andreipaduroiu This was not on incorrect test setup.

**Comment by fpj** [comment]
What I see in the segment store logs is the following:

1- The segment store instance is trying to recover segment container 8, but it fails:
```
2018-08-02 03:26:00,778 403428949 [core-30] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[8]: Exit RecoveryMode.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,778 403428949 [core-30] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[8] Exit RecoveryMode.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,778 403428949 [core-30] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[8]: Cleared.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,780 403428951 [core-30] ERROR i.p.s.server.logs.DurableLog - DurableLog[8] Recovery FAILED.
```

2- There are a bunch bk errors, and I see zk session expiration as well. They might be connected.
3- At some point, it gives up and starts to close the segment store instance:
```
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,787 403428958 [core-28] WARN  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[8]: Failed due to component failure.
pravega/pravega_segmentstore  STDOUT 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1245)
pravega/pravega_segmentstore  STDOUT 	at org.apache.zookeeper.ClientCnxn.access$2700(ClientCnxn.java:99)
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,818 403428989 [core-30] INFO  i.p.s.s.i.bookkeeper.BookKeeperLog - Log[8]: Closed.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,819 403428990 [core-30] INFO  i.p.s.s.impl.rocksdb.RocksDBCache - RocksDBCache[Container_8]: Closed.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,818 403428989 [core-30] INFO  i.p.s.server.logs.DurableLog - DurableLog[8]: Closed.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,819 403428990 [core-30] INFO  i.p.s.s.rolling.RollingStorage - Closed
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,819 403428990 [core-30] INFO  i.p.s.s.reading.ContainerReadIndex - ReadIndex[8]: Closed.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,819 403428990 [core-30] INFO  i.p.s.s.s.StreamSegmentContainerRegistry - Unregistered SegmentContainer 8.
pravega/pravega_segmentstore  STDOUT 2018-08-02 03:26:00,819 403428990 [core-30] INFO  i.p.s.s.c.StreamSegmentContainer - SegmentContainer[8]: Closed.
```
4- After that, I only see GC activity, and I suppose that eventually it crashed with OOM.

Is my analysis correct, @andreipaduroiu ?

**Comment by andreipaduroiu** [comment]
@fpj you are probably right.

Given that neither ZK or BK was accessible no Container was able to start in the Segment Store. In addition it had trouble cleaning things up (due to ZK problems) which is why you see so many timeout exceptions.

And yes, eventually an OOM state is reached from which nothing else should be usable.

**Comment by andreipaduroiu** [comment]
@sumit-bm Can you re-run this and get a JVM heap dump when it runs out of memory? Unfortunately logs are not useful in situations where we run out of memory. I know there's some args you can pass to the JVM to dump the heap; if you could get one such dump to me it would be very useful in diagnosing what caused it.

Thanks!

**Comment by andreipaduroiu** [comment]
There is not enough information in this issue to find the root cause. Like @fpj stated, both ZooKeeper and Bookeeper were unavailable so the Segment Store could not start without them. This is by design and there is no remedy in this case except retrying until it succeeds.

If this issue recurs, please include a JVM heap dump alongside with full logs for the Segment Store. That will aid in the debugging.
