### ISSUE TITLE
Revisit use of `UnixPrincipal` in `PasswordAuthHandler`

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2821]
**Problem description**
The PR #2802 uses `UnixPrincipal` as an implementation of `Principal` that is expected to be returned as implementation of `AuthHandler` interface.

Importing `com.sun.*` packages may have issues with JDK9 modularity.

**Problem location**
`PasswordAuthHandler` implementation.

**Suggestions for an improvement**
Find out whether using `UnixPrincipal` will cause an issue with modularity.
Introduce a `DefaultPrincipal` that simply carries the username.

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [2821 - Replace UnixPrincipal](https://trello.com/c/ax8BN3Zm/4-2821-replace-unixprincipal)
