### ISSUE TITLE
Possible privilege elevation using delegation token

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2824]
**Problem description**
Reviewing the `PravegaInterceptor` class, there is a troubling block of code ([ref](https://github.com/pravega/pravega/blob/ce32932b7b6ea03e9c784b028e0c4d804fe84c95/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L80)) that produces a powerful delegation token, as fallback logic when no interceptor is in the GRPC thread-local context.    Seems that the caller must call `retrieveDelegationToken` from the GRPC thread or else the user will silently be granted a powerful level of access.  

**Problem location**
`io.pravega.controller.server.rpc.auth.PravegaInterceptor`

**Suggestions for an improvement**

Consider reworking the code to grant no privileges when explicit information isn't available, and consider accepting the `Context` as a parameter (rather than rely on a thread-local) into such utility methods as `retrieveDelegationToken`.   This would force the caller to be aware of which context is being retrieved, and make the overall behavior more explicit when using futures.

**Comment by arvindkandhare** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Delegation token handling refactoring](https://trello.com/c/HEVhxEAP/32-delegation-token-handling-refactoring)
