### ISSUE TITLE
Events read out of sequence (r0.3.1)

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2826]
**Problem description**
In our `smallScale` test we are writing events to a stream with autoscaling (triggered by an event rate). At the beginning of the test, we are randomly generating 20 routing keys. 
Later on, one of the routing keys would be randomly chosen to write the next event to.
As part of the test, we are keeping track of the number of the events written to each routing key, and the corresponding sequence number is written to the Pravega stream as a part of the event payload. 
When reading from the stream, we have an assertion that the sequence numbers are always increasing for the same routing key.

During one of the test runs with Pravega commit `3e49d00` (r0.3.1), we observed two events being read out of sequence:
```
2018-08-05 23:02:42,324 451675413 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Event out of sequence d5136ab1-4552-4faa-ba6b-22b63a1d6d5a-599f89ae-e449-4e30-9efb-f414d67e6e8b: lastSeq: 267694, currentSeq:267692
...
2018-08-05 23:02:42,329 451675418 [pool-8-thread-1] ERROR c.e.n.h.t.w.readers.PravegaReader - Event out of sequence d5136ab1-4552-4faa-ba6b-22b63a1d6d5a-599f89ae-e449-4e30-9efb-f414d67e6e8b: lastSeq: 267694, currentSeq:267693
```

See the attached client logs (DEBUG level) for more information:
[dust.smallScale.eos.controller_server_2018-08-05.427.log](https://github.com/pravega/pravega/files/2271268/dust.smallScale.eos.controller_server_2018-08-05.427.log)

Unfortunately, we were not able to save any controller or SS logs for the pertinent time frame.

**Problem location**
Reader(?)

**Suggestions for an improvement**
Events with the same routing key should be read in the same order they are being written.

**Comment by fpj** [comment]
I'm closing as we have merged a pull request to address this issue. Please reopen if it manifests again.
