### ISSUE TITLE
B+ Tree Index Auto-Compaction

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2834]
**Problem description**
The initial implementation for B+Tree index for extended attributes has a major drawback: due to the append-only nature of Tier2 storage, the index file size can only grow, and it does grow at a very fast rate, especially for large indices.

**Problem location**
BTreeIndex.

**Suggestions for an improvement**
- Compaction
    - Maybe keep additional metadata in the index to figure out the fragmentation, and decide on compaction. Then copy pages with very low offsets to the end and truncate.

**Comment by tkaitchuck** [comment]
We could also add batching of the writes. When the data is already durable buffering up the writes together will reduce the total data that needs to be written because multiple updates to the nodes closer to the root can be coalesced.

**Comment by andreipaduroiu** [comment]
The updates are already batched up by the StorageWriter. All changes to this index are done in the background where multiple changes are aggregated together and then applied to this index.

**Comment by andreipaduroiu** [comment]
Here is a comparison of the index sizes for various scenarios. I compared Baseline (PR #2842 ) with the changes proposed by this issue.

How to interpret the table below:
- I tested maximum page sizes of 4KB, 8KB, 16KB and 32KB.
- I tested batch sizes of 10, 100, 1000, and 1M (batch = did this many inserts/updates at a time).
- Insert tests involved writing 1M extended attributes (16 byte key, 8 byte value) in mostly sorted order. These inserts were done in various batch sizes. This is mostly a theoretical scenario.
- Update tests involved bulk-loading 1M extended attributes, then randomly updating random keys at a time (it is possible that the same key was updated multiple times). These updates were also performed in various batch sizes. This is a more realistic scenario.
- Index size is expressed in MB.
- Compact/Base% is the percentage of Compacted Index size vs Baseline Index size.
- These tests are repeatable; they are checked in as Load Tests in the branch for this issue.

```
Page   | Count     |     Batch | Idx Size(Base.) |Idx Size(Compact)| Compact/Base %	
       |           |           | Insert | Update | Insert | Update | Insert | Update
-------+-----------+-----------+--------+--------+--------+--------+--------+-------	   
4,096  | 1,000,000 |        10 |    809 |  7,486 |    129 |    121 |    16% |     2%
4,096  | 1,000,000 |       100 |     90 |  5,348 |     89 |    159 |    99% |     3%
4,096  | 1,000,000 |     1,000 |     31 |  3,774 |     38 |    156 |   123% |     4%
4,096  | 1,000,000 | 1,000,000 |     23 |     46 |     27 |     30 |   118% |    65%
-------+-----------+-----------+--------+--------+--------+--------+--------+-------	   
8,192  | 1,000,000 |        10 |  1,221 | 12,671 |    116 |    107 |    10% |     1%
8,192  | 1,000,000 |       100 |    143 |  8,477 |     87 |    127 |    61% |     1%
8,192  | 1,000,000 |     1,000 |     37 |  6,713 |     44 |    139 |   121% |     2%
8,192  | 1,000,000 | 1,000,000 |     23 |     46 |     27 |     30 |   117% |    65%
-------+-----------+-----------+--------+--------+--------+--------+--------+-------	   
16,364 | 1,000,000 |        10 |  2,264 | 19,456 |    115 |     80 |     5% |     0%
16,364 | 1,000,000 |       100 |    247 | 15,515 |     97 |    106 |    39% |     1%
16,364 | 1,000,000 |     1,000 |     45 | 11,397 |     52 |    118 |   114% |     1%
16,364 | 1,000,000 | 1,000,000 |     23 |     46 |     27 |     30 |   117% |    65%
-------+-----------+-----------+--------+--------+--------+--------+--------+-------	   
32,767 | 1,000,000 |        10 |  3,991 | 32,990 |    115 |     72 |     3% |     0%
32,767 | 1,000,000 |       100 |    416 | 29,402 |     97 |    103 |    23% |     0%
32,767 | 1,000,000 |     1,000 |     60 | 17,083 |     54 |     91 |    89% |     1%
32,767 | 1,000,000 | 1,000,000 |     23 |     46 |     27 |     30 |   117% |    65%
```
