### ISSUE TITLE
Cherry pick master commits for 0.3.2 release

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2838]
**Problem description**
We need cherry-pick the following commits from master to r0.3:
Issue 2801: Remove redundant invocation of fetch successors during Abort transaction. (#2795)
Issue 2773: Do not check for data availability in the stream locally (#2774)
Issue 2805: Improve resilience of Pinger (#2806)
Issue 2823: Updated StreamCuts in ReaderGroup (#2829)
Issue 2813: Ensure the correct Segment routing key range is updated with replacement range. #2814

**Problem location**
Branch r0.3.

**Suggestions for an improvement**
Cherry pick.

**Comment by tkaitchuck** [comment]
#2825  should also be merged.

**Comment by fpj** [comment]
We are additionally picking the following:

Issue 2384: Standardize use of `Authorization` header (#2385)
Issue 2391: Apply security checks for `listScopes` API (#2802)
Issue [2824] [2816]: Document and refactor delegation token creation in controller. (#2825)
