### ISSUE TITLE
In deploying docker swarm documentation, location of hdfs.yml and zookeeper.yml need to be provided

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#2840]
**In deploying docker swarm documentation, location of hdfs.yml and zookeeper.yml need to be provided**

In current documentation " http://pravega.io/docs/latest/deployment/docker-swarm/ " ,  prerequisites section mentioned as below

> Prerequisites
> 
> - A working single or multi-node Docker Swarm. See https://docs.docker.com/engine/swarm/swarm-tutorial.
> 
> - HDFS and ZooKeeper. We provide compose files for both of these, but both are single instance deploys that should only be used for testing/development.
> 
> To deploy our HDFS and ZooKeeper:
> 
> ```
> docker stack up --compose-file hdfs.yml pravega
> docker stack up --compose-file zookeeper.yml pravega
> ```
> 

Seems that the yml file locations are not provided and might create confusion to users. It would be good to provide yml file locations as follows:

hdfs.yml and zookeeper.yml example files could be found in https://github.com/pravega/pravega/tree/master/docker/compose/swarm  

**Problem location**
Documentation

**Suggestions for an improvement**
File locations need to be specified

**Comment by RaulGracia** [comment]
This has been already fixed.
