### ISSUE TITLE
Write a tutorial on how to work with the Synchronizer interface

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#287]
The concept behind the `Synchronizer` interface is fairly simple: processes keep a copy of the state of a given object, and agree on the order of changes to the object via a Pravega segment and conditional appends. Going from the abstraction to the using the current interface is fairly big leap, so it is important that we right a tutorial on it because this is a concept that we are counting on promoting heavily to our users.

**Comment by RaulGracia** [comment]
We have the following documentation items for StateSynchronizer:
- Tutorial on how to work with StateSynchronizer: http://pravega.io/docs/latest/state-synchronizer/
- Sample code using StateSynchronizer: https://github.com/pravega/pravega-samples/tree/v0.5.0/pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer

I think that this is meeting the purpose of the issue.
