### ISSUE TITLE
Client and Wire Protocol for Tables

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2895]
**Problem description**
Implement Client code and supporting Wire Protocol for Tables. Contracts defined in #2876 .
- TableSegment
- ClientFactory

**Problem location**
Client and Wire Protocol.

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
@shrids You may already have a (different) issue for this. Feel free to merge them or close this one if that's the case.

**Comment by shrids** [comment]
SubTasks: 
- [ ] create wireProtocol and PravegaRequestProcessor implementation for the following tablestore apis : `createSegment`, `deleteSegment`, `merge`, `seal`, `put`, `remove` and `get` - PR: #3283 
- [ ] create WireProtocol and PRP implmentation of `keyIterator` and `entryIterator` tablestore apis.
- [ ] ClientFactory implementation.

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AsyncIterator Table API WireCommand changes.](https://trello.com/c/1zmeVpC4/102-asynciterator-table-api-wirecommand-changes)
