### ISSUE TITLE
WriteEvents are failing for re-created streams

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#2898]
**Problem description**
whenever the stream is sealed , deleted and created, afterwards if the writeEvent is performed then it failed with segment truncation/sealed error

**Problem location**
controller
segment store

here is the client log:

[root@white-master-1 pravega-benchmark]# ./pravega-benchmark/bin/pravega-benchmark  --controller tcp://10.240.135.50:9091  --stream StreamName-same  -producers 1  -writeonly true --size 10000  -eventspersec 1 --runtime 1
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.135.50:9091
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.240.135.50:9091], attrs={}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - Scope already exists: Scope
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.135.50:9091
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/StreamName-same with configuration: StreamConfiguration(scope=Scope, streamName=StreamName-same, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - Stream already exists: StreamName-same
The stream: StreamName-same may already exists, so manually scaling to 1 segments
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.240.135.50:9091], attrs={}]]
Current active segments for stream = StreamSegments:{1.0=Scope/StreamName-same/0.#epoch.0}
Number of Segments before manual scale: 1
ERROR : Scale operation on stream StreamName-same did not complete
Sealing and Deleteing the stream : StreamName-same and then recreating the same
[grpc-default-executor-1] INFO io.pravega.client.stream.impl.ControllerImpl - Successfully sealed stream: StreamName-same
[grpc-default-executor-1] INFO io.pravega.client.stream.impl.ControllerImpl - Successfully deleted stream: StreamName-same
[grpc-default-executor-1] INFO io.pravega.client.stream.impl.ControllerImpl - Stream created successfully: StreamName-same
The stream :StreamName-same recreated
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 10.240.135.50:9091
[main] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Shutting down ControllerNameResolver
[main] INFO io.pravega.client.stream.impl.ClientFactoryImpl - Creating writer for stream: StreamName-same with configuration: EventWriterConfig(initalBackoffMillis=1, maxBackoffMillis=20000, retryAttempts=10, backoffMultiple=10, transactionTimeoutTime=29999)
[main] INFO io.pravega.client.stream.impl.SegmentSelector - Refreshing segments for stream StreamImpl(scope=Scope, streamName=StreamName-same)
[clientInternal-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/10.240.135.50:9091], attrs={}]]
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/StreamName-same/0.#epoch.0, writerID: ff2aca2e-7fac-445e-82de-25eba6dbfc25
[clientInternal-3] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=10.240.135.50, port=12345) for Scope/StreamName-same/0.#epoch.0, writerID: ff2aca2e-7fac-445e-82de-25eba6dbfc25
[epollEventLoopGroup-4-1] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x0a3ef08e])
[epollEventLoopGroup-4-1] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=5, lowVersion=5)
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.client.segment.impl.NoSuchSegmentException: Segment does not exist:Scope/StreamName-same/0.#epoch.0 for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@665a180 on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25. SetupCompleted: false, Closed: false
[epollEventLoopGroup-4-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-same/0.#epoch.0 on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25 failed due to: Segment does not exist:Scope/StreamName-same/0.#epoch.0
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Ending reconnect attempts on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25 to Scope/StreamName-same/0.#epoch.0 because segment is truncated
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Segment being written to Scope/StreamName-same/0.#epoch.0 by writer ff2aca2e-7fac-445e-82de-25eba6dbfc25 no longer exists due to Stream Truncation, resending to the newer segment.
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer ff2aca2e-7fac-445e-82de-25eba6dbfc25 with exception io.pravega.shared.protocol.netty.ConnectionFailedException
[epollEventLoopGroup-4-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException for connection null on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25. SetupCompleted: null, Closed: false
[epollEventLoopGroup-4-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-same/0.#epoch.0 on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25 failed due to: class io.pravega.shared.protocol.netty.ConnectionFailedException
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.EventStreamWriterImpl - Sealing segment Scope/StreamName-same/0.#epoch.0
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:Scope/StreamName-same/0.#epoch.0 for connection null on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25. SetupCompleted: null, Closed: false
[ScalingRetransmition-Scope/StreamName-same-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-same/0.#epoch.0 on writer ff2aca2e-7fac-445e-82de-25eba6dbfc25 failed due to: SegmentSealed Exception for segment:Scope/StreamName-same/0.#epoch.0
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.EventStreamWriterImpl - Resending 1 events
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.EventStreamWriterImpl - No writer for segment during resend.
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.SegmentSelector - Refreshing segments for stream StreamImpl(scope=Scope, streamName=StreamName-same)
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.EventStreamWriterImpl - Sealing another segment null
[clientInternal-8] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/StreamName-same/0.#epoch.0, writerID: dd0b7fef-ed5c-4416-afef-b57a3cd92230
[clientInternal-10] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=10.240.135.50, port=12345) for Scope/StreamName-same/0.#epoch.0, writerID: dd0b7fef-ed5c-4416-afef-b57a3cd92230
[epollEventLoopGroup-4-2] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0xab3b55d6])
[epollEventLoopGroup-4-2] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=5, lowVersion=5)
[epollEventLoopGroup-4-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.client.segment.impl.NoSuchSegmentException: Segment does not exist:Scope/StreamName-same/0.#epoch.0 for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@5a31f2c7 on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230. SetupCompleted: false, Closed: false
[epollEventLoopGroup-4-2] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-same/0.#epoch.0 on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230 failed due to: Segment does not exist:Scope/StreamName-same/0.#epoch.0
[epollEventLoopGroup-4-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Ending reconnect attempts on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230 to Scope/StreamName-same/0.#epoch.0 because segment is truncated
[epollEventLoopGroup-4-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Segment being written to Scope/StreamName-same/0.#epoch.0 by writer dd0b7fef-ed5c-4416-afef-b57a3cd92230 no longer exists due to Stream Truncation, resending to the newer segment.
[epollEventLoopGroup-4-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer dd0b7fef-ed5c-4416-afef-b57a3cd92230 with exception io.pravega.shared.protocol.netty.ConnectionFailedException
[epollEventLoopGroup-4-2] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException for connection null on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230. SetupCompleted: null, Closed: false
[epollEventLoopGroup-4-2] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-same/0.#epoch.0 on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230 failed due to: class io.pravega.shared.protocol.netty.ConnectionFailedException
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.EventStreamWriterImpl - Sealing segment Scope/StreamName-same/0.#epoch.0
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.client.segment.impl.SegmentSealedException: SegmentSealed Exception for segment:Scope/StreamName-same/0.#epoch.0 for connection null on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230. SetupCompleted: null, Closed: false
[ScalingRetransmition-Scope/StreamName-same-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/StreamName-same/0.#epoch.0 on writer dd0b7fef-ed5c-4416-afef-b57a3cd92230 failed due to: SegmentSealed Exception for segment:Scope/StreamName-same/0.#epoch.0
[ScalingRetransmition-Scope/StreamName-same-1] INFO io.pravega.client.stream.impl.EventStreamWriterImpl - Sealing another segment null

**Comment by RaulGracia** [comment]
@kmgowda, which is the version of Pravega that are you using in your tests? Because PR #2800  addresses this problem and it was merged 3 or 4 weeks ago. Could you please verify that you are working on a Pravega version with this PR included?

**Comment by kmgowda** [comment]
its nautilus versions : 0.3.1-1909.3e49d00 and 0.3.2
are you sure that its fixed in 0.4 version?

**Comment by kmgowda** [comment]
thanks Raul.. your PR has lot of details about the fix

**Comment by RaulGracia** [comment]
I see that branch `r0.3` does not include this PR, so you will find this error until you switch to version `0.4`. In this case, we may close the issue as the fix for this problem is already available, right?

**Comment by kmgowda** [comment]
yes..  I will close this.. however 0.4 i will not be able to deploy to nautilus because julia told me that there are issues with 0.4 with DC/OS.. they are making it to happen on kubernetics.. 
do you have any custom build for nautilus to test this fix?

**Comment by RaulGracia** [comment]
I recommend you to create a branch off `r0.3.2` and then `cherry-pick` PR #2800.

**Comment by kmgowda** [comment]
hi Raul.. yes I validated this on 0.4  , its fixed 👍
