### ISSUE TITLE
Byte-oriented client API

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#291]
There are applications for which writing very large events will be very natural. While we can for the application to chunk it up and append chunks individually via the event API, it would be nice to enable an application to stream such events into a Pravega stream. 

To be able to stream a large event into Pravega, we propose to have a byte-oriented API that enables an application to stream bytes of an event rather than sending the event as whole. Internally, we already manipulate bytes rather than events, so it is natural to have such an API. We additionally need the ability of reading byte chunks rather than events on the read side.

One complication is the fact that the bytes of multiple events might end up interleaved in a stream, which complicates reading the data of the stream. Currently, we guarantee that the bytes of an event are contiguous in a stream.

**Comment by RaulGracia** [comment]
Closed via #2978.
