### ISSUE TITLE
Update hdfs docker image

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega#2975]
hdfs docker image version used for Pravega is "2.7.3-1". There are a huge number of bug fixes and improvements available in the newer(2.7.x, 2.8.x, 2.9.x. 3.x) releases,

Please refer https://hadoop.apache.org/releases.html

Maybe we need to review the hdfs docker images for Pravega also.

**Comment by adrianmo** [comment]
I'm actually struggling to find an updated and supported Docker image for HDFS. The options I have on the table are the following:

- https://hub.docker.com/r/dsrw/hdfs/
Currently in use. Latest tag: 2.7.3-1
- https://hub.docker.com/r/flokkr/hadoop-hdfs-datanode
Latest tag: 3.0.0, 2.9.0 (more than 1 year ago)
- https://hub.docker.com/r/imagenarium/hdfs-datanode/
Latest tag: 2.7.6_2 (few months ago), but judging by the number of tags, I'm not sure if the repo is maintained.
- https://hub.docker.com/r/uhopper/hadoop-datanode/
Latest tag: 2.8.1, 2.7.2 (almost a year ago). 

Does anybody know any other alternatives? Maybe we should build and maintain our own Docker image for HDFS...

**Comment by adrianmo** [comment]
After talking to Scott, the owner of the [HDFS image we are currently using](https://hub.docker.com/r/dsrw/hdfs/), I forked [his GitHub repository](https://github.com/dsrw/docker-hdfs) and made the following changes to the build process:

- Replace base image from [`java:7`](https://hub.docker.com/r/library/java/tags/) (2 years old) to [`openjdk/8`](https://hub.docker.com/r/library/openjdk/tags/) (6 days old)
- Updated HDFS binay from `2.7.2` (2017-06-26) to `2.7.7` (2018-07-20, latest 2.7.x release)
- Updated build process to work with new updates

I've temporarily pushed the image to [`adrianmo/hdfs:2.7.7`](https://hub.docker.com/r/adrianmo/hdfs/tags/). Once we verify the correct functioning, we'll move under Pravega.
 
@mejodev1 @sumit-bm @deenav can you please test the new image and report back?
