### ISSUE TITLE
Complete migration to jCenter

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2976]
**Problem description**
As a follow-up to #2155, Pravega should complete its migration from Maven Central to jCenter for production builds. 

Consider deleting the old sonatype account.

**Comment by fpj** [comment]
Why should we stop publishing release artifacts to Maven Central altogether? I understand that we are publishing snapshots to JCenter, and it is desirable to publish release artifacts there as well, but that doesn't preclude publishing release artifacts to Maven Central. Am I missing anything?

**Comment by EronWright** [comment]
The benefits seem to be:
1. have a single authoritative source for publications
2. able to simplify the build scripts to use only the bintray plugin, which is able to handle jCenter and Artifactory.  As opposed to also maintaining the sonatype-related publishing code.
