### ISSUE TITLE
Use Micrometer library for Pravega metrics

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2977]
**Problem description**
Pravega relies on codahale for concrete metrics providers.   Some issues:
1) the set of providers is quite limited, e.g. lacks prometheus support
2) the statsd provider is of low quality, e.g. treats all metrics as gauges ([ref](https://github.com/ReadyTalk/metrics-statsd/blob/8407b985d81a91c719ea55cbb2ef2abd5e089a30/metrics-statsd-common/src/main/java/com/readytalk/metrics/StatsD.java#L96)).

There's also a design issue that Pravega assumes that the metrics backend is _hierarchical_ rather than _dimensional_  ([ref 1](https://micrometer.io/docs/concepts#_supported_monitoring_systems), [ref 2](https://prometheus.io/docs/concepts/data_model/)).  For example, Pravega combines the metric name with one or more contextual tags before invoking the provider.   This is a lossy approach that necessitates complex templates, e.g. [telegraf templates](https://github.com/influxdata/telegraf/blob/master/docs/TEMPLATE_PATTERN.md).

**Suggestions for an improvement**
Pivotal maintains an OSS metrics library that is similar to codahale called [micrometer.io](https://micrometer.io/docs/concepts).  Micrometer has a richer interface for publishing dimensional metric data to a great variety of backends including StatsD, Prometheus and Influx (without need for Telegraf templates).    Suggest moving the metrics impl to micrometer while retaining the same abstract inferfaces.

**Comment by fpj** [comment]
I'm not sure why we marked this issue as a bug, it is not a bug, it is an improvement.

**Comment by kevinhan88** [comment]
This issue can be closed now with the Micrometer migration.
