### ISSUE TITLE
Update statsd library to send the correct metric type.

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3004]
**Problem description**
Pravega uses a third-party metrics provider for statsd ([ReadyTalk/metrics-statsd](https://github.com/ReadyTalk/metrics-statsd)), and it has a bug ([#39](https://github.com/ReadyTalk/metrics-statsd/issues/39)): all metrics are erroneously labeled as 'gauges' (as opposed to counters, etc).  

The impact is that InfluxDB/Grafana doesn't interpret the data correctly.

Related to #2977.

**Problem location**
Notice the `|g` constant on [this line](https://github.com/ReadyTalk/metrics-statsd/blob/8407b985d81a91c719ea55cbb2ef2abd5e089a30/metrics-statsd-common/src/main/java/com/readytalk/metrics/StatsD.java#L96), which means 'gauge' as per the statsd protocol.

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
@kevinhan88 is this still being a problem after the migration to Micrometerin #3501?

**Comment by kevinhan88** [comment]
@RaulGracia Flavio has tagged this issue as version/0.5.0 so I guess it will be marked as closed after the release.

**Comment by RaulGracia** [comment]
@kevinhan88 issues are not closed just based on the tag, but depending on whether they are still present or not. For this reason, the question I was referring to is whether this issue is still a problem with the new metrics framework?

**Comment by kevinhan88** [comment]
This is no longer a problem since statsd (ReadyTalk/metrics-statsd) has been replaced by Micrometer. Yes the issue can be closed.

**Comment by RaulGracia** [comment]
Fixed via #3501.
