### ISSUE TITLE
Move event stream client to its own package

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3007]
**Problem description**
Since we are adding the byte stream client to its own package, it makes sense to do the same for the event stream client. This observation is as per PR #2978 .

**Problem location**
Client

**Suggestions for an improvement**
Move the event client and its support classes to its own `eventStream` package.

**Comment by shrids** [comment]
Closing this since the event stream writer has been moved to `io.pravega.client.stream.EventStreamWriter`
