### ISSUE TITLE
ReadOnlySegmentContainer should be resilient to the changes to the underlying store because of truncation

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#3030]
**Problem description**
This issue is a proper fix for #2944.
The interactions between `ReadOnlySegmentContainer` and underlying storage are not atomic.  As The same container may be running on some other Pravega node in read-write mode, any changes made to the segments through that node may cause out of sync data in the read only segmentstore.
As both the segmentstores use `RollingStorage`, even simple operations like `getStreamSegmentInfo` may fail.

Here is a scenario that is observed in #2944.
1. A read-write segmentstore causes truncation. Which involves updation of the header after deletion of the truncated segmentchunk.
2. While this is happening the readonly segmentstore is reading the header file. It tries to look for the segmentchunk which is deleted now.

**Problem location**
`ReadOnlySegmentContainer` and `RollingStorage`.

**Suggestions for an improvement**
1. Rethink the need for `ReadOnlySegmentStore` as this is not used in any scenarios currently, we can remove this functionality.
2. As a work around add retries to the `ReadOnlySegmentContainer` implementation where we try n times before throwing an exception.

**Comment by RaulGracia** [comment]
Closed via #3040.
