### ISSUE TITLE
Bookkeeper replicas in pravega.yml need to be modified to 4 in order to have fault tolerance.

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega#3037]
Number of bookkeeper replicas in pravega.yml is currently 3 by default, which will not provide any fault tolerance even in case of single bookkeeper instance failure. Hence it need to be modified to 4.

```
[root@tinkerer-master-1 ~]# cat  pravega/docker/compose/swarm/pravega.yml
.
.
.
version: '3'
services:
  bookkeeper:
    image: pravega/bookkeeper
    environment:
      ZK_URL: ${ZK_URL:-zookeeper:2181}
    deploy:
      replicas: 3
.
.
.
.
```

**Comment by fpj** [comment]
An alternative to the proposal here is to bring down the degree of replication to two, which should be sufficient for development and testing purposes. Production settings will need to be set independently.
