### ISSUE TITLE
Docker entrypoint ignores command failures

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega#3039]
**Problem description**
Currently, the Docker entrypoint script ignores the failures of some commands by adding the `|| :` suffix. This was done to ignore common errors that should not cause the script to fail. However, it is a bad practice because we are not only silencing a particular error case, but any kind of error that the command can potentially throw.

**Problem location**
Docker entrypoints at:
- `docker/pravega/entrypoint.sh`
- `docker/bookkeeper/entrypoint.sh`

**Suggestions for an improvement**
Instead of ignore all errors, ignore only the errors that we are expecting (e.g. "Node already exists"). If the command uses a particular exit code for that error, then just ignore that error code. Otherwise, a wrapper function might be needed to compare against the _stdout_ or _stderr_.

**Comment by RaulGracia** [comment]
@adrianmo has this been fixed with #2991.

**Comment by adrianmo** [comment]
@RaulGracia no, actually this issue is a technical debt generated in #2991.
