### ISSUE TITLE
Refactor ClientFactory interface

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3070]
**Problem description**
Right now the ClientFactory and StreamManager interfaces seem disorganized. There are multiple types of client and they aren't all instantiated in the same way. ReaderGroup manager is separate entirely. BatchClient has it's own interface, but it is created off ClientFactory and everything else is just in ClientFactory.

**Suggestions for an improvement**
We should refactor the interfaces to be uniform following the pattern of the BatchClient.
The main ClientFactory should have methods that create the appropriate clientFactories for the type of client. These functions should take a scope and a config object. We should have the following factories:
- One for EventReader, EventWriter, and TransactionalEventWriter.
- One for ByteReader and ByteWriter.
- One for StateSynchronizer and the RevisionedStreamClient (which maybe should be renamed)
- One for a TableReader and TableWriter
- One for the ReaderGroupClient and the StreamMetadataClient.

Separate from this we should retain the StreamManager and the ReaderGroupManager.

**Comment by RaulGracia** [comment]
Fixed via #3126.
