### ISSUE TITLE
Segment store fails to create segments if hammered with large volume of requests in short span

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3074]
**Problem description**
I was attempting to create a stream with 10k segments. This meant controller sent out 10k CreateSegment requests within 8 seconds to segment store. 
However, none of the requests completed in over 1 hour and controller continued waiting forever. 

**Problem location**
SegmentStore

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
I would like to see logs at least. I want to see that the requests did reach the Segment store and I want to see what happened there. I have some suspicions, but the logs will tell the truth.

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pravega Metrics are being reported as Histograms](https://trello.com/c/OEk8u3Vu/33-new-pravega-metrics-are-being-reported-as-histograms)

**Comment by andreipaduroiu** [comment]
#3075 is likely to add significant improvements here.
