### ISSUE TITLE
Unable to deploy Bookkeeper using docker swarm based system test framework

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3078]
**System tests on Docker swarm environment failed with error  "Request error -- message: rpc error: code = 3 desc = port '3181' is already in use by service 'bookkeeper'}" on  Pravega 4.0 Beta testing build**

**Below is the error:**
```
Caused by:
       com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://<Cluster IP>2375/services/create: 500, body: {"message":"rpc error: code = 3 desc = port '3181' is already in use by service 'bookkeeper' (t6n0vmegbrj5an068bmgk91xb)"}
```
[SystemTestsWithDockerSwarm.zip](https://github.com/pravega/pravega/files/2546001/SystemTestsWithDockerSwarm.zip)

**Docker swarm setup**
```
4 Nodes - 1 Master, 3 Workers. Deployment:
1 Controller
1 Zookeeper
1 Segment Store
3 BookKeeper
1 Pravega_HDFS
```

**Console snip:**
```
./gradlew --info clean startSystemTestsWithDocker -PrepoUrl=http://<artifactory address> -PdockerRegistryUrl=devops-repo.isus.emc.com:8116 -DmasterIP=<public-ip-of-the-cluster> -DimageVersion=r0.4-0.4.0-2005.9df106d -DskipServiceInstallation=false -Dlog.level=DEBUG -DexecType=DOCKER -PCLUSTER_NAME=<name> -PMASTER=<PUBLISHED IP > -PNUM_SLAVES=3

Gradle Test Executor 1 finished executing tests.

> Task :test:system:startSystemTestsWithDocker FAILED

25 tests completed, 24 failed
Finished generating test XML results (0.103 secs) into: /root/pravega/test/system/build/test-results/startSystemTestsWithDocker
Generating HTML test report...
Finished generating test html results (0.107 secs) into: /root/pravega/test/system/build/reports/tests/startSystemTestsWithDocker

:test:system:startSystemTestsWithDocker (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 21 mins 15.218 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test:system:startSystemTestsWithDocker'.
> There were failing tests. See the report at: file:///root/pravega/test/system/build/reports/tests/startSystemTestsWithDocker/index.html
```

**Comment by shrids** [comment]
The current health check for used Bookkeeper docker instances is ```ss -l | grep "+port+" || exit ``` ref : https://github.com/pravega/pravega/blob/master/test/system/src/main/java/io/pravega/test/system/framework/services/docker/DockerBasedService.java#L195 

The base image for pravega and bookkeper docker containers were changed to use Alpine as part of #2987  and the command ```ss``` does not exist on alphine base image.

Either the health check command used by the docker swarm based system test framework should be changed or ss command should be installed on the containers.

**Comment by fpj** [comment]
Good catch, @shrids . According to this documentation, we need to either install the `iproute2` or use `netstat`:

https://wiki.alpinelinux.org/wiki/Configure_Networking
