### ISSUE TITLE
Enhancement: A log collection tool for collecting all pravega related logs for all type of deployments.

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega#3088]
It is observed that collecting different logs in case of any failure is bit tiring, hence it will be good if we have a tool/script to collect all the logs required for debugging. This will definitely help us in collecting the logs in customer environment so that no need to ask customers for different logs, instead we can ask them to run this tool/script and provide the tar file created.

We may also need to keep in mind about different deployment environment we support while creating such tool.

**Comment by sumit-bm** [comment]
Pravega-k8-log-collection-utility for PKS / K8 / GKE environment and readme
Pull request: https://github.com/pravega/pravega-tools/pull/6

**Comment by RaulGracia** [comment]
Fixed via https://github.com/pravega/pravega-tools/pull/6,
