### ISSUE TITLE
Update security documentation

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3096]
**Problem description**
This security document:

https://github.com/pravega/pravega/blob/master/documentation/src/docs/security/pravega-security-encryption.md

says the following:

```
Encrypted access to Apache Zookeeper

This implementation is still in progress.
````

"progress" however points to an issue that has already been closed (https://github.com/pravega/pravega/issues/2034). We need to update the document accordingly.

**Problem location**
Documentation.

**Suggestions for an improvement**
Update the document to reflect the current state of the system.

**Comment by Aparnarr** [comment]
@fpj Will check with him and do the update
