### ISSUE TITLE
Enable Configurable Stats Providers in Bookkeper docker container

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3101]
**Problem description**
It is not possible to enable or configure Codahale metrics for the bookkeeper server deployed as the docker container using pravega-provided [Dockerfile](https://github.com/pravega/pravega/blob/master/docker/bookkeeper/Dockerfile).
There are no environment variables that one could pass to the docker container to enable the metrics and to set up the metrics provider.
Moreover, the container does not have the Stats Provider java classes needed to provide the Codahale or Prometheus metrics (see the related [BK issue](https://github.com/apache/bookkeeper/issues/458)).

**Problem location**
https://github.com/pravega/pravega/blob/master/docker/bookkeeper/

**Suggestions for an improvement**
The bookkeeper docker container should have all required Stats Provider java classes to be able to report Codahale and Prometheus metrics.
Also, it should take environment variables to make the metric settings configurable (see the list of configurable settings in the [bookkeeper docs](http://bookkeeper.apache.org/docs/4.5.0/admin/metrics/)).

**Comment by adrianmo** [comment]
According to https://github.com/apache/bookkeeper/issues/499, this was fixed in BookKeeper 4.6. Therefore, this issue is blocked on #3192, which updates Pravega's BookKeeper version to 4.7.3. Also this issue is blocked on https://github.com/pravega/pravega-operator/issues/63, which allows users to configure BK metrics on the `PravegaCluster` specification.

**Comment by adrianmo** [comment]
This issue was resolved by upgrading to BookKeeper 4.7 (#3192) and enabling metrics configuration in the Pravega Operator (https://github.com/pravega/pravega-operator/issues/63). Closing...
