### ISSUE TITLE
Controller restart  observed due to OutOfMemory on GKE environment after 17hrs of IO workload

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3121]
**Controller restart  observed due to OutOfMemory on GKE environment**

0.4.0-rc1 In a GKE cluster, started moderate IO with Pravega Benchmark tool, after ~17hrs of IO run observed controller restart due to OutOfMemory error. Each pod on K8 GKE environment is assigned with 3.7G memory.

```
State:          Running
      Started:      Sat, 17 Nov 2018 14:27:08 -0500
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Sat, 17 Nov 2018 06:54:13 -0500
      Finished:     Sat, 17 Nov 2018 14:27:06 -0500
    Ready:          True
    Restart Count:  1
```
**Steps Followed**

1. Created GKE cluster and deployed `Pravega Build : 0.4.0-rc1` by using `PravegaOperator` method
2. Started moderate IO longevity run with `Pravega Benchmark` tool
3. Observed Controller pod restarted after ~17hrs due to OOM

Please find the attached logs of complete cluster

[pravega-k8s-logging-2018-11-18-00-08-29.zip](https://github.com/pravega/pravega/files/2595190/pravega-k8s-logging-2018-11-18-00-08-29.zip)

**Comment by RaulGracia** [comment]
Probably related to #3042.

**Comment by fpj** [comment]
How do I know this was properly provisioned on GKE?

**Comment by RaulGracia** [comment]
@deenav We need to verify that this issue is still present:
1) Using the last version of `master` that contains multiple memory improvements for the Controller.
2) Using the provisioning guidelines for Pravega clusters to provision an adequate amount of resources to the Controller.

Could you please reproduce this?

**Comment by RaulGracia** [comment]
We have not seen any reproduction of this after merging PRs #3541 and #3525 and with the new deployment guidelines. Please @deenav, re-open this issue if the same issue appears again.
