### ISSUE TITLE
Inclusion of content for Retention Policy in Pravega concepts

### ISSUE THREAD

**Issue by Aparnarr** [pravega/pravega#3133]
**Problem description**
1. Need to include content for Retention Policy

**Problem location**
Documentation/Pravega-concepts.md

**Comment by RaulGracia** [comment]
Maybe you can just address this as part of #3098, given that the changes are linked, right?

**Comment by Aparnarr** [comment]
@yes! to make the links works, better to merge this pravega concepts.md
