### ISSUE TITLE
StatsD Reporter to support configured metrics prefix

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3137]
**Problem description**
In order to differentiate metrics data that is coming from various segment stores, the metric name should contain the hostname as a prefix.   There exists a configuration setting to support this, `metrics.metricsPrefix`, but the `StatDReporter` isn't being configured appropriately to use it (whereas other reporters are).

**Problem location**
`StatsProviderImpl`

**Suggestions for an improvement**
Supply the configured prefix to the StatsD reporter using `.withPrefix`.  This should improve consistency across the reporters.

**Comment by fpj** [comment]
Good catch, @EronWright . I don't understand why it is not added uniformly across the reporters. I see it added for graphite and ganglia, but not for cvs, statsd, imx, console.

The code reference for completeness:

https://github.com/pravega/pravega/blob/3f5b65084ae17e74c8ef8e6a40e78e61fa98737b/shared/metrics/src/main/java/io/pravega/shared/metrics/StatsProviderImpl.java#L65

**Comment by fpj** [comment]
It looks like jmx and console do not implement `prefixedWith`.

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pravega Metrics are being reported as Histograms](https://trello.com/c/OEk8u3Vu/33-new-pravega-metrics-are-being-reported-as-histograms)

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Metrics prefix](https://trello.com/c/M1P28xK5/45-metrics-prefix)

**Comment by EronWright** [comment]
Reopening this to track backport to 0.4.

**Comment by RaulGracia** [comment]
@fpj just ported the PR to branch `r0.4`.
