### ISSUE TITLE
Configure the default metrics prefix to be the hostname

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3138]
**Problem description**
Each segment store and controller should have a unique value for `metrics.metricsPrefix`, that being the hostname (i.e. `$HOST`). 

**Suggestions for an improvement**
There's a few ways to solve this:
1. Set the prefix in `entrypoint.sh` as a system property based on `$HOST`. 

2. Set the default value of the configuration setting in `MetricsConfig`, e.g.
```
public final static Property<String> METRICS_PREFIX = Property.named("metricsPrefix", InetAddress.getLocalHost().getHostName());
```
We should strive to use the short name (not FQDN) if possible.

3. In the config file, use a variable that would be expanded by the typesafe config parser. e.g.
```
metrics.metricsPrefix=${HOST}
```
Unclear whether environment variable expansion works here.

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Pravega Metrics are being reported as Histograms](https://trello.com/c/OEk8u3Vu/33-new-pravega-metrics-are-being-reported-as-histograms)

**Comment by RaulGracia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Metrics prefix](https://trello.com/c/M1P28xK5/45-metrics-prefix)

**Comment by fpj** [comment]
@adrianmo and I were talking about this issue offline as I was trying to understand whether this is a blocker issue. We can't see a good way of passing the hostname as the prefix with the pravega operator for kubernetes. As we need to be able to differentiate the metrics from the different instances and there is no good way to rely on the application to do it, it is sensible to use the hostname as the prefix default, and even mandatory in the case of the operator because I'm not sure we would be able to change once we hardwire it.

@adrianmo any further thoughts here?

**Comment by EronWright** [comment]
Thanks all for taking another look at this.   We do still consider it a blocker for 0.4; why was the version label removed?

**Comment by adrianmo** [comment]
The only way I see we can achieve this with the operator is leveraging the Downward API as we are doing [here](https://github.com/pravega/pravega-operator/blob/master/pkg/util/k8sutil.go#L20) with the `POD_NAME` variable.

@EronWright what do you think?

**Comment by EronWright** [comment]
OK that seems fine to use the pod name as the metrics prefix.

**Comment by adrianmo** [comment]
OK I will submit a PR to this repo to read and use `HOSTNAME` as metrics prefix and another one to the operator repo to set the `HOSTNAME` variable to the pod name via the Downward API.

**Comment by EronWright** [comment]
$HOSTNAME is a built-in bash variable.   Why would you need step two if you do step one?

**Comment by adrianmo** [comment]
Wow, I didn't know that... I just checked in Kubernetes and the variable is set in all pods. 

```
$ kubectl exec -ti example-bookie-0 printenv |grep HOSTNAME
HOSTNAME=example-bookie-0
$ kubectl exec -ti example-pravega-controller-67c66585d8-8bhz2 printenv |grep HOSTNAME
HOSTNAME=example-pravega-controller-67c66585d8-8bhz2
$ kubectl exec -ti example-pravega-segmentstore-1 printenv |grep HOSTNAME
HOSTNAME=example-pravega-segmentstore-1
```

In that case, if we rely on this, we don't need to change anything in the operator.
