### ISSUE TITLE
Eliminate the pravega auth environment variables

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3147]
**Problem description**
The auth plugin system should not rely on environment variables because it complicates the app developer experience.    The current experience involves setting such variables as:
- `PRAVEGA_CLIENT_AUTH_LOADDYNAMIC`
- `PRAVEGA_CLIENT_AUTH_METHOD`
- `PRAVEGA_CLIENT_AUTH_TOKEN`

**Suggestions for an improvement**
A better solution may be to either:
1. allow only one auth plugin to be loaded, or
2. negotiate with the loaded plugins, e.g. offer a user-supplied credential object (if any) to each plugin.

Here's a broader suggestion, that we improve on the design of the client-side plugin interface as follows.
1. Continue to accept a `Credentials` object from user code, with two concrete classes that are built-in to the Pravega client lib.  These classes contain state only, no behavior.
a. `UsernamePasswordCredentials`
b. `ApplicationDefaultCredentials` (a mere marker, no additional state)

2. Rework the service loader to find a `PravegaAuthCredentialsManager`, which implements an interface for generating the `Authorization` header based on the user-provided credentials object.   Pravega would load all available managers and negotiate as to which to use.   For example, the keycloak implementation would accept the `ApplicationDefaultCredentials` if a Keycloak credential (`keycloak.json`) is present in the environment.

**Comment by ravisharda** [comment]
Closing this issue after a prolonged period of inactivity.
