### ISSUE TITLE
AssertExtensions.assertThrows accepts ambiguous arguments

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3151]
**Problem description**
Both these statements compile currently.
```
        AssertExtensions.assertThrows("", ()->Futures.failedFuture(new Exception()), ex->true); // 1
        AssertExtensions.assertThrows("", ()->{throw new Exception();},ex->true);  // 2
```

Statement 1 will incorrectly report no exception has been thrown, while statement 2 will correctly report an exception has been thrown.

The first one should not compile at all because it returns a future (it should only work with `assertSuppliedFutureThrows`). This can cause weird bugs in testing if the developers trying to use it are confused about which one to choose.

**Problem location**
AssertExtensions.

**Suggestions for an improvement**

**Comment by fpj** [comment]
This is a result of the #3118 merge, yes? Maybe we can assign it to @eolivelli, would you be ok with it @eolivelli ? If you can accept the invitation to become a collaborator, I'll assign the issue to you.

**Comment by eolivelli** [comment]
Sure

**Comment by andreipaduroiu** [comment]
@eolivelli Thanks for looking at this. @tkaitchuck  and I thought about this for a bit yesterday and we couldn't find any pretty solutions.

The reason I consider this urgent is because there are quite a number of callsites where this is incorrectly used. The only reason it does "work" is because those callsites use mocks which throw synchronously, and not asynchronously, which is how real code would work. The previous syntax would have the compiler route the call to the correct method, but now it seems to route (statement 1) to `RunnableWithException`.

**Comment by eolivelli** [comment]
Did you find some case of wrong execution/call ?

**Comment by andreipaduroiu** [comment]
Yes. PR #3093 had to be changed yesterday due to this.

You can update any code locally and paste the snippet I put in this issue's description and see how it works. If you change the first one to `assertSuppliedFutureThrows` then it correctly determines it throws; but if you leave it as it is it does not. I simply want to avoid confusion going forward so that devs don't scratch their heads when the code compiles but it doesn't seem to work.

**Comment by eolivelli** [comment]
Okay, let me play with javac. 

The important thing is that currently we don't have tests which are passing while they shouldn't

**Comment by eolivelli** [comment]
I have an idea.
We can use a little bit of reflection to assert that the lambda does not 'return' a value.
I will prepare a prototype during the weekend

**Comment by eolivelli** [comment]
I have tried to use reflection to inspect the synthetic method which is generated at runtime to implement RunnableWithException, and unfortunately it really returns a 'void'. And the class declares only that single method.
```

    public static void assertThrows(String message, RunnableWithException runnable, Predicate<Throwable> tester) {
        try {
            Method[] declaredMethods = runnable.getClass().getDeclaredMethods();
            for (Method method : declaredMethods) {
                System.out.println("FOUND "+method.getReturnType()+" "+method);
            }
```

But the result is this one:
FOUND *void* public void io.pravega.test.common.UtilityMethodsTest$$Lambda$4/487888102.run()

So there is no chance

**Comment by eolivelli** [comment]
@andreipaduroiu 
Maybe a feasible approach to help rebasing existing pull requests is to rename even assertThrows, this way he developer will be forced to re-consider if he was using the RunnableWithException or the Supplier version of the module.

**Comment by andreipaduroiu** [comment]
I would not close this. It allows for ambiguous code. At the same time a developer will not have their unit test pass if they use the wrong method, so they will eventually figure out which one to use.

I think it's fine to close this if the only solution to this would be to rename the method.

**Comment by eolivelli** [comment]
As the method is 'asserThrows' there is no danger that the developer uses this method with something that returns a failing CompletableFuture: in this case the assertion will fail.

The problem would arise if we had 'assertNotThrows'

**Comment by eolivelli** [comment]
An alternative I have dropped it to change RunnableWithException to

```
interface RunnableWithException {
       public Object run() throws Exception;
}
```
But we will have to change all call sites and add a *return null*

 With such signature we can check that the method returns a null and not a CompletableFuture or anything else

**Comment by eolivelli** [comment]
It looks like we can close this old ticket.
I do not have other suggestions

@andreipaduroiu
