### ISSUE TITLE
Remove warning: No SupportedSourceVersion annotation during build.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3152]
**Problem description**
Ensure the build does not throw the below warnings.

```
warning: No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.BuildableProcessor' less than -source '1
```
and enable -Werror complier flag.

**Problem location**
`build.gradle`
**Suggestions for an improvement**
Enable -Werror for :test:system module once issue is resolved.

https://github.com/sundrio/sundrio/issues/120
https://github.com/kubernetes-client/java/issues/436

**Comment by LinuxSuRen** [comment]
In my use case, I solve this by setting idea. You can follow these steps:

Build, Execution, Deployment>Compiler>Java Compiler>Project bytecode version: 8
