### ISSUE TITLE
Non-unique projection of client key to segmentstore key

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3173]
**Problem description**
We are running a longevity test where the client writes to a stream at a constant event rate to 20 randomly pre-chosen keys. The stream has an event-rate triggered scaling policy. There are three writers in one writer group.

The event rate for an individual client key is **lower** than the scaling trigger, and we expect that for each value of the 20 client keys it would be possible to have a segment of a **finite** width that contains only one key, so we don't expect any segments to be splitting infinitely.

However, in reality we observe that after one day of running the test the stream arrives at a state when the number of  stream segments is less than 20 (the number of client keys) and almost half of the segments are empty (not being written into).
As to the active segments, some of them are infinitely narrow within the numerical precision (so that further splitting is impossible) and have the write rates that are double of the client write rate. 
This is the indication that more than one String-typed client key is being written to the same hash value of the segment key.

Example of the stream that stopped scaling at 19 segments per stream:
![heat-chart](https://user-images.githubusercontent.com/25368596/49536044-ffcc5280-f89b-11e8-87af-7626a0c12b0f.png)
(most of the active segments here are very narrow to be seen and are located between the light-blue inactive segments).

The client is writing to the following 20 keys:
```
0f5c8e82-4a90-4dab-b866-745cac949d72
1203a27d-d5aa-405c-87ba-cc4811b80e82
22cd4044-32a3-4f59-b49b-c467bdc09aaf
37138de7-c701-4042-bc9d-91a1fc52d4be
41f79861-39fe-4231-a980-d84e8a753c5d
452e4ea9-ca70-48a8-9f4b-59a0c7d3030f
4a83d604-83ca-4e27-9119-48d764ef4f2b
7eb437db-631d-49e8-8fd6-46c5bda879d1
8133ce55-0206-4e62-9991-c4c89e4d5822
883e76c3-6556-4751-93d8-08e9a734ab9d
93c9f3ad-a76e-4046-9fe6-63909c303988
aab63967-6ca0-4b15-89f3-e0625a558e54
ad88ceb4-703a-4fc0-9102-4ab6f4d6fab4
b476f659-e8f3-42b1-bea4-47c691c3a6fe
cf45b9fc-3244-4ec8-a26e-298a52866a1c
d6a890a4-051d-4f63-8b22-dade01cc0a6d
f617e1c4-eb5a-4e85-b576-1f0e5c9466bc
f62a2f91-7fe2-4e49-aa54-0b0c1cee4cdf
e7851825-f9b6-4601-bd42-0ce4fad2fb26
e94ce3e6-26d4-48ab-a48a-448aa9bd5203
```
(See the [client log file](https://github.com/pravega/pravega/files/2650036/logs-from-small-scale-young-worker-in-small-scale-young-worker-6fcd78db45-r99d7.txt.zip) for detail)

However, only 11 segments are being written into:
![write_rates](https://user-images.githubusercontent.com/25368596/49535324-491ba280-f89a-11e8-80ba-11a212d085a7.png) 

Looking at the response from the `scaling_events` API, 9 of the 11 active segments  (namely 904, 991, 1259, 1346, 1363, 1411, 1584, 1638, and 1656) have zero width (to the numerical precision) and have the write rates of 3 kB/s which is twice the 1.5 kB/s write rate per single client key. Check the [attached file](https://github.com/pravega/pravega/files/2650043/scaling.txt) for the exact key values.
So each of this 9 segments has its numerical segment key value being mapped from two distinct string values of client key.  

The two remaining active segments (1391 and 1647) have finite width and a write rate of 1.5 kB/s, suggesting that they are getting writes from one client key each.

The above behavior is observed for commit `26fb466`. 
It did not happen when we were running `0.3` pravega.

**Problem location**
Segmentstore

**Suggestions for an improvement**
Client keys should be uniquely mapped to segment keys

**Comment by shiveshr** [comment]
I computed the routing keys and no two keys seem to fall within same 
```0.010230615400202536
0.06631562903566057
0.0750030592002906
0.10059649959290495
0.1981993965791391
0.21545380617360688
0.28221637292493074
0.31922935652137796
0.3209129465032421
0.3428964395010723
0.3656542224898871
0.3948764982987092
0.5072847136524725
0.5356335129115986
0.644974303351473
0.7627678260683592
0.7836782129000528
0.8467609778626846
0.8648520646087436
0.8748416049381984
```

based on the segment list you shared, this is what the mapping seems to be:
```
            {
                "number": 1606,
                "epoch": 1040,
                "start": 1542293746347,
                "keyStart": 0.0,
				
				0.010230615400202536
				0.06631562903566057
				0.0750030592002906
				0.10059649959290495
				
                "keyEnd": 0.10775080511591957
            },

            {
                "number": 1650,
                "epoch": 1069,
                "start": 1542298842723,
                "keyStart": 0.13169599392275882,
				
				0.1981993965791391
				0.21545380617360688
				
                "keyEnd": 0.2665285889764868
            },

			
			{
                "number": 1647,
                "epoch": 1067,
                "start": 1542298229076,
                "keyStart": 0.26652858897648685,
				
				0.28221637292493074
				0.31922935652137796
				0.3209129465032421
				
                "keyEnd": 0.3256446003041333
            },

			
            {
                "number": 1391,
                "epoch": 896,
                "start": 1542279327801,
                "keyStart": 0.32564460030413334,
				
				0.3428964395010723
				0.3656542224898871
				0.3948764982987092

                "keyEnd": 0.4555873419055948
            },


            {
                "number": 1417,
                "epoch": 914,
                "start": 1542280546912,
                "keyStart": 0.45558734190559486,
				
				0.5072847136524725
				0.5356335129115986
				
                "keyEnd": 0.591123102211402
            }

			
			{
                "number": 1405,
                "epoch": 906,
                "start": 1542279930795,
                "keyStart": 0.5911231022114021,
				
				0.644974303351473
				0.7627678260683592
				0.7836782129000528
				
                "keyEnd": 0.7860536176139465
            },


            {
                "number": 1659,
                "epoch": 1076,
                "start": 1542301529715,
                "keyStart": 0.7860536176139467,
				
				0.8467609778626846
                0.8648520646087436
				0.8748416049381984
				
				"keyEnd": 0.897807548296801
            }
```

now this is unusual because these dont contain segments being written to according to the traffic pattern.. because none of the above segments have any data being written to you according to the heat map.. 

so i must be doing something wrong in computing the hash for routing key.. 
@tkaitchuck 
here is how i computed these hashes:
```        HashHelper hasher = HashHelper.seededWith("EventRouter");
hasher.hashToRange(x)
```
is that correct?

**Comment by shrids** [comment]
@shiveshr @tkaitchuck 

- Verified the hashes computed for the specified routing keys, it is correct.
- Verified that writes are happening on these keys. (PravegaWriter does write to all above 20 keys at a regular interval). 
- Based on the routing keys 
```
1. Events should not be written these 12 segments : 904, 951, 991, 1259, 1346, 1363, 1411, 1584, 1600, 1638, 1656, 1658
2. Events should be written only to these 7 segments : 1391, 1405, 1417, 1606, 1647, 1650, 1659
```
- Wrote a test to verify if the pravega writer choses the correct segment to write to with the given segment list (19) and 20 routing keys
ref: https://gist.github.com/shrids/d0c8fda982a80e54baaaa27488a4305f
This validates that data should be written to these 7 segments.
- The data log indicating that event is read from Segment 1638  (or the 12 listed above) is the part that I am unable to understand.

**Comment by tkaitchuck** [comment]
I have a unit test that might be reproducing this. It looks like a bug on line 91 of `StreamSegments`.
