### ISSUE TITLE
List of prerequisites: Release notes v0.4.0

### ISSUE THREAD

**Issue by Aparnarr** [pravega/pravega#3189]
I request the team to provide the latest version used and further updates on the below:

Zookeeper
Bookkeeper

**Deployment Methods:**
Docker Swarm 
Pravega Operator

**Integration Tool**
Flink connector 
**Tier 2 Storage:**
Cloud AWS is used as an optional tier 2 storage
HDFS is another optional tier 2 storage

**Comment by Aparnarr** [comment]
@adrianmo @sumit-bm @vijikarthi  requested for review

**Comment by Aparnarr** [comment]
@RaulGracia requested for review

**Comment by sumit-bm** [comment]
including @mejodev1

**Comment by Aparnarr** [comment]
@adrianmo @fpj @vijikarthi @RaulGracia @sumit-bm @mejodev I have shared the doc in the following link:
https://github.com/Aparnarr/Pravega-release-notes/blob/master/prerequisite.md
Please comment directly in the above repo.

**Comment by Aparnarr** [comment]
@ybasetty
https://github.com/Aparnarr/Pravega-release-notes/blob/master/prerequisite.md

**Comment by Aparnarr** [comment]
The following repo contains the draft of release notes: Please review
https://github.com/Aparnarr/Pravega-release-notes/blob/master/issue-list.md

**Comment by RaulGracia** [comment]
We can close this issue, as there are release notes for `0.4` (and we are actually going to release `0.5`).
