### ISSUE TITLE
Expensive metadata operation to calculate ongoing transactions

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3216]
**Problem description**
To report the number of ongoing transactions on a Stream we resort to a complex metadata operation (i.e., `getNumberOfOngoingTransactions`). Invoking this operation too frequently may impact Controller performance under heavy workloads.

**Problem location**
`getNumberOfOngoingTransactions` method.

**Suggestions for an improvement**
Look for optimizations to implement this function (see this [proposal](https://github.com/pravega/pravega/pull/3194/files#r242600863)).

**Comment by pbelgundi** [comment]
This has been fixed by PR: https://github.com/pravega/pravega/pull/6283
