### ISSUE TITLE
Support for user-supplied tags on scopes/streams

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3246]
**Problem description**
It would be a useful feature to be able to associate annotations or tags on scopes/streams that one creates via the controller API.  

A relevant scenario is to associate a scope with some external identifier related to the scope's purpose.  Imagine a [service broker](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/) for Pravega scopes where a service instance represents a provisioned Pravega scope.   Such a broker would create the scope with a friendly name, and track the underlying service instance ID (which is a UUID) as a tag on the scope.  In this way, the broker needn't have any additional database to store its state.

**Comment by EronWright** [comment]
Simply want to be able to create _and update_ labels on a scope.   Similar to how one applies labels to GCP VMs, to Kubernetes resources, etc.  

There is no ' update scope' API today AFAIK.  One option would be to introduce a `labels` sub-resource.

**Comment by claudiofahey** [comment]
Re https://github.com/pravega/pravega/wiki/PDP-50:-Stream-Tags:

> A valid Tag or singleton label must begin with an alphanumeric character ([a-z0-9A-Z])

Why are we limiting tags like this? This makes it impossible to use base64 or to encode non-english character sets. We should allow any UTF-8 string.

**Comment by claudiofahey** [comment]
> LIST STREAMs with a given tag(s)

Clarify whether returned streams must have **all** given tags or **any** given tags.

**Comment by claudiofahey** [comment]
> The update/delete tag APIs are strongly consistent given that it is treated similarly to an update stream operation.
> The read and filter tag APIs will show the current state of the tags or streams. It will eventually reflect the correct state in case any update operations are performed on the stream/tags.

This is not clear. Will this provide read-after-create or read-after-update consistency?
To be clear, is this pseudo-code guaranteed to work?
```
createStream("scope", "stream1", "tag1").await;
let tags = getTags("scope", "stream1").await;
assert(tags.contains("tag1"));
let streams = listStream("scope", "tag1").await;
assert(streams.contains("stream1");)
updateStream("scope", "stream1", "tag2").await;
let tags = getTags("scope", "stream1").await;
assert(tags.contains("tag2"));
```

**Comment by shrids** [comment]
Thanks for the feedback @claudiofahey I will update the PDP with this.

> Why are we limiting tags like this? This makes it impossible to use base64, JSON, or non-English characters. We should allow any UTF-8 string.

Ok, will update the doc

>To be clear, is this pseudo-code guaranteed to work?

yes.

**Comment by claudiofahey** [comment]
> > To be clear, is this pseudo-code guaranteed to work?
> 
> yes.

Then I don't understand what is meant by "eventually" in "It will **eventually** reflect the correct state in case any update operations are performed on the stream/tags." If the pseudo-code is guaranteed to work, that is strong consistency, not eventual consistency. If it were eventual consistency, then the caller would need to be prepared to repeat `tags.contains("tag2")` until it returned true.

**Comment by shrids** [comment]
yes, the wording in the PDP was not upto the mark. I have improved the PDP to eliminate this confusion.

**Comment by medvedevigorek** [comment]
Support of tags at Stream level is tracked by #6013. This one could be left to track tags support at Scope level. Thx
