### ISSUE TITLE
Delete empty test files

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3254]
**Problem description**
There are some stale test file that don't contain anything that have been sitting around for over two years. 

**Problem location**
EventStreamWriterTest.java
SegmentEventReaderTest.java
SegmentEventWriterTest.java
SegmentManagerTest.java
TransactionTest.java

**Suggestions for an improvement**
They should be deleted.

**Comment by RaulGracia** [comment]
Closed via #3255.
