### ISSUE TITLE
Lower read latency on periodically idle stream

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3395]
We can improve read latency at the expense of order by changing Orderer to be pathologically unfair and use the futures from the `fillBuffer` call to select which segment to read from. Because this negativity impacts fairness it should not be done before PDP-33 is complete. 

This could be implemented as follows: 
1. Change the `CompletableFuture<Void> fillBuffer()` call on SegmentInputStreamImpl to return `CompletableFuture<Segment>` where it returns it's own segment. (This can be made into a constant completed future to avoid overhead)
2. In EventStreamReaderImpl.readNextEventInternal move the sleep following the call to nextSegment into that call. So Orderer.nextSegment will need to be modified to take a timeout.
3. Inside of Orderer.nextSegment in the else block for isSegmentReady collect the returned futures into an array called `readyFutures`.
4. At the end in the unhappy case instead of `segments.get(MathHelpers.abs(counter.incrementAndGet()) % segments.size())` it can return `Futures.anyOf(readyFutures).get(timeout)`

**Comment by EronWright** [comment]
Looks like a redux of #2609.
