### ISSUE TITLE
Document Update: Pravega Security documentation 

### ISSUE THREAD

**Issue by Aparnarr** [pravega/pravega#3402]
**Problem description**
Updating documentation about setting up TLS for standalone mode

**Problem location**
documentation/pravega-security-configurations.md
documentation/deployment/run-local.md

**Suggestions for an improvement**
https://github.com/pravega/pravega/pull/3399

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 217: Connection pooling Design document](https://trello.com/c/BtKprslb/131-issue-217-connection-pooling-design-document)
