### ISSUE TITLE
Revisit authorization model

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3410]
**Problem description**
The discussion in issue #3277 made clear that we have inconsistencies in our security model, and there are at least two broad tasks we need to execute:

1- To make the permissions uniform across operations and resources. For example, deleting a stream requires `READ_UPDATE` on the parent resource.
2- To refine the permissions required for specific operations. For example, listing stream segments currently requires `READ_UPDATE`, while it should require `READ`.

**Problem location**
Security.

**Suggestions for an improvement**
This work encompasses the followjng tasks:

1. [x] Enhancements to authorization model (issue #3277)
2. [x] Reducing the level of permission required for some of the read operations that require higher permission levels (issue #3411)

**Comment by ravisharda** [comment]
The two sub-tasks mentioned in the description are done. Consequently, I'm closing this issue.
