### ISSUE TITLE
Event Processor Fairness deadlock

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3444]
**Problem description**
- commit-transactions happen on commit-event-processor
- all other request processing happen on request-event-processor

For mutual exclusion, if one processor is processing an event on a stream, it creates a fence by changing the state. Any other processor attempting to process another type of event, is fenced out and retries later. And it could potentially have continued to be fenced out upon each retry if there was a continuous large volume of incoming traffic on the other.
We saw this with large volumes of transactions stalling scale operations and hence we introduced a fairness logic that was as follows:

If a processor cannot process an event for a stream because it is fenced out, it sets a waiting processor flag with its id and postpones event processing..

Before processing a new event, each processor sees if there is a waiting processor and relinquishes processing by postponing it if there is a different processor in waiting.

now this causes deadlock in following situation:
```
1. event processing started on processor 1
2. processor 2 sets waiting processor 
3. processor 1's processing fails with retryable exception even after several retries
(or crashes mid way into processing). event is posted back (repicked) later and
attempted processing. 
4. event for processor 1 is picked again to complete the incomplete processing,
but before it starts processing, it checks the waiting processor flag and it honors
"waiting processor 2" and doesn't start execution. 
5. processor 2 cannot process any event because it is fenced out on metadata
and hence cant remove its waiting flag until it gets an opportunity to at least run once.

so `4` and `5` both back off, one for fairness, other because its fenced out. hence deadlock.
``` 

This was observed in system test run.

**Problem location**
AbstractRequestProcessor

**Suggestions for an improvement**
Before processing the event first call a new method called `ignoreWaitingProcessor` which looks at the metadata fence.. and if metadata fence matches the event to be processed, it should ignore any waiting processor

**Comment by fpj** [comment]
@shiveshr I understand the deadlock situation, but there is one point I don't understand. In step 3 of the scenario described above, the processor 1 fails to process the event for whatever reason. If in step 4 it ignores the waiting processor and fails again, then aren't we still preventing the progress of processor 2? 

One alternative that I'm not sure whether it is viable is that in the case processor 1 determines via the metadata fence that it is reprocessing an event, then it could roll back the state of the stream. Such a rollback would enable processor 2 to make progress independent of whether the processing of processor 1 eventually completes.

**Comment by shiveshr** [comment]
> If in step 4 it ignores the waiting processor and fails again, then aren't we still preventing the progress of processor 2

> In step 3 of the scenario described above, the processor 1 fails to process the event for whatever reason. If in step 4 it ignores the waiting processor and fails again, then aren't we still preventing the progress of processor 2?

The approach we have taken with our workflows is -- 
1. if work has started, it has to be brought to completion. 
2. mutual exclusion processing of distinct workflow

So we cannot make any progress until the work started in step `3` is completed once started. 
Once it completes (even if it fails several times but it should eventually complete), only then do we allow next work to be processed. And the next work is chosen from the waiting processor if there is one.
