### ISSUE TITLE
FileSystemStorage append-with-offset bug

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3454]
**Problem description**
- Append-with-offset only checks for larger offset, not smaller. This should be fixed.

This is thought to be the cause of:
```
2019-02-18 11:34:08,727 427188629 [core-14] ERROR i.p.s.s.h.handler.AppendProcessor - Error (Segment = 'Scope/_RGtest14/0.#epoch.0', Operation = 'append')
io.pravega.segmentstore.server.DataCorruptionException: Unable to parse AttributeSegment. LastSnapshot = (Offset=0, Length=0), Known Segment Length = 106662.
    at io.pravega.segmentstore.server.attributes.SegmentAttributeIndex.lambda$readAllSinceLastSnapshot$22(SegmentAttributeIndex.java:436)
...
Caused by: io.pravega.common.io.SerializationException: Unsupported format version 226.
    at io.pravega.common.io.serialization.VersionedSerializer.ensureCondition(VersionedSerializer.java:161)
```

Possible reproduction case:
- We have some sort of failover event but the old instance isn't allowed to terminate properly, so it still has writes in flight.
- The Segment Attribute Index on the old instance prepares to write some data. It picks its HashMap (I say this because it leads to unpredictable enumeration order), serializes it to a buffer and ships it to NFS. A similar thing happens on the new instance, but this one has a different data set (fewer or more attributes, depending on how it fetched them during recovery - pretty likely actually).
- The NFS layer, checks the size of the file, and then executes the write at that offset. So both instances will pass this size (since that's the original file size), then the NFS will write one, then the other at the same offset (the check+write is not atomic).
- If the shorter write happens to execute first, then we're good. If the longer write executes first, then the shorter write will overwrite some bytes from the longer one, then leave the rest dangling. At this point data is corrupted. Any new writes will occur after the "long" write.
- Reading will work well until it encounters those dangling bytes. It will call `VersionedSerializer` to interpret them, but that will fail since the first byte (header) doesn't map to a valid version (0). Hence `DataCorruptionException`.

**Problem location**
FileSystemStorage.

**Suggestions for an improvement**
Fix offset check.

**Comment by sachin-j-joshi** [comment]
https://github.com/pravega/pravega/issues/3489 has already fixed the offset bug mentioned here,
With  recent changes to Segment Attribute Index, this bug is no longer relevant. 
Also planned changes to simplified tier-2 will change the way fencing works.
