### ISSUE TITLE
No SegmentStore docker init failure when deploying with failed services in K8s

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3462]
**Problem description**
Deploying Pravega cluster with external access enabled and LoadBalancer as the service type,
I'm observing segment store servers to be in a running state when LoadBalancer services have not come up properly.

Checking the SegmentStore logs, I'm observing the following:
```
Running in a Kubernetes environment and managed by the Pravega Operator with external access enabled
Trying to obtain the external service endpoint...
Found external service endpoint: null:12345
Checking whether NFS mounting is required
```
This means that the `init_kubernetes.sh` script does not fail when `PUBLISHED_ADDRESS` variable comes back with a `null` value.

**Problem location**
SegmentStore docker init script 
https://github.com/pravega/pravega/blob/master/docker/pravega/scripts/init_kubernetes.sh

**Suggestions for an improvement**
`init_kubernetes.sh` should fail if either `PUBLISHED_ADDRESS` or `PUBLISHED_PORT` get a `null` value.

**Comment by adrianmo** [comment]
Thanks for reporting that @jkhalack. Can you tell a bit more about your environment? i.e. versions/commits of Pravega and operator, Kubernetes platform (PKS?) and version. I'll try to reproduce the issue and get back to you. 

Thank you.

**Comment by jkhalack** [comment]
@adrianmo I'm trying to deploy on PKS w/ NSX-T, and the LoadBalancer Services are not getting external IPs for some reason (I suspect it to be a separate non-related PKS issue).
