### ISSUE TITLE
Intermittent failure in io.pravega.segmentstore.server.host.HDFSIntegrationTest

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#3503]
**Problem description**
Intermittent failure in io.pravega.segmentstore.server.host.HDFSIntegrationTest.
This test fails occasionally.

           io.pravega.segmentstore.server.host.HDFSIntegrationTest > testEndToEnd FAILED
     java.util.concurrent.CompletionException: 
           io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0$offset.0'] The StreamSegment does not exist.
 
                  Caused by:
                  io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'Segment_0$offset.0'] The StreamSegment does not exist.
 
                      Caused by:
                      java.io.FileNotFoundException: Segment_0$offset.0

**Problem location**
io.pravega.segmentstore.server.host.HDFSIntegrationTest

**Suggestions for an improvement**
Need to repro this by continuously running the test in loop until it fails.

**Comment by RaulGracia** [comment]
While the situation with this test has improved recently with #3294, it is a recurrent issue: #2944, #2359, #2250, #1757.

**Comment by RaulGracia** [comment]
Closed via #4408
