### ISSUE TITLE
K8sClient should not retry on  UnknownHostException

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3527]
**Problem description**
Currently `K8sClient` retries if an IOException is observed while downloading logs and tracking the status of a pod. The K8sClient should not retry if it faces `UnknownHostException` which also of type `IOException`. 

**Problem location**
K8sClient.

**Suggestions for an improvement**
On observing an UnknownHostException the test framework should fail the test.

**Comment by fpj** [comment]
What about retrying a bounded number of times?
