### ISSUE TITLE
Observing Bookie restart with error "BookieException$CookieNotFoundException" 

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega#3535]
**While deploying Pravega-Operator Observing Bookie restart with error "BookieException$CookieNotFoundException"** 

Environment details: PKS / K8 with medium cluster:
```
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
```
Pravega version: zk-closed-client-issue-0.5.0-2162.0bbfa42
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: adrianmo/pravega-operator:pr-145-2
```
```
# kubectl logs -p pravega-bookie-1
wait for zookeeper
pravega
zookeeper
format bookie data and metadata
10:59:14,811 WARN  No cookie to remove :
org.apache.bookkeeper.bookie.BookieException$CookieNotFoundException: pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181
        at org.apache.bookkeeper.discover.ZKRegistrationManager.readCookie(ZKRegistrationManager.java:345)
        at org.apache.bookkeeper.bookie.Cookie.readFromRegistrationManager(Cookie.java:332)
        at org.apache.bookkeeper.bookie.Cookie.readFromRegistrationManager(Cookie.java:316)
        at org.apache.bookkeeper.bookie.BookieShell$BookieFormatCmd.lambda$runCmd$0(BookieShell.java:423)
        at org.apache.bookkeeper.meta.MetadataDrivers.lambda$runFunctionWithRegistrationManager$1(MetadataDrivers.java:398)
        at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:373)
        at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:398)
        at org.apache.bookkeeper.bookie.BookieShell$BookieFormatCmd.runCmd(BookieShell.java:421)
        at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:232)
        at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2816)
        at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2907)
start bookie
Environment Vars for bookie:
  BK_bookiePort bookie service port is 3181
  BK_zkServers is pravega-zk-client:2181
  BK_DATA_DIR is /data/bookkeeper
  BK_CLUSTER_ROOT_PATH is /pravega/pravega/bookkeeper
  BK_metadataServiceUri is zk://pravega-zk-client:2181/pravega/pravega/bookkeeper/ledgers
  BK_dlogRootPath is /pravega/pravega/bookkeeper/distributedlog
conf files:
['/opt/bookkeeper/conf/log4j.shell.properties', '/opt/bookkeeper/conf/log4j.cli.properties', '/opt/bookkeeper/conf/zookeeper.conf', '/opt/bookkeeper/conf/zookeeper.conf.dynamic', '/opt/bookkeeper/conf/bk_server.conf', '/opt/bookkeeper/conf/bk_cli_env.sh', '/opt/bookkeeper/conf/jaas_example.conf', '/opt/bookkeeper/conf/nettyenv.sh', '/opt/bookkeeper/conf/bkenv.sh', '/opt/bookkeeper/conf/log4j.properties']
[/opt/bookkeeper/conf/bk_server.conf] Applying config bookiePort = 3181
[/opt/bookkeeper/conf/bk_server.conf] Applying config indexDirectories = /bk/index
[/opt/bookkeeper/conf/bk_server.conf] Applying config journalDirectory = /bk/journal
[/opt/bookkeeper/conf/bk_server.conf] Applying config ledgerDirectories = /bk/ledgers
[/opt/bookkeeper/conf/bk_server.conf] Applying config metadataServiceUri = zk://pravega-zk-client:2181/pravega/pravega/bookkeeper/ledgers
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsKeyStore = /var/private/tls/bookie.keystore.jks
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsKeyStorePasswordPath = /var/private/tls/bookie.keystore.passwd
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsKeyStoreType = JKS
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsProvider = OpenSSL
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsTrustStore = /var/private/tls/bookie.truststore.jks
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsTrustStorePasswordPath = /var/private/tls/bookie.truststore.passwd
[/opt/bookkeeper/conf/bk_server.conf] Applying config tlsTrustStoreType = JKS
[/opt/bookkeeper/conf/bk_server.conf] Applying config useHostNameAsBookieID = true
[/opt/bookkeeper/conf/bk_server.conf] Applying config zkLedgersRootPath = /pravega/pravega/bookkeeper/ledgers
[/opt/bookkeeper/conf/bk_server.conf] Applying config zkServers = pravega-zk-client:2181
Created bookie dirs :
  journal = /bk/journal
  ledger = /bk/ledgers
  index = /bk/index
wait for zookeeper
pravega
zookeeper
create the zk root dir for bookkeeper
Path /pravega/pravega/bookkeeper already exists
Path /pravega/pravega/bookkeeper/ledgers/available/readonly doesn't exist
Path /pravega/pravega/bookkeeper/bkInitLock already exists
Bookkeeper znodes not exist in Zookeeper, do the init to create them.
10:59:15,871 ERROR Ledger root path: /pravega/pravega/bookkeeper/ledgers already exists
Bookkeeper znodes init failed. please check the reason.
```

**Comment by anishakj** [comment]
I am observing the same issue in docker swarm with master branch.
One of the bookie is  getting started and is getting unhealthy  in few seconds.

bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | wait for zookeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | zookeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | format bookie data and metadata
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | 05:56:46,474 WARN  No cookie to remove :
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | org.apache.bookkeeper.bookie.BookieException$CookieNotFoundException: 10.0.0.162:3181
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.discover.ZKRegistrationManager.readCookie(ZKRegistrationManager.java:345)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.Cookie.readFromRegistrationManager(Cookie.java:332)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.Cookie.readFromRegistrationManager(Cookie.java:316)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.BookieShell$BookieFormatCmd.lambda$runCmd$0(BookieShell.java:423)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.meta.MetadataDrivers.lambda$runFunctionWithRegistrationManager$1(MetadataDrivers.java:398)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:373)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithRegistrationManager(MetadataDrivers.java:398)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.BookieShell$BookieFormatCmd.runCmd(BookieShell.java:421)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.BookieShell$MyCommand.runCmd(BookieShell.java:232)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2816)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |         at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2907)
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | start bookie
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Environment Vars for bookie:
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   BK_bookiePort bookie service port is 3181
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   BK_zkServers is 10.0.0.159:2181
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   BK_DATA_DIR is /data/bookkeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   BK_CLUSTER_ROOT_PATH is /pravega/pravega-cluster/bookkeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   BK_metadataServiceUri is zk://10.0.0.159:2181/pravega/pravega-cluster/bookkeeper/ledgers
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   BK_dlogRootPath is /pravega/pravega-cluster/bookkeeper/distributedlog
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | conf files:
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | ['/opt/bookkeeper/conf/bk_cli_env.sh', '/opt/bookkeeper/conf/bk_server.conf', '/opt/bookkeeper/conf/bkenv.sh', '/opt/bookkeeper/conf/jaas_example.conf', '/opt/bookkeeper/conf/log4j.cli.properties', '/opt/bookkeeper/conf/log4j.properties', '/opt/bookkeeper/conf/log4j.shell.properties', '/opt/bookkeeper/conf/nettyenv.sh', '/opt/bookkeeper/conf/zookeeper.conf', '/opt/bookkeeper/conf/zookeeper.conf.dynamic']
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config bookiePort = 3181
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config indexDirectories = /bk/index
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config journalDirectory = /bk/journal
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config ledgerDirectories = /bk/ledgers
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config metadataServiceUri = zk://10.0.0.159:2181/pravega/pravega-cluster/bookkeeper/ledgers
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsKeyStore = /var/private/tls/bookie.keystore.jks
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsKeyStorePasswordPath = /var/private/tls/bookie.keystore.passwd
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsKeyStoreType = JKS
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsProvider = OpenSSL
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsTrustStore = /var/private/tls/bookie.truststore.jks
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsTrustStorePasswordPath = /var/private/tls/bookie.truststore.passwd
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config tlsTrustStoreType = JKS
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config zkLedgersRootPath = /pravega/pravega-cluster/bookkeeper/ledgers
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | [/opt/bookkeeper/conf/bk_server.conf] Applying config zkServers = 10.0.0.159:2181
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Created bookie dirs :
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   journal = /bk/journal
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   ledger = /bk/ledgers
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    |   index = /bk/index
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | wait for zookeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | pravega
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | zookeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | create the zk root dir for bookkeeper
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Path /pravega/pravega-cluster/bookkeeper already exists
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Path /pravega/pravega-cluster/bookkeeper/ledgers/available/readonly doesn't exist
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Path /pravega/pravega-cluster/bookkeeper/bkInitLock already exists
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Bookkeeper znodes not exist in Zookeeper, do the init to create them.
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | 05:56:47,372 ERROR Ledger root path: /pravega/pravega-cluster/bookkeeper/ledgers already exists
bookkeeper.2.uw3a7pcntqfp@redhook-master-3    | Bookkeeper znodes init failed. please check the reason.

**Comment by vedanthh** [comment]
Observing same behavior for one of the Bookie in my cluster with build `0.5.0-2189.cabe11b`
```
Containers:
  bookie:
    Container ID:   docker://6c50d8a3aebcea5a16381cc680412aa9d975c78f95f8532d48727eb9f9190a7d
    Image:          devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2189.cabe11b
    Image ID:       docker-pullable://devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:2531729651c88b9912fcce7781d5fe97035e2a147657ac7879a62001addfaa8e
    Port:           3181/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 05 Apr 2019 03:45:42 -0400
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      1
      memory:   2Gi

```
Events:
  Type     Reason     Age                         From                                           Message
  ----     ------     ----                        ----                                           -------
  Warning  Unhealthy  <invalid> (x16119 over 4d)  kubelet, 85b36a2b-6e69-4e9d-a38f-a1a9bb4e6563  (combined from similar events): Readiness probe failed: 06:45:39,334 INFO  Created ledger 129529
06:45:39,555 ERROR Could not get additional bookie to remake ensemble, closing ledger: 129529
06:45:39,555 ERROR Closing ledger 129529 due to NotEnoughBookiesException: Not enough non-faulty bookies available
06:45:39,556 ERROR Write of ledger entry to quorum failed: L129529 E0
06:45:39,557 WARN  Error in bookie sanity test
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
  at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
  at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
  at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91)
  at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:361)
  at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1546)
  at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:523)
  at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.lang.Thread.run(Thread.java:748)
06:45:39,566 INFO  Deleted ledger 129529
```

**Comment by sumit-bm** [comment]
Observed in docker swarm environment too and couple of initial Bookie failure observed before gaining stability:
```
create the zk root dir for bookkeeper
Path /pravega/pravega-cluster/bookkeeper already exists
Path /pravega/pravega-cluster/bookkeeper/ledgers/available/readonly doesn't exist
Path /pravega/pravega-cluster/bookkeeper/bkInitLock already exists
Bookkeeper znodes not exist in Zookeeper, do the init to create them.
05:30:15,572 ERROR Ledger root path: /pravega/pravega-cluster/bookkeeper/ledgers already exists
Bookkeeper znodes init failed. please check the reason.
```
```
[root@nautilus-master-1 ~]# docker ps -a
CONTAINER ID        IMAGE                                                                                                                       COMMAND                  CREATED             STATUS                      PORTS                                                          NAMES
0300f2f94086        devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:9ecc9be59396ea733a61f0afcff338eafef67d33ebafced56407cc6dff0c0cfb   "/bin/bash /opt/bo..."   19 minutes ago      Up 19 minutes (healthy)     3181/tcp                                                       pravega_bookkeeper.2.pxv0yjre8qgqfzguje9f7mbcb
7c8808089e19        devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:9ecc9be59396ea733a61f0afcff338eafef67d33ebafced56407cc6dff0c0cfb   "/bin/bash /opt/bo..."   19 minutes ago      Up 19 minutes (healthy)     3181/tcp                                                       pravega_bookkeeper.3.kzvz2oqinftv2dlyti3vorkiw
c8c501de411f        devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:9ecc9be59396ea733a61f0afcff338eafef67d33ebafced56407cc6dff0c0cfb   "/bin/bash /opt/bo..."   19 minutes ago      Exited (0) 19 minutes ago                                                                  pravega_bookkeeper.3.kpeyxq0xpp0ame0qns8br2rgr
1f7a68407d68        devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:9ecc9be59396ea733a61f0afcff338eafef67d33ebafced56407cc6dff0c0cfb   "/bin/bash /opt/bo..."   19 minutes ago      Exited (0) 19 minutes ago                                                                  pravega_bookkeeper.2.ntpeo5110f35z479z71s2bjn9
dd4c42c3b9ee        devops-repo.isus.emc.com:8116/nautilus/pravega@sha256:0e3996ac9fb7c2755922115ed9f67b8ff0a3492e4638b83f67cbd89cda2a4869      "/opt/pravega/scri..."   19 minutes ago      Up 19 minutes               9090-9091/tcp, 10000/tcp, 12345/tcp                            pravega_segmentstore.1.cohqyugsxybsm0g2qqbco6ork
95636f1af4c4        devops-repo.isus.emc.com:8116/nautilus/bookkeeper@sha256:9ecc9be59396ea733a61f0afcff338eafef67d33ebafced56407cc6dff0c0cfb   "/bin/bash /opt/bo..."   19 minutes ago      Up 19 minutes (healthy)     3181/tcp                                                       pravega_bookkeeper.1.zh5nwxo9918fglli8qaxmoxdp
e2ca9245cf04        devops-repo.isus.emc.com:8116/nautilus/pravega@sha256:0e3996ac9fb7c2755922115ed9f67b8ff0a3492e4638b83f67cbd89cda2a4869      "/opt/pravega/scri..."   19 minutes ago      Up 19 minutes               9090-9091/tcp, 10000/tcp, 12345/tcp                            pravega_controller.1.ian2lm7lrvqwkb5uq3hq1d0lp
5180b45d1bff        zookeeper@sha256:12b1073f0ae08e97f3253bc2c214176959986575f64213a4ae454f31da25c11f                                           "/docker-entrypoin..."   21 minutes ago      Up 20 minutes               2181/tcp, 2888/tcp, 3888/tcp                                   pravega_zookeeper.1.p3o7z0aiwuafvyqbdkt7coxpy
eaee10b0ea29        pravega/hdfs@sha256:2ad9c621f08da3ad8fdbdb5488b3f09abe580cf8e61c467a5d382372eebbea53                                        "/entrypoint.sh -d"      21 minutes ago      Up 21 minutes               22/tcp, 8020/tcp, 50020/tcp, 50070/tcp, 50075/tcp, 50090/tcp   pravega_hdfs.1.lxmcrkucbijzi3o2gcvwm0ixh
```

**Comment by RaulGracia** [comment]
I also have observed this behavior while the Bookkeeper service is being deployed. In the conversation I had with @adrianmo about this, it looks to be the expected behavior when multiple Bookies are racing in the service initialization. Note that any failed pod with this error is automatically restarted and the Bookkeeper service works correctly from that point onwards.

**Comment by vedanthh** [comment]
Observed same issue in `AWS cluster` environment while deploying pravega build `0.5.0-2305.31c34b9` as well.

```
09:58:20,805 ERROR Ledger root path: /pravega/pravega/bookkeeper/ledgers already exists
Bookkeeper znodes init failed. please check the reason.
```
