### ISSUE TITLE
Incorrect segment splits/merges Micrometer metrics

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3556]
**Problem description**

On a stream with a dynamic scaling, the controller reports incorrect metrics for segment splits (`pravega_controller_segment_splits_<scope>_<stream>_Counter`) and segment merges  (`pravega_controller_segment_merges_<scope>_<stream>_Counter`). 

Example: 
The split metrics report the following sequence of split events: 
`1, <0>, 3, <0>, 7, <0>, 14, <0>, 20, <0>, 23, ...`
![segments_metrics](https://user-images.githubusercontent.com/25368596/55345550-8679f080-5486-11e9-8112-8ddf0e6f5b5f.png)

The controller REST API reports the following split numbers for the same time intervals:
`1, <0>, 2, <0>, 4, <0>, 7, <0>, 6, <0>, 3, ...` 
![segments_api](https://user-images.githubusercontent.com/25368596/55345560-8a0d7780-5486-11e9-9b7d-61915df941df.png)

The issue is observed on commit `b49b761`  with single-controller deployment.
This commit has the Micrometer migration PR #3501  merged in, so the Counters are supposed to report only the number of splits or merges during the last `metrics.outputFrequencySeconds` time interval, not the total number of splits or merges from the stream creation. 

The issue is **not** observed on commit `f65a978` with single-controller deployment (with the old style counter that **is expected** to report the number of splits or merges since stream creation).

**Note:** Issue #1761 that also shows incorrect splits/merges metrics is a multi-controller issue, and here the metrics are broken with a single controller.

**Problem location**
[AbstractStreamMetadataStore.java](https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/store/stream/AbstractStreamMetadataStore.java) ?

**Suggestions for an improvement**
Controller should report correct `segment_splits` and `segment_merges` metrics

**Comment by RaulGracia** [comment]
This is already fixed in #1761. Once this PR gets merged, splits and merged will be reported correctly.
