### ISSUE TITLE
Missing asynchronous read event and byte stream write methods

### ISSUE THREAD

**Issue by akurilov** [pravega/pravega#3587]
**Problem description**
Pravega client API provides asynchronous methods for
- event write (e.g. https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/stream/EventStreamWriter.java#L39)
- controller API (create/delete the stream/scope)
- byte stream read
  https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/byteStream/ByteStreamReader.java#L137

This allows the client to rely on the Pravega client thread/connection pool and write more resource-effective client code using some reactive approach. However, the following methods:
- event read
- byte stream write

are blocking. Moreover, these blocking methods are wrapping the underlying asynchronous calls likely reducing the client side performance (e.g. package private class https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/segment/impl/AsyncSegmentInputStreamImpl.java#L42)

**Problem location**
https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/stream/EventStreamReader.java#L42
https://github.com/pravega/pravega/blob/3fd167ecd36603251d92d9da09adeebc5293981d/client/src/main/java/io/pravega/client/byteStream/ByteStreamWriter.java#L51

**Suggestions for an improvement**
Provide/expose the asynchronous methods to the client for:
- event read
- byte stream write

**Comment by tkaitchuck** [comment]
No. Please read the javadoc. It is implementing OutputStream and it says:
```The data is buffered internally to avoid blocking.
As such it cannot be assumed to be durably stored until a flush completes.
It is intended that this method not block, but it may in the event that the server becomes disconnected for sufficiently long or is sufficiently slow that that backlog of data to be written becomes a memory issue.```

**Comment by tkaitchuck** [comment]
It could return a future, to make is more clear that it is async, but then it would not be complaint with the OutputStream interface. Which is very important for passing it into libraries that are not specific to Pravega.
