### ISSUE TITLE
Tracking issue: Pravega recovery from an unstable deployment

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3589]
Filing this issue to track Pravega recovery areas needs to be planned / featured from an unstable deployment or various failure scenarios. Some of the open questions would be following:

1. What is expected when a complete cluster went down ( Pravega Operator on PKS / K8 or GCP environment / production deployment like Docker swarm / AWS) where Pravega IO was running? Could the whole cluster with data be recovered or could only data be recovered and customer would curve out a new cluster and be able to restore the data?

2. What is expected when some of the Pravega components are down (Complete SS failure after a few days of operation / BK failures), how to recover customer data in these scenarios?

3. What happens if the persistent store data is not available (VSAN datastore / PVC failure)?

4. Could we recover data from Tier 1 storage / SSD?

5. Could we have safe checkpoint and mention that till this point data be recovered in any point of catastrophic failures?

**Comment by fpj** [comment]
If this is still an issue, please reopen.
