### ISSUE TITLE
Adjust dependency relationship for Pravega metrics and beyond

### ISSUE THREAD

**Issue by kevinhan88** [pravega/pravega#3631]
**Problem description**
With the migration of micrometer, Pravega metrics becomes more sophisticated; new it becomes necessary for metrics to dependent on basic Stream/Segment definitions and controller configs, in order to avoid coping/pasting some internal details into metrics code base.

**Problem location**
pravega/shared/protocol/.../segment/StreamSegmentNameUtils.javas
pravega/controller/.../util/Config.java

**Suggestions for an improvement**
move shared/protocol/....StreamSegmentNameUtils.java to "shared" level;
move controller/...Config.java to "shared" level too.
So "shared/protocol" and "shared/metrics" can both depend on "shared".

**Comment by fpj** [comment]
Moving:

 ```
pravega/shared/protocol/.../segment/StreamSegmentNameUtils.java
```

seems ok, but I'm not convinced about moving the controller config to `shared`. Logically, the controller config concerns only the controller, and by making it shared we are violating abstraction. If there is some aspect of the config that needs to be shared, then let's talk about it, but not make the config shared.

**Comment by kevinhan88** [comment]
Exactly, the config should be broken down with its own hierarchy. Today we have metricConfig, controllerConfig, so we may have a new config called commonConfig, actually a portion of the controller config, and move it into "shared".
