### ISSUE TITLE
Make direct reads configurable in RocksDB

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3645]
**Problem description**
According to RocksDB [documentation](https://github.com/facebook/rocksdb/wiki/Direct-IO), enabling direct reads is desirable because i) it avoids using the OS page cache, which requires extra copies of the data, and ii) RocksDB should have a better knowledge of the logical semantics of the data than OS (e.g., replacement policies). For this reason, `RocksDBCache.java` has by default `setUseDirectReads(true)`. However, direct reads are not always available for all OS. In this case, we should expose this parameter in the configuration to disable direct reads when this option is not available in the host OS. 

**Problem location**
`RocksDBCache` and config.

**Suggestions for an improvement**
Make RocksDB direct reads configurable.

**Comment by fpj** [comment]
Reopen so that we also fix it in `r0.5`.

**Comment by RaulGracia** [comment]
Merged in `0.5`.
