### ISSUE TITLE
"gradlew distribution" failed on "branch-0.5" release source code

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3649]
**Cannot invoke method log() on null object** error while building Pravega from release `branch-0.5` source code (tar & zip) files 
https://github.com/pravega/pravega/archive/branch-0.5.tar.gz
https://github.com/pravega/pravega/archive/branch-0.5.zip

**gradlew distribution log**
```
[root@master pravega-branch-0.5]# ./gradlew distribution

> Configure project :
Build JVM Version is : 1.8.0_181 (Oracle Corporation 25.181-b13)
No git repository found for :. Accessing grgit will cause an NPE.

FAILURE: Build failed with an exception.

* Where:
Build file '/root/workdir/pravega-branch-0.5/build.gradle' line: 918

* What went wrong:
A problem occurred evaluating root project 'pravega'.
> Cannot invoke method log() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**gradlew distribution --info log**
```
[root@master pravega-branch-0.5]# ./gradlew distribution --info
Initialized native services in: /root/.gradle/native
The client will now receive all logging from the daemon (pid: 28402). The daemon log file: /root/.gradle/daemon/4.10.2/daemon-28402.out.log
Starting 16th build in daemon [uptime: 1 hrs 19 mins 12.216 secs, performance: 99%, no major garbage collections]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/root/workdir/pravega-branch-0.5/settings.gradle'.
Projects loaded. Root project using build file '/root/workdir/pravega-branch-0.5/build.gradle'.
Included projects: [root project 'pravega', project ':bindings', project ':client', project ':common', project ':controller', project ':segmentstore', project ':shared', project ':standalone', project ':test', project ':segmentstore:contracts', project ':segmentstore:server', project ':segmentstore:storage', project ':shared:authplugin', project ':shared:cluster', project ':shared:controller-api', project ':shared:metrics', project ':shared:protocol', project ':test:integration', project ':test:system', project ':test:testcommon', project ':segmentstore:server:host', project ':segmentstore:storage:impl']

> Configure project :
Evaluating root project 'pravega' using build file '/root/workdir/pravega-branch-0.5/build.gradle'.
Build JVM Version is : 1.8.0_181 (Oracle Corporation 25.181-b13)
No git repository found for :. Accessing grgit will cause an NPE.

FAILURE: Build failed with an exception.

* Where:
Build file '/root/workdir/pravega-branch-0.5/build.gradle' line: 918

* What went wrong:
A problem occurred evaluating root project 'pravega'.
> Cannot invoke method log() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by fpj** [comment]
Thanks for reporting this, @deenav . A couple of things:

1- It is good practice to `clean` before building the distribution, we say it in the release notes, which is what we use this `distribution` for. You should run `./gradlew clean distribution`.
2- The `branch-0.5` is only reference tag, I'm not sure why you're using it as a release tag.
3- I can't reproduce it, but I'd like others here to try and see if they can.

**Comment by shrids** [comment]
@deenav I was not able to reproduce it with the below sequence of steps. You could compare it against the steps that you followed.

1- `git clone https://github.com/pravega/pravega.git`
2 - `cd pravega`
3-  `git tag -l`  this command is used to list all tags.
4-  `git checkout tags/branch-0.5`  this checks out the tag branch-0.5
5- `./gradlew clean distribution`

**Comment by deenav** [comment]
@fpj I have tried with `./gradlew clean distribution` but that also failed to build. I was in the impression that `branch-0.5` is release tag since I could see it in https://github.com/pravega/pravega/releases location.

@shrids , The steps what you have mentioned (using `git clone`) is working for me too. 
But as I already mentioned, building Pravega from the release `branch-0.5` source code (tar & zip) files fails. 
https://github.com/pravega/pravega/archive/branch-0.5.tar.gz
https://github.com/pravega/pravega/archive/branch-0.5.zip

1. `wget https://github.com/pravega/pravega/archive/branch-0.5.tar.gz`
2. `tar -xvf branch-0.5.tar.gz`
3. `cd pravega`
4. `./gradlew clean distribution` --> It fails with the error `Cannot invoke method log() on null object`

Please note that I am following these same steps for 2 reasons.
1. It worked fine with earlier releases like `v0.4.1-rc0` and `v0.4.0`
2. I need to build the Pravega client for `8ba5431` commit id which is given to QE team to start testing. So, I can not use `git clone` method since it already merged with latest commits `ce3ba81` in `r0.5` branch.

Let me know if I am missing something.

**Comment by shrids** [comment]
@deenav 
` git checkout tags/branch-0.5` checks out the tag `branch-0.5`. The tag `branch-0.5` points to commit id `8ba5431`. Hence a `./gradlew clean distribution` after `git checkout tags/branch-0.5` step will build Pravega  with commit id `8ba5431` .

(Performing a build on `https://github.com/pravega/pravega/archive/branch-0.5.tar.gz` fails as the `grgit` plugin fails since it does not find the git information as the tar.gz is not a git repository, leading to the error)

**Comment by deenav** [comment]
My observation on `grgit` plugin is, it fails for previous releases ` v0.4.1-rc0` and `v0.4.0` too but the `./gradlew clean distribution` was success over there. I see that `build` directory is missing in the extracted  `tar` file contents of `branch-0.5`. 

 Now, I am able to build Pravega with commit id `8ba5431` by following your steps. Thanks @shrids

**Comment by sumit-bm** [comment]
@fpj  @shrids I have observed same issue too. RC builds of 0.4.0 are working fine while doing `./gradlew install` where `branch-0.5` contents building (same method) fails.
```
[root@manager1 pravega-branch-0.5]# ./gradlew install

> Configure project :
Build JVM Version is : 1.8.0_181 (Oracle Corporation 25.181-b13)
No git repository found for :. Accessing grgit will cause an NPE.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sumit/pravega-050-fc-bld-2222/pravega-0.5.0-2222.8ba5431/pravega-branch-0.5/build.gradle' line: 918

* What went wrong:
A problem occurred evaluating root project 'pravega'.
> Cannot invoke method log() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```
