### ISSUE TITLE
Exceptions raised by controller gRPC API are overly abstract

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3653]
**Problem description**
The Controller gRPC API throws the rather general [StatusRuntimeException](https://grpc.io/grpc-java/javadoc/io/grpc/StatusRuntimeException.html), which is problematic in these respects:
* *Leaky abstraction*. One has to inspect the inner exceptions and/or the message itself to understand the exception condition, which is perhaps OK for human users. But, the client app shouldn't need to depend on exception messages or inner exceptions, as those things can/should be allowed to change without any compatibility concerns.

* *Lack of expressiveness*. The exception name `StatusRuntimeException` is not expressive, even though it is perfectly OK as a top-level exception (as explained below). For instance, receiving the generic `StatusRuntimeException` when auth has failed, doesn't tell you what really went wrong. One can look at the message, but its really the exception name itself which should convey the meaning of the condition leading to the exception. Besides, not to mention, for exception handling on the client app, it really can only handle exceptions by catching the exception itself. 

* *Difficulty in error handling*. `StatusRuntimeException` homogenizes several classes of exception conditions, which is useful for callers if they don't care about what has failed. This is much like Java's `RuntimeException`,  `SQLException` or `IOException`. 

   It's not useful to throw such top-level exceptions directly though: you'd rather throw subtypes like `IllegalArgumentException`, `SQLIntegrityConstraintViolationException` or ` FileNotFoundException`. Similarly, it'd be much more useful if subtypes of `StatusRuntimeException` (and not `StatusRuntimeException` itself) were thrown, each representing a precise exception condition. 

  A negative side-effect of this sub-problem can be seen in the client-side proxy `ControllerImpl` in the lines shown below. It retries calls to the server upon encountering `StatusRuntimeException`, irrespective of the underlying exception condition and whether it is recoverable or not. It has to do that because the exception encapsulates both recoverable and irrecoverable conditions. However, there is no point in retrying if authentication or authorization has failed. It might make sense to do so if the condition was a transient connectivity issue. A side effect of automatic retries on irrecoverable errors is that it takes much longer than expected for a client application to get the feedback later rather than sooner. The root of this problem ultimately lies in the absence of precise exceptions being thrown by the server.
https://github.com/pravega/pravega/blob/cb253c8c73b076adbe76cd87da8418c09a8989b3/client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java#L156-L159

**Problem location**
Controller grpc service implementation

**Suggestions for an improvement**
Creating an exception hierarchy rooted at `StatusRuntimeException` and throwing those (as opposed to `StatusRuntimeException` should solve the problem.

**Comment by shrids** [comment]
The current version of the controller client does not retry on every `StatusRuntimeException`. It uses the status code to decide if a retry needs to be performed.
https://github.com/pravega/pravega/blob/5e89a55ac03d94e6426909346d89a4e89a113764/client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java#L210-L241

I think this addresses the issue here. cc: @shiveshr @ravisharda WDYT?
