### ISSUE TITLE
Allow read and write of large events

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega#3679]
**Problem description**
Several use cases of Pravega involve storing high resolution images of up to 100 MB. The Pravega event API is limited to 1 MB.

**Problem location**
Pravega client

**Suggestions for an improvement**
Splitting into 1 MB Chunks
In this method, super-events are split into chunks of 1 MB or less. Each chunk is prefixed with the chunk index and the final chunk index (number of chunks minus 1). Chunks from the same super-event should be written within the same transaction to ensure that they are atomic and contiguous in a segment. As such super-events are expected to be >1 MB, the amortized cost of a transaction is expected to be minor.

A reader of a single segment using the Pravega batch API can easily and reliably reassemble the chunks into the original super-event because the chunks are guaranteed to come in order. The segment reader must be stateful to remember previous chunks but it must only remember enough chunks for a single super-event.

The Pravega Spark Connector has been updated to perform this reassembly process transparently to the Spark application. To enable it, the Spark application must set the option "encoding" to "chunked_v1". See ChunkedV1EventIterator.scala for the reassembly code. Sample code that shows writing chunked super-events is video_data_generator.py.

However, a reader group client does not have this guarantee because a reader may interleave events (chunks) from different segments. Changes to the Pravega client and possibly the server are required for this. One possible solution is to make the reader group reader chunk-aware and not let it change segments until a complete super-event has been read.

**Comment by tkaitchuck** [comment]
One approach to this would be to implement this inside of AppendProcessor on the server side, by opening a transaction, appending to it, and committing. This would require a new wire command to transfer the event incrementally. It would also require some refactoring in Append Processor to deal with both types of appends. Finally it would require a new API from the store: the ability to update an attribute atomically with a transaction commit.

**Comment by tkaitchuck** [comment]
We could also help by raising the base event size to 8mb. This is possible if we up the max wire command size to it's present limit 2^24-1 bytes.

**Comment by claudiofahey** [comment]
An increase to 8 MB would be great. It wouldn't solve all problems but it would avoid the need for any complexity in many use cases. Are there any significant drawbacks to changing the hard coded limit from 1 MB to 8 MB, even when events are <= 1 MB?

**Comment by andreipaduroiu** [comment]
The Segment Store does not put any limit to the size of the appends it can process. But bear in mind that all appends end up being written to BookKeeper, which has a hardcoded max write size of (just under) 1MB.

Appends larger than 1MB will therefore be split into 2 or more BK writes which will be pipelined to BK. This will affect the latency of those writes as well as any other writes that go to the same Segment Container around that time.

They will also need to be buffered server-side (in the heap) so you will run into memory limitations.

8MB should not be an issue. 100MB will be.

**Comment by tkaitchuck** [comment]
> Are there any significant drawbacks to changing the hard coded limit from 1 MB to 8 MB, even when events are <= 1 MB?

No. There would be no effect.

**Comment by claudiofahey** [comment]
FYI, here is an example that splits large images into smaller chunks and reassembles them using Flink.
https://github.com/pravega/video-samples

**Comment by RaulGracia** [comment]
Closed via #4370.
