### ISSUE TITLE
Need to update the pravega image with curl version 7.61.1-r2

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega#3683]
Need to update the pravega image with curl version  7.61.1-r2

Please update the below packages:
  - libcurl: 7.61.1-r2
  - curl: 7.61.1-r2

**Comment by ravisharda** [comment]
The most recent stable version of cURL is 7.64.1 ([source](https://curl.haxx.se/)). The minimum upgrade version should be 7.64.0 to resolve all publicly disclosed vulnerabilities, as per [this](https://curl.haxx.se/docs/vulnerabilities.html) documentation.

**Comment by fpj** [comment]
@adrianmo is it ok to upgrade to any of these versions? what's your take?

**Comment by adrianmo** [comment]
`curl` is present on the base image we are using (i.e. [`apache/bookkeeper:4.7.3`](https://github.com/apache/bookkeeper/blob/release-4.7.3/docker/Dockerfile), which in turn is using the `centos:7` base image. What we can do in our Dockerfile is running `yum update curl` to update the package to the latest version available on the official CentOS repositories (but it might be outdated as well). 

Before going forward, I would like to understand what are the vulnerability threats affecting the current curl version. @mejodev1 can you post the vulnerability report that motivated this issue?

**Comment by mejodev1** [comment]
@adrianmo, please let me know if you are looking for any more info.

**Comment by pbelgundi** [comment]
I tried logging into bookie pods and did not find 'curl' installed on any of these.

@mejodev1 could you post the vulnerability report that motivated this issue?
It would help to know if the report only found curl lib in the container or curl actually running there... This has potential to change the threat severity of this issue.

**Comment by mejodev1** [comment]
Yes, Bookkeeper does not have curl or libcurl. This issue is about updating pravega image, not bookkeeper image.

**Comment by pbelgundi** [comment]
Checked Pravega version : 0.5.0-2222.8ba5431 and it does have curl installed in the pravega containers.

**Comment by pbelgundi** [comment]
Current pravega base image is openjdk:8u181-jre-alpine
This has Apline Linux 3.8... which does not support curl versions beyond 7.61.1-r2:
https://pkgs.alpinelinux.org/packages?name=curl&branch=v3.8&arch=x86_64

**Comment by pbelgundi** [comment]
On executing './gradlew buildPravegaImage' on the latest pravega/master branch I see, curl-7.6.1_r2 being installed in the image...
```
(3/25) Installing libcurl (7.61.1-r2)
(4/25) Installing curl (7.61.1-r2)
```

Also tried creating a container using this image and it had curl-7.6.1_r2 libraries...
```
/opt/pravega # apk list | grep curl
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such file or directory
libcurl-7.61.1-r2 x86_64 {curl} (MIT) [installed]
curl-7.61.1-r2 x86_64 {curl} (MIT) [installed]
```

So there is nothing to upgrade to here...

**Comment by pbelgundi** [comment]
As stated above, the current Pravega Image is already on curl 7.61.1-r2, so closing this issue..
