### ISSUE TITLE
Need to update pravega with the latest bookkeeper image

### ISSUE THREAD

**Issue by mejodev1** [pravega/pravega#3696]
Need to update pravega with the latest bookkeeper image.

**Comment by andreipaduroiu** [comment]
@mejodev1 Can you please edit this issue and use our standard issue format. We need to understand why this is needed. For reference, the standard format contains these fields:
- Problem Description
- Problem Location
- Suggestions for Improvement

**Comment by RaulGracia** [comment]
The description provided is not supporting that there is a "P0 bug" that requires to upgrade Bookkeeper to solve it. As @andreipaduroiu suggested, if there is an issue in this regard, please re-open the issue and report it with appropriate description so we can handle it.

**Comment by RaulGracia** [comment]
We have #4425 and #4420 to track this issue on branches 0.6 and 0.7 respectively.
