### ISSUE TITLE
Design for providing scaling hints to readers

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#370]
Today the client library supports scaling the number of segments on demand. However what would be really useful is to help users scale their readers up and down in response to that load. 

There are several ways we could do this. As a straw man:
We could put a `long getEventsPerSecond()` or similar method on a ReaderGroup object to allow the user to query metrics.

**Comment by shrids** [comment]
Closing this issue based on the following points:

- Scaling hints to readers are enabled using `ReaderGroup` api `io.pravega.client.stream.notifications.ReaderGroupNotificationListener#getSegmentNotifier`

- ReaderGroup metrics have also been enabled using `io.pravega.client.stream.ReaderGroup#getMetrics` .
