### ISSUE TITLE
Prevent suppression of stack traces in tests

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3702]
**Problem description**
Sometimes tests have the following pattern:
```
try {
 // some operation
} catch (SomeException e) {
    Assert.fail("should not get an exception");
}
```
This is unnecessarily verbose, but also prevents the stack trace or message of the exception from being logged. If the exception is unexpected this is critical debugging information that we could miss. 

**Problem location**
Numerous files

**Suggestions for an improvement**
Remove the try catch and just throw the exception.

**Comment by fpj** [comment]
@tkaitchuck yes, suppressing the stack trace isn't a good idea, I agree we should make sure to output it when it is the cause of a test failure. we need to decide on guidelines for this, though.

one reason I like the idea of assert failing is that the developer is intentionally saying "I know this code can throw this exception and I know it is wrong in this case.". the assertion makes that reasoning evident in the test code.  letting the exception propagate weakens a bit that assessment, but is not the end of the world.

my main goal at this point is to make sure we follow a concrete set of guidelines, let's see if we can agree on it.

**Comment by tkaitchuck** [comment]
@fpj I'm not sure I agree in general, but even so, that sort of reasoning doesn't apply to the cases changed in #3703. There were a few cases that looked intentional that I left as-is. The ones I changed are just catching blanket Exception or something like IllegalStateException that the test is not implying is a possible outcome.

**Comment by fpj** [comment]
@tkaitchuck 

> The ones I changed are just catching blanket Exception or something like IllegalStateException

It seems to be mostly true, but I'm seeing, for example:

- `IOException`
- `URISyntaxException`
- `ReinitializationRequiredException`

which are not consistent with your statement. Again, I'm ok with changing the way we are doing it as long as we agree on guidelines and try to stick to them.

**Comment by tkaitchuck** [comment]
Yes. It is conceivable that could potentially be caught and handled manually in a way that adds more information or makes it more clear to someone attempting to debug a failing test what is failing and why. However in the case of the PR, I don't think the places where I changed it actually do that.
