### ISSUE TITLE
Sporadic test failure MetricsTest.metricsTimeBasedCacheEvictionTest

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3725]
**Problem description**
We are observing `MetricsTest.metricsTimeBasedCacheEvictionTest` test failing sporadically both on Travis:
```
io.pravega.test.integration.MetricsTest > metricsTimeBasedCacheEvictionTest FAILED
    java.lang.NullPointerException
        at io.pravega.test.integration.MetricsTest.lambda$metricsTimeBasedCacheEvictionTest$1(MetricsTest.java:247)
        at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:48)
        at io.pravega.test.integration.MetricsTest.metricsTimeBasedCacheEvictionTest(MetricsTest.java:246)
```
and Jenkins:
```
java.lang.NullPointerException
	at io.pravega.test.integration.MetricsTest.lambda$metricsTimeBasedCacheEvictionTest$0(MetricsTest.java:203)
	at io.pravega.test.common.AssertExtensions.assertEventuallyEquals(AssertExtensions.java:48)
	at io.pravega.test.integration.MetricsTest.metricsTimeBasedCacheEvictionTest(MetricsTest.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
See the [complete log for Jenkins failure](https://github.com/pravega/pravega/files/3133206/failure_log.txt).

**Problem location**
`MetricsTest.metricsTimeBasedCacheEvictionTest`

**Suggestions for an improvement**
Fix the test.

**Comment by kevinhan88** [comment]
@RaulGracia could you please add at least the commit id of the Travis/Jenkins job for the job failure?

**Comment by RaulGracia** [comment]
@kevinhan88 I attached the full log for the test. I got that log from build number 4 in the `pravega-0.5` Jenkins job. What else do you need?

**Comment by kevinhan88** [comment]
Thanks @RaulGracia

**Comment by kevinhan88** [comment]
The context of the issue:
Changes
Issue 3659: Set hdfs.replaceDataNodesOnFailure = false in K8s system (commit: c0bee07) (detail / githubweb)
Issue 3659: Update the config.properties file to document (commit: b11ac6b) (detail / githubweb)
Issue 3643: Fix reliability issues of standalone mode tests (#3656) (commit: 101e938) (detail / githubweb)
Issue 3649: Invoke grgit plugin only if git repository is present. (commit: 79934a8) (detail / githubweb)
Issue 3673: New controller instance is not updating segment container (commit: c602824) (detail / githubweb)
Issue #3333, #2572: Keep completed segments in position objects. (#3364) (commit: 61b40e9) (detail / githubweb)
Issue 3708: Sporadic failure of HostStoreTest.zkHostStoreTests (#3712) (commit: c7974c3) (detail / githubweb)
Issue 3710: (SegmentStore) Delete Segment if Empty Bug Fix (#3711) (commit: bd6aba5) (detail / githubweb)
Issue 2830: PingTxnStatus now informs if the Transaction is closed (commit: 79f9596) (detail / githubweb)
Issue 3702: Prevent suppression of stack traces in tests (#3703) (commit: f1566a7) (detail / githubweb)
Issue 3638: Ensure the AsyncSegmentInputStreamImpl handles (commit: 5228e2d) (detail / githubweb)

===== console output ===================
11:41:33 Started by an SCM change
11:41:33 [jarvis ping] http://lglop122.lss.emc.com:3424/jarvis/platform-ci/ping?build=https://asd-nautilus-jenkins.isus.emc.com/jenkins/job/pravega-0.5/4/
11:41:33 [EnvInject] - Loading node environment variables.
11:41:33 Building remotely on 10.244.117.208 (slave pravega platform-centos dcos platform docker-multistage) in workspace /var/jenkins_home/workspace/pravega-0.5
11:41:33 [WS-CLEANUP] Deleting project workspace...
11:41:33 [WS-CLEANUP] Deferred wipeout is used...
11:41:33 [WS-CLEANUP] Done
11:41:33 No credentials specified
11:41:33 Cloning the remote Git repository
11:41:33 Cloning repository https://github.com/pravega/pravega.git
11:41:33  > git init /var/jenkins_home/workspace/pravega-0.5 # timeout=10
11:41:33 Fetching upstream changes from https://github.com/pravega/pravega.git
11:41:33  > git --version # timeout=10
11:41:33  > git fetch --tags --progress https://github.com/pravega/pravega.git +refs/heads/*:refs/remotes/origin/*
11:41:39  > git config remote.origin.url https://github.com/pravega/pravega.git # timeout=10
11:41:39  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
11:41:39  > git config remote.origin.url https://github.com/pravega/pravega.git # timeout=10
11:41:39 Fetching upstream changes from https://github.com/pravega/pravega.git
11:41:39  > git fetch --tags --progress https://github.com/pravega/pravega.git +refs/heads/*:refs/remotes/origin/*
11:41:39  > git rev-parse refs/remotes/origin/r0.5^{commit} # timeout=10
11:41:39  > git rev-parse refs/remotes/origin/origin/r0.5^{commit} # timeout=10
11:41:39 Checking out Revision 5228e2dae1ffca973eb9cfdc3e15708e4ac1acb0 (refs/remotes/origin/r0.5)
11:41:39  > git config core.sparsecheckout # timeout=10
11:41:39  > git checkout -f 5228e2dae1ffca973eb9cfdc3e15708e4ac1acb0
11:41:40 Commit message: "Issue 3638: Ensure the AsyncSegmentInputStreamImpl handles ConnectionFailedException during sendAsync. (#3654)"
11:41:40  > git rev-list --no-walk baf23192b1b805b20379c7b40d3527c1e2ca58e1 # timeout=10
11:41:40 [pravega-0.5] $ /bin/sh -xe /tmp/jenkins1134706436419476323.sh
11:41:40 ++ grep pravegaVersion= gradle.properties
11:41:40 ++ sed s/pravegaVersion=//
11:41:40 ++ sed 's/-.*//'
11:41:40 + BASE_VERSION=0.5.0
11:41:40 ++ git rev-list HEAD --count
11:41:40 ++ git rev-parse --short HEAD
11:41:40 + VERSION=0.5.0-2236.5228e2d
11:41:40 + REGISTRY=asdrepo.isus.emc.com:8101
11:41:40 + DEPLOY_URL=http://asdrepo.isus.emc.com:8081/artifactory/nautilus-prerelease-local
11:41:40 + echo 'VERSION: [0.5.0-2236.5228e2d]'
11:41:40 VERSION: [0.5.0-2236.5228e2d]

**Comment by kevinhan88** [comment]
Just to clarify, if this failure just started happening after the many cherry picks into 0.5, then it is not sporadic. (In my understanding, sporadic happens to a relatively stable branch, e.g. master, with some occasionally failures).

**Comment by RaulGracia** [comment]
@kevinhan88 this failure is apparently happening in both `0.5` and `master` (see the labels in the issue). Moreover, I used the word "sporadic" because this test is only failing sometimes, both on Jenkins and Travis (e.g., a race condition?). After re-running the same job in Jenkins and Travis, the build was green. But we are at risk of seeing this issue again.

**Comment by kevinhan88** [comment]
The failure happened in both r0.5 and master, which could be still reasonable if the recent changes caused the issue - just trying to narrow the scope of the problem for the sake of troubleshooting. At lease as far as I remember, we didn't encounter the similar NullPointerException before.
