### ISSUE TITLE
System test failure StreamCut Test

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#3735]
**Problem description**
`io.pravega.test.system.StreamCutsTest` test failed for branch ` issue-3719-cherry-pick-for-r0.5-0.5.0-2236.137147`  with the following error.

```
2019-04-30 22:16:06,178 74382 [main] ERROR i.p.t.s.f.TestFrameworkException - TestFramework Exception. Type: InternalError, Details: Exception while running test method: streamCutsTest
java.lang.IllegalArgumentException: Segment offset in startStreamCut should be <= segment offset in endStreamCut.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at io.pravega.client.stream.ReaderGroupConfig$ReaderGroupConfigBuilder.lambda$verifyStartAndEndStreamCuts$2(ReaderGroupConfig.java:223)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
```

This issue is observed even on the master build.

**Problem location**
ReaderGroup initialization with StreamCuts.

**Suggestions for an improvement**

With PR https://github.com/pravega/pravega/pull/3364 StreamCut can have segments(completed) with an offset as `-1L`. This causes

* ReaderGroupConfig's streamCut validation to fail in the case of startStreamCut and endStreamCut both consisting of the same `Segment`. If the endStreamCut points to the end of the `Segment` with offset `-1L` then the `io.pravega.client.stream.ReaderGroupConfig.ReaderGroupConfigBuilder#verifyStartAndEndStreamCuts` will fail.

* Having -1L in StreamCut can cause issues while serializing it  as `io.pravega.client.stream.impl.StreamCutImpl.StreamCutSerializer` serializes the offset as `out.writeCompactLong()`. (-1L cannot be represented with compact long.

* The bounded Processing logic reader group needs to be tweaked to handle this scenario where segments with -1L are passed.

**Comment by tkaitchuck** [comment]
The -1 indicates it has reached the end of that segment. So we should either:
a) Adjust it to tolerate that.
b) Replace that value with the successors at offset 0.

I would lean towards the former, as it keeps the existing code path for handling it.

**Comment by shrids** [comment]
Thanks @tkaitchuck 
Realized that the system test `io.pravega.test.system.StreamCutsTest` also needs to be refactored to handle the changes introduced in https://github.com/pravega/pravega/pull/3364.
