### ISSUE TITLE
Writers are failing with DecoderException: InvalidMessageException: AppendBlockEnd without AppendBlock.

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3754]
**Problem description**
ref: https://github.com/pravega/pravega/issues/3749#issuecomment-489555531

Writers in smallScale job started failing with following exception for setup append requests to two of the segments
```
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
```

Eventually the said segments are truncated and writers seem to have stopped completely. 

**Problem location**
Pravega Client Writer

**Suggestions for an improvement**
Fix the issue

**Comment by shrids** [comment]
This is similar to issue https://github.com/pravega/pravega/issues/3624

**Comment by shrids** [comment]
This has been fixed as part of https://github.com/pravega/pravega/pull/3820
