### ISSUE TITLE
Remove deprecated Controller RPC getSegmentsImmediatlyFollowing

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#3760]
**Problem description**
We have deprecated `getSegmentsImmediatlyFollowing` in #3758 due to a typo that we have fixed. We should eventually remove it.

**Problem location**
Controller RPC.

**Suggestions for an improvement**
Remove the RPC.

**Comment by TisonKun** [comment]
Hi @fpj I'm curious about how we eventually remove this RPC call :-)
