### ISSUE TITLE
Performance drop in Pravega master  and 0.5 branch

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#3774]
**Problem description**
The Pravega performance is droped in the master of Pravega.

**Problem location**
Following commit id is causing lower performance.

02f1c0036da29e2db34cc319714d99fd08da941a is the first bad commit
commit 02f1c0036da29e2db34cc319714d99fd08da941a
Author: Sandeep <sandeep.shridhar@emc.com>
Date:   Thu Apr 11 02:25:11 2019 +0530

   Issue 217: Enable connection pooling with SegmentStore. (#3562)

   * Implements connection pooling infrastructure and enables
   connection pooling for RawClient and Pravega Readers and
   Pravega Writers.

   Signed-off-by: Sandeep <sandeep.shridhar@emc.com>

**Suggestions for an improvement**
This commit id : 02f1c0036da29e2db34cc319714d99fd08da941a

**Comment by tkaitchuck** [comment]
@kmgowda Looking at that change, it doesn't seem plausible that this PR is the cause. 
Can you define what you mean by a "performance drop". IE: Do you mean write throughput? 
And can you double check the PRs before and after this, it really seems likely that some other PR caused the issue, because this really shouldn't have an impact.

**Comment by andreipaduroiu** [comment]
It would also help if you could provide a standard benchmark with results for multiple builds. That way it will make it easier to define "performance drop".

**Comment by kmgowda** [comment]
I have updated the commit id which is causing performance drop.
This commit id : 02f1c0036da29e2db34cc319714d99fd08da941a 
The issue in pravega client. 
This  pravega 0.5 is affected.

The performance drop is observed with multi producers.

Here are the performance results:

I tested on top of this commit id : 717eeeb81c942abbf8218c1501570712d7519144   (good one)
which is prior to commit id : 02f1c0036da29e2db34cc319714d99fd08da941a  (bad one)
here are performance numbers with 10 producers and 10 segments.
[root@white-master-1 pravega-benchmark]# ./build/distributions/pravega-benchmark/bin/pravega-benchmark -controller tcp://10.240.135.49:9090 -stream topic-t10-1 -segments 10  -producers 10  -size 1000 -time 60

1195364 records Writing,  234707.2 records/sec, 223.83 MB/sec,    82.1 ms avg latency,   330.0 ms max latency
 1222998 records Writing,  244550.7 records/sec, 233.22 MB/sec,   140.8 ms avg latency,   514.0 ms max latency
 1278102 records Writing,  255569.3 records/sec, 243.73 MB/sec,   163.2 ms avg latency,   593.0 ms max latency
 1273444 records Writing,  251470.0 records/sec, 239.82 MB/sec,   187.9 ms avg latency,   760.0 ms max latency
 1284881 records Writing,  256924.8 records/sec, 245.02 MB/sec,   216.2 ms avg latency,   780.0 ms max latency
 1235753 records Writing,  247101.2 records/sec, 235.65 MB/sec,   261.8 ms avg latency,  1088.0 ms max latency
 1288718 records Writing,  257692.1 records/sec, 245.75 MB/sec,   245.7 ms avg latency,  1068.0 ms max latency
 1298052 records Writing,  259558.5 records/sec, 247.53 MB/sec,   234.3 ms avg latency,   969.0 ms max latency
 1303788 records Writing,  260705.5 records/sec, 248.63 MB/sec,   239.9 ms avg latency,   905.0 ms max latency
 1290766 records Writing,  258101.6 records/sec, 246.14 MB/sec,   254.9 ms avg latency,  1008.0 ms max latency
 1304074 records Writing,  260762.6 records/sec, 248.68 MB/sec,   270.9 ms avg latency,   990.0 ms max latency
15052842 records Writing, 253402.050 records/sec, 1000 bytes record size, 241.66 MB/sec, 213.6 ms avg latency, 1088.0 ms max latency, 162 ms 50th, 266 ms 75th, 599 ms 95th, 764 ms 99th, 906 ms 99.9th, 993 ms 99.99th.


With the commit id : 02f1c0036da29e2db34cc319714d99fd08da941a  ,
below are the performance numbers with 10 producers and 10 segments.

[root@white-master-1 pravega-benchmark]# ./build/distributions/pravega-benchmark/bin/pravega-benchmark -controller tcp://10.240.135.49:9090 -stream topic-t10-2 -segments 10  -producers 10  -size 1000 -time 60

  343889 records Writing,   68764.0 records/sec,  65.58 MB/sec,    38.8 ms avg latency,   210.0 ms max latency
  342802 records Writing,   68546.7 records/sec,  65.37 MB/sec,    49.1 ms avg latency,   280.0 ms max latency
  343458 records Writing,   68677.9 records/sec,  65.50 MB/sec,    52.1 ms avg latency,   253.0 ms max latency
  351400 records Writing,   70265.9 records/sec,  67.01 MB/sec,    49.0 ms avg latency,   239.0 ms max latency
  353430 records Writing,   70671.9 records/sec,  67.40 MB/sec,    48.1 ms avg latency,   242.0 ms max latency
  348633 records Writing,   69712.7 records/sec,  66.48 MB/sec,    50.3 ms avg latency,   221.0 ms max latency
  340751 records Writing,   68136.6 records/sec,  64.98 MB/sec,    53.8 ms avg latency,   263.0 ms max latency
  357152 records Writing,   71416.1 records/sec,  68.11 MB/sec,    52.3 ms avg latency,   264.0 ms max latency
  355039 records Writing,   70993.6 records/sec,  67.70 MB/sec,    49.9 ms avg latency,   248.0 ms max latency
  346812 records Writing,   69348.5 records/sec,  66.14 MB/sec,    53.6 ms avg latency,   246.0 ms max latency
  357325 records Writing,   71450.7 records/sec,  68.14 MB/sec,    52.8 ms avg latency,   297.0 ms max latency
4132153 records Writing, 69757.462 records/sec, 1000 bytes record size, 66.53 MB/sec, 50.1 ms avg latency, 297.0 ms max latency, 31 ms 50th, 76 ms 75th, 140 ms 95th, 179 ms 99th, 223 ms 99.9th, 250 ms 99.99th.

**Comment by kmgowda** [comment]
so the performance drop is from 230 MB/s to 66 MB/s.

**Comment by shrids** [comment]
@kmgowda The `DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE` configured in the client 5. This implies only 5 connections are utilized for all the segment readers, segment writers, state synchronizers, SegmentMetadataClients spawned by the client. This also implies a connection drop would also impact all the users of the particular connection. Could we also have a run with a higher number of connections per segment store? This would help us to root cause the performance drop further.

**Comment by tkaitchuck** [comment]
@kmgowda Yes. It would be good to test setting that to a large number so we can make sure it is the switching causing the problem not some accidental issue introduced in the same PR. If it works with a large number, we should try 10. My suspicion is that anything above the number of segments being written to per writer should have negligible impact.

**Comment by kmgowda** [comment]
@shrids and @tkaitchuck 
I will do something like this:
1. take the performance numbers without this PR
2. take the performance numbers with this PR
3. now, starting changing the DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE value so that we get the point with idle value where the performance numbers are comparable with step 1

**Comment by kmgowda** [comment]
| event   size : 1000 Bytes | Throughput in MB/s | DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE=5  | DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE=10   |   DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE=20  |   DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE=100  |
|---------------------------|--------------------|--------------------------------------------------|----|-----|-----|
| Writers                   | without fix        | -                                                | - |-  |- |
| 10                        | 240                | 50                                               | 80 | 130 | 240 |
| 20                        | 260                | 40                                               | 40 | 100 | 170 |
| 30                        | 260                | 30                                               | 30 | 90  | 170 |
| 40                        | 250                | 25                                               | 30 | 50  | 140 |
| 50                        | 240                | 25                                               | 30 | 50  | 140 |

**Comment by kmgowda** [comment]
@shrids @tkaitchuck 
By increasing the value DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE , there is improvement in the performance; its still lower than the previous results of without fix.
I could see that by setting DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE to 100 , there is optimal performance of 240 MB/s for 10 writers , but for 20, 30, 40 and 50 writers performance is still low (<50%)

**Comment by tkaitchuck** [comment]
This may be pooling interacting poorly with the AppendBatchSizeTracker. 
It is living down at the netty level and is unaware of switches from one segment to another. So it may be providing pathologically bad values.

**Comment by kmgowda** [comment]
@tkaitchuck 
  I could see that DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE is not proportional to number of segments of the steam. if the number of segments of the stream 10 and DEFAULT_MAX_CONNECTIONS_PER_SEGMENT_STORE is also set to 10; then also with 10 producers I could see the connection reuse logs.

I looked into this AppendBatchSizeTrackerImpl implementation, is this method : getAppendBlockSize causing any issue? please advise.

**Comment by kmgowda** [comment]
Hi @tkaitchuck 
   I set the value of  to 100; just see how the number of connection grows with respect to number of writers and segments.
below table indicates the segments v/s writes and throughput we get

| Number of segments | Number of Writers | Number of connections | Throughput in MB/s |
|--------------------|-------------------|-----------------------|--------------------|
| 1                  | 1                 | 1                     | 33                 |
| 1                  | 2                 | 2                     | 58                 |
| 1                  | 3                 | 3                     | 70                 |
| 1                  | 6                 | 6                     | 113                |
| 1                  | 9                 | 9                     | 146                |
| 2                  | 1                 | 2                     | 53                 |
| 2                  | 2                 | 4                     | 99                 |
| 2                  | 3                 | 6                     | 121                |
| 2                  | 6                 | 12                    | 167                |
| 2                  | 9                 | 18                    | 202                |
| 3                  | 1                 | 3                     | 56                 |
| 3                  | 2                 | 6                     | 101                |
| 3                  | 3                 | 9                     | 139                |
| 3                  | 6                 | 18                    | 210                |
| 3                  | 9                 | 27                    | 226                |
| 6                  | 1                 | 6                     | 50                 |
| 6                  | 2                 | 12                    | 98                 |
| 6                  | 3                 | 18                    | 130                |
| 6                  | 6                 | 36                    | 202                |
| 6                  | 9                 | 54                    | 210                |
| 9                  | 1                 | 9                     | 49                 |
| 9                  | 2                 | 18                    | 93                 |
| 9                  | 3                 | 27                    | 129                |
| 9                  | 6                 | 54                    | 194                |
| 9                  | 9                 | 81                    | 234                |



we get optimal performance if the producers <= number of connections;

if the performance is lower then as per your hints
I could see the following in the code

1. There are very frequent BlockTimeout  in encode method of commandEncoder.java
     and breakFromAppend is frequent.
2. whenever the wire command gets called in between data, then also breakFromAppend is invoked.

The frequent breakFromAppend  may cause performance drop right? please do comment on this.

so, proposal here it is 
- is it possible to have dedicated data path ( means a separate connection for stream data)?
  and separate path (connection ) for wire commands and any other stuff.

please advise...

**Comment by kmgowda** [comment]
Ok, here is the issue :

   protected void encode(ChannelHandlerContext ctx, Object msg, ByteBuf out) throws Exception {
        log.trace("Encoding message to send over the wire {}", msg);
        if (msg instanceof Append) {
            Append append = (Append) msg;
            Session session = setupSegments.get(new SimpleImmutableEntry<>(append.segment, append.getWriterId()));
            validateAppend(append, session);


            if (!append.segment.equals(segmentBeingAppendedTo) || !append.getWriterId().equals(writerIdPerformingAppends)) {
                breakFromAppend(out);
            }

breakFromAppend is very frequent because segment may differ and writerId differs in the multiwriter environment.

**Comment by kmgowda** [comment]
@tkaitchuck , @andreipaduroiu  and @shrids 
Need your inputs here..
since the failure is in 

   if (!append.segment.equals(segmentBeingAppendedTo) || !append.getWriterId().equals(writerIdPerformingAppends)) {
            breakFromAppend(out);
        }

in case of multi writers and multi segment;  the breakFromAppend is called every-time and hence the performance drops.

As a solution, 
The code  changes requires in both client and segment store side
1. the client will send multiple appends containing different writer id and segment ids
2. segment server should be able to parse them and queue them for particular segments and writer. Currently segment server does not do that.
So,  it means  that it requires a protocol change now.

please let me know your thoughts about the above proposed solution.

**Comment by shrids** [comment]
@kmgowda I do not understand the need for a protocol / WireCommand change. Could you elaborate on this ?

**Comment by kmgowda** [comment]
@shrids , @tkaitchuck  and @andreipaduroiu 
Yes, I wont say change is required for wire command ; but we need to change the following to the netty channel is multiplexed for multiple writers and segments.
the performance drop is due to appendblock is immediately followed by append end , if the writer and segment changes. this is breaking the accumulation of 32k data at the server side and ends with ends up with smaller size data.
as I mentioned earlier , we need to remove the below code:

      if (!append.segment.equals(segmentBeingAppendedTo) || 
                !append.getWriterId().equals(writerIdPerformingAppends)) {
        breakFromAppend(out);
               }

but removing this will break the communication between client and append processor (server side).
so, we need to following

At client side
1. the AppendBatchSizeTracker should per session basis ; this should be part of Session of CommandEncoder
2. for every message it should append block ; so there will multiple append blocks per writer id.
3. upon sending wire command, all the session should be committed.

At server side (Append processor side)
1. for every append block per writer id, it should accommodated
2. upon receiving the append end, it should be processed further.
But, server side changes requires additional buffering which may have impact on the performance.

**Comment by tkaitchuck** [comment]
> for every message it should append block ; so there will multiple append blocks per writer id.

This defeats the whole purpose of append blocks, if we have to parse a separate one for each event. At that point we'd be better off removing the concept all together and removing setupAppend and just sending individual request-replies. In general I think this would make things much worse from both a latency and throughput perspective. (Vs a single flow connection)

However:
> the AppendBatchSizeTracker should per session basis ; this should be part of Session of CommandEncoder

Yes. This is what I was alluding to earlier when I said: 
> This may be pooling interacting poorly with the AppendBatchSizeTracker.
It is living down at the netty level and is unaware of switches from one segment to another. So it may be providing pathologically bad values.

Right now the AppendBatchSizeTracker is per connection not per session. If you look at `AppendBatchSizeTrackerImpl.recordAppend()` you can see this makes no sense. It's assuming the event numbers are sequential and using this to track the number of events outstanding. However if there are multiple sessions these are going to differ a lot and it could give crazy high values. 

To correct this we should make two changes:
1. Make the BatchSizeTracker per flow.
2. Add a method to the size tracker to indicate that it the appendWasBroken out of. (The implementation of this can be to add a sample for `appendsOutstanding` at zero and have it ignore those acks)
This will have the effect that if the connection switches from segment X to Y every 10kb there is no point in having a batch size larger than this, so it will adjust downward the size.

**Comment by kmgowda** [comment]
Hi @tkaitchuck 

Couple of points to discuss here.

 on a single netty connection/channel , the append is breaking  if "segment" changes or even "Writer id " changes.    this means in the code either segmentBeingAppendedTo or writerIdPerformingAppends every invocation of encode method of CommandEncoder 
so ,  do we really need to maintain the writer ids at append processor also?
if the segment writes are happening and ignoring the writer ids  will improve the little bit  of performance.   

as per your suggestions.

1. Make the BatchSizeTracker per flow.
    yes this is feasible , but how does it improve? append break happens even if the writer id changes.

2. Add a method to the size tracker to indicate that it the appendWasBroken out of. (The implementation of this can be to add a sample for appendsOutstanding at zero and have it ignore those acks)
This will have the effect that if the connection switches from segment X to Y every 10kb there is no point in having a batch size larger than this, so it will adjust downward the size.

I dint get this part ;  do mean it say,  we need addsample(0) for outstanding appends, but again here the bottleneck is  either segmentBeingAppendedTo or writerIdPerformingAppends every invocation of encode method of CommandEncoder.


so, My proposal is

Solution 1:
-------------
1. client will keep sending the append blocks , server (append processor) buffers it till it receives the append block end.
2. in each append block, the segment id and writer id may differ.
3. but this solution, as you already indicated , may have latency and throughput issues; but,
4. this ensure the netty channel multiplexing among multiple segments and writers.
5. in this case, append batch size is different, for each session client ensure that append block End is sent to server/append processor if data is more than 32K or 100ms timeout on every write.


Another solution as you mentioned that "(It's worth noting that we can always fall back on this by simply disabling pooling in the append path if we want to) "

Solution 2:
--------------

1. we can have two connection pools
2. one  pool is for writer (Appends) another one for reader ; we can set two different values  something like  DEFAULT_MAX_WRITE_CONNECTIONS_PER_SEGMENT_STORE   and DEFAULT_MAX_READ_CONNECTIONS_PER_SEGMENT_STORE 
3.  this case is helpful only if both producers and consumers are present in the client.
4. However , we can keep the writer connections more to improve the performance.

please provide your feedback on these two proposals and let me know your choice for the implementation.

**Comment by tkaitchuck** [comment]
These approaches are not mutually exclusive. We should make appends work as well as possible in the case that they are on a shared connection, because there will always be some situations where they are. This is going to involve reworking how the AppendSizeTracker is supplied to the CommandEncoder. This doesn't mean we shouldn't try to avoid having appends overlap if possible. I already have an issue on this: https://github.com/pravega/pravega/issues/3618
