### ISSUE TITLE
Huge latency noticed during read and write operation with 10k segments

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3788]
**Problem description**
Observed huge latency as close as 26000 ms to 38000 ms while performing read and write operations to a single stream with 10k segments. 
Even though the client interaction with Pravega was local that is from one of the internal cluster pod (no external connectivity) but still noticed such latency while passing IO workload of 10 readers, 10 writers, 100 bytes data, 100 events/sec, 1 stream, 10k segments, runtime 300secs.
```
37 records Writing,      11.9 records/sec,     0.001 MB/sec, 84.1351 ms avg latency.
2 records Reading,       0.0 records/sec,     0.000 MB/sec, 26166.5000 ms avg latency.
3 records Writing,       0.1 records/sec,     0.000 MB/sec, 6828.0000 ms avg latency.
1 records Writing,       0.0 records/sec,     0.000 MB/sec, 38426.0000 ms avg latency.
```
The client Stream run with the above mentioned workload could not get completed even after running for 900 secs whereas it should close the stream and stop the execution after 300secs and kept running endlessly.

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by shrids** [comment]
Observations from the logs.
a. A stream with 10K segments are created  (`Scope/numSegtest21`) with a fixed segment count policy.
b. 10 Pravega writers are created against this stream.  This implies  10 * 10K = 100K segment writers are created.
c. 10 Pravega readers are created against this stream. This implies 100K segment readers are created.
d. The default connection pool size is used. i.e. all the writers and readers use at max 5 connections/Segment store.
e. Observing that the connection is being dropped causing the writers to retry. Not able to figure the reason for the connection failure since the SegmentStore logs are missing from the snapshot.

@SomeshJoshi19  thanks agreeing the to run it with the latest version of Pravega and also to use the latest log collection script.

**Comment by SomeshJoshi19** [comment]
@shrids As discussed, on recreating the same scenario using latest pravega version : `0.5.0-2260.b477eec`  by passing IO workload of 1 stream having 10 writers, 10 readers, at 100 events/sec rate, 100 bytes data size and runtime as 600 secs over 10k segments, the observations are same as reported previously. 

Even though the client interaction with Pravega was local that is from one of the internal cluster pod (no external connectivity) but still noticed such latency: -
```
       0 records Reading,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
       0 records Writing,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
    1177 records Reading,     235.2 records/sec,   0.02 MB/sec,     4.1 ms avg latency,  4224.0 ms max latency
   11637 records Writing,    2325.1 records/sec,   0.22 MB/sec,  1925.0 ms avg latency,  4219.0 ms max latency
       1 records Reading,       0.2 records/sec,   0.00 MB/sec, 19748.0 ms avg latency, 19748.0 ms max latency
       6 records Writing,       1.0 records/sec,   0.00 MB/sec,  1370.0 ms avg latency,  1744.0 ms max latency
       0 records Reading,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
      32 records Writing,       5.7 records/sec,   0.00 MB/sec,   750.2 ms avg latency,  3519.0 ms max latency
       3 records Reading,       0.2 records/sec,   0.00 MB/sec,  4025.3 ms avg latency,  7169.0 ms max latency
```
Even for this trial the client Stream with the above mentioned workload could not get completed even after running for 1 hour whereas it should close the stream and stop the execution after 900 secs and kept running endlessly.

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2260.b477eec
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

@shrids sharing the latest run logs on internal channel collected using latest log collection scripts as discussed before.

**Comment by shrids** [comment]
Thanks @SomeshJoshi19 for sharing the logs of the test which creates a Stream with 10K segments and then creates 100K Segment writers and 100K Segment readers on a single process.

Observing the following from the logs.

a. The stream creation with 10K segments is successfull [1]. 
b. Post this point the only errors from the logs observed are gRPC calls failures, which are retried [2] and then we observe `OutOfMemoryError` errors while invoing the calls to the controller [3] and to segment store.
Basically from this point onwards the stress test fails with OOM exceptions.

c. From the controller logs observing that one of the controllers is not in a healthy state as it looses connection to zookeeper [3]

Couple of questions:
 - is there a Xmx specified for the stress test tool? Also, we need to enable timestamps in the logs generated by the too.
 - we need to get a heap dump of the bench mark tool to understand why it is crashing with OOM.





[1]
```
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/numSegtest1 with configuration: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=10000), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-3606474276933840846] Tagging client request (createStream-Scope-numSegtest1).
[grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-3606474276933840846] Stream created successfully: numSegtest1
```

[2] we see that grpc calls to fetch current segments fail due to unavailability.
```
 [grpc-default-executor-12] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
228073 io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
228074 Received Goaway
228075         at io.grpc.Status.asRuntimeException(Status.java:530)
```

[3]
```
2019-05-28 10:19:46,179 4757432 [controllerpool-10] ERROR i.p.c.cluster.zkImpl.ClusterZKImpl - Connection lost with Zookeeper
2019-05-28 10:19:46,179 4757432 [controllerpool-10] INFO  i.p.c.f.ControllerClusterListener - Received error event when monitoring the controller host cluster, ignoring...
2019-05-28 10:19:46,280 4757533 [ControllerServiceMain-SendThread(pravega-example-zk-1.pravega-example-zk-headless.default.svc.cluster.local:2181)] ERROR o.a.c.f.imps.CuratorFrameworkImpl - Background operation retry gave up
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:131)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:844)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:629)
```

Logs: 
[part2.zip](https://github.com/pravega/pravega/files/3240789/part2.zip)

**Comment by shrids** [comment]
@SomeshJoshi19 the failure here is that 100K segment writers and 100K segment readers is causing the test program to face an `java.lang.OutOfMemoryError` hence read and writes never progressed.

**Comment by sumit-bm** [comment]
As per triaging, a couple of points had been discussed.

1. The more iterative approach in scaling needs to be tried to get an identification of tools issue vs Pravega specific issues. The suggestion was to experiment with more granularity like does 10 streams with 1000 segment each could fulfill latency guidelines? And if so, could 100 streams with 1000 segment fulfill that even if 10 streams to 100 streams could be broken in intervals so that overall segments latency baselines could be identified. 

2. Does tools require more enhancement, like if OOM error is coming from the tool in handling so many segments could more client instance lessen down the tool's loading?

Including Pravega 0.6.0 version tagging in the issue and this might not be a blocker for 0.5.0 release, s discussed in the meeting,

**Comment by SomeshJoshi19** [comment]
@shrids 
On running single stream with 10k segments having workload as 100 events/sec, 100 bytes data size, run time 600 secs and 1 worker ( 1 reader and 1 writer ), following are the observations: -

1) reading operation failed giving `java.lang.OutOfMemoryError: Java heap space`. Heap dump created during the error - 
[java_pid477.zip](https://github.com/pravega/pravega/files/3324733/java_pid477.zip)

```
[grpc-default-executor-0] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=172.24.1.10, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@3f053cc3, connected=java.util.concurrent.CompletableFuture@688db7fa[Completed normally])
[grpc-default-executor-0] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 1470 for endpoint 172.24.1.10. The current Channel is [id: 0x536003e1, L:/172.24.1.18:54934 - R:172.24.1.10/172.24.1.10:12345].
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=172.24.1.15, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@63221112, connected=java.util.concurrent.CompletableFuture@717110de[Completed normally])
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 1471 for endpoint 172.24.1.15. The current Channel is [id: 0xae42e789, L:/172.24.1.18:39656 - R:172.24.1.15/172.24.1.15:12345].
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=172.24.1.16, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@3df19fd6, connected=java.util.concurrent.CompletableFuture@7e6c1255[Completed normally])
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 1472 for endpoint 172.24.1.16. The current Channel is [id: 0x96653bb9, L:/172.24.1.18:40490 - R:172.24.1.16/172.24.1.16:12345].
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid477.hprof ...
Heap dump file created [1577687187 bytes in 1.624 secs]
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.ConnectionPoolImpl - Reusing connection: Connection(uri=PravegaNodeUri(endpoint=172.24.1.15, port=12345), flowHandler=io.pravega.client.netty.impl.FlowHandler@7bcc5cc4, connected=java.util.concurrent.CompletableFuture@63e4466c[Completed normally])
[grpc-default-executor-1] INFO io.pravega.client.netty.impl.FlowHandler - Creating Flow 1473 for endpoint 172.24.1.15. The current Channel is [id: 0xdcc033c9, L:/172.24.1.18:39658 - R:172.24.1.15/172.24.1.15:12345].
[main] INFO io.pravega.client.state.impl.StateSynchronizerImpl - Closing stateSynchronizer StateSynchronizerImpl(currentState=null, segment=Scope/_RGscaleTest1/0.#epoch.0)
[main] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 6 for endpoint 172.24.1.10
[main] INFO io.pravega.client.segment.impl.ConditionalOutputStreamImpl - Closing segment metadata connection for Scope/_RGscaleTest1/0.#epoch.0
[main] INFO io.pravega.client.segment.impl.SegmentMetadataClientImpl - Closing segment metadata connection for Scope/_RGscaleTest1/0.#epoch.0
[main] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Closing reader for Scope/_RGscaleTest1/0.#epoch.0
[main] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Closing connection to segment: Scope/_RGscaleTest1/0.#epoch.0
[main] INFO io.pravega.client.netty.impl.FlowHandler - Closing Flow 5 for endpoint 172.24.1.10
[main] INFO io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl - Connection failed due to a io.pravega.client.stream.impl.ConnectionClosedException. Read requests will be retransmitted.
       0 records Reading,       0.0 records/sec,   0.00 MB/sec,     NaN ms avg latency,     0.0 ms max latency
0 records Reading, 0.000 records/sec, 100 bytes record size, 0.00 MB/sec, NaN ms avg latency, 0.0 ms max latency, 0 ms 50th, 0 ms 75th, 0 ms 95th, 0 ms 99th, 0 ms 99.9th, 0 ms 99.99th.
```

 2) Writing operation passed successfully matching expected results: -
```
     500 records Writing,      99.8 records/sec,   0.01 MB/sec,    10.6 ms avg latency,    33.0 ms max latency
     501 records Writing,      99.8 records/sec,   0.01 MB/sec,    12.9 ms avg latency,    91.0 ms max latency
     502 records Writing,     100.3 records/sec,   0.01 MB/sec,    12.0 ms avg latency,    46.0 ms max latency
     500 records Writing,     100.0 records/sec,   0.01 MB/sec,    12.9 ms avg latency,    48.0 ms max latency
59316 records Writing, 99.999 records/sec, 100 bytes record size, 0.01 MB/sec, 13.7 ms avg latency, 5662.0 ms max latency, 5 ms 50th, 20 ms 75th, 31 ms 95th, 92 ms 99th, 194 ms 99.9th, 209 ms 99.99th.
```
  3) Client pod eviction `did not occurred` due to lack of resources. The resource allocation for the pod is: -
```
      Started:      Fri, 21 Jun 2019 13:00:20 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  6Gi
    Requests:
      cpu:        2
      memory:     4Gi
```
   4) The heap dump analysis suspects instances from `io.pravega.client.stream.impl.EventStreamReaderImpl` class for memory leakage problem.

```

Class Name                                                                  | Objects | Shallow Heap |    Retained Heap
------------------------------------------------------------------------------------------------------------------------
io.pravega.common.util.Retry$RetryWithBackoff                               |   1,473 |       58,920 |        >= 58,920
io.pravega.client.netty.impl.ClientConnectionImpl                           |   1,468 |       46,976 |        >= 71,536
io.pravega.client.segment.impl.SegmentInputStreamImpl                       |   1,465 |       82,040 | >= 1,537,002,088
io.pravega.common.util.CircularBuffer                                       |   1,465 |       35,160 | >= 1,535,314,432
io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl                  |   1,465 |       93,760 |       >= 789,688
io.pravega.client.segment.impl.AsyncSegmentInputStreamImpl$ResponseProcessor|   1,465 |       23,440 |        >= 23,744
io.pravega.client.segment.impl.EventSegmentReaderImpl                       |   1,464 |       35,136 | >= 1,537,164,976
io.pravega.shared.protocol.netty.WireCommands$SegmentRead                   |   1,177 |       56,496 |     >= 1,553,344
------------------------------------------------------------------------------------------------------------------------
```

**Comment by SomeshJoshi19** [comment]
Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2269.6f8a820
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
``` 
Sharing the logs for the retest on internal channel due to size limit

**Comment by shrids** [comment]
This too is a resource provisioning issue similar to issue https://github.com/pravega/pravega/issues/3957.
10_000 segments readers would cause to attempt to allocate 10GB of read buffers (10_000 * 1MB) which will cause an OOM of the reader processor which is running on a pod with 4GB memory allotted.
