### ISSUE TITLE
SegmentStore OOM Error while doing segment scaling and descaling through Pravega-Benchmark in PKS 

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3803]
**SegmentStore OOM Error while doing segment scaling and descaling testing through Pravega-Benchmark in PKS** 
In PKS environment while running `smallTx` longveity, started a stream named `stream-test` using Pravega-benchmark tool with 10 segments and scaled up to 100 segments and again scaled up to 1000 segments and finally descaled it to 200 segments. In between the above process observed `OOM` error on `segmentstore-0` pod and pod got restarted.

**pravega-pravega-segmentstore-0 logs**
```
2019-05-19 07:44:19,534 779967125 [epollEventLoopGroup-11-7] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: ba123452-cc17-40e6-be6e-636d0871a2c6 on segment: Scope/test12/1398.#epoch.0
2019-05-19 07:44:19,534 779967125 [epollEventLoopGroup-11-7] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: c806b3cc-9e63-4498-9b6e-6c9fd2fb9d9c on segment: Scope/test12/1410.#epoch.0
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid1.hprof ...
Heap dump file created [2646161372 bytes in 16.554 secs]
Aborting due to java.lang.OutOfMemoryError: Java heap space
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (debug.cpp:308), pid=1, tid=0x00007fde61e5aae0
#  fatal error: OutOfMemory encountered: Java heap space
#
# JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.9.0
# Distribution: Custom build (Tue Oct 23 11:27:22 UTC 2018)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/pravega/hs_err_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
```

**Pravega details:**
```
Pravega version : 0.5.0-2236.5228e2d
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by fpj** [comment]
Without the logs, it will be difficult to tell what has happened.

**Comment by sumit-bm** [comment]
@fpj @andreipaduroiu posted the log in internal channel as it was too big to post here.

**Comment by andreipaduroiu** [comment]
For OOM issues, we need a core dump; logs aren't that useful.

Also, by looking at the logs you shared with us, it seems that you are running a rather old build which doesn't contain the recently cherry-picked commits into 0.5. For example, #3765, #3790 are not in.

Please re-run with the latest commits and with core dump on so that we may collect the relevant data needed to debug this.

**Comment by sumit-bm** [comment]
@andreipaduroiu we have collected heap-dump logs for this case and shared in internal channel due to size restriction, please take a look. It contains following
```
-rw-r--r-- 1 root root     136895 May 19 07:44 hs_err_pid1.log
-rw------- 1 root root 2646161372 May 19 07:44 java_pid1.hprof
```
