### ISSUE TITLE
Authentication is bypassed when credentials are missing

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3813]
**Problem description**

When auth is enabled in Pravega, clients applications are expected to specify credentials (via either ClientConfig or system properties or environment variables). If the client fails to specify the credentials, clients are disallowed access as a result of authorization failure. Missing credentials should cause authentication failure even before authorization kicks in. 

**Problem location**
https://github.com/pravega/pravega/blob/9a734d273a51fed757db327a8a67c8b373cc4da3/controller/src/main/java/io/pravega/controller/server/rpc/auth/PravegaInterceptor.java#L53

(The new problem location is: 
https://github.com/pravega/pravega/blob/5c38d07f24f46f988c09a4345dd5d06b8bcfa770/controller/src/main/java/io/pravega/controller/server/rpc/auth/AuthInterceptor.java#L67
) 

**Suggestions for an improvement**

**Comment by EronWright** [comment]
It is typical of authentication logic to authenticate when possible while not presupposing that the anonymous user should be blocked.   The authorization logic should make the determination as to whether an anonymous request is valid.    This would be important for an API that offered some info to anonymous callers, e.g. a `GetVersion` calls or to obtain an API schema document.
