### ISSUE TITLE
A page in Pravega Website about reporting security vulnerabilities 

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3825]
**Problem description**
We need a page in Pravega Website that explains how to report security vulnerabilities. (security@pravega.io)

**Problem location**
Pravega Website

**Suggestions for an improvement**

**Comment by derekm** [comment]
This is required by bestpractices.coreinfrastructure.org, which is a CNCF requirement.

**Comment by derekm** [comment]
* The project MUST publish the process for reporting vulnerabilities on the project site. (URL required)
> E.g., a clearly designated mailing address on https://PROJECTSITE/security, often in the form security@example.org. This MAY be the same as its bug reporting process. Vulnerability reports MAY always be public, but many projects have a private vulnerability reporting mechanism.
* If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. (URL required)
> Examples include a private defect report submitted on the web using HTTPS (TLS) or an email encrypted using OpenPGP. If vulnerability reports are always public (so there are never private vulnerability reports), choose "not applicable" (N/A).
* The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days.
> If there have been no vulnerabilities reported in the last 6 months, choose "not applicable" (N/A).
