### ISSUE TITLE
Segment Store is flooded with KeepAlive messages

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3878]
**Problem description**
We have realized that a single Segment Store instance may receive a really high number of `KeepAlive` messages. For instance, in a system test build, we have analyzed a Segment Store instance logs and counting the for number of `Received KeepAlive` message occurrences within a second each 5 minute interval:

![keepalive_requests](https://user-images.githubusercontent.com/717112/58897798-7934e880-86f9-11e9-9d13-69a346ce04a3.png)
 
As can be observed, most of the time we observe +200 `KeepAlive` messages per second, reaching up to `480` at the end of the test. Given that the `KeepAlive` message is assumed to be sent by the client every `10` seconds, either i) there is some problem in the client/controller that justifies this amount of `KeepAlive` message, or ii) we are using `KeepAlive` messages in the IO communication between clients and the Segment Store (e.g., [flush method](https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java#L498)). In either case, it may be worth to revisit the use of this kind of messages. 

**Problem location**
Client/Controller

**Suggestions for an improvement**
Revisit if the high rate of `KeepAlive` messages against the Segment Store is legitimate and expected.

**Comment by shrids** [comment]
My current findings...
```
- KeepAlive flush is sent on the following conditions
a. 20 seconds post the connection is established. (only if no msg is sent on the connection recently)
b. After (a), once every 10 seconds (only if no msg is sent on the connection recently)
c. During a flush, while the Segment writer is waiting for the inflight events to acked by the SSS.
```
Point a) implies that for every disconnect there is a corresponding reconnect which would lead to a KeepAlive being sent.

From the controller logs observe that the connection gets terminated for 400 times a minute.
```// no of times the connection gets terminated every minute
  400 controller_2019-06-04.185.log:2019-06-04 03:44
    1 controller_2019-06-04.186.log:2019-06-04 03:45
  400 controller_2019-06-04.198.log:2019-06-04 03:46
  400 controller_2019-06-04.203.log:2019-06-04 03:47
  400 controller_2019-06-04.210.log:2019-06-04 03:47
```
This has a corresponding effect on the the number of `Hello` messages sent as by trying to connect.
```
// number of times a Hello is recieved by the SSS every minute
  482 segmentstore_2019-06-04.199.log:2019-06-04 03:44
    1 segmentstore_2019-06-04.202.log:2019-06-04 03:45
  400 segmentstore_2019-06-04.202.log:2019-06-04 03:46
    2 segmentstore_2019-06-04.205.log:2019-06-04 03:46
  398 segmentstore_2019-06-04.206.log:2019-06-04 03:46
  400 segmentstore_2019-06-04.208.log:2019-06-04 03:47
```

But these disconnects do not answer the number of `KeepAlive` msgs being sent.
```
// Number of times a KeepAlive is recieved by SSS every minute
     96 segmentstore_2019-06-04.199.log:2019-06-04 03:44
      3 segmentstore_2019-06-04.200.log:2019-06-04 03:44
   2056 segmentstore_2019-06-04.202.log:2019-06-04 03:45
      7 segmentstore_2019-06-04.202.log:2019-06-04 03:46
    404 segmentstore_2019-06-04.203.log:2019-06-04 03:46
    399 segmentstore_2019-06-04.204.log:2019-06-04 03:46
   2163 segmentstore_2019-06-04.205.log:2019-06-04 03:46
    477 segmentstore_2019-06-04.206.log:2019-06-04 03:46
      2 segmentstore_2019-06-04.206.log:2019-06-04 03:47
    325 segmentstore_2019-06-04.207.log:2019-06-04 03:47
   1693 segmentstore_2019-06-04.208.log:2019-06-04 03:47
    813 segmentstore_2019-06-04.209.log:2019-06-04 03:47
   1203 segmentstore_2019-06-04.210.log:2019-06-04 03:47
   1192 segmentstore_2019-06-04.211.log:2019-06-04 03:47
    717 segmentstore_2019-06-04.212.log:2019-06-04 03:47
    491 segmentstore_2019-06-04.213.log:2019-06-04 03:47
```
This implies flush() is the source for these KeepAlive, which is sent only if there are events inflight.

**Comment by kmgowda** [comment]
my observation is as follows:

since the single connection is shared among multiple writer, upon flush , every writer sends the keealive ; lets say if 10 writers sharing a single connection , then each writer sends the keepalive during flush then its 10 keep alives to the channel.  

due to connection pooling, more keep alives per channel.

solution:
     Avoid sending keepalive duing flush. 
     any flush waits for all the inflight events to get acked.

**Comment by shrids** [comment]
Had a discussion with @tkaitchuck on this, the  reason for sending a KeepAlive is to ensure the flush happens sooner.
> The purpose of sending KeepAlive on flush is not specifically to send a keep alive, but to send any message that will force a flush. That is done to lower latency. KeepAlive was just chosen as it clearly has no meaning or meaningful overhead.

**Comment by kmgowda** [comment]
Hi @tkaitchuck  and @shrids 
    we need to have another message not a Wire command  just flush the data to channel but it should not send any keepalive.  
shall I send the PR for this?

**Comment by andreipaduroiu** [comment]
FYI I removed the segment-store side logging of KeepAlives with PR #3949. We recorded about 2 million of them during a system test run, which was unnecessarily polluting our logs.

**Comment by kmgowda** [comment]
@andreipaduroiu 
   Thanks.. I am trying to avoid the keepAlive but ensure the pending data is written with lower latency. 
please review the PR.

**Comment by shrids** [comment]
Current updates:

This issue is observed where connection pooling is not used by the `SegmentHelper` to read and write meta data into the Segment store. 
The reason for this is that the netty channel is not closed  when `io.pravega.client.netty.impl.ClientConnection`  is closed by the SegmentHelper. This can lead to unnecessary keepAlives to be sent by the periodic `KeepAliveTask`.  Closing the channel immediately in the case of `FLOW_DISABLED` will reduce the number of keepAlives. (This has been fixed in PR 3952)

SegmentHelper which uses `RawClient` has a lower count of KeepAlives since it uses connection pooling.
(This has been implemented as part of https://github.com/pravega/pravega/pull/3623)

**Comment by shrids** [comment]
Closing this issue as it has been already fixed.
