### ISSUE TITLE
Authentication failure should not automatically retry.

### ISSUE THREAD

**Issue by zwx14700** [pravega/pravega#3884]
**Problem description**
Create a pravega-client with a PravegaCredential that only have read scope permission.
Call streamManager.createScope()
After about 2 mins, Pravega will throw
`io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication.`

**Problem location**
The client-controller automatically does the retry, which cause a quite long time to get Authentication failure.

**Suggestions for an improvement**
Should not retry if the grpc exception is an Authentication failure.

**Comment by ravisharda** [comment]
@zwx14700 this issue is already reported under "Difficulty in error handling" item in issue #3653 description.
