### ISSUE TITLE
Do not suppress exceptions on a failed system test.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#3892]
**Problem description**
Currently when a system test throws an error, on several tests it goes into a finally block which makes additional assertions. If any of these fire the original cause of the failure is lost and the test fails with the assertion from the finally block.

**Problem location**
Several system tests.

**Suggestions for an improvement**
Do not make assertions in a finally block.

**Comment by shrids** [comment]
Closed as part of PR #3894
