### ISSUE TITLE
Client-to-Segment-Store communication uses TLS based on Controller URI scheme 

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3895]
**Problem description**

First, a bit of background. To use TLS for client-to-controller communication, you specify a Controller URI in the client application that uses URI(s) of the form `tls://...` (for a static set of endpoints) or `pravegas://...` (for auto-discovery). The schemes `tls` and `pravegas` indicate TLS/secure channel. 

The problem is that if the client sees a scheme indicating TLS in the Controller URI, it assumes that TLS is also enabled for Segment Store services. Also, if TLS is enabled for Segment Store, but not for the Controller - i.e., the scheme in Controller URI is `tcp` or `pravega`, the client infers plaintext scheme for client-to-segment-store communications as well. 

Using Controller URI to determine whether to communicate to Segment Store over TLS is OK for scenarios where both Controller and Segment Store services are accessible over TLS-enabled channels. Note that TLS may be terminated directly in the Pravega services or alternatively, in an infrastructure component front-ending those services like Kubernetes Ingress or reverse proxies. 

However, the behavior mentioned above is problematic in heterogeneous scenarios where either the Controllers or the Segment Stores, but not both, are not accessible over TLS -enabled channels. There are two cases to consider here:

| Title | TLS enabled for Controllers? | TLS enabled for Segment Stores? |
|:-----|:--------------------------------|:--------------------------------------|
| Case 1 | Yes | No |
| Case 2 | No | Yes |

**Problem location**

**Suggestions for an improvement**

Use Segment Store service URI to determine whether to use TLS for client-to-segment-store communications. This is assuming that the protocol can be inferred from the Segment Store endpoint addresses returned by the Controller.

If the Segment Store endpoint addresses don't contain enough information for the client to identify the protocol, bigger changes shall be needed to register protocol in addition to IP address and port on the Segment Store side as well as in Pravega Operator.

**Comment by EronWright** [comment]
A little detail to keep in mind: in practical use, the segment store address should be a hostname not an IP address.   I realize that the term "IP address" is used loosely, but I want to clarify, because TLS relies on hostname verification to be secure.

**Comment by ravisharda** [comment]
Pull request #4163 added support for enabling TLS for segment store while keeping it disabled for Controller, and vice versa. So, this issue is not relevant anymore.
