### ISSUE TITLE
Pravega stream under performs with 10000 events/sec and 1000 segments on comparing it with 10000 events/sec and 100 segments

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#3897]
**Problem description**

On running the stream with 5 workers ( readers & writers ), data size 100 bytes, **10000 events/sec rate**, run time 300 secs and **segments 100**, the following output is noticed: -

```
2995047 records Writing, 9997.386 records/sec, 100 bytes record size, 0.95 MB/sec, 101.1 ms avg latency, 1245.0 ms max latency, 95 ms 50th, 185 ms 95th, 299 ms 99th, 661 ms 99.9th.
2993764 records Reading, 9985.171 records/sec, 100 bytes record size, 0.95 MB/sec, 0.0 ms avg latency, 987.0 ms max latency, 0 ms 50th, 0 ms 95th, 1 ms 99th, 8 ms 99.9th.
```

Whereas on running the stream with same workload as mentioned above, i.e., 5 workers ( readers & writers ), data size 100 bytes, **10000 events/sec rate**, run time 300 secs and giving **segment** value as **1000**,
1) performance seems to get reduced by more than 50% (,i.e., number of records read/written ) and 
2) avg latency for write operation increases by 5 times.

```
1149089 records Writing, 3829.671 records/sec, 100 bytes record size, 0.37 MB/sec, 539.7 ms avg latency, 3625.0 ms max latency, 494 ms 50th, 1179 ms 95th, 1584 ms 99th, 2583 ms 99.9th.
1146965 records Reading, 3818.482 records/sec, 100 bytes record size, 0.36 MB/sec, 0.2 ms avg latency, 7447.0 ms max latency, 0 ms 50th, 1 ms 95th, 1 ms 99th, 4 ms 99.9th.
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2269.6f8a820
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by SomeshJoshi19** [comment]
sharing the logs on internal channel due to size limit

**Comment by kmgowda** [comment]
please use the latest tool version of performance bench-marking tool...

**Comment by SomeshJoshi19** [comment]
@kmgowda  

1)  If the same tool produces expected results with the same workload but lesser number of segments and does not matches the expected results for higher number of segments then how can it be a tool issue. It seems like Pravega system is not able to handle operation over 1000 segments.

2) Not able to get differentiated output for readers and writers if tested for performance using latest build of benchmark tool

**Comment by kmgowda** [comment]
@SomeshJoshi19 
1.  The old version of the tool had the following problems
        - due to threads interlocking, tool was not able to push event effectively.
         - write randomness is improved by calling write method of event writer so that pravega client takes care of random writes to segments.

2. if you are using latest pravega for testing ; then its expected you should use latest client and latest benchmark tool for testing. otherwise test results would be debatable unnecessarily. 

3. if you are testing the write performance, then use only "-producers" options

4. if you are testing the read performance, then use only "-consumers" options.

5. both "-producers" and "-consumers" options are used to measure only the end to end latency.

**Comment by SomeshJoshi19** [comment]
On reproducing the scenario of comparing single stream run of **1000 segments** with **100 segments** having workload of 5 workers ( readers & writers ), data size 100 bytes, **10000 events/sec rate** and run time as 300 secs, following are the observations: -
>  performance to read and write records/events gets varied by 70% 

End results of write and read records with 100 segments
```
2978257 records Writing, 9976.341 records/sec, 100 bytes record size, 0.95 MB/sec, 474.2 ms avg latency, 2601.0 ms max latency, 457 ms 50th, 670 ms 75th, 937 ms 95th, 1235 ms 99th, 1756 ms 99.9th, 2027 ms 99.99th.
2978257 records Reading, 9959.760 records/sec, 100 bytes record size, 0.95 MB/sec, 0.4 ms avg latency, 988.0 ms max latency, 0 ms 50th, 0 ms 75th, 0 ms 95th, 1 ms 99th, 147 ms 99.9th, 336 ms 99.99th.
```

End results of write and read records with 1000 segments
```
594157 records Writing, 1996.569 records/sec, 100 bytes record size, 0.19 MB/sec, 414.2 ms avg latency, 2303.0 ms max latency, 375 ms 50th, 531 ms 75th, 911 ms 95th, 1192 ms 99th, 1446 ms 99.9th, 1513 ms 99.99th.
594157 records Reading, 1986.337 records/sec, 100 bytes record size, 0.19 MB/sec, 0.6 ms avg latency, 3659.0 ms max latency, 0 ms 50th, 0 ms 75th, 1 ms 95th, 1 ms 99th, 86 ms 99.9th, 409 ms 99.99th.
```

Pravega-Operator deployment with 2 controllers, 3 Zookeepers, 4 Bookies and 3 Segment stores.
Environment details: PKS / K8 with medium cluster:
```
1 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
3 worker nodes @ xlarge.cpu(4 cpu, 16 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```
Pravega details:
```
Pravega version : 0.5.0-2269.6f8a820
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: pravega/pravega-operator:0.3.2
```

**Comment by kmgowda** [comment]
yes.. I could see that read there is no  impact irrespective number of segments.
writer is proportionately slow as the number of segments.

**Comment by SomeshJoshi19** [comment]
@kmgowda the result clearly shows huge difference between the number of records written and read between the two streams,

~3 million records for 100 segments whereas ~0.6 million records in case of 1000 segments

**Comment by fpj** [comment]
I'm moving this issue to `0.6`.
