### ISSUE TITLE
Use external DNS name as segment store advertised endpoint

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3899]
**Problem description**
For TLS to work end-to-end with hostname verification enabled, the segment store's advertised endpoint must be a DNS name.   The advertised value is determined at segment store startup (`init_kubernetes.sh`) and has a problem; the external IP is advertised, rather than the external DNS name as required for hostname verification.

**Problem location**
`docker/pravega/scripts/init_kubernetes.sh`

**Suggestions for an improvement**
1. The external DNS name is available as an annotation on the `Service` resource.   Use that value in lieu of the IP address that is contained in the `status` section.  The annotation is:
`external-dns.alpha.kubernetes.io/hostname`
Note that the value may have a period as a suffix; if it does, strip it.  [More info about the annotation](https://github.com/kubernetes-incubator/external-dns/blob/master/docs/faq.md#how-do-i-specify-a-dns-name-for-my-kubernetes-objects).

**Comment by kevinhan88** [comment]
Add tag 0.5.0 into this issue as this is required for nautilus 1.0

**Comment by fpj** [comment]
@kevinhan88 we have marked this for `0.6.0`, and at this point we are only looking at critical issues for `0.5.0`.

**Comment by EronWright** [comment]
@pbelgundi note that #4004 altered the logic to incorporate some hostname information.  I would suggest we continue with #3899 as planned, but the overall priority order of the available info should be (high- to low-priority):
1. `external-dns.alpha.kubernetes.io/hostname` annotation
2. `.status.loadBalancer.ingress[0].hostname` field
3. `.status.loadBalancer.ingress[0].ip` field

**Comment by fpj** [comment]
I'm wondering about the traffic of clients internal to the cluster. Please help me understand what happens for the case that we have one or more clients running inside the kubernetes cluster.

If the external address is used, then it will be resolved to an external address. Consequently, is it the case that all traffic from the clients inside the cluster will be routed outside and then back in? Or is it only the resolution that happens externally?

I'm sure we have discussed this before, but I can't find the issue covering it. At the time, I believe the suggestion was for the segment store to advertise both an internal and an external endpoint. In the case that this change forces inside traffic to go outside, should this be done in conjunction with the change that advertises both endpoints? Are there other options?

**Comment by EronWright** [comment]
@fpj the status quo is that Pravega is capable of advertising exactly one address to the client.  Since some clients are internal and others are external, an external address must be advertised.  This PR relates to advertising the DNS name rather than the IP address of the address, but is otherwise orthogonal.

I agree that it is sub-optimal for internal clients to use the external route.   My suggestion would be that the segment store be able to advertise numerous addresses, which in K8 would correspond to the pod FQDN and the external FQDN.   Treating the addresses as ordered from least-costly to most-costly, the client would work down the list until a connection is successful.    Assumedly a failure to resolve a given FQDN would cause the client to quickly move on to the next address.

**Comment by pbelgundi** [comment]
Filed pravega-operator issue #[252](https://github.com/pravega/pravega-operator/issues/252) to deal with routing traffic for internal clients when external access is enabled.
