### ISSUE TITLE
Verify: Issue #3121 : Controller restart observed due to OutOfMemory 

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3913]
Verify issue #3121 on PKS environment whether controller restart is being observed with adequate resource allocation as mentioned in the provisioning detailing and longevity workload.

**Comment by deenav** [comment]
Verified that issue #3121 is not reproducible with Pravega build #0.5.0-2269.6f8a820 and controller restart not happening due to OOM in the longevity workloads which are running for >5 days.
