### ISSUE TITLE
Verify: Issue #3750: NPE in ServerConnectionInboundHandler - DecoderException

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega#3914]
Verify issue #3750 with the latest build with similar longevity cycle and check NPE in ServerConnectionInboundHandler - DecoderException

**Comment by deenav** [comment]
Verified that issue #3750 is not reproducible with Pravega build #0.5.0-2269.6f8a820 and `ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection:
io.netty.handler.codec.DecoderException: java.lang.NullPointerException` message not there in medium-scale longevity workload running for >5 days.
