### ISSUE TITLE
JVM and controller.host  metrics have colliding `host` tag

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3923]
**Problem description**
Both JVM metrics and [Controller Host metrics](https://github.com/pravega/pravega/blob/master/shared/metrics/src/main/java/io/pravega/shared/MetricsNames.java#L182-L184) have a `host` tag.
The JVM metrics report host name as a `host` tag (something like `pravega-segmentstore-0.pravega-segmentstore.pravega.svc.cluster.local` for a Kubernetes deployment), while controller host metrics report host IP (something like `1.2.3.4:12345:`).
This create a confusion when creating automated queries for JVM metrics (half availabe  `host` tag values do not have any JVM metrics for them).

**Problem location**
HostContainerMetrics.java ?

**Suggestions for an improvement**
It would be great if the Controller host metrics reported a `host` tag that is a kubernetes hostname instead of IP.

**Comment by kevinhan88** [comment]
This issue is also closed by https://github.com/pravega/pravega/pull/4103
