### ISSUE TITLE
Simplify Segment Store token verification logic

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3927]
**Problem description**

Token verification logic in `TokenVerifierImpl.java` that validates whether the claim key matches the resource being accessed, is difficult to read and decipher. It should be simplified after verifying the logic with various combinations of token claims and segment store resource representations. 

**Problem location**
`io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.java`

**Suggestions for an improvement**

**Comment by sachin-j-joshi** [comment]
@ravisharda is this issue resolved? can we close it ? Looks like the PR is merged.

**Comment by ravisharda** [comment]
No, this issue is not fixed yet. The referenced PR #3887 contains a conversation that was the source of this issue.
