### ISSUE TITLE
Controller gRPC list streams operation fails to list authorized streams for unprivileged users

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3940]
**Problem description**

Consider a scenario where:
* There is a user account `user1` having an `scope1,READ;scope1/stream1,READ`. 
  
   W.r.t. listing operation, this implies that the user can list the streams in scope `scope1`, and upon listing will see `stream1`. (For details about the auth model, see [this](https://github.com/pravega/pravega/pull/3386#issuecomment-468679456) comment in PR [3386](https://github.com/pravega/pravega/pull/3386).)

* Scope `scope1` and streams `stream1`, `stream2`, and `stream3` are present in the system.

If you invoke the Controller gRPC operation `listStreamsInScope` passing `scope1` in the request with credentials of `user1`, the result should list `stream1`. Currently, due to a bug, the result is an empty list. 

**Problem location**
io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl.listStreamsInScope(...)`

**Suggestions for an improvement**

**Comment by sarlaccpit** [comment]
One question, when a user is not authorized to list streams of a scope, should it return an empty list or throw an exception?    I'm mixed on it myself.

On one hand, returning an empty list is consistent with the use case of having READ on "/" and the list of scopes is _filtered_.     On the other hand, now the scenario of not being authorized on a scope and the scope not having any streams behaves the same way: an empty list.  Which may or may not be a bad thing.

@ravisharda what are your thoughts?

**Comment by ravisharda** [comment]
@sarlaccpit if a user is not authorized to list `streams` of a `scope,` an exception is thrown to indicate authorization failure. That is consistent with how we deal with authorization failures for other operations in the Controller gRPC and REST API. 

One way to think of it is that there two kinds of authorization in place:
1. Can the `subject` perform this `operation`? For the list streams operation in Pravega, this access is granted by providing a subject `READ` permission on the `SCOPE` (the parent resource). 
   In this case, there is an authorization failure. 

2. Can the `subject` view/edit this particular `object`/instance? The list streams operation shows only those instances that the user has been granted access to. 
   In this case, the output is filtered. There is no authorization failure. 

I think the behavior seems to be OK and simple to articulate and understand.
