### ISSUE TITLE
Improve the Performance with Connection Pooling

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#3969]
**Problem description**
The Connection Pooling has reduced the writer performance.
Another  issue #3774 gives quantifies the performance degradation.

**Problem location**
Pravega Client / Append Processor

**Suggestions for an improvement**
its observed that reducing the connection is causing multiplexing the netty channel and performance degradation.
So, if one writer is using channel , the buffer the next writer data and then serialize would improve the performance

**Comment by tkaitchuck** [comment]
There are several possible solutions. One that might be a mitigation, is to replace the null padding with unrelated data. This would be abstraction breaking and make the wire protocol very complicated. So we first attempt to understand the performance it will achieve. This may be similar to disabling batching when the number of segments >> number of connection.
