### ISSUE TITLE
Assign Resources to Kubernetes Pods in System Tests

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3974]
**Problem description**
We need to assign a sufficient amount of resources to Pravega pods executing system tests. Currently, they have the default resources assigned by the system.

**Problem location**
Kubernetes System Test Framework.

**Suggestions for an improvement**
Extract the resource-related changes from PR #3922 in a separate PR.

**Comment by pbelgundi** [comment]
Fixed by PR: https://github.com/pravega/pravega/pull/4141
