### ISSUE TITLE
Low HDFSStorage Performance

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3977]
**Problem description**
In the last weeks, we have seen consistent system test failures using HDFS as Tier 2. After some analysis, we concluded that `HDFSStorage` presents a much lower performance compared to `FileSystemStorage` in our system tests. While for some operations this may be expected (a single `SyncStorage` API call may translate in various HDFS operations), the performance difference we have observed seems too high as we present in the following plots:
![tier2_performance_comparison_1test_throttling_vs_no_throttling_added_run_1](https://user-images.githubusercontent.com/717112/60334657-4e5a4f00-999c-11e9-9fe5-0080d1f762c8.jpg)
![tier2_performance_comparison_1test_throttling_vs_no_throttling_added_run_2](https://user-images.githubusercontent.com/717112/60334663-50bca900-999c-11e9-94de-09d9d8a55104.jpg)

Some observations from these plots:
- The IO performance difference between `HDFSStorage` and `FileSystemStorage` are important in most operations, and particularly for very common ones like `openWrite`, `openRead` and `write`, among others.
- As can be observed, throttling transactional writers in system tests (#3950, continuous blue line in the plots) alleviates the performance problem for `HDFSStorage`. This indicates that Tier 2 is not able to handle the amount of workload we are generating in the tests.
- The variability in performance across runs is also high, as it can be inferred from comparing the two HDFS dotted lines.
- While failures induced by the saturation of HDFS as Tier 2 are disparate and have many manifestations, common issues is that Segment Container recoveries take too long to complete (e.g., +30 seconds ) and Storage Writer iterations are very slow (up to 14 minutes). Given that several tests induce a rapid succession of failovers, Pravega starts trashing and several correlated failures occur. 
- 99% of writes are <10KB, which is a very bad scenario for HDFS.

**Problem location**
`HDFSStorage`

**Suggestions for an improvement**
Need to optimize the management of Tier 2 data in HDFS. PDP 34 may be already considering how to solve the problems in HDFS: https://github.com/pravega/pravega/wiki/PDP-34:-CRWD-Tier-2

**Comment by sachin-j-joshi** [comment]
This PR specifically targets to reduce use of globStatus https://github.com/pravega/pravega/issues/3265
