### ISSUE TITLE
Docker Swarm: scale_segmentstore script scales up  SSS with version: pravega:latest

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3982]
**When scale up of SSS is done with script `scale_segmentstore`, the scaled up SSS comes up with image`pravega:latest` whereas the original Pravega installation and SSS is in some other version.** 
```
[root@nautilus-master-3 swarm]# d service ls
ID            NAME                    MODE        REPLICAS  IMAGE
0001hgipf06s  pravega_segmentstore_2  replicated  1/1       pravega/pravega:latest
5pvxab8jygji  pravega_controller      replicated  1/1       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
bez0i20ikxre  pravega_segmentstore    replicated  1/1       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
pwgybs26ratz  pravega_bookkeeper      replicated  4/4       devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2284.8c6c176
r7h0vsfxz5fz  pravega_hdfs            replicated  1/1       pravega/hdfs:2.7.7
w9sjhhmqr9xl  pravega_zookeeper       replicated  1/1       zookeeper:3.5.4-beta
```
Same case doesn't happen when scaling is done with `docker service scale pravega_segmentstore=N` for(Installation without published IP)and the scaled up SSS comes up with the existing SSS version:
```
[root@nautilus-master-3 swarm]# d service ls
ID            NAME                  MODE        REPLICAS  IMAGE
65l7e7zufcf3  pravega_hdfs          replicated  1/1       pravega/hdfs:2.7.7
8lay47v2fd1b  pravega_controller    replicated  1/1       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
9ge2n9w4n3cm  myapp                 replicated  1/1       openjdk:8
mddpmm8zn1vb  pravega_zookeeper     replicated  1/1       zookeeper:3.5.4-beta
ql3bld8kaelr  pravega_bookkeeper    replicated  4/4       devops-repo.isus.emc.com:8116/nautilus/bookkeeper:0.5.0-2284.8c6c176
ysnni6oe4t2d  pravega_segmentstore  replicated  2/2       devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2284.8c6c176
```
**Suggestions for an improvement**: `scale_segmentstore ` should also take care of the current version and scaled up SSS should match with the existing SSS version.

**Comment by shrids** [comment]
@Richa-Srivastava Could you please share the `pravega.yml` used to deploy Pravega ?

**Comment by Richa-Srivastava** [comment]
[pravega_2284.zip](https://github.com/pravega/pravega/files/3345195/pravega_2284.zip)
Hi @shrids attached is pravega.yml I used

**Comment by shrids** [comment]
Currently the pravega.yml and `scale_segmentstore`  both are configured to use the latest pravega/pravega image on docker hub. Modifying the pravega.yml to use a custom version of pravega requires you to modify the `scale_segmentstore` script too.

**Comment by sumit-bm** [comment]
@shrids : Modifying `pravega.yml` is easy but the script modification is difficult for customers. How about script would evaluate existing SS (deployed from yml) and find the image tag and scale SS based on that?
