### ISSUE TITLE
pravega segmentstore could not obtain service endpoint in AWS environment

### ISSUE THREAD

**Issue by gaddamas** [pravega/pravega#4002]
**Problem description**
When external connectivity is enabled in AWS environment provega-segmentstore is stuck in getting LoadBalancer external endpoint.

build 0.5.0-2291

**Problem location**
https://github.com/pravega/pravega/blob/master/docker/pravega/scripts/init_kubernetes.sh#L57

**Suggestions for an improvement**
script should look for hostname from the service status block. ingress.ip or ingress.hostname
status:
  loadBalancer:
    ingress:
    - hostname: aws-elb-hostname  <-- elb name redacted. it was assigned

**Comment by Tristan1900** [comment]
Is this because the external endpoint IP is provisioned slow on AWS? The current script works fine on GKE and PKS, so I'm not sure what happened.

**Comment by keedya** [comment]
@Tristan1900  here is the issue; in the init_kuebernetes.sh script:
`export PUBLISHED_ADDRESS=$( k8 "${ns}" "services" "${podname}" ".status.loadBalancer.ingress[0].ip" )`
the script is looking for "IP"
In AWS  the LB is a hostname not an IP and can be retrieved as follow:
`export PUBLISHED_ADDRESS=$( k8 "${ns}" "services" "${podname}" ".status.loadBalancer.ingress[0].hostname" )`

**Comment by gaddamas** [comment]
endpoint was provisioned, it is not IP, it ELB's hostname.

**Comment by gaddamas** [comment]
suggested fix:
https://github.com/ravisharda/pravega/pull/1/files
