### ISSUE TITLE
Cherry-pick merges from master to r0.5

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4025]
**Problem description**
We need to cherry-pick the following merges to `r0.5`:

```
Issue 4011: (SegmentStore) Making Commit Backlog Throttler more aggressive (#4016)
Issue 4011: Fixed ThrottlerCalculator.Delay.ToString() (#4023)
```

**Problem location**
Release 0.5

**Suggestions for an improvement**
Backport the changes.

**Comment by RaulGracia** [comment]
Closed via #4026.
