### ISSUE TITLE
Enable RocksDB logging

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega#4029]
**Problem description**

The RocksDB log is not redirected to the Segmenstore log right now, it is nice to have RocksDB log displayed as well.

**Problem location**

RocksDBCache.java

**Suggestions for an improvement**

Enable the RocksDB log

**Comment by andreipaduroiu** [comment]
Similar to #4053, RocksDB was not a contributing factor towards our stability issues, so this is no longer a priority. #4044 will remove RocksDB altogether so this may not be needed.

**Comment by Tristan1900** [comment]
Got it, shall we close this issue? Or wait for it until 4044 is resolved?
