### ISSUE TITLE
Enable test pod image configuration for system tests

### ISSUE THREAD

**Issue by anishakj** [pravega/pravega#4040]
**Problem description**
Currently we are  hard coding the test pod image to use  `openjdk:8-jre-alpine`. By making it configurable, we will be able to run system tests with different jdk images.  There is a requirement to run system tests with `jdk9` test pod image 

**Problem location**
System tests

**Suggestions for an improvement**
Configure the test pod image selection.

**Comment by sachin-j-joshi** [comment]
@anishakj can we close this issue?
