### ISSUE TITLE
Direct Memory Cache

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4044]
**Problem description**
Our current cache implementation is based on RocksDB and has several drawbacks:
- It's a Key-Value store. We do not need a KVS; it's sufficient to insert data and get an address back that can later be used to access that data.
- It has overhead due to being a Key-Value Store. This includes indexing and compaction work.
- It has inflexible APIs that aren't appropriate for Streaming. For example, the only way (using the JNI) to append to an existing entry is to read it, copy it to a new byte array, add the new data, then re-insert the updated array. For this reason we chose to have an entry for each append we receive in the Segment Store.
- It has disk-spilling abilities which aren't as useful as we anticipated. While it would be nice to be able to have a cache larger than available RAM, doing one without specialized hardware (SSD or NVM) will introduce a significant performance bottleneck once memory buffers are full.

**Problem location**
Segment Store.

**Requirements**
We need a cache storage that meets the following requirements:
- Does not store data in Java heap and hence is not subject to GC governance.
- Has performance on par or better than using a Java HashMap (excluding GC pauses).
- Does not suffer from memory fragmentation or frequent allocation/deallocation problems.
- Has minimal heap and non-heap overhead.
- Supports appending to existing entries.
- Minimizes the number of memory copies required when inserting into or reading from it.
- Has a clear maximum bound and optionally notifies (whomever is listening) when the capacity is reached and/or exceeded.

**Suggestions for an improvement**
A solution that meets all the above requirements would implement a pooled block-based cache that works along the following lines:
- Splits the cache into large direct memory buffers of equal size (i.e., 2MB each)
- Each buffer is split into equally-sized blocks (i.e., 512 4KB blocks)
- Block 0 in each buffer is reserved for metadata, and the rest are used for storing data.
    - Each block's metadata indicates whether it's used, its successor or predecessor and its length. For efficiency, empty blocks may also be chained together to make writing faster.
- Inserting would involve finding the first available buffer, writing as much data to it as possible, then locating additional buffers and repeating until the entire data is stored. A pointer to the last block (codified as an Int32/64) will be returned and serves as the entry's address.
- Deleting would involve walking all the blocks reachable from an address and marking them as unused.
- Reading would involve walking all the blocks reachable from an address and combining them into a composite buffer that can be returned to the caller.
- Appending would append as much data as possible to the last block (if non-full) and optionally create new blocks.

Disadvantages:
- Rather complex compared to simply allocating direct memory via `ByteBuffer.allocateDirect`
    - Using `ByteBuffers` would require us to keep pointers to each one individually (extra heap overhead) and would be subject to memory fragmentation, so the complexity is warranted.
- Internal fragmentation. An entry will occupy a number of blocks, and the last block will be fully reserved, even if only 1 byte is required. This has the potential of allocating a lot of unused memory, however that's where `append` comes into play. We can append to an existing entry until we fill up its last block, and then we can insert a new entry. This plays well into the Streaming world, where we append by default so we are guaranteed to always have new data to add at the end.
- Reserved memory for metadata. There is one block reserved in each buffer for metadata, which could constitute memory that could otherwise be used for storage. However this overhead is minimal. For a 4KB block/2MB buffer, the reserved space is 0.2% of the total capacity. So a 10GB cache would only need 20MB of reserved space for metadata.

Benchmarking:
- See comment below.

**Comment by EronWright** [comment]
Please take the time to audit the JVM flags that are applied (especially in pravega-operator-managed scenarios) as part of this effort, e.g. ensure that any needed containerization flags are applied.  Thanks!

**Comment by andreipaduroiu** [comment]
@EronWright That's a good suggestion. We've already identified a few JVM options and flags that need to be set and easily configured in the operator (such as `XX:MaxDirectMemorySize`). Those will make it in the next version of the operator, regardless of the outcome of issue #4044..

**Comment by andreipaduroiu** [comment]
Benchmark results:
I wrote a benchmark that executes two types of tests:
- Sequential: Inserts, then Gets, then Appends (if supported), then Deletes .
- Random: Inserts with a certain probability (>50%), Deletes with a certain probabilty (<50%) and reading every time.

Legend:
- **HeapMemory**: `io.pravega.segmentstore.storage.mocks.InMemoryCache`.
- **RocksDB**: `io.pravega.segmentstore.storage.impl.rocksdb.RocksDBCache`.
- **DirectMemory**: `io.pravega.segmentstore.storage.cache.DirectMemoryStorage` (PR #4074).
- Values are elapsed times, expressed in milliseconds.

```
Sequential Operations: 10KB Entries, 1M Inserts, 1M Gets, 1M deletes
HeapMemory   : Insert:  2516, Get:  2201, Delete:  35
RocksDB      : Insert: 25234, Get: 12283, Delete: 577
DirectMemory : Insert:   890, Get:   830, Delete:  84, Append: 209


Random 10KB keys, 1M operation count (60% Insert, 40% delete, 100% read)
HeapMemory   : Random operations  3633
RocksDB      : Random operations 21499
DirectMemory : Random operations  3188

Random 100KB keys, 1M operation count (60% Insert, 40% delete, 100% read)
HeapMemory   : Random operations 22008
RocksDB      : Aborted after 5 minutes.
DirectMemory : Random operations 9440
```

**Comment by andreipaduroiu** [comment]
**Segment Store Streaming Benchmark results.**
(To be used for comparison purposes only; this was tested on my development machine, your actual numbers may vary on hardware setup)

For this benchmark, the following configs were used (not encoded in the below commands):
- Cache Max Size: 6GB, Target Threshold: 85%, Throttling 90-98%.
- Writer: 64MB flush/max threshold.
- Cache Eviction after 30 seconds of inactivity.

Each experiment was ran 3 times, and the best run was chosen for each.

**2M x 1KB Appends, 100x100 producers**
Command: `-Dtarget=InProcessStore -Dbkc=0 -Dcc=0 -Dssc=1 -Dc=1 -Ds=1 -Dsc=4 -Dp=100 -Dpp=100 -Dws=1000 -Do=2000000`

Base:
```
0:00:25.714 [Reporter]: 2003214/2000000; Ops = 5478/91012; Data (P/T/C/S): 1910.4/0.0/0.0/0.0 MB; TPut: 5.2/86.8 MB/s; TPools (Q/T/S): S = 4/1/80, T = 0/1/80, FJ = 0/0/3.
0:00:25.714 [Reporter]: Operation Summary
0:00:25.714 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:25.715 [Reporter]:             Append | 2003214 |    56 |    13 |    99 |   107 |   558 |   878
```

Base + Direct Memory Cache
```
0:00:24.884 [Reporter]: 2005043/2000000; Ops = 95810/94971; Data (P/T/C/S): 1912.2/0.0/0.0/0.0 MB; TPut: 91.4/90.6 MB/s; TPools (Q/T/S): S = 3/1/80, T = 0/1/80, FJ = 0/0/1.
0:00:24.885 [Reporter]: Operation Summary
0:00:24.885 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:24.888 [Reporter]:             Append | 2004940 |    46 |    17 |    98 |   109 |   161 |   362
```

**1M x 10KB Appends, 100x100 producers**
Command: `-Dtarget=InProcessStore -Dbkc=0 -Dcc=0 -Dssc=1 -Dc=1 -Ds=1 -Dsc=4 -Dp=100 -Dpp=100 -Dws=10000 -Do=1000000`

Base:
```
0:01:15.904 [Reporter]: 1009010/1000000; Ops = 9194/14317; Data (P/T/C/S): 9622.7/0.0/0.0/0.0 MB; TPut: 87.7/136.5 MB/s; TPools (Q/T/S): S = 3/2/80, T = 0/1/80, FJ = 0/0/3.
0:01:15.904 [Reporter]: Operation Summary
0:01:15.904 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:01:15.905 [Reporter]:             Append | 1009010 |   541 |   276 |   652 |  1414 |  3261 |  3604
```

Base + Direct Memory Cache
```
0:00:26.591 [Reporter]: 1005807/1000000; Ops = 54119/45163; Data (P/T/C/S): 9592.1/0.0/0.0/0.0 MB; TPut: 516.1/430.7 MB/s; TPools (Q/T/S): S = 3/1/80, T = 0/1/80, FJ = 0/0/4.
0:00:26.592 [Reporter]: Operation Summary
0:00:26.592 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:26.594 [Reporter]:             Append | 1005769 |   130 |    95 |   150 |   246 |   797 |  1077
```

**Comment by andreipaduroiu** [comment]
**Segment Store Table Benchmark results.**
(To be used for comparison purposes only; this was tested on my development machine, your actual numbers may vary on hardware setup)

For this benchmark, the following configs were used (not encoded in the below commands):
- Cache Max Size: 6GB, Target Threshold: 85%, Throttling 90-98%.
- Writer: 64MB flush/max threshold.
- Cache Eviction after 30 seconds of inactivity.

Each experiment was ran 3 times, and the best run was chosen for each.

**1M x 1KB Entries, 100x100 producers**
Command: `-Dtarget=SegmentStoreTable -Dbkc=0 -Dc=1 -Ds=1 -Dsc=4 -Dws=1000 -Dp=100 -Dpp=100 -Do=1000000`

Base:
```
0:01:27.771 [Reporter]: 1005362/1000000; Ops = 0/41899; U/G/GK:1005362/1133/39040; Data: 1007.2 MB; TPut: 0.0/42.0 MB/s; TPools (Q/T/S): S = 3/1/80, T = 0/1/80, FJ = 0/0/1.
0:01:27.771 [Reporter]: Operation Summary
0:01:27.771 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:01:27.771 [Reporter]:       Table Remove |  109319 |   118 |   110 |   164 |   216 |   525 |   673
0:01:27.772 [Reporter]:       Table Update |  896043 |   117 |   110 |   164 |   216 |   528 |   673
0:01:27.772 [Reporter]:    Table Batch Get |    1133 |   178 |   163 |   189 |   241 |   672 |   678
```

Base + Direct Memory Cache
```
0:01:24.752 [Reporter]: 1003546/1000000; Ops = 0/47539; U/G/GK:1003546/4953/167151; Data: 1005.6 MB; TPut: 0.0/47.6 MB/s; TPools (Q/T/S): S = 3/1/80, T = 0/1/80, FJ = 0/0/1.
0:01:24.752 [Reporter]: Operation Summary
0:01:24.752 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:01:24.753 [Reporter]:       Table Remove |  108898 |    67 |    29 |    91 |   183 |   422 |   709
0:01:24.753 [Reporter]:       Table Update |  894648 |    67 |    29 |    91 |   182 |   423 |   711
0:01:24.754 [Reporter]:    Table Batch Get |    4953 |    26 |    19 |    28 |    50 |   138 |   400
```

**100K x 10KB Entries, 100x100 producers**
Command: `-Dtarget=SegmentStoreTable -Dbkc=0 -Dc=1 -Ds=1 -Dsc=4 -Dws=10000 -Dp=100 -Dpp=100 -Do=100000`

Base:
```
0:00:39.598 [Reporter]: 102651/100000; Ops = 0/4631; U/G/GK:102651/181/5600; Data: 888.3 MB; TPut: 0.0/40.1 MB/s; TPools (Q/T/S): S = 4/0/80, T = 0/1/80, FJ = 0/0/1.
0:00:39.598 [Reporter]: Operation Summary
0:00:39.598 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:39.599 [Reporter]:       Table Remove |   11143 |   191 |    69 |   305 |   586 |   926 |  1076
0:00:39.599 [Reporter]:       Table Update |   91508 |   193 |    73 |   311 |   578 |   920 |  1083
0:00:39.600 [Reporter]:    Table Batch Get |     181 |   676 |   498 |   781 |  1083 |  2929 |  2929
0:00:39.601 [Reporter]: Tbl Iterator Init. |       1 |  8482 |  8482 |  8482 |  8482 |  8482 |  8482
0:00:39.601 [Reporter]:  Tbl Iterator Loop |   23140 |     0 |     0 |     0 |     0 |     0 |     1
```

Base + Direct Memory Cache
```
0:00:31.656 [Reporter]: 100085/100000; Ops = 0/4450; U/G/GK:100085/240/7592; Data: 867.0 MB; TPut: 0.0/38.6 MB/s; TPools (Q/T/S): S = 4/0/80, T = 0/1/80, FJ = 0/0/1.
0:00:31.656 [Reporter]: Operation Summary
0:00:31.656 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:00:31.657 [Reporter]:       Table Remove |   10768 |    90 |    26 |   126 |   277 |   573 |   884
0:00:31.658 [Reporter]:       Table Update |   89317 |    93 |    27 |   133 |   287 |   580 |   859
0:00:31.658 [Reporter]:    Table Batch Get |     240 |   338 |   340 |   482 |   527 |   831 |   831
0:00:31.658 [Reporter]: Tbl Iterator Init. |       1 |  3349 |  3349 |  3349 |  3349 |  3349 |  3349
0:00:31.658 [Reporter]:  Tbl Iterator Loop |   22920 |     0 |     0 |     0 |     0 |     0 |     1
```
