### ISSUE TITLE
Recovery fails with DataCorruptionException if an operation was only partially written to Tier 1

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4046]
**Problem description**
Consider this scenario:
1. We need to write a large operation that does not fit into a single Tier 1 write.
2. The operation is split across two `DataFrame`s (or more)
3. The first `DataFrame` makes it to Tier 1, but not the second one (because Tier 1 crashed or the host process crashed or whatever other reason)
4. The Container recovers - all is OK; the above operation is ignored.
5. More operations are written to the log in this container.
6. The Container fails over again.
7. Subsequent recovery fails with `DataCorruptionException` on the partially written operation (which should have been ignored).
8. The Container enters 'Offline` mode (due to a perceived corruption during recovery) and becomes unusable - manual intervention is needed to bootstrap it.

**Problem location**
Somewhere in `DurableLog`, `RecoveryProcessor` or beneath.

**Suggestions for an improvement**
Fix whatever recovery bug is there.

**Comment by fpj** [comment]
Reopen so that we can also merge it to `r0.5`.

**Comment by RaulGracia** [comment]
Closed via #4048.
