### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#406]
**Problem description**
A release typically involves a number of steps that are better documented as recipe so that we both don't forget the steps and don't depend on a single person to do it. Here is a sample list of high-level tasks involved when initiating a release:

- Create a release candidate
- Create a tag for the release candidate
- Sign and checksum the artifacts
- Stage the artifacts
- Test the artifacts
- Assuming the release candidate has been approved, publish the artifacts
- Produce the release notes. The release notes should contain all changes that the release includes. Specifically, a list of highlights with the major changes and features and a list of issues resolved.
- Create a new branch for the new version
- Announce the new release in all relevant channels

**Problem location**
This is part of documenting the release process.

**Comment by Prabha-Veerubhotla** [comment]
Taken care in https://github.com/pravega/pravega/issues/1087

**Comment by Prabha-Veerubhotla** [comment]
https://github.com/pravega/pravega/wiki/Pravega-release-process
