### ISSUE TITLE
Document a checklist to test and validate a release

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#407]
**Problem description**
Once a release candidate is staged, we need multiple people in the team to test and validate the RC. We need a checklist of steps to execute against staged artifacts so that we can execute against a staged RC.

**Problem location**
This is to document the process for testing and validating a release candidate.

**Suggestions for an improvement**
Initially, we will perform such tests manually, but going forward, we should consider automating the process as much as possible.

**Comment by Prabha-Veerubhotla** [comment]
https://github.com/pravega/pravega/wiki/Pravega-Release-Validation-Checklist

**Comment by Prabha-Veerubhotla** [comment]
@arvindkandhare , @fpj Please review the document.
