### ISSUE TITLE
Upgrade lombok plugin version for Java 11.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4078]
**Problem description**
`lombok.var` is not supported for java 10+ based builds which can caused build errors on java 11.
ref #4075 

**Problem location**
lombok plugin.

**Suggestions for an improvement**
https://projectlombok.org/changelog 
lombok version `v1.18.8 (May 7th, 2019)` fixes this issue related to var usage.

**Comment by TisonKun** [comment]
@shrids I locally start a branch bump lombok version and pass `gradle check`. However, since you already addressed effective problems in #4076 I am not sure whether we still need tp bump version. If so, why?

cc @fpj

**Comment by shrids** [comment]
We are currently using lombok version `1.18.4` and given that we are not using `lombok.var` in the code there is no pressing need to update the plugin version at the moment.

Listing out some of the new fixes in lombok in the newer version: 

- PLATFORM: A few lombok features (most notably delombok) failed on JDK12. Lombok Issue 2082
- BUGFIX: Delombok now delomboks java10's own var as var and not as the actual underlying type. Issue 2049
- BUGFIX: If you use @Builder and manually write the build() method in your builder class, javac would error out instead of deferring to your implementation. Lombok Issue 2050 Issue 2061
- FEATURE: Javadoc on fields will now also be copied to the Builders' setters. Lombok Issue 2008.
- PLATFORM: Due to changes to switch statements in JDK12, Lombok wasn't working with the JDK12 preview. Lombok Issue 1888

**Comment by andreipaduroiu** [comment]
This has been done with the recent migration to JDK11.
