### ISSUE TITLE
Rolling storage feature for data segments

### ISSUE THREAD

**Issue by ybasetty** [pravega/pravega#4084]
**Problem description**

Rolling storage feature that enables us to avoid issues with underlying file size limitation (e.g 4 TB on isilon). Currently, we do not allow rolling the segment file for data segments. We do it only for attribute segments, which is where we store extended attributes for a segment.

 

We need to support rolling the segment file. See attached email.
**Problem location**
Rolling Storage

**Suggestions for an improvement**

**Comment by andreipaduroiu** [comment]
@ybasetty The description of this issue is incorrect. Rolling storage can be done for every segment. Please clarify if you need something else, otherwise I will close this issue as already supported.

**Comment by sachin-j-joshi** [comment]
Andrei believes the segment rolling functionality is already implemented. We are not yet clear what is the exact ask here (or in other words what functionality is missing). 

@ybasetty we are waiting on your answer.
