### ISSUE TITLE
How to obtain a specific streamcut via timestamp parameters  e.g. event time, etc?  

### ISSUE THREAD

**Issue by frank-dkvan** [pravega/pravega#4098]
**Problem description**
currently Pravega client SDK just provides a simple API to obtain streamcut offset. 

in many real senario, we need slice streams per time dimension, saying, we want to see  historical driving info of a Taxi between  2019-08-10 00:00:00 and  2019-08-10 08:00:00

**Problem location**
Pravega client SDK

**Suggestions for an improvement**
add timestamp property i.e. event time, ingest time and etc into index, 
and add  timestamp parameters into streamcut API in Pravega client SDK

**Comment by frank-dkvan** [comment]
is this the WaterMarking feature which can provide such functionality?

**Comment by maddisondavid** [comment]
Currently the watermarking feature does not provide this facility, however an ability to request StreamCuts given some high level construct (such as  ingestion time) is absolutely crucial to fully realize historical stream processing.
