### ISSUE TITLE
Question about how to manually specify streamcuts thru API for a batch data processing application 

### ISSUE THREAD

**Issue by frank-dkvan** [pravega/pravega#4104]
**Problem description**
I find in the streamcuts example codes provided by github, it just demo a very simple approach to specifying streamcuts....just simply read event one by one...then record the  streamcuts...attached example code below

is there any API to support manually defining a streamcut,   instead of needing to create a readergroup and a read to read all the events one by one?

**Problem location**

 public List<StreamCut> createStreamCutsByIndexFor(String streamName, int iniEventIndex, int endEventIndex) {
        // Create the StreamCuts for the streams.
        final List<StreamCut> streamCuts = new ArrayList<>();
        final String randomId = String.valueOf(new Random(System.nanoTime()).nextInt());

        // Free resources after execution.
        try (ReaderGroupManager manager = ReaderGroupManager.withScope(scope, controllerURI);
             ClientFactory clientFactory = ClientFactory.withScope(scope, controllerURI)) {

            // Create a reader group and a reader to read from the stream.
            final String readerGroupName = streamName + randomId;
            ReaderGroupConfig config = ReaderGroupConfig.builder().stream(Stream.of(scope, streamName)).build();
            manager.createReaderGroup(readerGroupName, config);
            @Cleanup
            ReaderGroup readerGroup = manager.getReaderGroup(readerGroupName);
            @Cleanup
            EventStreamReader<String> reader = clientFactory.createReader(randomId, readerGroup.getGroupName(),
                    new JavaSerializer<>(), ReaderConfig.builder().build());

            // Read streams and create the StreamCuts during the read process.
            int eventIndex = 0;
            **### _EventRead<String> event;
            do {
                // Here is where we create a StreamCut that points to the event indicated by the user.
                if (eventIndex == iniEventIndex || eventIndex == endEventIndex) {
                    reader.close();
                    streamCuts.add(readerGroup.getStreamCuts().get(Stream.of(scope, streamName)));
                    reader = clientFactory.createReader(randomId, readerGroup.getGroupName(),
                            new JavaSerializer<>(), ReaderConfig.builder().build());
                }

                event = reader.readNextEvent(1000);
                eventIndex++;
            } while (event.isCheckpoint() || event.getEvent() != null);_**

            // If there is only the initial StreamCut, this means that the final one is the tail of the stream.
            if (streamCuts.size() == 1) {
                streamCuts.add(StreamCut.UNBOUNDED);
            }
        } catch (ReinitializationRequiredException e) {
            // We do not expect this Exception from the reader in this situation, so we leave.
            log.error("Non-expected reader re-initialization.");
        }
        return streamCuts;
    }

**Suggestions for an improvement**
provide API to manually specify streamcuts ? just like we specify index for a JAVA Array?

**Comment by frank-dkvan** [comment]
the code above comes from io.pravega.example.streamcuts.StreamCutsExample.java
btw, I am new to pravega but very interested in it.  maybe there has been such a kind of API I just don't know yet? :-)

**Comment by RaulGracia** [comment]
Thanks for your interest, @frank-dkvan. In my understanding, `StreamCut`s can be seen as "bookmarks". You are reading a Stream, you see something interesting, and then you bookmark this point in the Stream to come back later on if needed (i.e., `StreamCut`). When you do this via the `ReaderGroup` API, you ensure that the `StreamCut` is constructed correctly (i.e., the segment and offset mapping is right). While it may be possible, creating `StreamCut`s manually is complex (and risky) due to the dynamic nature of the number of segments within a Stream and the variable length that events may have.

**Comment by frank-dkvan** [comment]
Thanks for ur reply @RaulGracia  that is helpful for me to understand current version of pravega
one of my understanding in some real application senario is that:  we not only need to read next event one by one or get some interesting event via bookmark,  we also need some rewind or playback mechanism to fetch old event batch via specific time range or some other parameters....hopefully future Pravega can support that
