### ISSUE TITLE
Delegation token does not renew automatically upon expiry

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#4107]
**Problem description**
Pull request [3887](https://github.com/pravega/pravega/pull/3887) implemented delegation token expiry. As a result, delegation tokens eventually expire. When a client makes a request to segment store using a delegation token that has expired, the segment store rejects the request and the client application encounters a TokenException which looks like the stack trace shown below. 

```
io.pravega.auth.TokenExpiredException: io.jsonwebtoken.ExpiredJwtException: JWT expired at 2019-08-14T11:15:40Z. Current time: 2019-08-14T11:45:04Z, a difference of 1764381 milliseconds.  Allowed clock skew: 0 milliseconds.
        at io.pravega.shared.security.token.JsonWebToken.parseClaims(JsonWebToken.java:161)
        at io.pravega.shared.security.token.JsonWebToken.fetchClaims(JsonWebToken.java:180)
        at io.pravega.segmentstore.server.host.delegationtoken.TokenVerifierImpl.verifyToken(TokenVerifierImpl.java:56)
        at io.pravega.segmentstore.server.host.handler.AppendProcessor.setupAppend(AppendProcessor.java:159)
        at io.pravega.shared.protocol.netty.WireCommands$SetupAppend.process(WireCommands.java:501)
        at io.pravega.segmentstore.server.host.handler.ServerConnectionInboundHandler.channelRead(ServerConnectionInboundHandler.java:53)
```

The client application may catch the exception and retry the transaction to recover from the failure. But doing so unnecessarily complicates client application code. 

Rather than throwing an exception to the client application, the client library should automatically get the delegation token renewed. A couple of subtly different alternative options seem to be: 

1. Upon encountering the exception, reauthenticate with the Controller using the credentials supplied by the client application or its environment, obtain a new delegation token and retry the client-to-segment-store transaction transparently.
2. Get the existing delegation token refreshed by the Controller periodically. 

**Problem location**
Pravega Client library

**Suggestions for an improvement**

**Comment by sarlaccpit** [comment]
@EronWright I follow what you're saying I think.  My interpretation of that is: solution 1 is what we want.  As re-authentication will allow re-interaction with the authorization server and its policies, will the refreshing of delegation tokens would blindly assume "everything is still ok".

I think we definitely need to re-authenticate.

**Comment by maddisondavid** [comment]
But we also need to remember that this is going to be on the data path.  While this re-authentication is happening all Pravega communication stops, i.e. no more read/writes until a token is refreshed so we want to keep the number of moving parts to a minimum to make sure that there is as little interruption to the data path as possible.

That said, I guess it could be that the time taken to interact with the authentication server is fast enough and infrequent enough that in the scheme of things it's negligible.

**Comment by sarlaccpit** [comment]
I agree our interactions with the auth server need to be carefully crafted such that they are swift, and also use caching when possible.

We can decide how often that interaction happens based on the delegation token expiry we configure, it seems.
