### ISSUE TITLE
Enable checkstyle rule to forbid Trailing whitespace pattern

### ISSUE THREAD

**Issue by tisonkun** [pravega/pravega#4113]
**Problem description**

When I try to introduce a fix to dangling Javadoc in #4106 , I find that on save files my IDE automatically deletes trailing whitespaces and thus multiple lines regarded as diff. These diffs make code review a bit difficult time after time. We can enable a rule(see suggestion below) to enforce no trailing whitespace as an improvement.

**Problem location**

A lot of source files.

**Suggestions for an improvement**

```xml
    <module name="RegexpSingleline">
        <property name="format" value="\s+$"/>
        <property name="message" value="Trailing whitespace"/>
        <property name="severity" value="error"/>
    </module>
```

**Comment by TisonKun** [comment]
Before working on this I'm curious why our project haven't such a rule when introduce checkstyle plugin. Didn't it ever be a wart when reviewing lines of trailing whitespace diffs?

**Comment by TisonKun** [comment]
Another argument would be that when a contributor working on a specific issue, if he touched and trimmed spaces on working but actually not changed the file, codecov is likely unhappy for the file he touched but actually irrelevant to the issue.

cc @andreipaduroiu

**Comment by TisonKun** [comment]
Hi @shiveshr @andreipaduroiu I think this issue is almost of style. As the reply I received in https://github.com/pravega/pravega/pull/4130:

>we won't be seeing a slew of formatting-only changes in our commit history

Thus I wonder if this issue valid or just rejected by Pravega community.

**Comment by TisonKun** [comment]
A workaround is to forbid IDE or say editor from automatically trimming whitespace.
