### ISSUE TITLE
Detailed design for Simplified Tier-2 (PDP-34)

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#4128]
**Problem description**
We need to create detailed design for **PDP 34**. (https://github.com/pravega/pravega/wiki/PDP-34:-CRWD-Tier-2)

**Problem location**
Segment store tier-2.

**Suggestions for an improvement**
The output of this exercise should be following -
- [x] Create detailed design document 
- [x] Enumerate detailed requirements 
- [x] Create list of research/investigation tasks (features/issues)
- [x] Create list of tasks (features/issues)
- [ ] Create high level test scenarios to test 

**Links**

1. The Draft Design document is located here https://gist.github.com/sachin-j-joshi/8938d5be8986cfc5f61264852061c6a2

**Comment by sachin-j-joshi** [comment]
The Draft Design document is located here https://gist.github.com/sachin-j-joshi/8938d5be8986cfc5f61264852061c6a2

**Comment by sachin-j-joshi** [comment]
The design document is here https://github.com/pravega/pravega/wiki/PDP-34:-Simplified-Tier-2

**Comment by eolivelli** [comment]
This proposal is very interesting.
In my experience the adoption of Pravega is hard because it strictly needs some of the supported tier2 engines.
It supports pluggable tier2 but actually it is hard to implement one

**Comment by sachin-j-joshi** [comment]
This task is completed.
