### ISSUE TITLE
Verify stream exists before using it

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#417]
**Problem description**
If a stream does not exist, it fails when the client attempts to contact it. We could present a much cleaner error message if the client verified its existence first.

**Problem location**
ClkientFactoryImpl

**Suggestions for an improvement**
Contact the controller to verify the stream exists before using it.

**Comment by huide9** [comment]
After the conversation with Shivesh, a new controller RPCl need to be added to verify if a stream has been created successfully:  **a stream is fully created** -- indicated by the fact that stream state is "not" CREATING or UNKNOWN or DATA_NOT_FOUND_EXCEPTION
