### ISSUE TITLE
Fix excessive cache entry eviction bug

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4204]
**Problem description**
The CacheManager updates its Oldest/Newest Generations based on input it receives from its registered cache clients. However it has no way of telling if these clients report correct or incorrect data so it is important that all registered clients provide accurate information to the Cache Manager so that it may make the right decision.

It turns out that while `StreamSegmentReadIndex` works correctly, `SegmentAttributeBTreeIndex` and `ContainerKeyCache`/`SegmentKeyCache` report incorrect Old/New Gen information if their respective caches are empty. Instead of reporting `Integer.MAX_VALUE` in that case, they report `0`, which is a valid value. This causes the `CacheManager` to become paranoid about evicting items, essentially cornering it into a situation where it evicts data as soon as that data becomes eligible for eviction, thus rendering the cache mostly useless.

**Problem location**
CacheManager, ContainerKeyCache/SegmentKeyCache, SegmentAttributeBTreeIndex.

**Suggestions for an improvement**
Centralize computation of these values (they are all copy-pasted, which is why this bug propagated so easily) and fix it so that it reports values that make sense to the Cache Manager.

**Comment by RaulGracia** [comment]
I remember this issue being fixed, as now the amount of cached data is as expected (not kept to the minimum as before), @andreipaduroiu, please re-open this issue if I'm wrong.

**Comment by andreipaduroiu** [comment]
The changes for this are in branch `andreipaduroiu:issue-4204-cache-status` which depends on `andreipaduroiu:issue-4044-direct-mem-cache` to be merge in first.
