### ISSUE TITLE
Controller rest endpoint is not showing info about _MARK streams

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4251]
Deployment details:-
```
bookkeeper:0.6.0-2378.3ae8db3
pravega:0.6.0-2378.3ae8db3
pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.3
pravega/zookeeper-operator:0.2.2
raulgracia/pravega-grafana:latest
raulgracia/pravega-influxdb:latest
```

Pravega is deployed with external connectivity with grafana and influxdb to collect metrics.

Use benchmark or samples to send noteTime(). Use Scope1/stream1
Pravega controller logs shows the creation of _MARK stream.
Grafana dashboard shows details about _MARKstream1.

However curl call to Controller Rest end point doesn't show that info:-
$curl -X GET "http://10.240.119.245:10080/v1/scopes" -H "accept: application/json"
`{"streams":[{"scopeName":"Scope1","streamName":"stream1","scalingPolicy":{"type":"FIXED_NUM_SEGMENTS","minSegments":1}}]}`

But this curl call to get the _MARKstream1 shows the details about _MARKstream1 
$curl -x GET "http://10.240.119.245:10080/v1/scopes/Scope1/streams/_MARKstream1"
`{"scopeName":"Scope1","streamName":"_MARKstream1","scalingPolicy":{"type":"FIXED_NUM_SEGMENTS","minSegments":1}}`

**Comment by Raghuveera-Rao** [comment]
grafana screenshot attached in corresponding jira issue.

**Comment by shiveshr** [comment]
Not an issue. REST api filters all internal streams so it cannot be listed there.
