### ISSUE TITLE
High write performance overhead of Connection Pooling

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#4252]
**Problem description**
We have observed that connection pooling imposes a really high overhead to the maximum write throughput of clients, as well as important latency increase:

![comparison](https://user-images.githubusercontent.com/717112/66333020-57ad6d00-e936-11e9-83f4-8d377dca4b24.png)

We need to investigate if this problem can be mitigated.

**Problem location**
Client, connection pooling.

**Suggestions for an improvement**
Improve the performance of connection pooling (at least on the writer side).

**Comment by tkaitchuck** [comment]
This is in no way surprising. I think we should simply disable it on the append path. For all other APIs it makes sense but for append it forces small batches regardless of the optimal batch size determined by the algorithm. @fpj  Do you have any thoughts?

**Comment by RaulGracia** [comment]
@tkaitchuck disabling this for writers and not for readers would lead to an asymmetric performance situation in which readers will not be able to cope with written events?

**Comment by tkaitchuck** [comment]
@RaulGracia I don't think that should be the case. Can you measure Read throughput so we can tell if that is the case?

**Comment by RaulGracia** [comment]
@tkaitchuck should we close this issue based on #4253 or we need to keep this issue open for further investigating how to optimize the performance of connection pooling?
