### ISSUE TITLE
Watermark: _MARK streams are generated for writes without noteTime()

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4277]
_MARK streams are generated and this could be seen in controller logs(as well as in segment mounts /mnt/tier2 locations).

I tried with console writers of samples, puncher tool, benchmark tool and longevity tool.
With all these tools, _MARK stream is generated in all these.

**These tools doesn't specifically send noteTime()**

Deployment details:-
```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
raulgracia/pravega-grafana:latest
raulgracia/pravega-influxdb:latest
```
Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

I will share complete k8s logs in jira issue or in internal channel

**Comment by shiveshr** [comment]
This is by design. For all streams we create mark streams along with original stream creation.
