### ISSUE TITLE
Grafana shows 0 segment count  for _MARKS segment

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4282]
Deployment details:-
```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```

Environment details: PKS / K8 with medium cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

Used samples to generate watermark.
$curl -s -X GET 'http://10.100.200.25:10080/v1/scopes/Scope1/streams/_MARKstream1' -H 'accept: application/json'
`{"scopeName":"Scope1","streamName":"_MARKstream1","scalingPolicy":{"type":"FIXED_NUM_SEGMENTS","minSegments":1}}`

The grafana dashboard shows segment count as 0 for _MARKstream1.
Other info like read bytes, write bytes are displayed properly.

**Comment by Raghuveera-Rao** [comment]
![grafana_marks_stream](https://user-images.githubusercontent.com/48913376/66847882-c1aabf80-ef91-11e9-9c68-9df34c8524c2.jpg)

**Comment by Raghuveera-Rao** [comment]
k8s logs:

**Comment by Raghuveera-Rao** [comment]
k8s logs
[pravega-k8s-logging-2019-10-15-11-35-30.zip](https://github.com/pravega/pravega/files/3730265/pravega-k8s-logging-2019-10-15-11-35-30.zip)

**Comment by jkhalack** [comment]
This would be the case of controller metrics not being reported within 15 minutes period (see `No data points` in the `Segments` row).

**Comment by kevinhan88** [comment]
Yes this is known issue - "pravega_controller_segments_count" was only reported once when the segment was created, as a Gauge. After the TTL which is 15 minutes in Nautilus case, the Gauge object got evicted out from cache, then we'll see "No data point" on dashboard.

Refer https://github.com/pravega/pravega/issues/1761 for the background if interested.
