### ISSUE TITLE
Unique IDs for segments

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#429]
**Problem description**
Instead of referring to segments by a string name, it would be more efficient if we had an associated ID *number* generated uniquely by the controller. This way we can internally refer to segments by their unique IDs.

**Problem location**
Controller.

**Comment by andreipaduroiu** [comment]
FYI this has been done in the SegmentStore (see #1315). If there's no good reason to do this in the Controller I suggest we close this issue.
