### ISSUE TITLE
The unlimited pending events count causes OOM

### ISSUE THREAD

**Issue by akurilov** [pravega/pravega#4305]
**Problem description**
The `writeEvent` call adds all pending events into the `inflight` map. The map is not limited by size so this may cause client OOM.

**Problem location**
https://github.com/pravega/pravega/blob/43c5a16536736945cb0f862c5a920b72c6781c23/client/src/main/java/io/pravega/client/segment/impl/SegmentOutputStreamImpl.java#L110

**Suggestions for an improvement**
Experiments show that for the client application heap limit of 4GB up to several hundreds of thousands of pending events may be in flight simultaneously. So the count limit should be less than 1,000,000. For example, 100,000.

**Comment by tkaitchuck** [comment]
Existing back pressure should prevent this. This is why we don't observe the OOM in master that was introduced in the Draft PR: https://github.com/pravega/pravega/pull/4304
