### ISSUE TITLE
Functional Pravega without Tier 2

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#431]
**Problem description**
Currently, users need to install a Tier-2 storage system (for ex: HDFS) before they can install Pravega. The way Pravega currently works is highly coupled with Tier-2 interactions, which makes it impossible to run without Tier-2 even though user might have large capacity and enough number of nodes that bookie can be replicated in its Tier-1 storage layer. 

**Suggestions for an improvement**
Making Tier-2 storage optional during the installation. Users should be able to plug Tier-2 any time after they have installed their Pravega. It should be functional as long as its Tier-1 capacity allows. Or even forever if streams are temporary or customer has more than enough capacity in its Tier-1 layer.

**Comment by andreipaduroiu** [comment]
This looks related to #2022
