### ISSUE TITLE
Clarify when EventStreamReader.readNextEvent can return a null event

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega#4367]
**Problem description**
The current documentation for EventStreamReader.readNextEvent is vague on when it can return null values for the event and other fields. In fact, it may return null due to arbitrary delays in the Pravega cluster. Users may incorrectly assume that null is only returned when reading past the tail of a stream.

**Problem location**
client/src/main/java/io/pravega/client/stream/EventStreamReader.java

**Suggestions for an improvement**
Add "It is possible that null can be returned by readNextEvent().getEvent() even when the reader is not at the tail".

**Comment by twincitiesguy** [comment]
One example of when the event data is null, is when a checkpoint is emitted.  We should make note of this in the method javadoc, in the reader sample code, and the online documentation.
It would also be nice to have a documentation section that talks about how checkpoints are emitted, but perhaps that is a different issue.

**Comment by shrids** [comment]
Closing this issue based on the improvements done via PR : #4469 
ref: https://github.com/pravega/pravega/pull/4469/files#diff-3d09a7a7bdf3438b11d0cc2ca82304e9R36
