### ISSUE TITLE
Split controller thread pools to avoid potential deadlock

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4372]
**Problem description**
SegmentSelector.refreshSegmentEventWriters is invoking the controller and blocking on it in the current thread. If this code is executed on the controller this might cause a potential deadlock.

**Problem location**
Controller.

**Suggestions for an improvement**
Cherry pick this fix to r0.6. For the master it is being fixed as part of https://github.com/pravega/pravega/pull/4294

**Comment by RaulGracia** [comment]
Fixed via #4372.
