### ISSUE TITLE
Tier 1 Throttling

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4399]
**Problem description**
TBD

**Problem location**

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
Issue already fixed for Pravega 0.6 via #4405. We may want to hold on to merge #4402 if we want to test it jointly with the upgrade of Bookkeeper in PR #4394. If not, we can go ahead and merge #4402 as well.

**Comment by andreipaduroiu** [comment]
These are separate issues. Let's not tether one to the other. We should merge this one to master when we are comfortable with it (hopefully next Monday) and deal with the BK upgrade separately. I suspect there's a bit of work on that one too and I don't want to mix the two of them up.
