### ISSUE TITLE
Cherry-pick merges from master to r0.6

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#4406]
**Problem description**
 We need to cherry-pick the following merges to r0.6:

Issue 4396: For completed transactions the ping fails with DataNotFoundException (#4397)
Issue 4147: Adjust txn ping to perform multiple pings per transaction (#4400) 

**Problem location**
 Release 0.6.1

**Suggestions for an improvement**
 Backport the changes.

**Comment by RaulGracia** [comment]
Closed via #4407.
