### ISSUE TITLE
Upgrade Bookkeeper version from 4.7.3 to 4.8.0

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#4425]
**Problem description**
Upgrade the Bookeeper server from 4.7.3 to 4.8.2

**Problem location**
Bookkeeper fails with FileNotFoundException because of this issue: https://github.com/apache/bookkeeper/issues/1534

**Suggestions for an improvement**
Use closest Bookkeeper version having the fix for this issue.

**Comment by andreipaduroiu** [comment]
To be 100% clear: this change should target the `r0.6` release branch, and not `master`.

**Comment by RaulGracia** [comment]
Closed via #4522.
