### ISSUE TITLE
Consider enabling direct BK reads

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4438]
**Problem description**
Currently we read from BK only during recovery, which forces us to serve all Tier 1 reads (that haven't been moved to Tier 2) from the Cache, which ultimately causes us to throttle writes once the Cache is full and unevictable.

**Problem location**
Segment Store.

**Suggestions for an improvement**
Research the feasibility of allowing data to be evicted from the cache and read it directly from BK when needed.

**Comment by RaulGracia** [comment]
@andreipaduroiu to prevent sporadic heap OOM problems in Bookies under high loads, we have noted that using `InterleavedStorageLedger` is a good alternative. This is specially true as Pravega does not read from Bookkeeper, just for recovery. I don't know if this point and the motivation of this issue are actually conflicting, as the `InterleavedStorageLedger` may induce a penalty for reads.
