### ISSUE TITLE
PravegaTest.simpleTest is failing in docker swarm system tests

### ISSUE THREAD

**Issue by anishakj** [pravega/pravega#4458]
**Problem description**
There is a new test got added by  name `io.pravega.test.system.LargeEventTest.simpleTest` and 
we are having an existing test by name `io.pravega.test.system.PravegaTest.simpleTest`. In docker  swarm both tests will create containers with the same name. Due to that test is failing with error `container is in use`
**Problem location**
System tests

**Suggestions for an improvement**
Change the test name

**Comment by RaulGracia** [comment]
Fixed via #4462.
