### ISSUE TITLE
Retention policy is not configured for internal streams.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4476]
**Problem description**

Internal streams (`_system`) do not have a retention policy configured. This causes increased space usage on tier2 
https://github.com/pravega/pravega/blob/b8c18b2ad8118d35f950da08b4edca6314b70941/controller/src/main/java/io/pravega/controller/server/eventProcessor/ControllerEventProcessors.java#L227-L237

```
/mnt/tier2 # date
Tue Jan  7 10:13:39 UTC 2020
/mnt/tier2 # du -sh *
7.3G    _system
1.4T    flink-longevity-0
36.9G   longevity-0
```

**Problem location**
ControllerEventProcessors.

**Suggestions for an improvement**
Fix the issue.

**Comment by andreipaduroiu** [comment]
While we're at this, can we also ensure that we set the `Attributes.ROLLOVER_SIZE` on **all** segments that are created by the Controller. The value should be along these lines (and hopefully configurable):
- `4194304` (4MB) for all Table Segments. These are metadata segments and choosing a smaller value makes sense - it allows for self-compaction.
- `268435456` (256MB) for Stream Segments. This could be a different value or we could calculate it based on the Stream retention policy and observed traffic.
