### ISSUE TITLE
Controller points to old segment of MARK stream upon stream re-creation

### ISSUE THREAD

**Issue by pavanbhat21** [pravega/pravega#4478]
**Problem re-production steps**
1. Create a user stream and ingest data
2. Delete the user stream
3. Re-create the user stream with the same name.

**Problem description**
The MARK stream was deleted when the user stream was deleted
`2020-01-01 03:06:43,852 61095465 [epollEventLoopGroup-11-12] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=4741764153868288] Deleting segment WireCommands.DeleteSegment(type=DELETE_SEGMENT, requestId=4741764153868288, segment=application/_MARKapplication/0.#epoch.0)`

Upon re-creation of user stream, we can see the sequence number is 1 for the segment the segment
`$ curl -slk -u xxxx:xxxx "https://pravega-controller-api.example.com/v1/scopes/scope/streams/_MARKstream/scaling-events?from=0&to=1578473259121" | jq
[
  {
    "timestamp": 1577848408453,
    "segments": [
      {
        "number": 1,
        "epoch": 0,
        "start": 1577848408453,
        "keyStart": 0,
        "keyEnd": 1
      }
    ],
    "splits": 0,
    "merges": 0
  }
]`

The task manager of the flink application throws the below warnings:
`2020-01-01 12:30:07,991 WARN  io.pravega.client.stream.impl.ControllerImpl                  - Writer fed92934-59eb-4510-91f4-f05f9fa9d54b-1 failed to note time because: INTERNAL_ERROR time was: 33235926 position=WriterPosition(segments={application/application/1973.#epoch.474=9269250, application/application/1972.#epoch.473=19634625, application/application/1953.#epoch.460=58094250, application/application/1974.#epoch.474=9962250, application/application/1952.#epoch.460=50728500, application/application/1971.#epoch.472=24249000, application/application/1956.#epoch.463=74972250, application/application/1970.#epoch.472=20597250, application/application/1968.#epoch.471=28161000, application/application/1969.#epoch.471=23352000, application/application/1949.#epoch.458=68357625, application/application/1948.#epoch.457=50577375, application/application/1950.#epoch.458=76339125, application/application/1947.#epoch.457=59304750, application/application/1936.#epoch.449=149072250, application/application/1882.#epoch.415=310736250, application/application/1963.#epoch.468=17022750, application/application/1966.#epoch.469=18129375, application/application/1922.#epoch.441=135386625, application/application/1961.#epoch.467=52820625, application/application/1967.#epoch.470=44581875, application/application/1962.#epoch.467=52601250, application/application/1965.#epoch.469=17179500, application/application/1964.#epoch.468=22296375, application/application/1958.#epoch.465=57743250, application/application/1959.#epoch.465=57502125})`

System details:
Pravega-version **0.6.1-2419**

**Comment by shrids** [comment]
Relevant logs snippets during initial triaging.

Flink 
```
./flink-longevity-0-taskmanager-3-server.log:2020-01-08 05:11:12,279 WARN  io.pravega.client.stream.impl.ControllerImpl                  - Writer fed92934-59eb-4510-91f4-f05f9fa9d54b-0 failed to note time because: INTERNAL_ERROR time was: 607121054 position=WriterPosition(segments={flink-longevity-0/flink-longevity-0/15527.#epoch.9386=32170500, flink-longevity-0/flink-longevity-0/15526.#epoch.9386=26325375, flink-longevity-0/flink-longevity-0/15510.#epoch.9375=76733250, flink-longevity-0/flink-longevity-0/15540.#epoch.9395=15159000, flink-longevity-0/flink-longevity-0/15531.#epoch.9389=65845125, flink-longevity-0/flink-longevity-0/15530.#epoch.9388=48337125, flink-longevity-0/flink-longevity-0/15522.#epoch.9383=57308625, flink-longevity-0/flink-longevity-0/15523.#epoch.9383=66933750, flink-longevity-0/flink-longevity-0/15538.#epoch.9393=18367500, flink-longevity-0/flink-longevity-0/15533.#epoch.9390=21677625, flink-longevity-0/flink-longevity-0/15528.#epoch.9387=26487375, flink-longevity-0/flink-longevity-0/15542.#epoch.9396=10474500, flink-longevity-0/flink-longevity-0/15532.#epoch.9390=24783750, flink-longevity-0/flink-longevity-0/15529.#epoch.9387=28298625, flink-longevity-0/flink-longevity-0/15541.#epoch.9396=8710875, flink-longevity-0/flink-longevity-0/15539.#epoch.9394=15469875, flink-longevity-0/flink-longevity-0/15534.#epoch.9391=35580375, flink-longevity-0/flink-longevity-0/15537.#epoch.9393=15888750, flink-longevity-0/flink-longevity-0/15536.#epoch.9392=25097625, flink-longevity-0/flink-longevity-0/15535.#epoch.9391=32143875, flink-longevity-0/flink-longevity-0/15516.#epoch.9378=74501625, flink-longevity-0/flink-longevity-0/15519.#epoch.9380=73426875, flink-longevity-0/flink-longevity-0/15514.#epoch.9377=76497375, flink-longevity-0/flink-longevity-0/15518.#epoch.9380=78278625, flink-longevity-0/flink-longevity-0/15515.#epoch.9378=70303500, flink-longevity-0/flink-longevity-0/15513.#epoch.9377=74573250})    
```
The underlying cause from the controller logs.

```
2020-01-08 05:10:23,045 673232861 [watermarkingpool-7] WARN  i.p.c.s.bucket.PeriodicWatermarking - Exception thrown while trying to perform periodic watermark computation. Logging and ignoring.
java.util.concurrent.CompletionException: io.pravega.client.segment.impl.NoSuchSegmentException: Segment does not exist:No such segment: flink-longevity-0/_MARKflink-longevity-0/0.#epoch.0
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
```
The SSS logs for completeness
```
2020-01-08 05:10:23,043 673314656 [core-2] WARN  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=82542708719091713] Segment 'flink-longevity-0/_MARKflink-longevity-0/0.#epoch.0' does not exist and cannot perform operation 'getSegmentAttribute'.
```
