### ISSUE TITLE
Flakey test: ExtendedS3StorageTest.testParallelWriteTwoHosts

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4494]
**Problem description**
Sometimes the test fails with `StreamSegementNotExistsException`:
```
io.pravega.storage.extendeds3.ExtendedS3StorageTest > testParallelWriteTwoHosts FAILED
    java.lang.AssertionError: Write expected to complete OR throw BadOffsetException.threw an unexpected exception. Exception thrown was of unexpected type: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'foo_write'] The StreamSegment does not exist.
```
**Problem location**
ExtendedS3StorageTest

**Suggestions for an improvement**
Figure how to block on the creation of the segment.

**Comment by andreipaduroiu** [comment]
We haven't seen this since then. The introduction of SLTS has also changed all the underlying code that this is based on. If it resurfaces, we can reopen.
