### ISSUE TITLE
Pravega Metrics for logged ERRORs and WARNs

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4495]
**Problem description**
It would be nice if we could create 2 new metrics that tracked the number of errors and warning we log. This will enable us to quickly determine if we see an increase in errors (per component or overall) by looking at a metric dashboard.

**Problem location**
All components.

**Suggestions for an improvement**
This can be done in a non-invasive way using the Log4j configuration:
1. Custom appender.
    - We create a custom appender  that implements `Appender<ILoggingEvent>`
    - We override the `Appender.doAppend(ILoggingEvent)` method and intercept only those events that have `getLevel()` equal to `Level.ERROR` or `Level.WARN`.
    - We create Counters (`logged_errors` and `logged_warnings`) and increment their value accordingly. For extra accuracy, we can pass `ILoggingEvent.getLoggerName()` as a custom tag so we can filter out by component.
2. Wire up custom appender using `logback.xml`:
    - Define custom appender `<appender name="Metrics" class="path-to-custom-appender-class">`
    - Link it up. Modify `<root level="...">` by adding `<appender-ref ref="Metrics"/>`

** Example implementation**

MetricsAppender.java
```
public class MetricsAppender implements ch.qos.logback.core.Appender<ILoggingEvent> {
    private static final DynamicLogger DYNAMIC_LOGGER = MetricsProvider.getDynamicLogger();

    @Override
    public String getName() {
        return "Metrics Appender";
    }

    @Override
    public void doAppend(ILoggingEvent o) throws LogbackException {
        if (o.getLevel() == Level.ERROR) {
            DYNAMIC_LOGGER.incCounterValue("logged_errors", 1, o.getLoggerName());
        } else if (o.getLevel() == Level.WARN) {
            DYNAMIC_LOGGER.incCounterValue("logged_warnings", 1, o.getLoggerName());
        }
    }

   // Removed unimplemented methods for brevity.
}
```

logback.xml
```
<configuration scan="true">
   <!-- All other appenders defined here -->

    <appender name="Metrics" class="io.pravega.segmentstore.server.host.MetricsAppender"/>
    <root level="${log.level:-DEBUG}">
        <appender-ref ref="consoleAppender"/> <!-- Preexisting appender -->
        <appender-ref ref="Metrics"/>
    </root>
</configuration>
```

**Comment by kevinhan88** [comment]
Per the discussion it is implemented as Rate, so the description might read like this:
It would be nice if we could create 2 new metrics that track events of errors and warning...
