### ISSUE TITLE
Javadoc link does not work in Pravega.io.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4507]
**Problem description**
Observing that the hyper link to java docs for Pravega release 0.6.0 and 0.6.1 does not work 

![image](https://user-images.githubusercontent.com/11114165/72867091-bfc86900-3d03-11ea-8333-789f4d202e0b.png)

Invalid URI: http://pravega.io/docs/v0.6.1/javadoc/javadoc/clients/index.html
**Problem location**
documentation.

**Suggestions for an improvement**
Fix the issue.

**Comment by bibinss** [comment]
looks like this is fixed. I am able to get to documentation without any issues for both v0.6.1 and v0.6.0 now @shrids

**Comment by shrids** [comment]
Thanks for checking it @bibinss 👍 
Closing the issue.
