### ISSUE TITLE
Typo in Javadoc for "io.pravega.client.stream.StreamConfiguration"

### ISSUE THREAD

**Issue by bibinss** [pravega/pravega#4532]
**Problem description**
./gradlew javadocs throws a warning 

/home/travis/build/pravega/pravega/client/src/main/java/io/pravega/client/stream/StreamConfiguration.java:45: warning - Tag @link: can't find getCurrentTimeWindow() in io.pravega.client.stream.EventStreamReader
(https://travis-ci.org/pravega/pravega/jobs/642682990?utm_medium=notification&utm_source=github_status)

**Problem location**
Javadoc for io.pravega.client.stream.StreamConfiguration -> timestampAggregationTimeout

**Suggestions for an improvement**
replace {@link EventStreamReader#getCurrentTimeWindow()} with {@link EventStreamReader#getCurrentTimeWindow(Stream)}

**Comment by bibinss** [comment]
@shrids small documentation fix^^

**Comment by shrids** [comment]
Thanks @bibinss, will take a look at it ...
