### ISSUE TITLE
Can we turn on doclint on all modules since we have fixed all existing javadoc errors?

### ISSUE THREAD

**Issue by bibinss** [pravega/pravega#4556]
**Problem description**
Several modules under `pravega` have disabled doclint in the javadoc task. Since we fixed all existing javadoc errors as part of #4552 , can we enable doclint back? 
This will prevent anyone introducing (by mistake) javadoc errors in the future. 

**Problem location**
build.gradle

**Suggestions for an improvement**
remove following config from every module's javadoc task
```
failOnError = false
options.addBooleanOption("Xdoclint:none", true)```

**Comment by bibinss** [comment]
@tkaitchuck @ravisharda ^^

**Comment by ravisharda** [comment]
@bibinss it sounds like a good idea to me. Would you want to contribute a pull request incorporating that change?

**Comment by bibinss** [comment]
Sure, will raise a PR. Can you please assign this to me? Is there a way for me to add labels to the issues -- I don't see any option for it, probably a permission issue.
Also would like to see if there is any discussion group/slack channel I can be part of.

**Comment by ravisharda** [comment]
@bibinss sure, I've assigned this issue to you. 

Copying @fpj for rest of the stuff.

**Comment by bibinss** [comment]
Thanks @ravisharda, looks like someone (admin of the workspace) needs to invite me - I see the following message. My email - bibinvamattathil@gmail.com
`Don't have an account on this workspace yet?
Contact the workspace administrator for an invitation`

**Comment by ravisharda** [comment]
@bibinss sorry I gave you the wrong URL - that's only for login. You can find the self-registration icon on pravega.io, where you'll find slack `#` icon on the right-hand side.
