### ISSUE TITLE
Invalid Stream entry was updated in the controller metadata table even though the stream creation failed

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega#4564]
**Problem description**

On a failed attempt to create a stream with `26213` segments which is not practically possible in Pravega, an exception was observed from the controller end `ControllerFailureException: Failed to create stream` which is an expected behavior.
```
2020-02-18 21:22:47,160 105083 [grpc-default-executor-1] WARN  i.p.c.stream.impl.ControllerImpl - [requestId=6895740735006318360] Failed to create stream: testMaxActiveSegmentStream-26213
2020-02-18 21:22:47,161 105084 [grpc-default-executor-1] WARN  i.p.c.stream.impl.ControllerImpl - [requestId=6895740735006318360] createStream failed:
java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create stream: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, 
targetRate=0, scaleFactor=0, minNumSegments=26213), retentionPolicy=null, timestampAggregationTimeout=0)
``` 
Even though the **stream creation failed** but still the metadata table was updated with the same the stream entry in it which is technically an **invalid entry in the table**. This was seen while listing that stream through REST API call: -
```
**Request**
http://10.243.40.126/v1/scopes/testMaxActiveSegmentScope92EA5/streams/testMaxActiveSegmentStream-26213

**Response**
{"scopeName":"testMaxActiveSegmentScope92EA5","streamName":"testMaxActiveSegmentStream-26213",
"scalingPolicy":{"type":"FIXED_NUM_SEGMENTS","minSegments":26213}}
```

**Problem location**
`Pravega Controller`

**Environment Details**
```
Standard PKS NSX-T medium config cluster having 4 BK, 3 SS, 2 Cont instances and 1 ZK instance

Pravega version: 0.7.0-2481.304ddb7, 
ZK version: 0.2.5, 
Pravega Operator: 0.4.3, 
ZK Operator: 0.2.5
```

**Comment by SomeshJoshi19** [comment]
[maxactivesegmenttest-6bxfb.LOG](https://github.com/pravega/pravega/files/4229487/maxactivesegmenttest-6bxfb.LOG)

**Comment by SomeshJoshi19** [comment]
Due to size limit sharing the log location internally

**Comment by shiveshr** [comment]
This is the expected behavior. 
Any partially created stream will have metadata and should either be recreated or deleted.
