### ISSUE TITLE
Key-Value Tables: Implement Client Data Path

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4570]
**Problem description**
Implement Key Value Tables API.
Depends on #4568, #4333, #4603.

See [PDP-39](https://github.com/pravega/pravega/wiki/PDP-39-Key-Value-Tables) for details.

**Problem location**
Client.

**Suggestions for an improvement**
Implement.

**Comment by RaulGracia** [comment]
Closed via #4687.
