### ISSUE TITLE
Wake early in response to data arriving on another segment

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4578]
**Problem description**
When a reader is blocked waiting on a reply from the server it should be able to unblock and switch to another segment in the event that data arrives from the server.

This was previously implemented but it caused problems see: https://github.com/pravega/pravega/pull/4082

**Problem location**
EventStreamReaderImpl

**Suggestions for an improvement**
Add a variation on select so that we don't have to wait for the next iteration before selecting a new segment. Previously this caused problems with the CompletableFuture stack in Java 8 which had a bug. 
https://github.com/pravega/pravega/issues/4056
This form of solution should be avoided.

**Comment by shrids** [comment]
https://github.com/pravega/pravega/pull/4579 fixes this .
