### ISSUE TITLE
Allow client buffer size to be configured

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4585]
**Problem description**
Currently the client allocates 1mb buffers. This is not configurable even though the code supports it.

**Problem location**
ReaderConfig

**Suggestions for an improvement**
Add a configuration option to specify the buffer size.

**Comment by medvedevigorek** [comment]
Removing 0.7.1 label as it's nice to have enhancement which doesn't meet the bar for 0.7.1 release
