### ISSUE TITLE
Add license copy to binary artifacts on github.

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4628]
**Problem description**
The binary artifacts we are adding as part of a release on github are missing a copy of the license. We need to add it. For example, see:

https://github.com/pravega/pravega/releases/download/v0.7.0-rc1/pravega-0.7.0.tgz

The maven artifacts already refer to the Apache License 2.0, see here as an example:

https://mvnrepository.com/artifact/io.pravega/pravega-client/0.6.2

**Problem location**
Release, binary artifacts

**Suggestions for an improvement**
Change the build to Include a license copy in the artifact.

**Comment by medvedevigorek** [comment]
@fpj `NOTICE` file includes some statement related to the usage of Apache BookKeeper source code and it seems incorrect to include it as-is on Pravega Client package. Do you think we need a separate NOTICE file for Pravega Client artifacts?
