### ISSUE TITLE
Support stream retention based on positions of multiple reader groups

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4635]
**Problem description**
The scenario I'd like to support is the following. I have a stream _s_ and a set of reader groups _RG_ reading from that stream. The reader groups do not necessarily belong to the same application, and consequently it is undesirable that we force the distinct applications to coordinate, e.g., using state synchronization.

Each reader group moves at its own pace, and the overarching goal is to truncate the head of stream at position _p_ (_p_ is a stream cut) once all groups in RG have advanced their positions to _p_ or beyond _p_. Distinct groups update their positions independently.

To implement such a feature, we would need at least the following:

1- A way for each reader group to advance its position
2- A way to coordinate positions across reader groups and trigger truncation accordingly

We can optionally consider associating a time or space policy so that we give the option of truncating the head when some reader group is slow or stalled, and the head is consequently growing without bounds.

**Problem location**
It is a proposed new feature, not really a problem.

**Suggestions for an improvement**
Given that the feature involves potentially multiple reader groups, we cannot expect the reader groups individually to perform the coordination. They would need to at least share a state synchronizer, which they could setup with help from the controller or simply by naming convention.

Another option is that we rely entirely on the controller to track positions and trigger truncation.

**Comment by pbelgundi** [comment]
This has been implemented with the Consumption Based Retention feature.
