### ISSUE TITLE
Provide integration with Spring Cloud Data Flow

### ISSUE THREAD

**Issue by martingruening** [pravega/pravega#4643]
**Problem description**
Spring Cloud Data Flow is a powerful framework for 'Microservice based Streaming and Batch data processing for Cloud Foundry and Kubernetes' - https://spring.io/projects/spring-cloud-dataflow

Data Flow currently has no support for Pravega at all.

**Problem location**
Data Flow currently has no support for Pravega at all.

**Suggestions for an improvement**
Provide an integration for Pravega as 'source' and 'sink' to be build highly scalable Spring-based microservices to work with stream data in Pravega

**Comment by fpj** [comment]
That's a good suggestion, @martingruening, thank you. To clarify,  will you be able to contribute Data Flow support for Pravega or you want us to look into it?

**Comment by martingruening** [comment]
@fpj Thanks for your comment. Being only an amateur coder I believe that such a task is beyond my capabilities. But I am willing to spent time testing & providing feedback or writing documentation / blog article / sample code. I could reach out to some peers at Pivotal / VMware MAP whether they can find development support within their organisation, if you like.

**Comment by derekm** [comment]
@martingruening -- I reached out to the backlog owner of Spring Cloud Data Flow, and they don't have any extra development capacity.

I saw provided with a  few helpful hints. We could go about this two ways:

1. implement a sample app providing a reusable source/sink for Pravega
2. implement a Spring Cloud Stream binder for Pravega

Sample apps live here: https://github.com/spring-cloud-stream-app-starters

And these references would help in building such a sample app showing a Pravega integration:
https://dataflow.spring.io/docs/stream-developer-guides/
https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.3.RELEASE/reference/html/

With a binder implementation, we may not need source/sink application to ingest/egress data to/from Pravega. Users can instead leverage the named-destination support in SCDF, to directly pipe data in and out of Pravega using SCDF's DSL and UI.

See: https://dataflow.spring.io/docs/feature-guides/streams/named-destinations/

Example:

*SCDF DSL*
> stream1=:fromPravegaTopicFoo > transform | tensorflow | cassandra
> stream2=:fromPravegaTopicFoo > transform | filter > :toPravegaTopicBar 

*SCDF UI*
![SCDF Pravega pipeline](https://user-images.githubusercontent.com/379469/78073346-551c5500-7366-11ea-8ed0-b214bf035c69.png)

Both DSL/UI above represent the same streaming topologies. All the payloads in/out can come in+out from Pravega proper. `fromPravegaTopicFoo` and `toPravegaTopicBar` are Pravega topics, and users can directly plug the topic names in the source/sink positions.

**Comment by gustavomzw** [comment]
@martingruening - I am planning to work in this issue as my initial contribution to Pravega. I rewrote the getting started Pravega sample as a Binder prototype implementation to better understand the requirements for approach #2 above. The code is available [here](https://github.com/gustavomzw/pravega-binder) where you can find a README with steps to reproduce a simple test that I ran. I will follow up with @fpj and @derekm about the next steps.
