### ISSUE TITLE
Start Segment Container In Recovery Mode

### ISSUE THREAD

**Issue by naveenkothamasu** [pravega/pravega#4670]
**Problem description**
This is part of the solution for #3993. The recovery process (#[38](https://github.com/pravega/pravega-tools/issues/38)) by `dr-tool` requires creating segments with the required values for `length` and `sealed` statue in `StreamSegmentInformation`.
- Explore a way to create a segment with a pre-defined state i.e. carry `SegmentProperties` in the create path.

**Problem location**
Segment Store.

**Suggestions for an improvement**
- Add `DebugStreamSegmentContainer` implementing `DegbuStreamContainer` extending `StreamSegmentContainer`
-Expose `createSegment` API to accept the necessary params from the user.

**Comment by ManishKumarKeshri** [comment]
PR #4716 fixed it.
