### ISSUE TITLE
On demand truncation of a byte stream.

### ISSUE THREAD

**Issue by hyffrank** [pravega/pravega#4680]
**Problem description**
It is a valid case that an application needs to actively reduce the storage usage for old data in a stream that is no longer used for sure. Basically we can rely on the retention policy to do so, but the truncation triggered by retention policy is out of control from the application who consumes the stream. For example, if I need to save some data that I'd like to consume only once, after I consumed the data, it can be removed from the storage. Meanwhile I don't want to define a scope either by size or event count for retention purpose because I cannot affort to lose any data that I haven't consumed yet. 
The truncation APIs now serves as the function to explictly truncate a stream from a point described as a StreamCut. Now days we have several ways to truncate a stream on demand. 

1. Through StreamManager::truncateStream which only accepts a StreamCut.
2. Through RevisionedStreamClient::truncateToRevision if we versionize the events we read.
3. Implict truncation caused by StateSynchronizer::compact() action

Unfortunately, none of the above truncation methods fits the "ByteStream", whose design goal is to read/write a stream without any framing or demarcation of events, and it is consumed by ByteStreamReader rather than ReaderGroups since we read byte stream from one offset to another as "bytes" rather than "events". In order to truncate a byte stream we currently has to do some tricky by following:
1. Create a ReaderGroup and points the reader group to the byte stream we'd like to truncate
2. Call ReaderGroup::getStreamCuts() which is supposed to contain only one StreamCut
3. Call StreamCut::getPositions() to list position map which is supposed to contain only one Position
4. Extract the Segment object from the Position object we get from 3.
5. Construct a StreamCutImpl object by our own, put the Segment object we get from 4., along with Offset where we'd like to do the truncation.
6. Pass the StreamCutImpl object to StreamManager::truncateStream() to do the real truncation job.

This is not a convenient way we think it should be, and it exposes some inside implementations which disobeys the rule that we shall follow to communicate with Pravega using Pravega Client.

**Problem location**
Pravega Client (maybe the controller need to support such a call as well)?

**Suggestions for an improvement**
Pravega client add a truncation function based on "Offset", dedicated for "Byte Streams" which is one segment only and do not have framing/demarcation of events.

**Comment by shrids** [comment]
`io.pravega.client.segment.impl.SegmentMetadataClient` can be used to truncate a segment at a given offset.

**Comment by hyffrank** [comment]
Yes we still need to do some tricks if we want to use SegmentMetadataClient to achieve the same goal.

1. We still need to do 1~4 mentioned in the problem description, in order to get the Segment Object. 
2. We need to create a SegmentMetaDataClient by our own because the interface doesn't expose a factory method to create an instance, like other client factories do today.

For 1. I think it's better we can have something like ByteStreamReader::getSegment() to get the Segment object
For 2. We can follow the way other client factories do today, but it is not supposed to be done purely on client side.

`    static SegmentMetadataClientFactory withScope(String scope, ClientConfig config) {
        val connectionFactory = new ConnectionFactoryImpl(config);
        ControllerImpl controller = new ControllerImpl(ControllerImplConfig.builder().clientConfig(config).build(),
                           connectionFactory.getInternalExecutor());
        return new SegmentMetadataClientImpl(scope, controller, connectionFactory);
    }`

**Comment by tkaitchuck** [comment]
The client can just do the truncation directly like it does in RevisionStreamClient. I think for the bytestream api it would be reasonable to have based on an offset. 

My temptation would be to have one of two methods. On ByteStreamWriter:
`public void truncateDataBefore(long offset)`
Or on byteStreamReader
`public void truncateHere()`

Is one of these prefrable to the other.

**Comment by hyffrank** [comment]
I think putting the truncation API on ByteStreamWriter makes more sense to me.
It will also be helpful if this API could return a boolean indicating whether the truncation succeeded or not, just like what StreamManger::truncateStream returns.
