### ISSUE TITLE
znodes not getting deleted on Bookkeeper Cluster deletion

### ISSUE THREAD

**Issue by SrishT** [pravega/pravega#4688]
**Problem description**
The znodes are not deleted on Bookkeeper Cluster deletion since the `BK_LEDGERS_PATH` hasn't been updated.

**Problem location**
bookkeeper entrypoint.sh

**Comment by pbelgundi** [comment]
This is a bookkeeper operator issue and has been fixed there:
https://github.com/pravega/bookkeeper-operator/issues/25
