### ISSUE TITLE
PDP 40: Consistent order guarantees for storage flushes

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#4693]
**Problem description**
Issue to discuss PDP 40:

https://github.com/pravega/pravega/wiki/PDP-40:-Consistent-order-guarantees-for-storage-flushes

**Problem location**
Currently segments are flushed to long term storage at varying offsets and speeds which means there is no consistency guarantees for related segments. 

This PDP outlines an approach to ensure consistent order guarantees for flushing segments to tier 2 to aid disaster recovery.

The focus of this PDP is consistent order for the segments within one single container during a single flush cycle. This PDP does not cover any global (i.e cross container) order.

**Suggestions for an improvement**
Design and implement.

**Comment by fpj** [comment]
I have created a channel on our slack and posted some comments there. I can post them here too if better.

https://pravega-io.slack.com/archives/C013G7EK552

**Comment by fpj** [comment]
@sachin-j-joshi I can't remember what discussed before and the slack history seems to be gone  for this topic. I have a couple of points about this:

1- Reading the PDP, it would be great if we could list all explicitly all different types of segments we need to take into account, like a section called "Relevant segments" and list them all.
2- Is there any critical data structure that is stored exclusively in Tier 1, like some metadata or checkpoint?

**Comment by sachin-j-joshi** [comment]
Closing this outdated/stale ticket
The PDP is already discussed elsewhere and will be implemented in upcoming releases.
