### ISSUE TITLE
Improve AppendBatchSizeTracker algorithm

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4695]
**Problem description**
We have an intelligent batching algorithm that attempts to work without any configuration. It appears to work well in most cases, but does not handle very small events at high rates super effectively.

**Problem location**
AppendBatchSizeTracker

**Suggestions for an improvement**
Find a way to tune the algorithm to improve performance for small events without sacrificing it in other cases.

**Comment by RaulGracia** [comment]
Closed via #4696.
