### ISSUE TITLE
pvc-tier2 can not connected after restart

### ISSUE THREAD

**Issue by safronovD** [pravega/pravega#4742]
**Problem description**
When I restart my pravega_cluster (kubectl delete, kubectl apply), all pods start correctly, but it gives no response on curl GET.

![Screenshot_9](https://user-images.githubusercontent.com/40600792/80283439-3c624d80-8720-11ea-91bb-1f64c20635ad.png)

After I create new pvc pravega-tier2, all works.

Kubernetes state:
```
k8s@k8sp:~/k8s/pravega-operator$ kubectl get all | grep pravega
pod/example-pravega-controller-7c7475cbd4-9s8b8   1/1     Running   0          11m
pod/example-pravega-segmentstore-0                1/1     Running   0          11m
pod/example-pravega-segmentstore-1                1/1     Running   0          7m54s
pod/example-pravega-segmentstore-2                1/1     Running   0          7m40s
pod/pravega-operator-7b47777f6d-wbxtz             1/1     Running   0          27d
pod/pravega-writer-d5954f866-mrj6l                1/1     Running   0          6d21h
service/example-pravega-controller              ClusterIP   10.233.4.36     <none>        10080/TCP,9090/TCP                                                                                          11m
service/example-pravega-segmentstore-headless   ClusterIP   None            <none>        12345/TCP                                                                                                   11m
service/pravega                                 NodePort    10.233.27.115   <none>        10080:30952/TCP,9090:30768/TCP                                                                              7d3h
service/pravega-webhook-svc                     ClusterIP   10.233.29.51    <none>        443/TCP                                                                                                     27d
deployment.apps/example-pravega-controller   1/1     1            1           11m
deployment.apps/pravega-operator             1/1     1            1           27d
deployment.apps/pravega-writer               1/1     1            1           6d21h
replicaset.apps/example-pravega-controller-7c7475cbd4   1         1         1       11m
replicaset.apps/pravega-operator-7b47777f6d             1         1         1       27d
replicaset.apps/pravega-writer-d5954f866                1         1         1       6d21h
statefulset.apps/example-pravega-segmentstore   3/3     11m
```

Pravega version 0.5.0
$kubectl get pravegacluster -o yaml
[pravegacluster.yaml.txt](https://github.com/pravega/pravega/files/4533325/pravegacluster.yaml.txt)

$kubectl get pvc pravega-tier2 -o yaml
[nfs-pvc.yaml.txt](https://github.com/pravega/pravega/files/4533329/nfs-pvc.yaml.txt)

**Problem location**
Pravega-controller spams one type of error. In attached log:
[pravega-controller.log](https://github.com/pravega/pravega/files/4533335/pravega-controller.log)

**Suggestions for an improvement**
Is it planned, that I see no error while deploying?

**Comment by fpj** [comment]
hey @safronovD , thanks for reporting this issue, but could you please reopen it in the pravega/pravega-operator repo?

**Comment by safronovD** [comment]
> 
> 
> hey @safronovD , thanks for reporting this issue, but could you please reopen it in the pravega/pravega-operator repo?

Thank you. Reopened
