### ISSUE TITLE
Best practices for Integration Tests on a Java Client application

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#4782]
I am looking for some suggestion about creating integration (unit) tests for a client application written in Java.

Ideally I would like to start an in memory Standalone Pravega service.

```
 try (PravegaStandaloneForTests server = bootPravegaStandaloneForTests() {   
  String  connectionString = server.getConnectionString();
   run application that writes/reads to Pravega....
}

```

Context:
We are going to implement an integration between Pravega and [EmailSuccess.com](https://emailsuccess.com), EmailSuccess.com will be a source of data, it will write a stream of events to Pravega.
We want to create integration  tests with JUnit.

**Comment by eolivelli** [comment]
@derekm

**Comment by derekm** [comment]
@eolivelli -- There are some utility methods here for starting in-memory services:
https://github.com/pravega/pravega/blob/master/test/system/src/main/java/io/pravega/test/system/framework/Utils.java

There are other approaches taken in the `integration` module. E.g.,
https://github.com/pravega/pravega/blob/master/test/integration/src/test/java/io/pravega/test/integration/endtoendtest/AbstractEndToEndTest.java
https://github.com/pravega/pravega/blob/master/test/integration/src/test/java/io/pravega/test/integration/endtoendtest/EndToEndReaderGroupTest.java
https://github.com/pravega/pravega/blob/master/test/integration/src/test/java/io/pravega/test/integration/ByteStreamTest.java

Some JUnit `@Rule`s (aka `ExternalResource`s) for standing these things up might be a handy improvement, as there seems to be a fair bit of uniformity and copy/paste across tests.

I'll ask around and get back to you with more info.

**Comment by eolivelli** [comment]
Is that Util class usable for consumer applications?
I will check if it is deployed to Maven central.


Btw some public API would be useful.
I  will also check Flink connector test cases

**Comment by ravisharda** [comment]
@eolivelli 

Some more info on this front: 

* One can use Pravega Standalone as an embedded server like this: https://github.com/pravega/pravega/blob/ed2f71f06aa772640663becf353788570d18d9eb/standalone/src/test/java/io/pravega/local/InProcPravegaClusterTest.java#L128

* Alternatively, one can use the `ClusterWrapper` to bring up a cluster like is done for this test: https://github.com/pravega/pravega/blob/ed2f71f06aa772640663becf353788570d18d9eb/test/integration/src/test/java/io/pravega/test/integration/DelegationTokenTest.java#L66

Let us know if you need any more info.

**Comment by eolivelli** [comment]
@ravisharda @derekm thank you all.

Can you please confirm that correct Maven dependency for tests is this one ?
```
<dependency>
            <groupId>io.pravega</groupId>
            <artifactId>pravega-standalone</artifactId>
           <version>0.7.0</version>
</dependency>
```


I see that LocalPravegaEmulator#start is not "public".
But we can call it using Java reflection. We can make it public.
Once we have finished the first run of integration tests I will send a PR in order to make it public

**Comment by ravisharda** [comment]
@eolivelli  
> Can you please confirm that correct Maven dependency for tests is this one ?

Another dependency in addition to the one you mention, will be needed. Both of these are required: 
# `io.pravega:pravega-standalone:0.7.0`
# `io.pravega:pravega-shared-authplugin:0.7.0`

> I see that LocalPravegaEmulator#start is not "public".
> But we can call it using Java reflection. We can make it public.
> Once we have finished the first run of integration tests I will send a PR in order to make it public

Yes, that's an issue. We should make it public so that people can use the `LocalPravegaEmulator`. Would you consider raising a pull request for it? 
 
In the meantime, you can use the `InProcPravegaCluster` that the `LocalPravegaEmulator` uses internally. Something like this: 

```java 
 InProcPravegaCluster inProcCluster = InProcPravegaCluster.builder()
                .isInProcZK(true)
                .zkUrl("localhost:" + 2181)
                .zkPort(2181)
                .isInMemStorage(true)
                .isInProcController(true)
                .controllerCount(1)
                .enableRestServer(true)
                .restServerPort(9091)
                .controllerPorts(new int[]{9090})
                .isInProcSegmentStore(true)
                .segmentStorePorts(new int[]{6000})
                .segmentStoreCount(1)
                .containerCount(4)
                .enableTls(false)
                .enableAuth(false)
                .build();

       inProcCluster.start();
       
      // Add test logic

       inProcCluster.close();
```

cc @derekm

**Comment by eolivelli** [comment]
@ravisharda  this is my working test

https://github.com/eolivelli/pravega-testing/blob/master/src/test/java/PravegaIntegrationTest.java

This is the minimal set of dependencies:
https://github.com/eolivelli/pravega-testing/blob/master/pom.xml

Issues:
- you need to explicitly clean up netty dependencies, from the dependency tree you got several versions, with and without the '-all' suffix
- you need to explicitly add grpc

I didn't have to add pravega-shared-authplugin, maybe it is automatically imported by the java client, that you need in order to make any meaningfull test


Regarding the 'start' method I can raise a PR.
Regarding the dependencies I prefer that someone expert of the release process would do it.
It would be very good to have some integration tests that create a simple project like the one on my github.
Something that is "far" from Pravega codebase and this way we are sure that it is not affected by transitive dependencies injected by parent modules
