### ISSUE TITLE
Improvements to Pravega standalone

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4790]
**Problem description**
Pravega standalone (run with `./gradlew startStandalone`) does not provide a good experience to new users for the following reasons:

- It outputs log messages at `DEBUG` level by default and it is really a large number of messages
- It outputs several stack traces, which are false positives, but confuse new users as they don't know whether that's a problem or not
- It doesn't clearly indicate when it has started and if it has started correctly.

**Problem location**
Pravega standalone

**Suggestions for an improvement**
The main goal is to create a good experience for a new user and have the output as clean as possible. The three tasks I suggest:
- [ ]  Increase the log level or even turn off logging to stdout by default.
- [ ] Clean up spurious stack traces (false positives)
- [ ] Make sure to indicate clearly when it has started, it entails detecting that it has started and printing a clear message indicating it

**Comment by co-jo** [comment]
Can you elaborate on observed stack traces and or how to prompt them?

**Comment by derekm** [comment]
Standard output is improved for `./gradlew startStandalone`, but if you download the distribution as instructed in [the Quick Start](https://pravega.io/docs/nightly/getting-started/quick-start/) and run `./bin/pravega-standalone`, then you get the barrage of output again.

**Comment by abhinb** [comment]
@derekm   #6234  fixes the output in ./bin/pravega-standalone and the docker image
