### ISSUE TITLE
Define Wire Commands to support #4677

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4792]
**Problem description**
See #4637. 
Need to:
- Add a `expectedLength` field to `RemoveTableKeys` and `UpdateTableEntries` wire commands.
- Add wire commands for reading table entries delta.

**Problem location**
WireCommands.java

**Suggestions for an improvement**
See description.

**Comment by co-jo** [comment]
@andreipaduroiu Did you mean to reference #4677?

**Comment by RaulGracia** [comment]
Closed via #4789.
