### ISSUE TITLE
Flaky test: FileSystemIntegrationTest

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4807]
**Problem description**
Sometimes `FileSystemIntegrationTest` fails with:
```
io.pravega.segmentstore.server.host.FileSystemIntegrationTest > testEndToEnd FAILED
    java.lang.UnsupportedOperationException: fail() not supported on RedirectedReadResultEntry
```

**Problem location**
FileSystemIntegrationTest

**Suggestions for an improvement**
More debugging information needs to be added. Perhaps including the origional exception.

**Comment by andreipaduroiu** [comment]
Fixed with #5454
