### ISSUE TITLE
Use internal executor for checkpoints

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4816]
**Problem description**
The `initiateCheckpoint` call requires a background executor to check periodically the reader group state and eventually declare the checkpoint complete. Even though giving the ability to pass one is the right thing to do, applications might not care or even know how to instantiate an executor for this as we don't provide any sort of guidelines. Even if we did, it is still convenient that we have a variant of that call that uses an internal executor.

https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/stream/ReaderGroup.java#L72 

Note that this is not a bug or big issue with the client API, but an addition that makes it more convenient for applications.

**Problem location**
Reader group.

**Suggestions for an improvement**
Add a signature like:

```
CompletableFuture<Checkpoint> initiateCheckpoint(String checkpointName)
```

**Comment by ShwethaSNayak** [comment]
Add new API which except only checkpoint name and client internal thread pool executor is used to poll for the completion of the checkpoint.

Signature of new API
`CompletableFuture<Checkpoint> initiateCheckpoint(String checkpointName)`

This ensures the backward compatibility as well.

**Comment by ShwethaSNayak** [comment]
This issue is addressed by https://github.com/pravega/pravega/pull/6604 PR, so closing it.
