### ISSUE TITLE
Allow reader groups to resume from checkpoint stored in Pravega 

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4818]
**Problem description**
The Pravega reader group has the ability of producing checkpoints via the `initiateCheckpoint` call. Such checkpoints can also be generated automatically, which is the default behavior.

In the case of checkpoints initiated manually, Pravega returns a checkpoint object that the application can use to resume from in the case it needs, e.g., because of a crash.

Manual checkpoints enable applications to coordinate the checkpointing of state from source all the way to sink (e.g., see checkpointing in Apache Flink), enabling exactly-once semantics end-to-end. Some applications, however,  do not have such strict requirements and for convenience would prefer to have the latest checkpoint stored in Pravega itself and enable reader groups to resume from the latest stored checkpoint.

**Problem location**
Reader group, checkpoints

**Suggestions for an improvement**
At this point, I think the best way is to have some way in the reader group config to indicate that the application wants to start or reset a reader group.

**Comment by tkaitchuck** [comment]
This can be done today, simply by calling `readerOffline` for each reader and passing null.

**Comment by tkaitchuck** [comment]
An alternate way to do this would be to permit passing a 'null' for a config in `resetReaderGroup()` to reset the whole group without re-supplying the configuration.

**Comment by ShwethaSNayak** [comment]
This Issue has been addressed in PR https://github.com/pravega/pravega/pull/6586.
