### ISSUE TITLE
Hello Reply doesn't flush to the Channel immediately

### ISSUE THREAD

**Issue by zwx14700** [pravega/pravega#4820]
**Problem description**
When a client creates a connection to the server, it will send Hello to the server, and the server sends a Hello back either, however, the CommandEncoder doesn't flush the Hello immediately, which would make the native client block at verifying connection.
**Problem location**
CoomandEncoder.Java

**Suggestions for an improvement**
Add a FlushRequire() for the Hello

**Comment by shrids** [comment]
If a client sends a `WireCommand.Hello` with an incompatible WireCommand version then the SegmentStore closes the connection. Hence the Pravega java client does not wait for the response of `WireCommand.Hello` before sending the next requests. 
@zwx14700  With this in context IMO this enhancement is not required...

**Comment by zwx14700** [comment]
@shrids  This may be the correct scenario in Java client.  But this is not the correct way for rust client.
In rust client, after creating a client connection, connetionFactory will verify the connection by sending WireCommand.Hello to the server and wait for the reply. (It will block forever if the server doesn't flush)

I also do an experiment in rust side. I remove the logic that connectionFactory await the Hello reply, then use this connection sending another request(CreateSegment Request) to the server. The result is this connection would get two replies for this request. The first is WireCommand.Hello and second is WireCommand.SemgmentCreated.

This would make the rawClient in rust client get a Wrong reply.

**Comment by shrids** [comment]
@zwx14700 thanks for the clarification.
