### ISSUE TITLE
Differentiate between retriable and non-retriable exceptions thrown by Pravega APIs

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#4822]
**Problem description**
Pravega client retries in case of exceptions(retriable exceptions) based on the Retry configuration specified in the config, `EventWriterConfig` `ControllerImplConfig`. After all the retries are exhausted the exception is wrapped inside an `io.pravega.common.util.RetriesExhaustedException` before being thrown.

From an application/user of Pravega's perspective, it will be helpful to the users to distinguish retryable v/s non-retryable exceptions so that the applications can choose to retry over and above the retry policy provided.

**Problem location**
Exception handling

**Suggestions for an improvement**
Use a Retryable trait to distinguish the exceptions thrown.

**Comment by ravisharda** [comment]
FYI, there is another related issue (#3653) that was opened some time back.

**Comment by anju-c-das** [comment]
We could see that only a few exceptions on Client side are retriable, so it was discussed to not proceed with the change. Please find the excel with exceptions which captures retriable and Non-retriable exceptions.
[ClientExceptions_Pravega.xlsx](https://github.com/pravega/pravega/files/9680528/ClientExceptions_Pravega.xlsx)
