### ISSUE TITLE
Consolidate B+ Tree implementations in common

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4840]
**Problem description**
According to the conversation in this thread, we should look into opportunities to consolidate the B+ Tree implementations in common:

https://github.com/pravega/pravega/pull/4763/files/e23c68e3087386a7ba7090d86218ad916e2dabac#r432435393 

Note that they are not completely redundant as they are different data structures and make different assumptions about storage.

**Problem location**
Multiple implementations of B+ Tree data structures

**Suggestions for an improvement**
This is an exploratory task, and the goal is to determine whether there is some common logic that can be shared to avoid duplication.

**Comment by andreipaduroiu** [comment]
No longer applicable.
