### ISSUE TITLE
Cross language routing keys

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4864]
**Problem description**
Today routing keys are hashed using the Java's in memory utf-16 representation. This is fast but makes it difficult to interoperate with other languages. If two languages encode the string differently then clients which are writing to the same stream that are in different languages will route the same routing key to different segments.

For most applications that is not a problem, but it may become a problem should the need arise to have part of the application in another language.

**Problem location**
`HashHelper.hashToRange` uses `hashUnencodedChars` instead of `hashString`

**Suggestions for an improvement**
We could add a config flag on a per-stream basis as to which encoding to use. This is not without problems though, because often streams are created via the web-ui and its not clear at that time which language or version of the client will use them.

**Comment by ravisharda** [comment]
Would it make sense to take `byte[]` as a routing key?

**Comment by andreipaduroiu** [comment]
Taking `byte[]` as routing key would help make things more consistent as we can write a platform-independent hashing algorithm. 

However we'd still have a few issues to resolve:
- Upgrade/backwards compatibility.
- Converting from String to byte[]. I am not sure about the origins of the routing key (i.e., why did we choose a String over a `byte[]` or `ByteBuffer`) but users may still use Strings for RKs, which means we wouldn't solve much by having to convert it to a byte array.

**Comment by tkaitchuck** [comment]
Yes. Changing a public api to take a `byte[]` rather than a string would break all existing writer code. This is highly undesirable. We could add a new API to take a byte array for a routing key, and allow both, but it doesn't really help because I suspect most users would prefer strings, as that is more natural for most programs.

**Comment by eolivelli** [comment]
Apart from the public API change, that is needed anyway but we can deal with it somehow.
 I think that the better approach would be to use generics (java.lang.Object under the hood) and let the user configure an hash function.
This approach will help in saving memory copies in case you already have an Object as a key and you have a pre computed hash value (like lava.lang.String caches its hashCode)

**Comment by eolivelli** [comment]
byte[] is not good for instance if you already have your key in a ByteBuf coming from the network.
This can be very frequent.
We should not force the client to create copies into the head

**Comment by ravisharda** [comment]
I agree with @eolivelli that a generic object would be highly flexible. That'll require a key serializer to be provided by the client application as well. IMO, we could add this new API method and make the existing String-based method to use this new method internally. That way we wouldn't break existing clients.

**Comment by tkaitchuck** [comment]
The Rust client has adopted the Java standard for routing keys.
