### ISSUE TITLE
Speed up hashCode for byte buffers in SegmentStore

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4887]
Yes this is only for in-memory equality and hashes. So any improvement would be welcome and we wouldn't have to worry about backwards compatibility.

_Originally posted by @andreipaduroiu in https://github.com/pravega/pravega/pull/4842/threads/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkNDQxMTgzMzMz/resolve_

**Comment by RaulGracia** [comment]
Closed via #6842.
