### ISSUE TITLE
Does pravege plan to design  streamsql like KSQL for Kafka?

### ISSUE THREAD

**Issue by dawsongzhao** [pravega/pravega#4894]
**Problem description**
Does pravege plan to design  streamsql like KSQL for Kafka?
**Problem location**

**Suggestions for an improvement**

**Comment by derekm** [comment]
@dawsongzhao -- For now, you can grab https://github.com/pravega/flink-connectors and use Flink SQL.

@crazyzhou is the maintainer of the `flink-connectors` library. Our Flink connectors will be donated to Flink & ASF around the time of Flink 1.11.

Community members are welcome to report their successes integrating with Druid, Pinot, Presto, etc. We will also be doing more work in this area, and we will announce our progress as we are able to.

Maybe we can keep this issue open until we have some reliable HOWTOs in this area.

Some follow-ups to @RaulGracia's recent [Pravega on K8s blog post](http://blog.pravega.io/2020/06/20/deploying-pravega-in-kubernetes/) could show, for example, setting up Flink SQL.

**Comment by RaulGracia** [comment]
There is also a Pravega sample using FlinkSQL: https://github.com/pravega/pravega-samples/tree/master/scenarios/pravega-flink-connector-sql-samples

**Comment by RaulGracia** [comment]
The question has been answered, if more info is needed please re-open.
