### ISSUE TITLE
Lombok obfuscates Javadocs, @Data classes don't document methods

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#4919]
**Problem description**
Some Javadocs are devoid of class method information due to use of Lombok `@Data` annotation.

**Problem location**
http://pravega.io/docs/v0.7.1/javadoc/clients/io/pravega/client/admin/StreamInfo.html
vs.
https://github.com/pravega/pravega/blob/v0.7.1/client/src/main/java/io/pravega/client/admin/StreamInfo.java

**Suggestions for an improvement**
I'm not sure... Lombok `@Data` annotation is very helpful for generating boilerplate code that doesn't necessarily need to be reified in the source itself. I don't know if there's a general solution here, but there ought to be. I've seen this same problem with Swagger & auto-generating OpenAPI specs off of JAX-RS resources, where Swagger can't lift the Javadocs off of annotated methods for inclusion in the OpenAPI spec. In this case, Lombok can't lift the Javadoc off of wrapped member variables and stage the generated source for use by the Javadoc generator.

**Comment by eolivelli** [comment]
Is there any open issue on Lombok ?

**Comment by derekm** [comment]
> Is there any open issue on Lombok ?

There's a comment here about lifting Javadocs from wrapped member variables on the generated getters & setters: https://projectlombok.org/features/GetterSetter

**Comment by derekm** [comment]
@eolivelli -- I looks like the solution is integrating Javadoc with delombok: https://projectlombok.org/features/all#running-delombok

**Comment by eolivelli** [comment]
We are already using Delombok

**Comment by medvedevigorek** [comment]
We use Delombok in `javadoc` task of each project however when it comes to generate a distribution version of javadoc it uses the source code as-is hence it doesn't include generated methods.  The javadoc distribution is later published on pravega.io.
