### ISSUE TITLE
Javadoc warnings

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#4932]
**Problem description**
Our javadoc build currently generates a number of warnings. These should be fixed to avoid both problems in display as well as noise during the build process.

**Problem location**
Javadocs

**Suggestions for an improvement**
Correct the problems pointed to in the warning messages.

**Comment by medvedevigorek** [comment]
@tkaitchuck, would it be the same as #3373?

**Comment by tkaitchuck** [comment]
@medvedevigorek yes.
