### ISSUE TITLE
Basic Password Auth Handler should allow wildcard declarations at more than 1 level depth

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#4934]
**Problem description**
Currently Basic Password Auth Handler only allows wildcard declarations at 1 level depth. This is reasonable for pravega currently as the scope/* is fine. But if we start supporting more finer grained control on pravega streams or KVT like scope/stream/* vs scope/stream/update etc then this becomes a problem as the second level wild card is not supported for basic auth. 

**Problem location**
BasicAuthHandler.java

**Suggestions for an improvement**
Fix the issue.

**Comment by ravisharda** [comment]
The recent changes in the Password Auth Handler enable it to support wildcard declarations at any level, so this issue can now be resolved. 

https://github.com/pravega/pravega/blob/2e70f876c5eaeaf0ed51504174c5e6b13f0645a1/controller/src/main/java/io/pravega/controller/server/security/auth/handler/impl/AclAuthorizerImpl.java#L18
