### ISSUE TITLE
DR - Ability to migrate segment metadata to a new deployment when data is fully flushed to LTS.

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#4938]
**Problem description**
Pravega administrator should be able to migrate data from existing Pravega deployment to a new Pravega deployment when all segments in existing deployments are fully flushed to LTS. 

**Problem location**
Segment store
Admin tool

**Suggestions for an improvement**
Implement/Enhance DebugSegmentStore that enumerates segments on existing LTS and populates the metadata in new deployment.

**Comment by ManishKumarKeshri** [comment]
Though PR #4716 fixed it, but in that PR:
- We delete the old segment metadata from the LTS and create a new one using the segments(except shadow segments) listed from the LTS. While registering the segments onto new segment metadata, we only use segment's length and sealed status.

We now need to:
- Copy the core attributes from old metadata to new metadata.
