### ISSUE TITLE
TxnFailedException not RuntimeException on transaction aborts

### ISSUE THREAD

**Issue by ravibeta** [pravega/pravega#4940]
**Problem description**
The TransactionalEventStreamWriter throws both TxnFailedExceptions and RuntimeExceptions. The latter is used in a mixed manner where the former is exclusively defined for the purpose of the TransactionalEventStreamWriter. This puts the client in a dilemma when using syntax like the following:
        Retry.withExpBackoff(DELAY, MULTIPLIER, ATTEMPTS, MAXDELAY)
             .retryingOn(TxnFailedException.class)
             .throwingOn(RuntimeException.class)
             .run(() -> {stateHelper.afterWrite(); return true;});
because it has to be selectively thrown on a case by case basis. 

**Problem location**
The problem occurs in 
client/src/main/java/io/pravega/client/stream/TransactionalEventStreamWriter.java
client/src/main/java/io/pravega/client/stream/impl/TransactionalEventStreamWriterImpl.java

**Suggestions for an improvement**

This is very similar in nature to Issue 3003 that tries to unify logging for transaction writers while this is unifying exceptions. Other than that similarity, these are two different issues.

**Comment by shrids** [comment]
The current exception handling mechanism by the client API is as follows

- `TxnFailedException`:  This exception is thrown only when the Transaction is no longer in state {@link Status#OPEN}. For example, it is thrown when the application tries to `commit()`/`abort()` and an already closed transaction. This also implies it is wasteful for the application to retry this operation.

-  The client attempts to handle other connectivity related errors with the retry mechanism configured by `io.pravega.client.stream.EventWriterConfig`. Once all the retries have failed it throws a `RetriesExhaustedException `which is of type RuntimeException.

Ravi, with the above in context,  could you describe your issue further?
