### ISSUE TITLE
ListKeyValueTables API on Controller makes an additional recursive call when filteredKVTables<limit

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#4961]
**Problem description**
ListKeyValueTablesInScope API on Controller, recursively looks for KeyValueTables inside the given scope as long as number of KVTables fetched is < limit. Once KeyValueTable names are available, we check the user authorization and filter KeyValueTables this user is authorized to read and return a list of only those.

**Problem location**
https://github.com/pravega/pravega/blob/388a91d3235e8ef5b4e996c7da6f50d953460968/controller/src/main/java/io/pravega/controller/server/rpc/grpc/v1/ControllerServiceImpl.java#L905

**Suggestions for an improvement**
If there are elements that are filtered, only then should we make the recursive call.
So the if condition should be:
```
if (filteredKVTList.size() < response.getKey().size()) 
```

**Comment by shiveshr** [comment]
duplicate of https://github.com/pravega/pravega/issues/4956 which includes issues in listKVT and listStreams
