### ISSUE TITLE
Simplified-LTS : Add separate initialize method to ChunkStorage

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#4968]
**Problem description**
Currently ChunkStorage initialization needs to be done in constructor.
This is inconvenient when initialization  is non-trivial or time consuming.
In addition the error handling becomes complicated when exceptions are thrown in constructor.

**Problem location**
ChunkStorage.

**Suggestions for an improvement**
Add separate initialize method to ChunkStorage to allow non trivial initialization outside of constructor and call it on newly constructed ChunkStorage object .

**Comment by eolivelli** [comment]
Cool. That's what I requested

**Comment by sachin-j-joshi** [comment]
The initialization can be done in a factory method itself.

``` java
@RequiredArgsConstructor
public class FancyStorageFactory implements SimpleStorageFactory {
      ........
      public Storage createStorageAdapter(int containerId, ChunkMetadataStore metadataStore) { 
           val myFancyStorage = new FancyStorage();
           myFancyStorage.init(this.config); // You can do complicated or long running initialization here.

         return new ChunkedSegmentStorage(containerId,
                        myFancyStorage ,
                        metadataStore,
                        this.executor,
                        this.chunkedSegmentStorageConfig);
      }
}
```

**Comment by sachin-j-joshi** [comment]
Closing this as initialization can be done in a factory method itself and therefore the separate initialize  method is not required.
