### ISSUE TITLE
Pravega-0.7.1.tgz contains a  .config.properties.swp file

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#4980]
**Problem description**
When you download pravega-0.7.1.tgz from github and untar it you can find it a file named conf/.config.properties.swp 

https://github.com/pravega/pravega/releases/tag/v0.7.1

**Problem location**
Release tarball

**Suggestions for an improvement**
Remove the file, check the package script in order to make it sure that released packages are built automatically

**Workaround**
delete the file manually before installing Pravega

**Comment by ravisharda** [comment]
The swap file was removed in PR #4630 , fyi.

**Comment by eolivelli** [comment]
so the problem won't be present in 0.8.0.
works for me, thanks @ravisharda
