### ISSUE TITLE
PDP-34 Add a way to register a custom ChunkStorage implementation

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#4993]
**Problem description**
With PDP-34 is it easier to implement the LTS storage.
But it not actually possible to plug a custom implementation.

This issue tracks there request to be able to run a custom LTS storage, implemented as ChunkStorage.
We also need to have a way to start LocalPravegaEmulator with such a custom configuration, in order to allow simple integration tests. 

**Problem location**
SegmentStore

**Suggestions for an improvement**
After PDP-34 lands, or during the implementation of PDP34, remove StorageType enum, and create a way to configure a custom tier2.

Check https://github.com/eolivelli/pravega-blobit-chunkkmanager as an example of possible implementation of ChunkStorage using https://github.com/diennea/blobit a Storage Engine that stores data on Bookies.

**Comment by derekm** [comment]
PDP-42 as in #4907 deals with this.

**Comment by sachin-j-joshi** [comment]
Fixing it here https://github.com/pravega/pravega/pull/6231/

**Comment by sachin-j-joshi** [comment]
closed via following PR- 
Issue 6223: SLTS - Enable loading third party storages. #6231
