### ISSUE TITLE
The streamManager API should have a way to delete a scope that contains streams in any state

### ISSUE THREAD

**Issue by sarlaccpit** [pravega/pravega#5002]
**Problem description**

In practical uses of the streamManager api, we are able to create scopes, streams, list streams, delete streams, seal streams etc.  A given scope can at any time contain any number of streams, in different states.  Sealed, not sealed, some maybe stuck in creating state.  The scope can also contain reader groups, materialized as internal streams that can't normally be directly deleted. 

When the caller needs to delete the scope, it has become difficult to sort out the correct order and logic in which to clean up the scope to prepare for final deletion.  

**Problem location**

streamManager GRPC api.

**Suggestions for an improvement**

Provide a flag to the _deleteScope_ call which allows for a "force" or "purge" action which tells Pravega to do the needful to prepare the scope for deletion, then delete it.

Likely the correct default is for that flag to be assumed as false, which is backward compatible and safe.  (fail the deletion of the scope by default if it contains streams)

For reference, this is an example of code that callers needs to do today to delete a scope.  Note that the code below contains a flaw, outlined after the sample:

```
        try {
            List<Stream> userStreams = new ArrayList<>();
            List<Stream> readerGroupStreams = new ArrayList<>();
            Iterator<Stream> it = streamManager.listStreams(instance.getScopeName());
            if (it != null) {
                it.forEachRemaining((stream) -> {
                    if (streamIsUserStream(stream)) {
                        userStreams.add(stream);
                    } else if (streamIsReaderGroup(stream)) {
                        readerGroupStreams.add(stream);
                    } else {
                        LOG.info("Found unknown internal stream {}", stream.getStreamName());
                    }
                });
            }
            // Delete all the ReaderGroup first.
            ReaderGroupManager readerGroupManager = ReaderGroupManager.withScope(instance.getScopeName(), PravegaAutoConfiguration.controllerURI);
            for (Stream s : readerGroupStreams) {
                LOG.info("Deleting reader group {}", readerGroupNameFromStream(s));
                readerGroupManager.deleteReaderGroup(readerGroupNameFromStream(s));
            }
            readerGroupManager.close();
            // Then delete all the user streams.
            for (Stream s : userStreams) {
                LOG.info("Deleting stream {}", s.getStreamName());
                streamManager.sealStream(instance.getScopeName(), s.getStreamName());
                streamManager.deleteStream(instance.getScopeName(), s.getStreamName());
            }
            LOG.info("Deleting scope {}", instance.getScopeName());
            streamManager.deleteScope(instance.getScopeName());

```

The flaw in the code above is if there is a stream that was stuck in creating state somehow, it cannot be sealed.  So the _sealStream_ call throws an exception, does not get to be deleted and fails the overall _deleteScope_ operation.

It's just one nuance that the caller needs to know, an example of the type of internal complexity that would probably be best encapsulated in _deleteScope_ itself

**Comment by crazyzhou** [comment]
This is also a good supplement with the Catalog implementation in Pravega Flink connector for schema registry integration. In Flink catalog of the connector, we map the `scope` as database and the `stream` as table in a relational database.

Flink offers this API: https://github.com/apache/flink/blob/master/flink-table/flink-table-common/src/main/java/org/apache/flink/table/catalog/Catalog.java#L180 for us to implement which has a `cascade` boolean flag to determine whether to clean up the streams.

With this issue resolved, it can bring much convenience and code tidyness.
