### ISSUE TITLE
PDP-34 - SLTS : Deadlock in BaseMetadataStore 

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#5003]
**Problem description**
After about 5 minutes of run, we hit the deadlock where BaseMetadataStore.get call on key results in a table segment reads which in turn cause the re-entry into BaseMetadataStore.get and waits on the same lock. That essentially locks two thread in a deadlock.
This problem is made worse by clients retrying the same requests again and again and that basically exhausts thread pool.
ReaderWriter lock should be used here.

**Problem location**
BaseMetadataStore.get should use reader lock.

**Suggestions for an improvement**
Short term convert lock into reader/writer lock. Use reader lock for get .

**Comment by andreipaduroiu** [comment]
`ReaderWriterLock` has poorer performance than `synchronized`. It should be avoided.

**Comment by derekm** [comment]
I've seen `./gradlew check` test suite runs deadlock and hang for an hour or more after these tests:

>2020-07-29T20:00:17.8885954Z io.pravega.segmentstore.server.store.StreamSegmentServiceNoOpWriteReadTests > testEndToEnd PASSED
>2020-07-29T21:10:37.6869987Z ##[error]The operation was canceled.

>2020-07-30T20:14:02.0676883Z io.pravega.test.integration.StreamSeekTest > testStreamSeek PASSED
>2020-07-31T01:26:29.5475327Z ##[error]The operation was canceled.

>2020-07-30T16:06:05.3933340Z io.pravega.test.integration.StreamSeekTest > testStreamSeek PASSED
>2020-07-30T21:18:42.5429099Z ##[error]The operation was canceled.

From the timestamps, you can see how long the subsequent test hung for before I cancelled the job.

I'm unsure if this is related, but it is worth looking into. These builds occurred in a constrained environment where the likelihood of deadlocks could be increased.

**Comment by sachin-j-joshi** [comment]
Closing as this is fixed by following

- Issue 5067: (SLTS) - Convert synchronous ChunkStorage and ChunkMetadataStore API into async #5200 
- Issue 5260: (SegmentStore) Adjustable Operation Priority Levels #5268
