### ISSUE TITLE
Create test scope jars for Pravega Client mocks

### ISSUE THREAD

**Issue by spiegela** [pravega/pravega#503]
**Problem description**
When developing applications that use the Pravega client, it is cumbersome to create a running Pravega service for all client related tests.

**Problem location**
`build.gradle`: [link](https://github.com/emccode/pravega/blob/master/build.gradle)

**Suggestions for an improvement**
It would be very nice to have access to the existing client mock classes in an external project.  These source sets are exported _between_ pravega projects, but not to external artifacts. A test scope jar for the client is an idiomatic way to provide these to users.

The following mock classes would be nice:
* `MockClientFactory`
* `MockConnectionFactoryImpl`
* `MockController`
* `MockSegmentIoStreams`
* `MockSegmentStreamFactory`
* `MockStreamManager`

**Comment by Prabha-Veerubhotla** [comment]
Closing this, as it is no more a requirement.
