### ISSUE TITLE
PDP 42: New Resource String Format for Authorization

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#5035]
**Problem description**
Discuss [PDP 42: New Resource String Format for Authorization](https://github.com/pravega/pravega/wiki/PDP-42:-New-Resource-String-Format-for-Authorization)

**Problem location**
See the [PDP](https://github.com/pravega/pravega/wiki/PDP-42:-New-Resource-String-Format-for-Authorization).

**Suggestions for an improvement**

**Comment by fpj** [comment]
It looks really good, @ravisharda , thanks for putting this together. A few questions and comments:

1- Does it need to be hierarchical? For example, could I use:

```
prn::/scope:myscope/stream:mystream
```

and

```
prn::/stream:mystream/scope:myscope
```

I understand that for Pravega it matters, but as far as resource declaration goes, it conveys the same information.

2- Can I use the wildcard `*` anywhere, like can I do this `*::*` or even use only `*` to represent everything in the system?

3- I'm not sure about the use of the backslash, perhaps we could stick only to colons like:

```
prn::stream:mystream::scope:myscope
```

but I don't know, maybe that's less clear and I don't have a strong opinion about that.

**Comment by ravisharda** [comment]
> 1- Does it need to be hierarchical? For example, could I use:
> 
> ```
> prn::/scope:myscope/stream:mystream
> ```
> 
> and
> 
> ```
> prn::/stream:mystream/scope:myscope
> ```
> 
> I understand that for Pravega it matters, but as far as resource declaration goes, it conveys the same information.

From an auth handler perspective, the hierarchical representation makes it easier to process the string during authorization (using regex, for instance). Also, it makes it easier to support positional wildcards like these:
* `prn::/*` - All resources under the root resource)
* `prn::/scope:abc/*` - All resources that are children of scope, such as streams, reader groups, key-value tables, etc. 

While Pravega shall be using a fixed format, ACLs may be specified in any format that the Auth Handler implementation supports.  So, if a new auth handler plugin supports non-hierarchical format and can authorize a resource `prn::/scope:myscope/stream:mystream` using an ACL defined using its own custom format, it is up to it.

**Comment by ravisharda** [comment]
> 2- Can I use the wildcard `*` anywhere, like can I do this `*::*` or even use only `*` to represent everything in the system?
> 

@fpj Yes, it could be anywhere in the ACL definitions of the built-in Password Auth Handler). A few examples: 

* `prn::*`  - All resources
* `prn::/scope:*` - All scopes
* `prn::/scope:myscope/*` - All direct and indirect child objects of the scope `myscope`, like reader groups, ke-value tables, streams, etc., and their children as well. 
* `prn::/scope:myscope/stream:*` - All streams of the scope `myscope` and any child objects of the streams. 
* `prn::/scope:*/stream:mystream` - A stream with name `mystream` in any scope.

**Comment by ravisharda** [comment]
> 3- I'm not sure about the use of the backslash, perhaps we could stick only to colons like:
>
> prn::stream:mystream::scope:myscope

Initially, I did consider the [URN format](https://tools.ietf.org/html/rfc8141) for resource representation, which uses `:` for delimiting the different parts. The format you mention is slightly different from the URN syntax in that it also uses the character `::`.

There are a few nice things we get from the proposed format which includes the character `/`:
* In Pravega, we have a notion of a `root` resource. To be able to create scopes, a user needs write permission on the root resource. Using `/` makes it more intuitive than something like `root`. 
* The `/` is also used to represent hierarchical relationship. I feel it is visually more appealing to distinguish levels via `/` than `::`. 
* Overloading the meaning of the characters `::` and `:` would make the format less intuitive. The suggested format keeps things simple: 
   * `::` for distinguishing the domain/namespace part from the resource-id. 
   * `:` for resource type tag names
   * `/` for levels

So, I believe the proposed format is better from a usability standpoint (apart from processing simplicity). What do you say?

**Comment by ravisharda** [comment]
@eolivelli @shiveshr could you please review the PDP too?

**Comment by sarlaccpit** [comment]
https://github.com/pravega/pravega/wiki/PDP-42:-New-Resource-String-Format-for-Authorization, in its current scope and contents looks good to me.

There are related concepts which i think will be discussed in a separate follow up PDP ( like permissions on reader groups in context of a read only experience, or general practicality of assigning ACLs on "things that don't exist yet" etc.) but PDP-42 on its own looks good to me.
