### ISSUE TITLE
Make dt_socket port configurable in Pravega standalone

### ISSUE THREAD

**Issue by crazyzhou** [pravega/pravega#5042]
**Problem description**
Some users may have application running on `8000` port and they may experience this exception when running pravega standalone.
```
$ ./bin/pravega-standalone
ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [:735]
```
It is because now the dt_socket port is hard coded as `8000` in this line: https://github.com/pravega/pravega/blob/fcc04a8aa092077fb771eb185db2fdaa3e80ef46/build.gradle#L694
It could be better if we can make it configurable so that users can find out this port easier.
 
**Problem location**
`build.gradle`

**Suggestions for an improvement**
Put it in the `config/standalone-config.properties` if possible, so users can see all the used ports in this one configuration file.

**Comment by ravisharda** [comment]
As a workaround, the debug port may be changed by modifying the `DEFAULT_JVM_OPTS` options in the `pravega-standalone` script. For example, in Windows, the `pravega\standalone\build\install\pravega-standalone\bin\pravega-standalone.bat` file contains the following line where the default port `8000` is specified. It can be modified to the desired value. 

```
set DEFAULT_JVM_OPTS="-server" "-Xmx4g" "-XX:+HeapDumpOnOutOfMemoryError" "-Dlogback.configurationFile=%~dp0../conf/logback.xml" "-Dsinglenode.configurationFile=%~dp0../conf/standalone-config.properties" "-Dlog.dir=%~dp0../logs" "-Dlog.name=pravega" "-Xdebug" "-Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n"
```

Also, `config/standalone-config.properties` is not the right place for storing this config, as that file contains application-level configurations, i.e., those that are used by Pravega components themselves. The debug address is really a JVM property. A system property may be a more suitable mechanism. So, in the rare scenario that you need to change the debug property, you'd specify it using like this: 

```
./gradlew startStandalone -DdebugPort=8999
./pravega-standalone -D debugPort=8999
```
