### ISSUE TITLE
How to read a specific date‘s data, says to read data belongs to 2020-08-08 in pravega?

### ISSUE THREAD

**Issue by bjwanghua** [pravega/pravega#5057]
After reading the documents, I have a prolem.
How to read specific date‘s data, says to read data belongs to 2020-08-08? Is there any examples?

**Comment by derekm** [comment]
@bjwanghua — Pravega doesn’t yet keep a time index like Kafka does.

**Comment by bjwanghua** [comment]
@derekm Thanks for your answer. Is there any methods to meet such demand currently?
