### ISSUE TITLE
Return appendSetup on sealed segment.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#5062]
**Problem description**
On the line:
https://github.com/pravega/pravega/blob/master/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java#L160
If the segment is sealed the catch block here:
https://github.com/pravega/pravega/blob/master/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/AppendProcessor.java#L171
will result in a `SegmentIsSealed` reply being sent. 
This means that the client won't be able to resolve the status of which messages were processed or not from before it's disconnection. 

**Problem location**
`AppendProcessor.setupAppend`

**Suggestions for an improvement**
Instead the catch block for `StreamSegmentSealedException` should call:
```
store.getAttributes(newSegment, Collections.singleton(writer), false, TIMEOUT)
```
and then use the result to return an `AppendSetup` similar to the happy path today.

**Comment by ravibeta** [comment]
Yes Tom
