### ISSUE TITLE
Java 11 Migration - Compile using JDK11.

### ISSUE THREAD

**Issue by co-jo** [pravega/pravega#5082]
**Problem description**

Currently the Pravega project is built upon JDK8. Upgrading to JDK11 will provide various new APIs and tools to benefit the project. Enumerating and updating to use these new features is out of scope for this issue. The one caveat is that in order to continue support for _Flink 1.8_ , we must compile the `client` project and it's dependencies using JDK8.

**Problem location**

Largely `gradle.build`.

**Suggestions for an improvement**

* Default the project builds to use `JavaVersion.VERSION_11`.
* Supply a `--release 8` flag in the `compilerArgs` for the `client`.
  * Do the same for it's dependencies.

**Comment by derekm** [comment]
I have an example Actions CI workflow in PR 4988 that compiles with Java 11 (but doesn't touch the gradle support mentioned here): https://github.com/pravega/pravega/pull/4988
