### ISSUE TITLE
Implement Consumption Based Retention on Controller for Streams with CBR policy

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5111]
**Problem description**
Implement CBR on Controller for Streams with CBR policy.

**Problem location**
Controller

**Suggestions for an improvement**
This includes the following:
1. Code for truncating Streams with CBR.
2. Code for generating common truncation Stream-Cut from all RG truncation Stream-Cuts.

**Comment by eolivelli** [comment]
Can you please add the long form of CBR? This way the issue will be more clearer for users that comes here

**Comment by pbelgundi** [comment]
CBR = Consumption Based Retention
