### ISSUE TITLE
Client API to Create Subscriber reader groups

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5112]
**Problem description**
Client side changes for storing Reader Groups on Controller.

**Problem location**
Client

**Suggestions for an improvement**
Make controller calls to create, delete and update the `ReaderGroup on Controller when user invokes create, reset, delete RG on Client.
Keep Reader Group Configuration in State Synchronizer updated with the version on Controller

**Comment by anirudhkovuru** [comment]
**Problem description**
Changes to the client API to allow for the creation, deletion and modification of subscriber `ReaderGroup`s. 

**Problem location** 
Client

**Suggestions for an improvement** 
Make controller calls to create. delete and update `ReaderGroup`s and keep track of a `generation` in the `ReaderGroupState` to ensure consistent subscription/unsubscription of the streams.
