### ISSUE TITLE
(R0.8) Cherry-pick #5120

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#5131]
**Problem description**
Cherry pick https://github.com/pravega/pravega/pull/5120 into 0.8
**Problem location**
https://github.com/pravega/pravega/pull/5120

**Suggestions for an improvement**
Cherry pick https://github.com/pravega/pravega/pull/5120 into 0.8

**How to verify it**
Build must pass.

**Comment by RaulGracia** [comment]
Closed via #5134.
