### ISSUE TITLE
Estimate the number of threads needed to run a controller instance

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#515]
**Problem description**
It is unclear how many threads a controller instance will be actively running. With some of the upcoming pull requests, like the event processor work, an estimate of how many threads will be actively running in a controller instance and how much load they will impose is badly needed. Such an estimate is also important so that we can communicate to users how to provision their deployments.

**Problem location**
Controller.

**Comment by bhargav-gulavani** [comment]
Superseded by #1387
