### ISSUE TITLE
Stream-Cuts get saved as "Checkpoints" in Reader Group State

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5203]
**Problem description**
Stream-Cuts can be generated on a Stream by invoking the _generateStreamCut()_ API on a ReaderGroup.
Internally the mechanism used to generate a Stream-Cut as same as the mechanism for generating a checkpoint. 
However, a "Stream-Cut" is conceptually a different thing from a checkpoint.
Stream-Cuts generated by _generateStreamCut()_ API should be returned to the user and there is no need to store them as a checkpoint in the RGState
This is what happens internally today as we don't distinguish between Stream-Cuts and Checkpoints.
This would interfere with the use of checkpoints for truncation when implementing Consumption Based Retention on Client.

**Problem location**
Client Code:
https://github.com/pravega/pravega/blob/6acd317344424bbc92c3f870d394f68d93ce1085/client/src/main/java/io/pravega/client/stream/impl/ReaderGroupImpl.java#L373
https://github.com/pravega/pravega/blob/e3d71202d057be75fbcca27cbef1963195626d60/client/src/main/java/io/pravega/client/stream/impl/CheckpointState.java
https://github.com/pravega/pravega/blob/ca0cbdd6622eaebfc309e03cea489a563880bcba/client/src/main/java/io/pravega/client/stream/impl/EventStreamReaderImpl.java#L258

**Suggestions for an improvement**
Stream-Cut generation should not have any impact on Checkpoint generation and generated Stream-Cuts should not be stored as checkpoints in RGState.

**Comment by tkaitchuck** [comment]
I am not clear what the actual problem here is. Stream cuts need to coordinate across all of the readers to gather their current position in the exact same way as a checkpoint. In fact a checkpoint is a type of stream cut. So what is the benefit of duplicating the code to do this?

**Comment by pbelgundi** [comment]
@tkaitchuck the problem is with **storing** the StreamCut as a checkpoint in the lastCheckpointedPosition.
And that is what we're aiming to fix.
This is necessary for implementing CBR correctly which requires publishing every completed checkpoint (and not streamcut) to Controller as a truncation point.
