### ISSUE TITLE
System exception ControllerFailureException is on a different  package on Pravega 0.8.0rc1

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#5210]
**Problem description**
While testing Pravega 0.8.0rc1 I found that ControllerFailureException has been moved from 
`io.pravega.client.stream.impl.ControllerFailureException`
to
`io.pravega.client.control.impl.ControllerFailureException`

This exception is a RuntimeException and the user does not have any way to catch the problem without depending directly on this class.

This exception is throws for instance when you run "deleteScope" and the Controller is not available.

Example of integration tests that tries to clean up the env before the execution
```
        try {
            streamManager.deleteScope(SCOPE);
        } catch (ControllerFailureException okTheStreamWasNotThere) {                  
        }
        streamManager.createScope(SCOPE);

```
**Suggestions for an improvement**
Create a new base exception  in the "admin" package io.pravega.client.admin.GenericControllerFailureException and make every Controller related exception depend on it.

**Comment by ravisharda** [comment]
From @derekm (in a thread from Slack): 
> We are talking about other breaking changes for 0.9, so perhaps we could save these breakages for then. For example, JavaSerializer and UTF8StringSerializer are in impl packages, but they are meant for re-use in client applications and deserve Javadocs, etc.
