### ISSUE TITLE
JVM args for Pravega server

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#522]
**Problem description**
To prevent handling errors we cannot deal with we should make sure the JVM dies when OOM or other Errors occur.

**Problem location**
Startup script

**Suggestions for an improvement**
http://www.oracle.com/technetwork/java/javase/clopts-139448.html#gbmum
We can use the JVM flags for OnError and OnOutOfMemoryError to kill the pid of the process.

**Comment by mganbold** [comment]
Hello, I am new to open source and I would like to contribute to this project. I saw the exp/beginner tag and was wondering if it was doable for first timers as well. Please let me know. Thank you.

**Comment by tkaitchuck** [comment]
> I saw the exp/beginner tag and was wondering if it was doable for first timers as well. 

Yes, that it the intention of the tag. If you want to take a crack at this, take a look at places where JVM args are being specified, and figure out a way to add the relevant parameters. Once you have a version with that locally, feel free to submit a pull request and assign it to me.

**Comment by andreipaduroiu** [comment]
Resolved with pr #1839.
