### ISSUE TITLE
Cannot read remaining bytes from a sealed segment.

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega#5247]
**Problem description**
This error happens when using ByteStreamReader in Rust client to read from a sealed segment. 

Details: 
1) The sealed segment has for example 100 bytes and reader wants to read 200 bytes. It is expected that the segmentstore returns 100 bytes, but instead segmentstore returns a `SegmentIsSealed` wirecommand. So it's not possible to read the remaining bytes from a sealed segment unless we know the length of remaining bytes.

2) Furthermore, if the remaining bytes are less than 8 in a sealed segment, we are not able to read those bytes because segmentstore will always issue a request to read at least 8 bytes from the container. This is because the `Event` in event stream has an 8 bytes header, but this is not the case for byte stream. 

**Problem location**
The first point is probably related to this [line](https://github.com/pravega/pravega/blob/2a5ea0e05f2fe04d9f40bdbb4d354c98b19ce861/segmentstore/server/src/main/java/io/pravega/segmentstore/server/reading/StreamSegmentReadIndex.java#L893).

The second point is from [here](https://github.com/pravega/pravega/blob/055494a2e2dabfb649e5b7e3c9c4f586dd18940e/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/handler/PravegaRequestProcessor.java#L196).

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
The "first point" should not cause the described behavior. It is checking if the start offset is beyond the end of the segment.

**Comment by Tristan1900** [comment]
closing this as the problem is acutally in Rust client.
