### ISSUE TITLE
the google group link is unavailable

### ISSUE THREAD

**Issue by lecssmi** [pravega/pravega#5266]
the google group link in http://pravega.io/  is unavailable. Any other mail list ?

**Comment by fpj** [comment]
hi @schahaha , that hasn't really been active, our slack (pravega-io.slack.com) is a lot more active. is it ok with you to join there?

**Comment by derekm** [comment]
@lecssmi -- I removed the google group links from the website while adding the CNCF footer: https://github.com/pravega/www.pravega.io/commit/659e96a4cd3bbaba7c1fafc051ca37f77e31b1bc#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051

As a CNCF project, we should be getting a users mailing list there soon.

I'll update this issue when the new users mailing list is available.

**Comment by derekm** [comment]
@lecssmi,

Our users mailing list is now up: https://lists.cncf.io/g/cncf-pravega-users

Feel free to join!

**Comment by zipzit** [comment]
Question for folks.  Is the slack group (pravega-io.slack.com) by invitation only?  I'm absolutely unable to login there.  

Based on the jan 14 comment above and my comment here, the information at https://pravega.io/docs/nightly/join-community/  is woefully inadequate.  Possible to get webpage updated to functional reality?   Many thanks..
