### ISSUE TITLE
Wiki Incompatibility With Windows

### ISSUE THREAD

**Issue by co-jo** [pravega/pravega#5288]
**Problem description**

Github names the `.md` files based on the title of the document. Most Wiki pages contain characters (colon)  in their title, which are invalid on the native Windows FS [1]. This prevents Windows users from successfully checking out and making changes to the Wiki on a Windows machine.

[1] https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Problem location**

`https://github.com/pravega/pravega.wiki.git`

**Suggestions for an improvement**

Remove the colon for the titles.

### Note

I have already made the required changes on the Wiki (https://github.com/co-jo/pravega/wiki) in my fork: `https://github.com/co-jo/pravega.wiki.git`. I have also make other improvements:

* Made all references to other pages in the Wiki relative, instead of absolute (I.E A wiki page in your fork will point to the corresponding page in your fork, instead of back to the upstream `pravega/pravega` wiki.)
* Removes all invalid characters from titles.
* Applies proper titlecase formatting to each of the PDPs (and their Sidebar references).

**Comment by co-jo** [comment]
Related Work: https://github.com/pravega/pravega/issues/5122

**Comment by derekm** [comment]
This was fixed July 12th when I merged @co-jo's wiki branch.

E.g., https://github.com/pravega/pravega/wiki/PDP-19:-Pravega-retention
vs.
https://github.com/pravega/pravega/wiki/PDP-19-%28Pravega-Retention%29
