### ISSUE TITLE
ADD ARM64 support to Pravega

### ISSUE THREAD

**Issue by odidev** [pravega/pravega#5297]
**Problem description**

Hi Team,

I am interested in adding ARM64 support to Pravega and ARM64 jobs in Travis-CI.

Travis-CI link in the Readme.md shows that the build takes around 1 hr 20 mins to complete. However, free travis jobs have a minimum time limit of 50 mins, hence my build terminates without completion after 50 mins, and I am unable to use Travis utility to build pravega.
I have tried building pravega locally on Ubuntu: Xenial x86_64 system with JDK set to openjdk11, following below commands:
~~~
$ ./gradlew assemble
$ ./gradlew check
~~~ 
**./gradlew assemble** completed successfully, but **./gradlew check** failed over executing some  BookKeeper test cases. Brief errored logs are below:
~~~
io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testOpenCloseClient FAILED
    io.pravega.segmentstore.storage.DataLogNotAvailableException: Unable to establish connection to ZooKeeper or BookKeeper.

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testEnableDisable FAILED
    java.util.concurrent.CompletionException: java.util.concurrent.CancellationException: BookKeeperLog has been closed.

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testAppendSequence FAILED
    java.util.concurrent.CompletionException: io.pravega.common.util.RetriesExhaustedException: io.pravega.segmentstore.storage.WriteFailureException: Active Ledger is closed.

io.pravega.segmentstore.storage.impl.bookkeeper.BookKeeperLogTests$RegularBookKeeperLogTests > testExclusiveWriteLock FAILED
    io.pravega.segmentstore.storage.DurableDataLogException: Unable to open-fence ledger 203.

> Task :segmentstore:storage:impl:test FAILED
> Task :segmentstore:storage:impl:jacocoTestReport

~~~

For adding ARM64 support to pravega, I have made the below changes to the source code:

_1. Updated “protoc-gen-grpc-java” version to 1.26.0 (aarch64 support has been added  to this package from 1.26.0 onwards)
2. Added dependency “com.google.code.gson:gson” with version ‘2.8.6’ to build.gradle file, in <project('controller')> and <project('cli:user')>
3. Removed -Werror flag from java options.
4. Updated nettyVersion to 4.1.51.Final.
5. Updated ‘protobufProtocVersion’ to ‘4.0.0-rc-2’.
6. Changed classifier to ‘aarch64’ for “netty-transport-native-epoll” dependency in project('client') in build.gradle file.
7. Changed value of arch to arm64 in pravega/test/system/aws/slave_script.sh and pravega/test/system/aws/master_script.sh files, and set JAVA_HOME accordingly.
8. Set JAVA_HOME to ‘/usr/lib/jvm/java-8-openjdk-arm64’ in pravega/deployment/aws/installer/entry_point_template.yml and pravega/deployment/aws/aws.tf files._

And then ran above commands for the build. 
**./gradlew assemble** completed successfully, but **./gradlew check** failed over executing test cases below:
~~~
io.pravega.segmentstore.server.tables.WriterTableProcessorTests > testFlushCompactions FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds

> Task :segmentstore:server:test FAILED
> Task :segmentstore:server:jacocoTestReport

~~~

If you are interested, I am happy to contribute.

Can you please provide me with some pointers that can help me to move further with pravega build on both x86_64 and ARM64 platforms?

**Problem location**
N/A

**Suggestions for an improvement**
N/A

**Comment by odidev** [comment]
Can you please suggest to me, on the above issues? 
Also, can you please tell if you are interested in accepting the PR to add Linux/ARM64 jobs to the Travis-CI?

**Comment by derekm** [comment]
@odidev -- Sorry I missed your issue and comment previously! I recently undertook a similar effort: #5748 && #5747 -- and encountered probably the same or similar issues.

It looks like Netty code in Pravega needs to be updated for us to do some of these upgrades.

**Comment by derekm** [comment]
@odidev -- Regarding CI, we have moved to GitHub Actions CI. This says ARM is only supported via self-hosted runners: https://github.community/t/does-github-actions-cloud-allow-running-of-arm-based-instances/119319

Travis-CI has shut down their unlimited free accounts, and we quickly exhaust the limits of their new free accounts.

We have some cluster resources available through the CNCF that we use for other builds, I'll see if ARM is an option there.

**Comment by derekm** [comment]
@odidev -- See PR #5747 for dependency upgrades that should enable a working Pravega on aarch64.

**Comment by derekm** [comment]
@odidev -- PR #5747 has been merged to master. Master branch and 0.10 SNAPSHOTs now support ARM64.
