### ISSUE TITLE
Event processor processing should fail on specific exceptions while retrying on all other exceptions.

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#5313]
**Problem description**
Event processor workflows are designed to retry indefinitely on handled or retryable exceptions. However, we have observed certain situations where exceptions not marked with retryable can also be potentially retryable. Example: there was a segment store bug that was causing incorrect bytes being sent back for read key requests but it was sporadic and caused by a race condition. And upon retrying, the system would perform correctly. 
So we should invert the retry logic and retry on all exceptions and fail on specific failure cases as failure cases are known. 

**Problem location**
Event processor workflows

**Suggestions for an improvement**
Retry workflows on all exceptions and fail on specific failure conditions.

**Comment by pbelgundi** [comment]
This issue is not relevant any more.
