### ISSUE TITLE
DR integration test does not work with FileSystem Storage

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#5325]
**Problem description**
When Debug segment container starts and creates it's own metadata segments, they were immediately flushed to the storage. When segments are listed with list segments iterator for recovery, the partially flushed metadata segments of debug segment containers would show up, which caused issues with segment iteration (like missing offset) & recovery(like metadata segment not found).

**Problem location**
`DebugStreamSegmentContainerTests.java`
`RestoreBackUpDataRecoveryTest.java`

**Suggestions for an improvement**
Doesn't let segments created while running the recovery to be flushed to the storage. After all segments have been recovered, then let them to be flushed.

**Comment by derekm** [comment]
Was this fixed with the corresponding merge, @ManishKumarKeshri? (Just looking to clean up flakeyTest issues a bit.)

**Comment by ManishKumarKeshri** [comment]
> Was this fixed with the corresponding merge, @ManishKumarKeshri? (Just looking to clean up flakeyTest issues a bit.)

Yes. But I wasn't related to flakey test issues.
