### ISSUE TITLE
Optimize metadata operations in Controller's StreamMetadataStore

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#5358]
**Problem description**
Controller's StreamMetadata store exposes apis whose implementation either retrieves the data from the cache or makes a call to table store. And we cache the immutable records. 
For an operation, like a user query or a workflow for instance, that may make multiple calls into the store, could end up fetching the same metadata from the table more than once. This is suboptimal and can be optimized by keeping reference of already retrieved objects in the OperationContext and only retrieve it from the store or cache if its absent in the operation context. 

**Problem location**
StreamMetadataStore

**Suggestions for an improvement**
Implement the suggested improvement.

**Comment by RaulGracia** [comment]
Closed via #5883.
