### ISSUE TITLE
Upgrade Bookkeeper to last stable version (4.11.1)

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#5385]
**Problem description**
We need to upgrade the Bookkeeper version in Pravega as the current one (4.9.2) is EOL and new versions contain important fixes for Pravega.

**Problem location**
Bookkeeper docker file (and maybe other files).

**Suggestions for an improvement**
Upgrade Bookkeeper version.

**Comment by eolivelli** [comment]
@RaulGracia if you do have prepared the patch yet I am happy to send it

**Comment by RaulGracia** [comment]
Thanks a lot @eolivelli, actually I started to explore this upgrade in this branch: https://github.com/RaulGracia/pravega/tree/issue-5385-upgrade-bk-version
I expected this to be a simple change, but there is some issue apparently related to a Bookkeeper file called `bin/coomon.sh` to start testing that this actually works. All feedback is welcome!

**Comment by eolivelli** [comment]
can you create a draft PR ?
