### ISSUE TITLE
Java 11+ is oracle jdk or open jdk

### ISSUE THREAD

**Issue by tonyC2016** [pravega/pravega#5450]
**Problem description**

**Problem location**

**Suggestions for an improvement**

**Comment by ravisharda** [comment]
The runtime environment could be either of them. In the code, we use OpenJDK wherever JDK is referenced - for example: https://github.com/pravega/pravega/blob/77b13981a3a63260344f530a7786080320168e00/docker/pravega/Dockerfile#L10.

**Comment by tonyC2016** [comment]
> The runtime environment could be either of them. In the code, we use OpenJDK wherever JDK is referenced - for example:
> 
> https://github.com/pravega/pravega/blob/77b13981a3a63260344f530a7786080320168e00/docker/pravega/Dockerfile#L10
> 
> .

is it possible to change the jdk version back to 1.8, coz my runtime envirinment is jdk 8
