### ISSUE TITLE
how to unstand the as data in Tier 1 Storage ages, it is automatically moved into Tier 2 Storage

### ISSUE THREAD

**Issue by tonyC2016** [pravega/pravega#5453]
**Problem description**
Storage tiering allows Pravega to achieve a sweet spot in the latency vs throughput trade-off. This makes Pravega an ideal storage substrate for serving data to both real-time and batch (analytics) applications. **Moreover, as data in Tier 1 Storage ages, it is automatically moved into Tier 2 Storage.** Thus, Pravega can store vasts amounts of Stream data and applications can read it at any time, while being oblivious to its actual location.

**### how to unstand the as data in Tier 1 Storage ages, it is automatically moved into Tier 2 Storage**

**Problem location**

**Suggestions for an improvement**

**Comment by tonyC2016** [comment]
yes its a question ,can u explan how it works?

**Comment by fpj** [comment]
Hi @tonyC2016, thanks for reaching out and asking about tiering in Pravega, and apologies for the delay, we are all still catching up after the end of yer break. Let me try to give you some information and pointers.

The segment store is the component that handles appends to stream segments. It initially writes to a durable log (the first tier), currently implemented with Apache BookKeeper, and asynchronously writes data to long-term storage (the second tier). When appending new data, the segment store writes the data additionally to its cache, and it eventually reads from this cache to write the data to long-term storage. The procedure to write to long-term storage can be controlled with segment store configuration parameters that we expose in this region of the configuration file:

https://github.com/pravega/pravega/blob/master/config/config.properties#L600

There is also a good amount of detailed information about how it works here:

https://pravega.io/docs/latest/segment-store-service/#storage-writer

It might also be relevant, but a bit more advanced, that we have worked on a re-implementation of long-term storage and the design document is here:

https://github.com/pravega/pravega/wiki/PDP-34:-Simplified-Tier-2

Let me know whether it helps, and if not, then please follow up.
