### ISSUE TITLE
Seemingly unnecessary doGetStreamSegmentInfo call during read path in ExtendedS3Storage

### ISSUE THREAD

**Issue by adrdc** [pravega/pravega#5475]
**Problem description**
Pravega cluster with S3 compatible tier 2 storage (ECS).  Noticed when reading stream data from tier 2 that there was roughly 1 get object metadata api call +1 get acl call per data read.  

Our test query ends up reading approx 75GB from tier 2.  tier 2 is test VM ECS deployment.
test run results in:
1. 138879 read requests to ECS, total processing time on ECS 1492337ms
2. 138083 requests for get metadata + get acl (each), total processing time on ECS 538872ms

So it seems to add non-trivial amount of overhead.

Traced it to ExtendedS3Storage#doGetStreamSegmentInfo.  Noticed that the return value of doGetStreamSegmentInfo was ignored.

**Problem location**
ExtendedS3Storage#doOpenRead

**Suggestions for an improvement**
It appears like the call to doGetStreamSegmentInfo could simply be removed.
I commented it out for a test and total run time of our test app decreased by about 30% or so.

**Comment by sachin-j-joshi** [comment]
I'm not sure this is an issue.
Current contract for Storage class says that ExtendedS3Storage#doOpenRead should throw an exception when object does not exist. That is the reason why doGetStreamSegmentInfo is done.

openRead is called the first time we have open a segment for read.
After that this handle is cached and reused, and rarely "evicted" during run time. So even if there can be multiple Read calls, the openRead is not called every time.

**Comment by sachin-j-joshi** [comment]
However we can definitely try to eliminate this check.

**Comment by adrdc** [comment]
thanks a lot @sachin-j-joshi !
i see from contract of openRead that it should return object not found.  
(if there it is purely a test of 'stream exists', might only need to call 1 of getObjectMetadata / getObjectAcl instead of both)

agree with you there though, it would be good if were able to read directly first if possible

**Comment by adrdc** [comment]
>> _After that this handle is cached and reused, and rarely "evicted" during run time. So even if there can be multiple Read calls, the openRead is not called every time._

i'm curious about this comment, though.  we saw roughly 1 getObjectMetadata and 1 getObjectAcl call per data read from ECS. 
and at least in RollingStorage#read there is an openRead to get a new handle that directly precedes every read.  based on your comment, is that the issue then?

**Comment by sachin-j-joshi** [comment]
yes. This is an issue with RollingStorage. 
However we are refactoring  LTS design and as such RollingStorage will eventually become deprecated. 
We are actively working on SLTS and is marked experimental in 0.9 https://github.com/pravega/pravega/wiki/PDP-34:-Simplified-Tier-2
I have fixed it there https://github.com/sachin-j-joshi/pravega/commit/1a5c98d72f057efe4b93c30ffe3f449a8ea72310 because SLTS has a different contract and still under development/experimental
