### ISSUE TITLE
Validate znode names according to ZK data model 

### ISSUE THREAD

**Issue by Abhijeet-Jadhav** [pravega/pravega#549]
**Problem description**
We need to validate znode names before creating one in ZK according to ZK data model: https://zookeeper.apache.org/doc/r3.2.2/zookeeperProgrammers.html#ch_zkDataModel

Also, what names are allowed for scope and stream, the length restrictions can also be validated.

**Problem location**
If we create a scope or stream with name "abc/def" it creates two nodes with 'def' as children of 'abc' i.e /abc/def/

**Suggestions for an improvement**
Helper method to validate name before creating a znode in zookeeper.

**Comment by fpj** [comment]
Our current naming convention does not allow backslashes in the naming, see:

https://github.com/pravega/pravega/blob/679c7b7c35dd112977815de5abebc6e077ecc044/shared/protocol/src/main/java/io/pravega/shared/NameUtils.java#L49
