### ISSUE TITLE
unknown os.arch: riscv

### ISSUE THREAD

**Issue by advancedwebdeveloper** [pravega/pravega#5504]
Hello.

I was trying to build Pravega on SiFive's board.
Here is what I got:

> $ git clone https://github.com/pravega/pravega.git
> Cloning into 'pravega'...
> remote: Enumerating objects: 105038, done.
> remote: Total 105038 (delta 0), reused 0 (delta 0), pack-reused 105038
> Receiving objects: 100% (105038/105038), 37.33 MiB | 3.35 MiB/s, done.
> Resolving deltas: 100% (44313/44313), done.
> cd pravega
> Updating files: 100% (2148/2148), done.
> $ $ ls
> CODE_OF_CONDUCT.md    build.gradle   deployment		lombok.config
> HEADER		      checkstyle     dist		segmentstore
> LICENSE		      cli	     docker		settings.gradle
> NOTICE		      client	     documentation	shared
> PravegaGroup.json     common	     gradle		standalone
> README.md	      common_server  gradle.properties	test
> aws-key-pair.pem.enc  config	     gradlew
> bindings	      controller     gradlew.bat
> $ ./gradlew distribution
> Downloading https://services.gradle.org/distributions/gradle-6.5.1-bin.zip
> .................................................................................................
> Unzipping /home/ivan/.gradle/wrapper/dists/gradle-6.5.1-bin/1m5048aptkfynhbvolwgr4ej9/gradle-6.5.1-bin.zip to /home/ivan/.gradle/wrapper/dists/gradle-6.5.1-bin/1m5048aptkfynhbvolwgr4ej9
> Set executable permissions for: /home/ivan/.gradle/wrapper/dists/gradle-6.5.1-bin/1m5048aptkfynhbvolwgr4ej9/gradle-6.5.1/bin/gradle
> 
> Welcome to Gradle 6.5.1!
> 
> Here are the highlights of this release:
>  - Experimental file-system watching
>  - Improved version ordering
>  - New samples
> 
> For more details see https://docs.gradle.org/6.5.1/release-notes.html
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Configure project :
> Build JVM Version is : 11.0.8 (Eclipse OpenJ9 master-dc7cbe4bd)
> 
> 
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':shared:controller-api'.
> > unknown os.arch: riscv
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 54m 28s
> 

I used

> $ javac -version && java -version
> javac 11.0.8
> openjdk version "11.0.8" 2020-07-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10-202007292333)
> Eclipse OpenJ9 VM AdoptOpenJDK (build master-dc7cbe4bd, JRE 11 Linux riscv-64-Bit Compressed References 20200729_78 (JIT disabled, AOT disabled)
> OpenJ9   - dc7cbe4bd
> OMR      - 1c0299f20
> JCL      - 94b9d6d2c6 based on jdk-11.0.8+10)

on

> $ uname -a
> Linux test-gdams-debian10-riscv64-1.adoptopenjdk.net 5.0.0-rc1-56210-g0a657e0d72f0 #1 SMP Fri May 15 18:05:26 EDT 2020 riscv64 GNU/Linux

> $ cat /proc/cpuinfo
> processor	: 0
> hart		: 1
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0
> 
> processor	: 1
> hart		: 2
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0
> 
> processor	: 2
> hart		: 3
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0
> 
> processor	: 3
> hart		: 4
> isa		: rv64imafdc
> mmu		: sv39
> uarch		: sifive,rocket0

**Comment by derekm** [comment]
@advancedwebdeveloper -- Hi, Ivan!

Thanks for checking out Pravega! I'd like to help you succeed in running Pravega on your SiFive!

I believe you're running into an issue with `netty-tcnative-boringssl-static` where `os.arch` becomes a classifier for which jar artifact with native code to download. See, for example, the list of filenames here: https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.35.Final/ ... there's an aarch_64 jar, but no riscv jar.

I don't find a lot of advice on building netty-tcnative-boringssl-static for other architectures. This issue may need to be brought upstream to Netty and BoringSSL. We could start by opening an additional issue here: https://github.com/netty/netty-tcnative/issues

I've also pinged some folks on our security team to come triage this issue in case there are other workarounds to get you moving forward.

Thanks!

**Comment by advancedwebdeveloper** [comment]
> @advancedwebdeveloper -- Hi, Ivan!
> 
> Thanks for checking out Pravega!
OK.

> I'd like to help you succeed in running Pravega on your SiFive!
I never claimed that it is mine - I am remotely operating, under an ordinary Linux user account, on @gdams 's board.

> I believe you're running into an issue with `netty-tcnative-boringssl-static` where `os.arch` becomes a classifier for which jar artifact with native code to download.
Yes, it looks like building an rv64gc build of a JNI library would be required.
> See, for example, the list of filenames here: https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.35.Final/ ... there's an aarch_64 jar, but no riscv jar.
Then you would have to share one in your repo, until it would be adopted by Netty's maintainers.
 
> I don't find a lot of advice on building netty-tcnative-boringssl-static for other architectures.
It is only required to have 2 different architectures, for the buiolding process, to compare. I could work on RISC-V build.
> This issue may need to be brought upstream to Netty and 
You can open issue for Netty's maintainers, from Pravega's side, as an end-user.
I could join you, for the JNI related stuff.
> BoringSSL
It is a must to use some SIMD, hard encryption capabilities of the board (check the ISA). That is a matter of a separate discussion, for BoringSSL.

> We could start by opening an additional issue here: https://github.com/netty/netty-tcnative/issues
Go ahead - and reference me, when you would compose the issues. I will mention that and would join the discussion.
> 

> I've also pinged some folks on our security team to come triage this issue in case there are other workarounds to get you moving forward.
Consider investigating https://github.com/riscv/riscv-crypto

Does Dell have any cooperation with SiFive?

**Comment by derekm** [comment]
I see. Yes, some way would be needed to either get upstream to build a riscv static jar or else replace the boringssl stuff in Pravega's build with something else. I'm not aware of any cooperation.

I've heard there has been discussion about getting Pravega to use system SSL libs instead of statically-compiled libs, so that security fixes to the SSL impl can be achieved by upgrading containers instead of rebuilding Pravega. Getting the build to use system libs may also address your issue.

If you are wanting to run clients on riscv, the Pravega server could be external to the riscv board.
