### ISSUE TITLE
Adding support for reading sensitive information from a file instead of reading them from environment variables

### ISSUE THREAD

**Issue by SrishT** [pravega/pravega#5525]
**Problem description**
The credentials for influxdb are currently included as plain text within the options section of the pravega manifest, which poses a significant security risk. The [following](https://github.com/pravega/pravega-operator/issues/280) issue in the pravega operator aims at accepting the name of the secret from the user and mounting its contents to a file. This issue is in order to read the influxdb credentials from the file `influxdb-secret` that has been mounted to the path `(/etc/secret-volume)`, read database credentials from the secret, then create 
- `controller.metrics.influxDB.connect.credentials.username` and `ccontroller.metrics.influxDB.connect.credentials.pwd` options for the controller 
- `metrics.influxDB.connect.credentials.username` and `metrics.influxDB.connect.credentials.pwd` options for the segmentstore

**Problem location**
On the controller and segmentstore

**Suggestions for an improvement**
In order to maintain backward compatibility, we need the current approach of reading the influxdb creadentials from the `JAVA_OPTS` environment variable to remain, while giving precedence to reading the credentials from the above mentioned file if it exists.

**Comment by jkhalack** [comment]
I'm not sure I understand why the need for a separate secret for influxdb (or any metrics) credentials.
Would it not be possible for pravega-operator to mount the `JAVA_OPTS` env variable from a secret instead of a configmap?

**Comment by anishakj** [comment]
> I'm not sure I understand why the need for a separate secret for influxdb (or any metrics) credentials.
> Would it not be possible for pravega-operator to mount the `JAVA_OPTS` env variable from a secret instead of a configmap?

In that case, user has to create a secret containing all the  java  options before installing pravega

**Comment by jkhalack** [comment]
> > I'm not sure I understand why the need for a separate secret for influxdb (or any metrics) credentials.
> > Would it not be possible for pravega-operator to mount the `JAVA_OPTS` env variable from a secret instead of a configmap?
> 
> In that case, user has to create a secret containing all the java options before installing pravega

My thought was that the operator would be able to create a new secret, combining user-supplied values together with the information from influxdb secret.
