### ISSUE TITLE
Setup JFrog snapshot publish in GitHub Actions

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5538]
**Problem description**
We need the `snapshot` stage that is triggered **only** on master branch push builds (not on pull requests) that will publish to JFrog.

See `.travis.yml` (`snapshot` section).

**Problem location**
GitHub/workflows.

**Suggestions for an improvement**
1. Get login credentials from JFrog for Pravega (DO NOT PUBLISH THEM ANYWHERE ON GITHUB).
2. Register them as secrets in the GitHub Pravega org (need a user name and a key)
3. Modify/create a GHA workflow that mimics the `snapshot` stage in `.travis.yml`.
3.1. This needs to be triggered on any push to `master` or to any release branch (see the regex in `.travis.yml`).

See this for how secret env vars are handled in Travis: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables

See this for how secret env vars are handled in GHA: https://docs.github.com/en/actions/reference/encrypted-secrets

**Comment by derekm** [comment]
@andreipaduroiu -- @fpj has created `BINTRAY_USER` and `BINTRAY_KEY` org-level GitHub Secrets for us.
