### ISSUE TITLE
Test Consumption based Stream Retention with Single Subscriber

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5554]
**Problem description**
_This test verifies that:_
1. Reads of Non-Subscriber Reader Groups do not impact Stream Truncation.
2. Reads of Subscriber Reader Groups impact Stream truncation only when a truncation stream-cut is published to Controller.
3. When truncation stream-cuts are **not** published, stream truncation happens based on min/max limits set in the retention policy.
4. When truncation stream-cuts **are** published by a Subscriber Reader Group, Stream truncation happens based on these stream-cuts.

_Test Steps:_
1. Create a Stream with SPACE based retention policy with min/max limits.
2. Set Controller retention cycle interval to be 1 minute.
3. Create a Non-Subscriber Reader Groups to read data from this Stream. 
4. Create a writer that writes more data to the Stream than the max limit.
5. Non-Subscriber RG starts reading data from the Stream.
6. Verify - After 1 minute, Stream gets truncated at max limit.
7. Create a new Subscriber Reader Group to read from the same Stream and set its RetentionType=MANUAL_RELEASE_AT_USER_STREAMCUT and enable automatic checkpointing.
8. Write more then max_limit data into the Stream and wait for 1 minute.
9. Stream should get truncated at the Stream-Cut that satisfies the max_limit for the Stream's Retention Policy, since we haven't yet published any truncation Stream-Cut.
10. On the Subscriber Reader Group create a new checkpoint using initiateCheckpoint() API
11. Publish this checkpoint as the truncation point for the Stream using updateRetentionStreamCut() API on this ReaderGroup
12. Verify that when the retention cycle runs, the Stream is truncated at this point.
13. Change Subscriber ReaderGroup configuration to RetentionType=AUTOMATIC_RELEASE_AT_LAST_CHECKPOINT.
14. Verify that when the retention cycle runs, the Stream does get truncated at the last-checkpoint stream-cut of the Subscriber ReaderGroup. Note that this will happen only if the published truncation Stream-Cut falls between `min` and `max` space limits set for the Stream. So Stream should be written to accordingly.

**Problem location**
System Tests

**Suggestions for an improvement**
Create a new Test Class ConsumptionBasedRetentionTest

**Comment by anirudhkovuru** [comment]
[Pseudocode for the test.](https://github.com/pravega/pravega/files/5884845/5554.txt)
