### ISSUE TITLE
Test Consumption based Retention with multiple Reader Groups

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5559]
**Problem description**
Test Consumption based Retention with multiple Reader Groups, few Subscribers and few non-subscribers.
This test should verify that :
1. The truncation stream-cut for the Stream is computed using Stream-Cuts published by all subscribers.
2. The Stream is truncated at the common truncation stream-cut.
3. When common truncation stream-cut is below "min", truncation happens at "min"
4. When common truncation stream-cut is above "max" truncation happens at "max"

**Problem location**
System Test

**Suggestions for an improvement**

**Comment by anirudhkovuru** [comment]
[Pseudocode for the test.](https://github.com/pravega/pravega/files/5884871/5559.txt)
