### ISSUE TITLE
Exception handling in ControllerServiceSyncImpl

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#559]
**Problem description**
Here is an example of a method in `ControllerServiceSyncImpl`:

```
public CreateStreamStatus createStream(final StreamConfig streamConfig) throws TException {
        return FutureHelpers.getAndHandleExceptions(controllerService.createStream(ModelHelper.
                          encode(streamConfig), System.currentTimeMillis()), RuntimeException::new);
    }
```

The throwable constructor it is passing is for runtime exception (unchecked), but the declaration of  `TException` is:

```
public class TException extends Exception 
```

which is checked. We should make this consistent.

**Problem location**
Controller.

**Comment by bhargav-gulavani** [comment]
This class has been removed while migrating from Thrift to gRPC.
