### ISSUE TITLE
System Test Logging Enhancements

### ISSUE THREAD

**Issue by co-jo** [pravega/pravega#5634]
**Problem description**

In the current state of Pravega, retrieving logs from a systems test deployment requires manually querying each process/service. Running the test suite on a set of non-local machines (or cloud environments) introduces several complications with respect to logging.

* Services that perform restart operations can lose logs from previous 'lives'. 
* Long running tests can overwrite previous logs due to storage limitations.
* Querying each process can be tedious when many components are involved. 

**Problem location**

`test/system/...`

**Suggestions for an improvement**

Create a service that exists outsides of the lifecycle of core Pravega components whose job is to aggregate logs into a centralize location. 
* A basic log sink will be able to preserve the logs across multiple restarts.
* Centralizes the location in which logs can be found.

**Comment by RaulGracia** [comment]
Closed via #5744.
