### ISSUE TITLE
Paginate the result of listStreamInScope and listScopes

### ISSUE THREAD

**Issue by Abhijeet-Jadhav** [pravega/pravega#564]
**Problem description**
The results of listStreamInScope and listScopes API could be huge. We need to paginate the same.

**Problem location**
listStreamInScope and listScopes API call.

**Suggestions for an improvement**
Paginate the results.

**Comment by skrishnappa** [comment]
We will need pagination support in zookeeper for this - https://issues.apache.org/jira/browse/ZOOKEEPER-2260
