### ISSUE TITLE
Convenience APIs for working with SegmentRanges and StreamCuts

### ISSUE THREAD

**Issue by adrdc** [pravega/pravega#5812]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The purpose of the changes would be a couple of APIs in order to help creating SegmentRanges.  The main api needed is:
- given a Segment, start stream cut, and end stream cut, return a SegmentRangeImpl for the given Segment start->end offset.

Also if a segment did not exist at head or tail of a stream (e.g. there was scale up/down), there did not seem to be an easy way to get beginning/end stream cut info for them.  So additional apis are:
- get first stream cut for a Segment
- get last stream cut for a Segment

**Describe alternatives you've considered**
Alternatives have involved doing a lot of extra work listing segments in order to produce similar results.

**Additional context**
My use case is consuming a pravega stream in parallel (in context of presto db).
The number of workers available for this processing can vary, but in a typical scenario there will be a few hundred (400 in my test system).
Working on a flexible system where each worker can process part of a segment of a stream.  As such would like to be able to create a SegmentRange of configurable desired byte size that can be handed off to a worker.  For example so far in our testing, approx ~32MB / worker seems to work well.  But this will need to change depending on workers available, overall size of stream, etc.

At a high level, to do my application uses a streams associated Watermark stream.
The application will read watermarks from the Watermark stream and will keep track of the distance in bytes between 2 stream cuts in a Segment.  When the distance is > configurable size a SegmentRangeImpl will be created for it (SegmentRange cannot be exactly the desired size, but will be close).

The suggested APIs help in this translation from Watermarks to a usable SegmentRange that can be processed.

I will link a draft PR of the changes to pravega, and would welcome any comments, suggestions, etc

Thanks a lot!

**Comment by tkaitchuck** [comment]
I think we can re-frame the above as:
1. Given a start and end stream cut. Return a list of segmentRanges between them.
2. On a segmentRange support getting the segment.
(These two above are sufficient for the first point)
3. Have watermarks return a streamCut for each watermark.
4. Given two stream cuts return the distance between them in bytes.
