### ISSUE TITLE
Cherry pick for issue 5393

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5823]
**Describe the bug**
This issue tracks cherry picking the fix for issue 5395 into r0.9 branch

**Expected behavior**
Issue 5393 should be fixed in branch 0.9.

**Comment by kotlasaicharanreddy** [comment]
> **Describe the bug**
> This issue tracks cherry picking the fix for issue 5395 into r0.9 branch
> 
> **Expected behavior**
> Issue 5395 should be fixed in branch 0.9.

Please change Issue number to 5393.

**Comment by pbelgundi** [comment]
> > **Describe the bug**
> > This issue tracks cherry picking the fix for issue 5395 into r0.9 branch
> > **Expected behavior**
> > Issue 5395 should be fixed in branch 0.9.
> 
> Please change Issue number to 5393.

done
