### ISSUE TITLE
Allow to use custom client for system test

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega#5844]
**Is your feature request related to a problem? Please describe.**
System test should be able to allow user to use their own Pravega client jar file.

**Describe the solution you'd like**
Have an optional Java property in system test.

**Describe alternatives you've considered**

**Additional context**

**Comment by Richa-Srivastava** [comment]
I am getting following error after applying changes required in build.gradle locally in my changes wrt https://github.com/pravega/pravega/pull/5845 when tried to run client from 0.8.1 branch:

```
/root/Richa/pravega-qe/test/system/src/main/java/io/pravega/test/system/framework/Utils.java:168: error: incompatible types: DefaultCredentials cannot be converted to Credentials
                               .credentials(new DefaultCredentials("1111_aaaa", "admin"))
                                            ^
/root/Richa/pravega-qe/test/system/src/main/java/io/pravega/test/system/framework/Utils.java:175: error: incompatible types: DefaultCredentials cannot be converted to Credentials
                               .credentials(new DefaultCredentials("1111_aaaa", "admin"))
```
                               
The command used to run testcase:
`./gradlew --info clean startK8SystemTests -DcustomClient=/root/Richa/client/pravega-client-0.8.1/pravega-client-0.8.1.jar`

**Comment by Tristan1900** [comment]
Hi @Richa-Srivastava , could you run again using `./gradlew --info clean startK8SystemTests -DcustomClient=/root/Richa/client/pravega-client-0.8.1` ? I think `pravega-client-0.8.1.jar` is not a uber jar and we need other dependencies to work. Thanks!

**Comment by Richa-Srivastava** [comment]
Tried with `./gradlew --info clean startK8SystemTests -DcustomClient=/root/Richa/client/pravega-client-0.8.1` but same issue what I mentioned above.

**Comment by Tristan1900** [comment]
@Richa-Srivastava Yeah I see the error now. I guess you are testing `0.9` Pravega with `0.8.1` client, is that right? That line of change happened for `0.9` [here](https://github.com/pravega/pravega/commit/4b4b7fadab73a7dfdfb24db331b38b800916a87d#diff-5c7f6e58e7cf0118cc28a31275160cac2a97db6162b66e7f36202ed8b7b1eef0L20). So if you are using a `0.8.1` client, that shouldn't work I suppose.

**Comment by Tristan1900** [comment]
@Richa-Srivastava thanks! Are you testing `0.9` server with `0.8.1` client, is that correct? Anyway, it looks like client is incompatible with server, I guess that's the purpose of this test?

**Comment by Richa-Srivastava** [comment]
No, I deployd 0.8.0 Pravega and tried to run 0.8.1 client.
