### ISSUE TITLE
Create exception to force Segment Container shutdown

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5846]
**Describe the solution you'd like**
Currently we overload the `DataCorruptionException` with situations that are not even remotely connected to data corruption (i.e., cache full). This causes unwanted confusion when parsing logs and trying to root cause problems.

**Solutions**
1. Create a new exception (`ServiceHaltException` which inherits from `StreamingException`),
2. Make `DataCorruptionException` extend from it. This means the `ServiceHaltException` may need to have the same constructor(s) as `DataCorruptionException`.
3. Look through the codebase where `DataCorruptionException` is thrown where **it does not indicate data corruption**. For example, a cache full exception is not a data corruption. Replace those usages with `ServiceHaltException`
3.  wire it to auto-shut down the Segment Container, DurableLog and StorageWriter and replace usages of `DataCorruptionException` with this one where appropriate.
4. Look for `instanceof DataCorruptionException` - some of these (but **not all**) will trigger various components to shut down. In these cases, replace it with `instanceof ServiceHaltException` (and optionally add a comment indicating it also covers DCE).
5. Optional: in `OperationProcessor.java#processCommits`, in the `isFatalException`, consider actually throwing the exception as well (after invoking callbacks) - this should force the commit processor to stop immediately and not log additional noise in the logs.

When this is done, `DataCorruptionException` should ONLY be used in those cases where data corruption is either suspected or has been confirmed.

**Comment by ManishKumarKeshri** [comment]
Thanks. One question: At present, Do `DataCorruptionException` shut down Segment Container, DurableLog, and StorageWriter at any place?

**Comment by andreipaduroiu** [comment]
If you look in those files, you'll see that some of them will check various exceptions to see if they're fatal (or something like that). Some of those explicitly check if the exception is a `DataCorruptionException`. I think the best way to resolve this is by finding all usages of `DataCorruptionException` (your IDE can help there) and then, among those, find cases where we `catch` them (in `try-catch` blocks) or check `instanceof DataCorruptionException`). Not all should be changed though - you'll have to decide on a case-by-case basis if you should change it or not.

**Comment by ManishKumarKeshri** [comment]
We already have [`cacheFullException`](https://github.com/pravega/pravega/blob/936958ed3398c848c1cc20c8a5871562556b3269/segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java#L185), it is never thrown as it is not a type of `VirtualMachineError`. Should we throw `CacheFullException` itself?
Will this [line ](https://github.com/pravega/pravega/blob/936958ed3398c848c1cc20c8a5871562556b3269/segmentstore/server/src/main/java/io/pravega/segmentstore/server/logs/MemoryStateUpdater.java#L264) ever be hit? I don't see any calls in try block throwing that exception.

**Comment by andreipaduroiu** [comment]
So that is just one of the places where CacheFullException is inspected. I recommend we do not alter that. Let it bubble up and be handled by upstream code. 

The places where I am thinking would be a good candidate for this are `OperationProcessor`, `DurableLog` and `StreamSegmentContainer` (and maybe `MemoryStateUpdater`).

Again, the goal of this is not to get rid of the `CacheFullException` or wrap it in something else. What I would like to do is split the usages of `DataCorruptionException` into 1) Real Data Corruption and 2) Non-data corruption. So we want to see where DataCorruptionException is thrown and reason if that is really a data corruption or not. If not, then instead of it, throw `ServiceHaltException` instead.
