### ISSUE TITLE
Docs Tech Debt

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#5874]
Order of PRs:

- [x] Igor's MkDocs PR https://github.com/pravega/pravega/pull/4871
- [x] Flavio's HEADER file PR https://github.com/pravega/pravega/pull/5807
- [x] Derek's MkDocs Reorg PR https://github.com/pravega/pravega/pull/5882
- [x] Sandeep's Beginner's Guide PR https://github.com/pravega/pravega/pull/5756
- [x] Shivesh's Controller & REST PR https://github.com/pravega/pravega/pull/5770
- [x] Raul's Admin Guide PR https://github.com/pravega/pravega/pull/5849

Foreign PRs used in MkDocs Reorg:

* https://github.com/pravega/pravega-operator/pull/512
* https://github.com/pravega/flink-connectors/pull/469
* https://github.com/pravega/schema-registry/pull/200
* https://github.com/pravega/spark-connectors/pull/104

**Comment by derekm** [comment]
@RaulGracia -- What do we do about PR https://github.com/pravega/pravega/pull/5620 ?

**Comment by RaulGracia** [comment]
@derekm we can close it, as we plan to delete that document in favor to import documentation from the Operator repo.

**Comment by derekm** [comment]
@dellThejas -- In line with @RaulGracia's comment above, can you make sure your PR is full redundant to the equivalent document from the Operator repo? You can comment here to move your info to the new document: https://github.com/pravega/pravega-operator/pull/512

Thanks!

**Comment by RaulGracia** [comment]
@derekm maybe it is worth it to keep #5745 as a reference and create a new PR for the 3rd work item.
