### ISSUE TITLE
Delete reader group throws for existing reader group

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#5916]
**Describe the bug**
When I try to delete a reader group with a name suffixed with `-rg`, the client throws an exception saying that the reader group doesn't exist. If I replace the suffix with say `-group`, then it works fine. There seem to be an issue with the parsing of the name, and in particular with the pattern `rg`.

**To Reproduce**
The code I run to repro it is this:

```
        String scope = "test";
        String stream = "test";
        String rg = "test-group";
        String rgBuggy = "test-rg";
        StreamManager streamManager = StreamManager.create(URI.create("tcp://127.0.0.1:9090"));
        ReaderGroupManager rgManager = ReaderGroupManager.withScope(scope, URI.create("tcp://127.0.0.1:9090"));

        streamManager.createScope(scope);
        streamManager.createStream(scope, stream, StreamConfiguration.builder().build());

        rgManager.createReaderGroup(rg, ReaderGroupConfig.builder().stream("test/test").build());
        rgManager.deleteReaderGroup(rg);

        rgManager.createReaderGroup(rgBuggy, ReaderGroupConfig.builder().stream("test/test").build());
        rgManager.deleteReaderGroup(rgBuggy);

        rgManager.close();
        streamManager.close();
```

and the second call to delete reader group throws:

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: ReaderGroup does not exist: test/test-rg
    at io.pravega.common.concurrent.Futures.getAndHandleExceptions (Futures.java:206)
    at io.pravega.client.admin.impl.ReaderGroupManagerImpl.deleteReaderGroup (ReaderGroupManagerImpl.java:110)
    at io.pravega.TestReaderGroup.main (TestReaderGroup.java:27)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:834)
    ...
```

**Screenshots**
N/A

**Additional information**
The problem seems to be with the processing in the controller as the exception indicates that it is coming from delete reader group in the controller client.

```
Caused by: java.lang.IllegalArgumentException: ReaderGroup does not exist: test/test-rg
    at io.pravega.client.control.impl.ControllerImpl.lambda$deleteReaderGroup$118 (ControllerImpl.java:1670)
```

**Comment by fpj** [comment]
I stopped getting that exception. I started playing with commit points, and now I can't repro any longer. I'm consistently using the Pravega `0.9.0` client with the code snippet I posted above, and I have tried `0.9.0`, the head of `0.9.0` and `master` head. None of them seem to reproduce now for me.

**Comment by fpj** [comment]
I'm now able to reproduce again. To be able to repro, I had to comment out the creation of the `test` stream, and try to create the reader group. After the creation failed, uncommenting the creation of the stream, enabled the creation of the reader group (at least the operation completed without error), but I get the exception above when deleting the reader group.

Attaching standalone logs for debugging:

[standalone.log](https://github.com/pravega/pravega/files/6278189/standalone.log)

**Comment by pbelgundi** [comment]
Tried reproduing this issue using an Integration test.
As explained above, I see that `createReaderGroup` API fails when the Stream does not exist with the following error:

```
io.pravega.test.integration.endtoendtest.EndToEndCBRTest > testReaderGroupDeletion STARTED
io.pravega.test.integration.endtoendtest.EndToEndCBRTest > testReaderGroupDeletion FAILED
    io.pravega.client.stream.InvalidStreamException: io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: test table: _system/_tables/test/streamsInScope.#.1001f7ce-7d4e-4acf-9941-661629814c21
        at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:233)
        at io.pravega.client.stream.impl.ReaderGroupImpl.getSegmentsForStreams(ReaderGroupImpl.java:325)
        at io.pravega.client.admin.impl.ReaderGroupManagerImpl.createReaderGroup(ReaderGroupManagerImpl.java:101)
        at io.pravega.test.integration.endtoendtest.EndToEndCBRTest.testReaderGroupDeletion(EndToEndCBRTest.java:223)
        Caused by:
        io.pravega.controller.store.stream.StoreException$DataNotFoundException: get entry: key: test table: _system/_tables/test/streamsInScope.#.1001f7ce-7d4e-4acf-9941-661629814c21
            at io.pravega.controller.store.stream.StoreException.create(StoreException.java:96)
            at io.pravega.controller.store.stream.StoreException.create(StoreException.java:76)
            at io.pravega.controller.store.PravegaTablesStoreHelper.lambda$getEntry$23(PravegaTablesStoreHelper.java:300)
```

However, when I uncomment the `createStream` line the createReaderGroup and deleteReaderGroup APIs both completed as expected without any error/exception....

Here is my test code:
```
public void testReaderGroupDeletion() throws Exception {
        String scope = "test";
        String streamName = "test";
        String groupName = "test-group";
        String groupName1 = "test-rg";

        LocalController controller = (LocalController) PRAVEGA.getLocalController();
        controller.createScope(scope).get();
        controller.createStream(scope, streamName, StreamConfiguration.builder().build()).get();
        Stream stream = Stream.of(scope, streamName);
        @Cleanup
        ConnectionFactory connectionFactory = new SocketConnectionFactoryImpl(ClientConfig.builder()
                .controllerURI(PRAVEGA.getControllerURI())
                .build());
        @Cleanup
        ClientFactoryImpl clientFactory = new ClientFactoryImpl(scope, controller, connectionFactory);
        // Create a ReaderGroup
        @Cleanup
        ReaderGroupManager groupManager = new ReaderGroupManagerImpl(scope, controller, clientFactory);
        groupManager.createReaderGroup(groupName, ReaderGroupConfig.builder().stream(stream).build());
        groupManager.deleteReaderGroup(groupName);

        groupManager.createReaderGroup(groupName1, ReaderGroupConfig.builder().stream(stream).build());
        groupManager.deleteReaderGroup(groupName1);
    }
```

Will try with Pravega standalone to make sure if this issue is reproducible there.

**Comment by pbelgundi** [comment]
Tried to reproduce this using standalone Pravega (_using latest master build_) but could not reproduce this issue there as well.
When `createStream` is commented, createReaderGroup() fails as expected and when uncommented things just work fine without any error/exception on create or delete.

Server version was the latest on master and client version was 0.9.0.

**Comment by pbelgundi** [comment]
The above exception log shows `getAndHandleException(deleteReaderGroup)`  at ln #110 in ReaderGroupManagerImpl, but this does not seem to match with ReaderGroupManagerImpl in r0.9:
https://github.com/pravega/pravega/blob/v0.9.0/client/src/main/java/io/pravega/client/admin/impl/ReaderGroupManagerImpl.java#L110

So the client version with which the issue was noticed seems to be < 0.9

**Comment by fpj** [comment]
This commit seems to be the one that changed the lines in `ReaderGroupManagerImpl`:

https://github.com/pravega/pravega/commit/251579183394bd52c95df1071f7cdb9da4e20a34#diff-fb5448817937e9e525a98412627505b80c95c129734d8aba1756e8a9b3f0b651

and that possibly fixed the issue. I have forced maven to reload the dependencies and now I don't observe the problem anymore. I probably had `0.9.0` from a release candidate that didn't make it. That's an issue with using the release version with candidates, it might end up leaving stale versions in the local cache.
