### ISSUE TITLE
KVT Beta 2: Change Segment Attribute Representation from UUID to a generic AttributeId

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5935]
**Describe the solution you'd like**
Currently all Segment Attributes are 16 bytes so in the code they are represented as UUIDs. With PDP-48, we will have:
- Stream Segments and Hash Table Segments (as they are today - both core and extended attributes are 16 bytes)
- Fixed-Key-Length Table Segments: core attributes are 16 bytes, extended attributes are an arbitrary value set at the creation of the segment.

As such, we need to:
- Create a new `AttributeId` abstraction for the Segment Attributes
- Create an `AttributeId.UUID` implementation that is fully compatible with the current `UUID` API (what we use from it)
- Update all usages of `UUID` in the segment store codebase (where appropriate) to use `AttributeId` (preferred to `AttributeId.UUID` if possible)
- Define (not necessarily fully implement) an `AttributeId.Variable` for arbitrary-sized attributes (these will be used later).

**Comment by RaulGracia** [comment]
Closed via #5980.
