### ISSUE TITLE
KVT Beta 2:  Dynamic Attribute Updates (by Segment Length)

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5936]
**Describe the solution you'd like**
For KVT Beta 2, as described in PDP-48, we need a way to dynamically assign a value to an attribute that is a function of some other value in the system. Currently we can only assign user-provided (constant) values to attributes. Since we need to update the Table Segment index on the fly (as we ingest), we need to be able to point to the location in the segment where various keys are located.

As such, we need to update the `AttributeUpdate` class with the ability to assign values "by-reference". For now, all we need is to assign values based on the current length of the segment (+/- some delta).

**Comment by RaulGracia** [comment]
Closed via #6001.
