### ISSUE TITLE
KVT Beta 2: Implement Fixed-Key-Length Table Segment Layout

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5937]
**Describe the solution you'd like**
See [PDP-48](https://github.com/pravega/pravega/wiki/PDP-48-Key-Value-Tables-(Beta-2)) for full details, including suggested design.

We need to:
- Define an abstract `TableSegmentLayout` class which exposes generic APIs that access and manipulate a Segment in order to interpret it as a Table Segment.
- Move existing Hash Table Segment layout code from `ContainerTableExtensionImpl` into a new `HashTableSegmentLayout` class.
- Update `ContainerTableExtensionImpl` to 1) select a layout (based on segment type) and 2) delegate actions to that layout. After this change, it should simply be a "bonding glue" that holds most components together (that relate to table segments).

**Comment by RaulGracia** [comment]
Closed via #6062.
