### ISSUE TITLE
KVT Beta 2: Final Cleanup

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#5942]
**Describe the solution you'd like**
Any cleanup tasks should be done here.

Things to check:
- [x] Are all APIs implemented?
- [x] Are all unit tests re-enabled/fixed/passing?
- [x] Are all integration tests re-enabled/fixed/passing?
    - [x] Verify both Base Test Class and all implementations (there's one for Client Only, and one for Integration (Client + Segment Store + Controller)).
- [x] CLI Commands (Fix and then update tests)
- [x] Is the code coverage (overall) sufficient for a merge to master?

**Comment by RaulGracia** [comment]
Closed via #6105.
