### ISSUE TITLE
KVT Beta 2: Keep Track of number of Attributes per Segment

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#6042]
**Describe the solution you'd like**
The B+TreeIndex does not have an easy way to get the number of entries stored in its index. The only way we can do it is by iterating through all entries. 

We need a way to maintain basic statistics (including at least number of entries) and persist these durably alongside the rest of the data in the index. This change must be backwards compatible (do not break existing segments), but it is OK if statistics are not enabled for existing segments. We only need that for the new Fixed-Key-Length Table Segments.

**Comment by RaulGracia** [comment]
Closed via #6043.
