### ISSUE TITLE
Add a method in event stream reader to return raw bytes directly

### ISSUE THREAD

**Issue by crazyzhou** [pravega/pravega#6087]
**Is your feature request related to a problem? Please describe.**

After @derekm finished the debezium sink for Pravega, the connector team is helping Derek to build an end-to-end demo using Postgres DB -> debezium -> Pravega -> Flink SQL -> some other JDBC sink, but we found a problem in the connector which is filed here: https://github.com/pravega/flink-connectors/issues/530. 

We had some further investigation and find it's actually hard to fix only on the connector side, so I would like to seek help here. First let me explain a bit here.

Now in the connector, we have some wrapper classes to transfer a normal Flink DeserializationSchema into a Pravega serializer, and it's calling the `T deserialize(byte[] message)`, and it works now and then in most cases.

However, to support more flexible deserialization, Flink has added an additional method in the deserialization schema to support deserializing bytes into multiple events instead of one. This is especially required in the debezium case because in a Row UPDATE case, it requires to deserialize into two events(UPDATE_BEFORE and UPDATE_AFTER) in Flink Table API.
This works for the other messaging systems like Kafka, Kinesis, RabbitMQ because their client can return raw bytes when read, and they delegate the deserialization methods to the user. However it does not work for us because Pravega's event stream reader requires a `Serializer`(A method turns bytes into one event) to construct and we only have readNextEvent API to return the deserialized event.

I think our reader is much more encapsulated that we cannot have such flexibility to deal with raw bytes.

I would like to ask if we can allow nullable Serializer in the reader and can offer a method returns raw bytes of an event?

**Describe the solution you'd like**
I would like to ask if we can allow nullable Serializer in the reader, and add a method in event stream reader to return raw bytes directly.
```
byte[] readNextEventInRawBytes(long readTimeout)
```
In the `EventStreamReaderImpl` Class, just do not call `deserialize` compared to `readNextEventInternal`

**Comment by medvedevigorek** [comment]
@tkaitchuck can you comment on the ask above? Wonder whether it can be achieved by providing a custom Serializer that just returns event as-is. Thanks

**Comment by crazyzhou** [comment]
Yes, I talked with @fpj about this and we can use the [`ByteBufferSerializer`](https://github.com/pravega/pravega/blob/070dfc5934f18fd53e9d90321b629e0bf2f07b53/client/src/main/java/io/pravega/client/stream/impl/ByteBufferSerializer.java) here, but this would totally change the way Flink connector work for its deserialization now. We are doing such change now to see if it works, so far generally good, but we have also found some corner cases like metadata(eventpointer) deserialization support that breaks the compatibility of the API, we are still looking for ways for supporting that.
I would suggest we keep this issue open until we have tested all the main code paths are still working with the `ByteBufferSerializer` way.

**Comment by medvedevigorek** [comment]
> we have also found some corner cases like metadata(eventpointer) deserialization support that breaks the compatibility of the API

@crazyzhou could you please elaborate more on this? I am sure missing something here.

**Comment by crazyzhou** [comment]
> @crazyzhou could you please elaborate more on this? I am sure missing something here.

Flink has its `DeserializationSchema` and Pravega has its `Serializer` to deserialize the data. The Flink connector provides the interoperability between these two. This means when reading event from Pravega in Flink, we first change the `DeserializationSchema` into `Serializer`, and then construct the `EventStreamReader` and start reading events, so what we get from the `readNextEvent` call are deserialized events instead of raw bytes. On top of it, we offer a way to let users to customize a transformation in `PravegaDeserializationSchema`  class with the deserialized data and metadata in `EventRead`, such customization allows users to include the metadata such as `EventPointer` in their events that can be used for indexing purposes. 

@fpj suggested to use the `ByteBufferSerializer` instead which we changed the code entirely in the deserialization path and tested feasible in normal cases, but it would break that customization. We are still looking for a way to support that

**Comment by crazyzhou** [comment]
We found way to support it and implemented in https://github.com/pravega/flink-connectors/pull/533, so it's not needed any more. Closing this issue for now.
