### ISSUE TITLE
Implement system tests.

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#612]
**Problem description**
We need test cases to run in our framework, and I'd like to propose a few to start with:

- [ ] Reader groups #613
- [x] Auto scaling #614 
- [x] Transactions #615 
- [x] Reader groups + Auto scaling + Transactions #616 
- [x] Controller REST #617 

**Problem location**
Test framework.

**Comment by bsideup** [comment]
Hi @fpj,

I noticed "Test framework" under **Problem location** and was wondering whether you considered Docker for it? 
I am one of the members of https://testcontainers.org project and will be happy to answer questions if you have some :)

I know that some other projects like Apache Pulsar and BookKeeper use it already and I see how Pravega can benefit from it.

On a side note - I would be especially happy to help given the good relationships between Dell EMC and Pivotal 😉
