### ISSUE TITLE
Health Checks for Controller Services

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6144]
**Is your feature request related to a problem? Please describe.**
This issue lists health checks to be implemented on Controller Health Service.
The purpose of these checks is to ensure all Controller services are up and running and healthy.
The Operators would use the /readiness and /liveness APIs on the Controller Health Service to know if the Controller is ready and alive respectively. This issue describes the checks that need to be performed as part of these API requests on Controller.

**Describe the solution you'd like**
The Health Service needs to report health of the Controller based on health information of its sub-component services.
Controller currently runs the following services (_in addition to the Health Service itself_) 
1. GRPC Server 
2. REST Server
3. SegmentContainerMonitor
4. Retention Service 
5. Watermarking Service 
6. Event Processor 
7. Cluster Listener

**Liveness check** for all services can be to check if the service is running using the `service.isRunning()` method.
If the liveness check passes for all sub-component services, Controller "/liveness" would return `true` else return `false`.
In addition to invoking this API, operators should also continue to do the current port checks for liveness.

Controller Readiness check would be a logical "and" of the readiness checks for each of its component services:
**Readiness check** for each component could be done as follows:
1. GRPC Server & 
--> isRunning() + ControllerEventProcessor ready.

2. Segment Container Monitor ---> 
isRunning() +
ClusterZKImpl  - check if ZK Session is healthy - can be done based on event returning "ERROR" State.

3. Cluster Listener  
isRunning() +
Add a new isReady() API to `ControllerClusterListener` that invokes isReady of each of the FailoverSweeper 
+ isZKConnected()

4. Retention Service &  Watermarking Service ---  isRunning() 
+ ZK Session ( ZKBucketStoreManager ---> ZKBucketStore --> ZKStoreHelper--> CuratorClient()
BucketService --> processNotification --> ConnectivityError  -- Error connecting to ZK

5. Event Processor 
-- change the current implementation of isReady() method as it just invokes `svc.isRunning()`
--- Add a boolean variable that changes to `true` when bootstrap completes.
--- Check if _system scope and streams used for doing event processing for the Streams API, txn processing, KVT API processing are present

**Comment by medvedevigorek** [comment]
@pbelgundi thank you for putting this together, this is very useful. It covers most of the internal Controller services. 

What about a health check to indicate that  `_system` scope has been provisioned/initialized and Controller can serve user requests?

**Comment by pbelgundi** [comment]
> @pbelgundi thank you for putting this together, this is very useful. It covers most of the internal Controller services.
> 
> What about a health check to indicate that `_system` scope has been provisioned/initialized and Controller can serve user requests?

The _system scope and system streams used to process events for Stream APIs, KVT APIs, transaction processing etc .. are needed for the GRPC & REST, as well as ControllerEventProcessor Service to work. So yes we could check for existence of these in the Readiness probe.

**Comment by pbelgundi** [comment]
The existence of the `_system` scope and the 4 Streams used by Controller can be checked by invoking `streamMetadataStore.checkScopeExists()` and streamMetadataStore.checkStreamExists()` calls on the `_system` scope and 4 Streams used by ControllerEventProcessor. However, this would mean making calls to Segment Store to confirm their existence and if Segment Store is down, these calls would fail making it look like the Controller is also not working.
Instead, we could use a boolean variable inside ControllerEventProcessors to indicate that these required objects are created when the `bootstrap` method of this class completes. and then just check the value of this variable to know if initialization is complete.
