### ISSUE TITLE
open bucket lead to leaks sesntive data

### ISSUE THREAD

**Issue by shadihh9** [pravega/pravega#6146]
**Describe the bug**
i found open bucket aws lead to leaks user data like user and password
**To Reproduce**
1. Go to https://pravega-contactimages-ap-south-1.s3.amazonaws.com/
2.and also go to https://pravega-contactimages-ap-south-1.s3.amazonaws.com/media/pravega_backup.json
3- and see session and emails and password leaks and more data leaks
3. this is an 
![1](https://user-images.githubusercontent.com/22076930/125191722-93344400-e24c-11eb-94a8-f5969a6028ff.png)
![2](https://user-images.githubusercontent.com/22076930/125191724-96c7cb00-e24c-11eb-83a9-a9c6a6cecef5.png)
information disclosure
impact
can attacker leaks sesntive data

**Screenshots**

**Additional information**
Add any other information about the problem here, including the root cause if known.

**Comment by shadihh9** [comment]
and also any bounty?

**Comment by medvedevigorek** [comment]
This S3 bucket doesn't belong to Pravega (pravega.io) project, It must be someone's else one. But thank you for bringing it up to our attention.
