### ISSUE TITLE
Pravega standalone uses port 9092 that conflicts with schema registry

### ISSUE THREAD

**Issue by crazyzhou** [pravega/pravega#6150]
**Describe the bug**
We want to test locally with both Pravega latest master and schema registry standalone. When Pravega starts first, it has below logs which indicates the health checker is using port 9092.
```
Jul 14, 2021 5:22:13 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.pravega.shared.health.bindings.resources.HealthImpl regisJul 14, 2021 5:22:13 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [localhost:9092]
```
This results that schema registry service cannot start, we receive  
```
Caused by: java.net.BindException: Address already in use: bind
```

cc. @co-jo

**Comment by co-jo** [comment]
Does this issue occur consistently? The HealthCheck package does not deploy a resource that requests a port, but instead is utilized by the `segmentstore` or `controller` to export health information via a `RESTServer`. The controller uses `9091` by default and the segmentstore uses `6061` by default. 

Various tests that instantiate a `RESTServer` will request an available port via `TestUtils.getAvailableListenPort` so I'm wondering if this was simply a fluke.

**Comment by crazyzhou** [comment]
> Does this issue occur consistently?

**Comment by crazyzhou** [comment]
@co-jo @fpj Any updates on this? Currently Schema registry standalone can only be started by manually changing this line to a different port in the Pravega source code when starting Pravega standalone.

**Comment by co-jo** [comment]
> 
> 
> @co-jo @fpj Any updates on this? Currently Schema registry standalone can only be started by manually changing this line to a different port in the Pravega source code when starting Pravega standalone.

Can you share the branch/hash you're using so I can test it out?

**Comment by crazyzhou** [comment]
> > @co-jo @fpj Any updates on this? Currently Schema registry standalone can only be started by manually changing this line to a different port in the Pravega source code when starting Pravega standalone.
> 
> Can you share the branch/hash you're using so I can test it out?

Just use Pravega schema registry [0.2.0](https://github.com/pravega/schema-registry/releases/tag/v0.2.0) and Pravega latest master branch. First bring up the pravega standalone with
`./rgadlew startStandalone` and then on the same machine, start the schema registry `./bin/schema-registry`
