### ISSUE TITLE
Semantics of AttributeUpdate of type None

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6181]
**Question**
Noticed the following behavior working with attribute updates:
1. Create a segment and a random attribute id.
2. Try to conditionally update that attribute with arbitrary values (i.e., use `AttributeUpdateType.ReplaceIfEquals` in the `updateAttributes()` operation).
3. The previous step fails with a `BadAttributeUpdateException`, as expected.
4. Now, try to update the same attribute to another arbitrary value, this time using `AttributeUpdateType.None`, as in theory this attribute should not exist yet (as the previous attempt failed with `BadAttributeUpdateException`).
5. While I expected step 4 to work, it doesn't. I get a `BadAttributeUpdateException`, as apparently the attribute exists and it has been initialized with the default `Attributes.NULL_ATTRIBUTE_VALUE`.

Note that doing the same but without attempting the conditional attribute update, step 4 works as expected.

So, the question is: why the attribute update of type `AttributeUpdateType.None` behaves differently depending on whether we have done a failed attempt to update an attribute? In other words, why attempting to conditionally update an attribute initializes it to `Attributes.NULL_ATTRIBUTE_VALUE`? 

**How to reproduce the scenario**

```
    @Test
    public void testAttributeUpdateTypeNone() throws Exception {
        @Cleanup
        TestContext context = createContext();
        context.container.startAsync().awaitRunning();

        final String segment = "segment";
        context.container.createStreamSegment(segment, getSegmentType(segment), null, TIMEOUT)
                .get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);
        SegmentType segmentType = getSegmentType(segment);

        // Execute an Attribute Update of type None for a random attribute. This should work.
        AttributeId attributeId = AttributeId.fromUUID(UUID.randomUUID());
        context.container.updateAttributes(
                segment,
                AttributeUpdateCollection.from(new AttributeUpdate(attributeId, AttributeUpdateType.None, 0L)),
                TIMEOUT).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);

        // Try a conditional update on a random attribute ID. This is expected to fail as the attribute does not exit.
        attributeId = AttributeId.fromUUID(UUID.randomUUID());
        AssertExtensions.assertFutureThrows("Expected to fail on attribute update",
                context.container.updateAttributes(segment,
                        AttributeUpdateCollection.from(new AttributeUpdate(attributeId, AttributeUpdateType.ReplaceIfEquals, 1L, 0L)),
                        TIMEOUT),
                ex -> ex instanceof BadAttributeUpdateException);

        // Now, let's update it assuming that the attribute has not been set (given that the previous operation failed).
        // In my understanding, this should work as no one has set that attribute, but it doesn't (it does exist initialized
        // with Long.MIN_VALUE).
        context.container.updateAttributes(
                segment,
                AttributeUpdateCollection.from(new AttributeUpdate(attributeId, AttributeUpdateType.None, 0L)),
                TIMEOUT).get(TIMEOUT.toMillis(), TimeUnit.MILLISECONDS);

        context.container.stopAsync().awaitTerminated();
    }
```

**Comment by andreipaduroiu** [comment]
`None` effectively means `Insert` (if not already exists). It isn't really used in any production scenario so I am not surprised that we haven't run into this before.

It probably should be fixed to accept `NULL_ATTRIBUTE_VALUE` as "attribute does not exist".
