### ISSUE TITLE
readSegment in SegmentHelper takes the offset parameter as an integer instead of long

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6183]
**Describe the bug**
SegmentHelper.readSegment() takes an integer segment offset as where as the underlying WireCommand it invokes can take a long offset. Using an Integer offset can limit us to reading at max first 2GB of data in a Segment and hence it would help to change this API to take a long offset instead of int.

**Additional information**
Fix method signature for SegmentHelper.readSegment() method: https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/SegmentHelper.java#L638

**Comment by anirudhkovuru** [comment]
As part of fixing this bug, every all usages of `SegmentHelper.readSegment()` need to be checked and fixed accordingly.
