### ISSUE TITLE
ControllerFailureException: Failed to update readergroup

### ISSUE THREAD

**Issue by shshashwat** [pravega/pravega#6269]
**Describe the bug**
Pravega Controller shows that the Reader Group call failed with "Reader group config update failed as another update was in progress.
After the first update ReaderGroup request that was submitted:- the logs show - `event posted successfully`
Post this all the updateReaderGroup requests will fail as an update is already in progress. The controller is not able to read this event back and process it; this is due to fact that the ConcurrentEventProcessors sweeper never executed. The sweeper never got executed since the isReady() method on ConcurrentEventProcessors returned a false

**To Reproduce**
Perform the updateReaderGroup() call multiple times, it will be observed that first call gets success but subsequent calls fail

**Additional information**
isZKConnected needs to be set with current state before adding listner

**Comment by shrids** [comment]
The controller continuously logs the following WARN message which prevents the ConcurrentEventProcessor sweeper from executing.
```
2021-08-31 22:42:52,656 12495987 [controllerpool-5] WARN  i.p.c.f.ControllerClusterListener - java.lang.RuntimeException: sweeper class io.pravega.controller.server.eventProcessor.ControllerEventProcessors not ready, retrying with exponential backoff.
```
