### ISSUE TITLE
SLTS - SystemJournal unnecessarily logs a warning about ChunkNotFoundException which pollutes logs.

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#6297]
**Describe the bug**

1. Recent change in SLTS system journals removed redundant `exists()` check followed by actual `read()` into optimistically attempting to read and instead catching ChunkNotFoundException  https://github.com/pravega/pravega/commit/56127851f076ba96938a1aae25294ac28d17abb9#diff-ee0502cc66ba41180775dee33a[…]f53ada35e46fd87fdb71942ba5dR855 
2.  However this approach unnecessarily logs a warning about `ChunkNotFoundException` which pollutes logs.

**To Reproduce**
This problem is seen in any working Pravega cluster after bootstrap

**Screenshots**
Logs from recent run.

> 2021-09-14 04:21:51,394 36618 [storage-io-25] WARN  i.p.s.s.chunklayer.SystemJournal - SystemJournal[31] Error while reading journal _system/containers/_sysjournal.epoch0.container31.file11. Attempt#1
> java.util.concurrent.CompletionException: io.pravega.segmentstore.storage.chunklayer.ChunkNotFoundException: Chunk _system/containers/_sysjournal.epoch0.container31.file11 not found - doGetInfo
>         at io.pravega.segmentstore.storage.chunklayer.AsyncBaseChunkStorage.lambda$execute$12(AsyncBaseChunkStorage.java:707)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
>         at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
>         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: io.pravega.segmentstore.storage.chunklayer.ChunkNotFoundException: Chunk _system/containers/_sysjournal.epoch0.container31.file11 not found - doGetInfo
>         at io.pravega.storage.extendeds3.ExtendedS3ChunkStorage.convertException(ExtendedS3ChunkStorage.java:326)
>         at io.pravega.storage.extendeds3.ExtendedS3ChunkStorage.doGetInfo(ExtendedS3ChunkStorage.java:237)
>         at io.pravega.segmentstore.storage.chunklayer.BaseChunkStorage.lambda$doGetInfoAsync$0(BaseChunkStorage.java:67)
>         at io.pravega.segmentstore.storage.chunklayer.AsyncBaseChunkStorage.lambda$execute$12(AsyncBaseChunkStorage.java:703)
>         ... 7 common frames omitted
> Caused by: com.emc.object.s3.S3Exception: Not Found
>         at com.emc.object.s3.jersey.ErrorFilter.handle(ErrorFilter.java:80)
>         at com.emc.object.s3.jersey.RetryFilter.handle(RetryFilter.java:65)
>         at com.emc.object.s3.jersey.ChecksumFilter.handle(ChecksumFilter.java:73)
>         at com.emc.object.s3.jersey.AuthorizationFilter.handle(AuthorizationFilter.java:72)
>         at com.emc.object.s3.jersey.BucketFilter.handle(BucketFilter.java:80)
>         at com.emc.object.s3.jersey.NamespaceFilter.handle(NamespaceFilter.java:78)
>         at com.sun.jersey.api.client.Client.handle(Client.java:652)
>         at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
>         at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
>         at com.sun.jersey.api.client.WebResource$Builder.method(WebResource.java:623)
>         at com.emc.object.AbstractJerseyClient.executeRequest(AbstractJerseyClient.java:107)
>         at com.emc.object.AbstractJerseyClient.executeAndClose(AbstractJerseyClient.java:54)
>         at com.emc.object.s3.jersey.S3JerseyClient.getObjectMetadata(S3JerseyClient.java:635)
>         at com.emc.object.s3.jersey.S3JerseyClient.getObjectMetadata(S3JerseyClient.java:629)
>         at io.pravega.storage.extendeds3.ExtendedS3ChunkStorage.doGetInfo(ExtendedS3ChunkStorage.java:227)

**Additional information**
Add any other information about the problem here, including the root cause if known.

**Comment by RaulGracia** [comment]
Closed via #6307.
