### ISSUE TITLE
CLI commands for Segment Container Monitor

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6310]
**Is your feature request related to a problem? Please describe.**
CLI that helps inspect the state of the Segment Container Monitor service.

**Describe the solution you'd like**
Add the following new commands to Pravega CLI:
1. Get Container-Host mapping
```
> controller segment-monitor mapping

HostId, IPAddress, Port, endpointId, List[SegmentContainerId]
---------------------------------------------------------------------
ss-1, 10.123.192.34, 12345, segmentstore-1, [2, 4,6,8]
. . .
ss-n, 10.123.192.71, 12345, segmentstore-2, [1,3,5,7]
```

2. Info
```
controller segment-monitor info

Container Count: 8
MinRebalanceInterval: 20 mins
isEnabled: true
isLeader: true
Status: Ready|Starting|Unknown
```

**Comment by anishakj** [comment]
There are cli  commands available to get the container mapping. They are
```
 cluster get-host-by-container
 cluster list-containers
```
closing this issue since cli commands already exists.
