### ISSUE TITLE
Reevaluate logs for SegmentStore

### ISSUE THREAD

**Issue by abhinb** [pravega/pravega#6365]
**Describe the bug**
This issue is created to track the below effort w.r.t logging in SegmentStore:-
1) Check for any potential scope of improving logging in the SegmentStore. 
      - See if there are any areas in the code which needs more logs that can help us during debugging. 
      - Also remove any redundant logs if any.
2)  Check if the log levels are appropriate.

**To Reproduce**
N/A

**Screenshots**
N/A

**Additional information**
N/A

**Comment by RaulGracia** [comment]
@abhinb I think we can close this one as it is not really concrete. If we find some place where logging can be improved, let's create an issue for that.
