### ISSUE TITLE
Pravega CLI commands that allow updating values in Controller Metadata tables

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6406]
**Is your feature request related to a problem? Please describe.**
The Pravega CLI should provide commands that allow an admin to update the value corresponding to a specific key in a Controller metadata table.
This should help remedy any unexpected issues with Controller metadata in a production environment.

**Describe the solution you'd like**
Update command for updating any Controller Metadata table could look like:
```
controller-metadata put <table-name> <key> <ValueRecord.subfeild.subfeild...> <value> <segment-store endpoint>
```
For example, to update the Stream State in StreamMetadata Table we'd issue a command like:
```
controller-metadata put  _system/_tables/testScope/testStream/metadata.#.a72083e1-3ee1-468d-8d33-a61bef474441> "state"  StateRecord.state  "ACTIVE" <segment-store endpoint>
```

**Comment by anirudhkovuru** [comment]
After some discussion with @pbelgundi, we have decided to have the command to look like this:
```
controller-metadata update <table-name> <key> <new-value-file> <segment-store-endpoint>
```
The file provided would contain the value in the form of a JSON string which will be parsed into the required record. The current `get` command can be updated to support printing the record as a JSON string. This JSON string can be updated by the user and then used in the update command.
