### ISSUE TITLE
Update the documentation of the Pravega Admin CLI

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega#6434]
**What To Add**
- Documentation for the newly added table segment commands.
    - `table-segment get-info <segment-name> <segmentstore-endpoint>`
    - `table-segment get <segment-name> <key> <segmentstore-endpoint>`
    - `table-segment put <segment-name> <segmentstore-endpoint> <key> <value>`
    - `table-segment modify <segment-name> <segmentstore-endpoint> <key> <value>`
    - `table-segment set-serializer <serializer-name>`
- Documentation for the controller metadata commands described in 
    - #6371 
    - #6406.

**Update To Existing**
- Update the existing documentation for some of the older commands in the Admin CLI if needed.

**Comment by RaulGracia** [comment]
@anirudhkovuru does this need to be a separate issue? Normally when we add a new command, we also add the necessary documentation for that command in the same PR.
