### ISSUE TITLE
Fix failing segmentstore test AttributeIndexTests.testConcurrentReads

### ISSUE THREAD

**Issue by shshashwat** [pravega/pravega#6464]
**Describe the bug**
Segemntstore test AttributeIndexTests.testConcurrentReads fails sometimes with following stacktrace

```
java.lang.AssertionError: Expected one attempt to read root page from Storage. expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
```
This looks like a flaky test and needs to be fixed

**Comment by RaulGracia** [comment]
Duplicate of #5701.
