### ISSUE TITLE
Analyze growth of System-Critical Table Segments when LTS is unavailable

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6467]
**Describe the bug**
In PR #6452, we make a distinction on the max amount of unindexed data that is allowed to system-critical Table Segments. Apart from that, we allow these segments to have up to 256MB of unindexed data by default, in order to reduce the chances that these table segments run out of credits and get blocked if enough updates are accumulated without processing, as it could block the Storage Writer of a Segment Container.

However, we do not have a quantitative evaluation of how unindexed data grows in system-critical Table Segments while LTS is unavailable. At first glance, once we reach the maximum ingestion size of the `OperationLog` the throttler stops any further operation, including updates to system-critical Table Segments. But we don't have certainty about the upper bound in unindexed data length that a single system-critical Segment may reach before the max throttling happens. We nee further understanding on that to evaluate configuration defaults as well as the probability of this problem happening in the future.

**To Reproduce**
Run a Pravega instance and leave LTS unavailable while doing puts on a Table Segment and check the amount of unindexed data before the max throttling occurs. Also, evaluate the growth of system-critical table segments in such a situation.

**Screenshots**
n/a

**Additional information**
We need to check if we have all the metrics necessary for this evaluation and, if needed, add more metrics.

**Comment by RaulGracia** [comment]
As part of this effort, I have created #6509.

**Comment by abhinb** [comment]
As part of the above activity, of analysing the growth of system critical table segments, I noticed a peculiar case of a significant increase in the use of throttler credits which I intend to describe below to bring to our attention.
These experiments were performed on my local VM, and all components of Pravega running as either local processes or docker containers.
In this experiment , we have a EventWriter client basically pumping a total of 10MB of events, each event having 100 bytes.
LTS is brought down after we write the first 100 bytes, and then brought back up when this client stops.

![image](https://user-images.githubusercontent.com/88840194/149276572-f01e5e40-34ef-4b45-b1f5-c4ae693884b0.png)


The above graph is the one newly added on setup to track the usage of credits on system critical table segments.
As you see in the above graph, **_22:58._** , is the time when LTS is brought back. Which means LTS was down momentarily before that time, when the client has pumped data worth 10MB.As we can see the for an input of 10MB worth of data from the  client, we see quite a significant increase in the growth of the “storage_metadata_3” system critical segment for example which is what I intend to just summarize/highlight below to check if it is a cause of conern:

Looking at the logs, in comparison to the graph above , and analysing the growth of specifically the "storage_metadata_3" segment , below is what we see:-

 1) LTS is brought back up at <22:58>.  We see at that instant that we have accumulated close to 19k operations in the inmemory log. 
 
 `2022-01-12 22:54:59,090 893723 [core-21] DEBUG i.p.s.server.logs.DurableLog - DurableLog[3]: ReadResult (Count = 1, Remaining = 0).
2022-01-12 22:58:39,670 1114303 [core-14] DEBUG i.p.s.server.logs.DurableLog - DurableLog[3]: ReadResult (Count = 1000, Remaining = **19790**). <-- acuumulated when LTS is down
`

2) We can see that  the storagewriter starts reading 1k of them around the same time.

`2022-01-12 22:55:01,092 895725 [core-19] DEBUG i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[828].InputRead (Count=0, Bytes=0, LastReadSN=1200).
2022-01-12 22:58:39,852 1114485 [core-24] DEBUG i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[829].InputRead (Count=1000, Bytes=69463, LastReadSN=2200).  <--- starts reading from here
2022-01-12 23:00:24,813 1219446 [core-4] DEBUG i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[830].InputRead (Count=1000, Bytes=66680, LastReadSN=3200).
`


3) The storage writer also prints what these read operations are. If we look at what these operations are ,
We can see this is how they look for majority of the operations.

`2022-01-12 22:58:39,732 1114365 [core-26] DEBUG i.p.s.s.writer.SegmentAggregator - StorageWriter[3-2]: Add StreamSegmentTruncateOperation: SequenceNumber = 1529, SegmentId = 2, Offset = 39421; OpCount=310, MergeCount=0, Seal=false.
2022-01-12 22:58:39,732 1114365 [core-26] DEBUG i.p.s.s.writer.SegmentAggregator - StorageWriter[3-2]: Add CachedStreamSegmentAppendOperation: SequenceNumber = 1530, SegmentId = 2, Offset = 39554, Length = 133, Attributes = 0; OpCount=311, MergeCount=0, Seal=false.
2022-01-12 22:58:39,732 1114365 [core-26] DEBUG i.p.s.s.writer.SegmentAggregator - StorageWriter[3-2]: Add StreamSegmentTruncateOperation: SequenceNumber = 1531, SegmentId = 2, Offset = 39554; OpCount=312, MergeCount=0, Seal=false.
2022-01-12 22:58:39,732 1114365 [core-26] DEBUG i.p.s.s.writer.SegmentAggregator - StorageWriter[3-2]: Add CachedStreamSegmentAppendOperation: SequenceNumber = 1532, SegmentId = 2, Offset = 39687, Length = 133, Attributes = 0; OpCount=313, MergeCount=0, Seal=false.
`


4) If we look at what the segmented = 2 , stands for , we see that it is mapped to a GC segment.

`2022-01-12 22:40:57,770 52403 [core-7] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[1]: MapStreamSegment SegmentId = 2, Name = '_system/containers/event_processor_GC.queue.1_1', Active = 2`



5) We see these GC operations on segmentid = 2 , for many subsequent iterations of storageWriter in the logs, specifically till iteration 849, which occurs at around 23:26 in the logs. Post this we see a lot of append operations On segment id = 7 which look like below. 

`2022-01-12 23:27:23,563 2838196 [core-29] DEBUG i.p.s.s.writer.SegmentAggregator - StorageWriter[3-7]: Add CachedStreamSegmentAppendOperation: SequenceNumber = 22201, SegmentId = 7, Offset = 136339, Length = 550, Attributes = 0; OpCount=1, MergeCount=0, Seal=false.`



6) We can see that segmentid = 7, is mapped to , storage_metadata_3.
`2022-01-12 22:41:05,300 59933 [core-30] INFO  i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[3]: MapStreamSegment SegmentId = 7, Name = '_system/containers/storage_metadata_3', Active = 5`


7) As we observe above, if we look at the graph, between `23:26-23:27` is the time at which we see the release of credits or a decline in the growth of the storage_metadata_3 system critical segment. And till this time the majority of the operations that seem processed by the storagewriter[3], seem to be pertaining to segmentid 2 which is a segment related to internal GC tasks of the container. As we can see till this time of 23:26 , we have recorded significant increase in usage of credits of storage_metadata_3 system critical segment to the order of ~13+MB till this time.



8)  If we recollect the size of the data sent by the client was 10 MB.This leads to the question if there is any possibility of a case, where the internal GC activity leads to significant increase in credits of the system critical storage_metadata segment, in turn leading to crossing the thresholds of 256MB set as mentioned in the issue description above, which can basically lead to halting the progress of the container.

**Comment by RaulGracia** [comment]
Thanks a lot @abhinb, this is a great analysis. I have a couple of questions regarding this behavior:
- Is the increase in `storage_metadata` credits usage related to the length of the outstanding operations to be moved to LTS? That is, if instead of accumulating 10MB of 100B events before restoring LTS we accumulate 100MBs, would the amount of credits consumed be 10x larger? This actually may be, but we need to be sure to understand the extent of the problem.
- Does this only happen in all the Segment Containers that do accumulate outstanding appends to be moved to LTS? Are there cases in which a container accumulates appends but the behavior does not reproduce?

All in all, this seems to be related to this issue #6523 we just identified.

**Comment by abhinb** [comment]
Thanks @RaulGracia 
- About point 1, let me  just get back with varying the sizes of individual events and see the behaviour.
- Also I have seen runs where the behaviour wasnt reproduced. That is there hasnt been an accumulation of credits when i have kept LTS down with client pumping data. I am trying to reproduce another such case and see what happens to the log with this particular perspective i posted.
I ll keep this thread updated as and when i get some notes, worth sharing.

**Comment by abhinb** [comment]
@RaulGracia 
Tried different usecases for example with 1k byte steps summing up to 30MB, another one of 100 bytes summing up to 100MB for example.
What i see is the accumulation due to GC clearly seems to be a function of how slow the storage iterations are; or in other words how slow the underlying writes to LTS are. For example in cases where i repeated the same usecase mentioned above where the issue did not get reproduced , i see the storage iterations have finished really quickly(within 30 secs whereas in the case of accumulation analysis posted above it took close to 20mins for all iterations to finish). I did the 100 bytes summing to 100mb couple of times, and the iterations have completed fast enough and there has been no accumulation or negligible accumulation of credits.

**Comment by abhinb** [comment]
As mentioned in the above comment, the increase in accumulation of credits due to GC could be related to the issue described in [6523](https://github.com/pravega/pravega/issues/6523). 
I tried with the changes made in #6523 post which i havent really seen any accumulation issue over multiple runs.

I also tried accumulating the maximum operation log size (which is 1million) number of operations in the operation log. And see how much credits we accumulate.

1) Did it for 100 byte events. The operation log reached the maximum size of 1M, when around 236 MB worth of data was queued in the operation log. The accumulation of credits as part of this was  ~ 320KB.

![image](https://user-images.githubusercontent.com/88840194/149707324-a114451f-6b62-4ef0-a0aa-e9495e4cbb69.png)

which translates to slightly over ~1kb of accumulation per MB.

2) Also repeated the exercise by increasing the per event size to 1000 bytes. The operation log was filled up with 1M operations at around 2.3GB of data sent. And for this amount of data the accumulation was upto ~2.5MB worth of credits.

![image](https://user-images.githubusercontent.com/88840194/149707733-c51e4c14-f52c-43a0-a453-c9fe8159b8e0.png)

which again transaltes to around 1kb worth of credits accumulation per MB of data written to LTS.

**Comment by RaulGracia** [comment]
I think we can wrap up this issue. As a result of it, we have:
- Improved our understanding on the issue.
- Added a new metric to monitor the Table Segment credits #6517.
- Substantially reduce GC-related activity by truncating `ContainerEventProcessor` internal Segment less often #6527.

Thanks @abhinb for your work on this.
