### ISSUE TITLE
Admin CLI Commands to view pending events for a particular Controller host

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6497]
**Is your feature request related to a problem? Please describe.**
The Cluster Listener fails-over 3 kinds of tasks from a dying Controller:
a. Event Processing Requests managed by Controller Event Processor -- ControllerEventProcessors, RequestSweeper
b. Task Processing Requests - for Stream creation -- TaskSweeper
c. Txn Processing Requests -- TxnSweeper

All metadata stored in zookeeper is not in clear text and some of it is stored as bytes. 
Add new CLI commands that will help look-up data in zookeeper znodes that is stores as raw bytes.

**Describe the solution you'd like**
When Controller submits events for processing various operations like updating s stream, creating a KVT, a reader Group etc. these events are also added to a zookeeper znode belonging to that particular Controller host with path like:
`/pravega/pravgea/hostRequestIndex/hostId/<some-random-uuid>`
With a command like `get /pravega/pravgea/hostRequestIndex/hostId/<some-random-uuid>` on zookeeper CLI we can query this information from the particular znode and display it to a user.

Add a new CLI command:
`
controller-metadata get request-detail host <host-id> <request-uuid>
`
should display Controller Event details like:
Event Type: Update Stream Event

Solution:
1. Construct path based on values provided by the user in the command and query the particular znode in zookeeper.
2. On receiving the content from Zookeeper, deserialize the ByteBuffer based on event type.

**Comment by RaulGracia** [comment]
Closed via #6828.
