### ISSUE TITLE
Hardcoded port 8000 in standalone mode

### ISSUE THREAD

**Issue by thekingofcity** [pravega/pravega#6498]
**Describe the bug**
The standalone mode hardcodes JDWP 8000 on running. This may conflict with other programs and it would be better to have this port either configurable or disabled by default.

**To Reproduce**
1. get the distribution from github: https://github.com/pravega/pravega/releases/download/v0.10.1/pravega-0.10.1.tgz
2. untar
3. run `.\bin\pravega-standalone`
4. confirm that port 8000 is occupied
5. no way to configure this port except manually changing the `DEFAULT_JVM_OPTS` in `.\bin\pravega-standalone` script

**Screenshots**

**Additional information**
https://github.com/pravega/pravega/blob/master/build.gradle#L985

**Comment by ShwethaSNayak** [comment]
I will look into this issue.

**Comment by thekingofcity** [comment]
I'm closing it as it is fixed.
