### ISSUE TITLE
Admin CLI Config Usability Improvements

### ISSUE THREAD

**Issue by anirudhkovuru** [pravega/pravega#6507]
**Is your feature request related to a problem? Please describe.**
The admin CLI config needs to be easier to configure when being used in the Pravega environments. This should make it so that the CLI is readily available to use without demanding too much from the user. Primarily in regards to configuring it to work in the given environment.

**Describe the solution you'd like**
This improvement involves the following issues:
- [x] #6493 
- [x] #6504 
- [x] #6505 
- [x] #6506

**Comment by RaulGracia** [comment]
Closing this one, as all the sub-task are marked as complete.
