### ISSUE TITLE
Table Segment tail-caching may populate tail cache with stale data

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6539]
**Describe the bug**
Root cause: When container restart happens immediately after compaction but before indexer is run we are incorrectly initializing the tail cache with stale value.

Here is a simple scenario to illustrate the issue. For simplicity assume just one key:
(The data before | is flushed to LTS and indexed but data after that is written to only BK. The latest value is in tail cache
In segment below left is head (v1) and right is tail (v3))

1. Initially the segment looks like below. data unitl V2 is flushed to LTS, v3 is in BK and tail cache:
```v1 v2 | v3 ....```
2. Then compaction happens which looks only at the values stored on LTS (v1,v2) and decide that v1 is to be garbage collected and v2 is the latest value. Note that Compactor does not look at the tail cache, only the data flushed to LTS. Now segment looks like this:
```      | v3 v2 ..```
3. The container restarts and replays the pending changes and re-populates the tail cache. This code has a bug in that it looks at the offset and NOT data version and hence puts v2 in tail cache. This way we get a stale value: https://github.com/pravega/pravega/blob/ad4497c425c2e0da6b593627dfd4f7ff32a2bfbb/segmentstore/server/src/main/java/io/pravega/segmentstore/server/tables/ContainerKeyIndex.java#L682

4. Generally this problem is self healing because as soon as this data is flushed to LTS, the indexer runs and will correctly point to the highest version which is v3.
```      v3 v2 | ..```

However, if LTS is not working well or there is a lot of data accumulated in the in-memory log, the system may be left in a deadlock in which the `StorageWriter` cannot get initialized because it detects that stale data is retrieved from the Table Segment:
```
2022-01-21 11:33:51,437 965564 [core-45] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[18]: Iteration[922].Error.
java.lang.IllegalArgumentException: value: New Storage Length cannot be smaller than the previous one.
        at io.pravega.common.Exceptions.checkArgument(Exceptions.java:216)
        at io.pravega.segmentstore.server.containers.StreamSegmentMetadata.setStorageLength(StreamSegmentMetadata.java:223)
        at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$initialize$3(SegmentAggregator.java:290)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
```
But the `WriterTableProcessor` and `IndexWriter` cannot make progress with indexing, as they are invoked via the `StorageWriter`, which cannot be initialized (deadlock). 

(text partially authored by @sachin-j-joshi).

**To Reproduce**
Complex task, but possible:
1. LTS should be malfunctioning or unavailable for a singnificant amount of time (this can be simulated).
2. Accumulate data in the in-memory log to induce throttling.
3. Wait for the `TableCompactor` to get triggered. You may want to change the config settings to trigger it more frequently. 
4. Induce a restart of containers (or Segment Store instance) so the `StorageWriter` gets initialized again, so it requires to get data from Table Segment.

In some cases, the issue manifests.

**Screenshots**
n/a

**Additional information**
This impacts Hash-Based TableSegments, which are exclusively used by Pravega itself to store the SLTS/Container/Controller metadata.

**Comment by sachin-j-joshi** [comment]
Another case to consider - everything before | is flushed to LTS and indexed, things after are in BK.
Suppose all values are flushed and indexed
` v1, v2, v3 |`
Then compactor comes in and partially compacts and moves v2 at the tail
` v3 | v2`
The container restarts
The tail population logic initializes cache reading all values from BK.
So it sees only v2 while index happily and correctly has latest vlaue v3.
However we end up initializing cache with v2.
And because it is cached , we always returned this stale value.
