### ISSUE TITLE
Prevent internal streams/segments from being manipulated directly via the API

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#656]
**Problem description**
We need to make sure that calls to manipulate internal streams and segments directly are not available to users. For example, a user must not be able to delete an internal stream via the UI. 

**Problem location**
Controller API.

**Comment by fpj** [comment]
@shiveshr what's the current story for internal streams and the API? I don't see any mention of it at least in the javadocs:

https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/admin/StreamManager.java

**Comment by andreipaduroiu** [comment]
Similarly for the Segment Store internal segments.

**Comment by shiveshr** [comment]
Internal streams start with _ prefix and hence cannot be accessed via stream manager. 
to manipulate them one needs to directly invoke controller apis (like typically from admin cli).

**Comment by kotlasaicharanreddy** [comment]
I've verified that it was not possible to delete internal streams that starts with _prefix.

**Comment by kotlasaicharanreddy** [comment]
![image](https://user-images.githubusercontent.com/7935495/202618608-01adb688-baff-4358-91f7-26d1e521e5c3.png)
