### ISSUE TITLE
Admin CLI : Run sanity test against LTS 

### ISSUE THREAD

**Issue by AJadhav29** [pravega/pravega#6657]
**Is your feature request related to a problem? Please describe.**
The UtilsWrapper class contains various utils methods useful for administration of LTS. Adding a new method checkChunkSegmentStoragesanity that performs sanity operations on chunk like create chunk, write to the chunk, check if the chunk exists, read back contents to the chunk and delete the chunk.

**Describe the solution you'd like**
Step 1 : Add following method to UtlisWrapper

```
public CompletableFuture<Void> checkChunkSegmentStorageSanity (){
// Create globally unique name for chunk
// Create + Write a chunk 
// Check chunk exists 
// Read back chunk contents
// Delete chunk
// Check chunk doesn't exist
}
```
Step 2 : Call this method from AdminUtils
**Describe alternatives you've considered**

**Additional context**
None.

**Comment by sachin-j-joshi** [comment]
Closing as https://github.com/pravega/pravega/pull/6659 is merged.
