### ISSUE TITLE
Enforce checkstyle import * rule in test code 

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#6668]
**Describe the bug**
We need checkstyle to check and prevent `import *` statements in test code as well. 

**To Reproduce**
Add `import *` in test code, `gradlew checkstyleTest` will pass.

**Screenshots**
n/a

**Additional information**
n/a

**Comment by tkaitchuck** [comment]
I have confirmed this is caught by our existing checkstyle rules.
