### ISSUE TITLE
Release Candidate documentation improvement

### ISSUE THREAD

**Issue by ShwethaSNayak** [pravega/pravega#6685]
**Problem description**
1. Building source code which is uploaded with RC is failing if we just follow the steps given in document
2. Complete path for "bin" folder can be added in documentation for better clarity on how to create, write and read stream.

**Problem location**
https://github.com/pravega/pravega/wiki/Pravega-Release-Validation-Checklist

**Suggestions for an improvement**
Update the https://github.com/pravega/pravega/wiki/Pravega-Release-Validation-Checklist documentation .
1. Running pravega -- > Standalone -- > from source code
2. Create a stream, write and read --- > Complete path for /bin/helloWorldWriter can be given in documentation for better clarify.

**Comment by ShwethaSNayak** [comment]
Below modifications can be done for "https://github.com/pravega/pravega/wiki/Pravega-Release-Validation-Checklist "
1. Under section,  **Running pravega** -- > **Standalone** --- >From source code(.zip) and (.tgz)

```
$ unzip pravega.zip

$ cd pravega
$ git init
$ ./gradlew startStandalone
```
**$ git init** should be added for both .zip and .tgz and instead of gradle "**./gradlew**" command should be used.

2. Under section **Create a stream, write and read**, before "Start HelloWorld Writer" it is good to mention complete path for folder from where ./bin/helloWorldWriter and ./bin/helloWorldReader commands should be executed.

`$ cd pravega-samples/pravega-client-examples/build/install/pravega-client-examples`
`Start HelloWorld Reader:`

`$ ./bin/helloWorldReader [-scope myScope] [-name myStream] [-uri tcp://127.0.0.1:9090]`

**Comment by RaulGracia** [comment]
@ShwethaSNayak done the changes, please check if this is what you expected: https://github.com/pravega/pravega/wiki/Pravega-Release-Validation-Checklist

**Comment by RaulGracia** [comment]
Done the requested changes in Wiki.
