### ISSUE TITLE
Can pravega standalone bind on 0.0.0.0?

### ISSUE THREAD

**Issue by Shoothzj** [pravega/pravega#6789]
Can pravega standalone bind on 0.0.0.0?
```bash
2022-06-24 14:56:13,287 1588 [main] INFO  i.p.local.LocalPravegaEmulator - Pravega Sandbox is running locally now. You could access it at 127.0.0.1:9090.
```

**Comment by Shoothzj** [comment]
@RaulGracia PTAL

**Comment by RaulGracia** [comment]
@Shoothzj sorry for the delayed response. I think that the `InProcPravegaCluster` already sets `0.0.0.0` as the listening address: https://github.com/pravega/pravega/blob/a10713f241123d654dfd03e5e4637fe86c477851/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L75
https://github.com/pravega/pravega/blob/a10713f241123d654dfd03e5e4637fe86c477851/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L311

But at the same time, I see in `build.gradle` file that the `./gradlew stadnalone` task configured setting `address=127.0.0.1`:
https://github.com/pravega/pravega/blob/695e63fd83018c1645d80d5627f55e8a29155f08/build.gradle#L933

I don't know if that parameterization in the `build.gradle` file is the one determining the actual binding address (maybe you could try by changing it).

**Comment by anju-c-das** [comment]
@Shoothzj @RaulGracia We bind on 0.0.0.0 today and I could see that the log have the hardcoded value as 127.0.0.1

https://github.com/pravega/pravega/blob/a10713f241123d654dfd03e5e4637fe86c477851/standalone/src/main/java/io/pravega/local/LocalPravegaEmulator.java#L161

**Comment by CharlieLChen** [comment]
I don't get why you try to bind on '0.0.0.0'. In Windows, '0.0.0.0' maybe can be translated into your network adapter IP address, but in Linux, it will be translated into '127.0.0.1', they are the same semantic. I guess you want to access the standalone from the remote, that can be achieved by exporting the following env:
```
 export JAVA_OPTS="-Dpravegaservice.service.published.host.nameOrIp=10.247.101.103"
``` 
the issue https://github.com/pravega/pravega/issues/6511 elaborates how it goes, you can check it.

**Comment by RaulGracia** [comment]
Closing this one at the moment, let's re-open it if there are more question in this regard.
