### ISSUE TITLE
Build fails on macOS with M1 processor

### ISSUE THREAD

**Issue by derekm** [pravega/pravega#6796]
**Describe the bug**
When building on macOS, the build fails unable to find protobuf tools:

```
Execution failed for task ':shared:controller-api:generateProto'.
> Could not resolve all files for configuration ':shared:controller-api:protobufToolsLocator_grpc'.
   > Could not find protoc-gen-grpc-java-1.39.0-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.39.0).
```

**To Reproduce**
Build on macOS with an M1 machine

**Additional information**
Required artifacts are found when using gRPC 1.47.0

**Comment by kotlasaicharanreddy** [comment]
@derekm Is this a transient error ? Were you able to reproduce it yourself ? It would be helpful if you provide the grpc release docs here which states that grpcversion:1.47.0 is solving the issue.
