### ISSUE TITLE
nit pick, missing closing parentheses in pravega samples README

### ISSUE THREAD

**Issue by jameskim0987** [pravega/pravega#6824]
`Problem description:` In Pravega samples README (https://github.com/pravega/pravega-samples/blob/v0.11.0/pravega-client-examples/README.md), the closing parentheses are missing for:

`uri - "tcp://127.0.0.1" (the URI to one of the controller nodes`

`Problem location:` https://github.com/pravega/pravega-samples/blob/v0.11.0/pravega-client-examples/README.md

`Suggestion for an improvement:` add the closing parentheses

**Comment by RaulGracia** [comment]
Closed via [#pravega-sa](https://github.com/pravega/pravega-samples/pull/332)
