### ISSUE TITLE
Cherry-pick #6738 to r0.12

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#6929]
**Is your feature request related to a problem? Please describe.**
0.12 is missing following commit https://github.com/pravega/pravega/commit/441a7df34646bd1b4ce9b95b8710a1df4069fdeb / PR #6738 

**Describe the solution you'd like**
Cherry-pick #6738 to r0.12

**Describe alternatives you've considered**
This is required.

**Additional context**
None

**Comment by RaulGracia** [comment]
Closed via #6930.
