### ISSUE TITLE
Controller crashes periodically 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#695]
**Problem description**
Controller keeps crashing periodically after running for few minutes. 
There are lots of logs of controller to server connection failure for getSegmentInfo.
This may eventually run out of retries and cause controller crash. Or it could be an out of memory issue.
It is not obvious from the logs. Needs more investigation as to why controller instance is crashing.  

**Problem location**
unknown

**Suggestions for an improvement**
Investigate and fix

**Comment by bhargav-gulavani** [comment]
This issue is no longer observed @shiveshr, @bayarsaikhan.
