### ISSUE TITLE
Cherry-pick PR 6947 into branch r0.12

### ISSUE THREAD

**Issue by shshashwat** [pravega/pravega#6952]
Describe the bug
Cherry-pick PR https://github.com/pravega/pravega/pull/6947 into branch r0.12.

To Reproduce
See https://github.com/pravega/pravega/issues/6945

Screenshots
N/A

Additional information
See https://github.com/pravega/pravega/pull/6947

**Comment by RaulGracia** [comment]
Closed via #6953.
