### ISSUE TITLE
Cherry-pick PR 6976 to r0.13

### ISSUE THREAD

**Issue by anju-c-das** [pravega/pravega#6978]
Describe the bug
Cherry-pick PR https://github.com/pravega/pravega/pull/6976 to r0.13.

To Reproduce
See https://github.com/pravega/pravega/issues/6975.

Screenshots
See https://github.com/pravega/pravega/issues/6975.

Additional information
See https://github.com/pravega/pravega/issues/6975.

**Comment by kotlasaicharanreddy** [comment]
closed via #6979
