### ISSUE TITLE
Upgrade dependencies with new Security Vulnerabilities

### ISSUE THREAD

**Issue by anju-c-das** [pravega/pravega#6985]
Describe the bug
As per the latest scan, few more dependencies are found to be vulnerable and needs to be updated.

Library | Current Version | Suggested Version
-- | -- | --
commons-net| 3.6 | 3.9.0
jackson-databind| 2.13.4 (we were on 2.14.0) | 2.14.1
Netty Project |  4.1.34.Final (we were on 4.1.82.Final) | 4.1.86.Final

To Reproduce
Run a security scan like BlackDuck or similar

Location
https://github.com/pravega/pravega/blob/master/gradle.properties

**Comment by shshashwat** [comment]
@anju-c-das , can you please update the list of dependencies found with Vulnerabilities and the suggested versions too?

**Comment by anju-c-das** [comment]
> @anju-c-das , can you please update the list of dependencies found with Vulnerabilities and the suggested versions too?

sure
