### ISSUE TITLE
Cherry-pick PR 6986 to r0.13

### ISSUE THREAD

**Issue by anju-c-das** [pravega/pravega#6987]
Describe the bug
Cherry-pick PR https://github.com/pravega/pravega/pull/6986 to r0.13.

To Reproduce
See https://github.com/pravega/pravega/issues/6988.

Screenshots
See https://github.com/pravega/pravega/issues/6985.

Additional information
See https://github.com/pravega/pravega/issues/6985.

**Comment by RaulGracia** [comment]
Closed via #6899.
