### ISSUE TITLE
Interactive Writer/Reader CLI tools

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#702]
**Problem description**
Currently, there is not simple way for a user to validate Pravega installation by sending a simple message and reading it back. We need to provide a cli based tool that can connect to any Pravega cluster that is reachable via IP address, and write an event and reads back in an interactive way. 

**Problem location**
area/samples

**Suggestions for an improvement**

```

// Run writer to send messages
$ ./bin/sampleWriter -controller http://192.168.11.11:9090 -stream sensors
$ test 1 2 3 
$ cntl + D

// Run reader to read messages
$ ./bin/sampleReader -controller http://192.168.11.12:9090 -stream sensors
test 1 2 3

```

**This part is optional and can be implemented in the next phase**

To make the experience more fun, we can also create a cli writer that sends tweets with the given hashtag from Twitter using its Streaming API. 

```
// Run twitter streaming service to read and ingest tweets with given hashtag
$ ./bin/sampleTweeter -controller http://192.168.11.11:9090 -stream tweets -hashtag DataStreaming
```
```
Reading tweets with hashtag #DataStreaming...
@pravegaProject 3/31/2017 10:00am PST Pravega alpha release is out #DataStreaming 
@vbayarsaikhan 3/31/2017 10:00am PST Pravega alpha release is out #DataStreaming
@aws_amazon 3/31/2017 10:01am PST Data Streaming defines the future pioneers in the retail industry ...
$ ...
$ cntl + D
```

```
// Run the **same** reader to read messages
$ ./bin/sampleReader -controller http://192.168.11.12:9090 -stream tweets

```

**Comment by askewj** [comment]
ConsoleReader / ConsoleWriter achieves this
