### ISSUE TITLE
Bookkeeper cluster fails to deploy

### ISSUE THREAD

**Issue by junglie85** [pravega/pravega#7087]
I'm trying to follow the installation steps for running on Kubernetes having done some initial testing locally in standalone mode. However, I cannot get bookkeeper to launch using the instructions provided:

```
kubectl get bookkeepercluster -n pravega
NAME         VERSION   DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
bookkeeper             0.12.0                                              25m

kubectl logs pod/bookkeeper-post-install-upgrade-rollback-bslm8 -n pravega
BookkeeperCluster replicas:
BookkeeperCluster readyReplicas:
BookkeeperCluster currentVersion:
BookkeeperCluster targetVersion: 0.12.0
```

At no point during the deployment do any bookkeeper pods try and come up. I can't find any other logs indicating a problem; I had a similar problem with zookeeper-operator and zookeeper, which was cause by entering watch namespaces as a yaml list instead of a string; I've double checked and all my Helm values look correct. How can I debug this and get a bookkeeper cluster running?

**Comment by anishakj** [comment]
@junglie85 This issue seems to be with bookkeeper-operator. could you please open the issue in bookkeeper-operator repo?

**Comment by junglie85** [comment]
I certainly can - https://github.com/pravega/bookkeeper-operator/issues/231.
