### ISSUE TITLE
Cherry-pick PR #7142 to r0.13

### ISSUE THREAD

**Issue by Bhupender-Y** [pravega/pravega#7145]
**Describe the bug**
Cherry-pick PR #7142  to r0.13

**To Reproduce**
see #7143 

**Screenshots**
N/A

**Additional information**
N/A

**Comment by RaulGracia** [comment]
@Bhupender-Y cherry-picking to a release branch is important as we may compromise the stability of a release branch (recently, we witnessed how a cherry-pick PR had to be reverted). For this reason, before considering a PR (not even merged) as a cherry-pick, make sure that it passes all the tests (including system tests, and hopefully longevity and performance). 

Also, I would like to recall that in general we consider PRs to cherry-pick if they fix some important bug or add some critical improvement. The PR referred here doesn't look like any of these cases. While having more logs may be "nice-to-have" for debugging, we can debug in `master` or specific branches, without having to touch release branches. In summary, let's be cautious with cherry-picking to release branches, as any change introduced to a release branch has a small chance of inadvertently inducing a regression of some type that we could find too late. Thanks.

**Comment by Bhupender-Y** [comment]
Thanks @RaulGracia, yes i totally agree with you on the above points. But this cherry pick PR is highly required for debugging a few corner case scenarios in prod environment.
