### ISSUE TITLE
New client API to cancel all outstanding checkpoints

### ISSUE THREAD

**Issue by ShwethaSNayak** [pravega/pravega#7147]
**Problem description**
In certain scenario when Client application call for `initiateCheckpoint()` by passing executor threadpool and because of any reason if thread poll is shutdown with some unexpected runtime exception(Observed in case of DNS down scenario), then it's been observed that outstanding checkpoint completion gets impacted. In such scenario adding new API to cancel all outstanding checkpoint helps in recovery.

**Problem location**
ReaderGroupImpl.java

**Suggestions for an improvement**
Adding new API to cancel all outstanding checkpoint.

**Comment by crazyzhou** [comment]
Is there a possibility that we set a TTL(Time-To-Live) time for the outstanding checkpoints in Pravega?

For example in reality, checkpoint calls lasting 1 hour does not help much on the real recovery use cases.
