### ISSUE TITLE
Allow Pravega operator to include AdminCLI port 9999 in SegmentStore Service

### ISSUE THREAD

**Issue by Amit-Singh40** [pravega/pravega#7173]
**Is your feature request related to a problem? Please describe.**
This is needed for backup and restore functionality of the LTS recovery.

**Describe the solution you'd like**
After enabling admin port, we had to add 9999 port in the Segment Store SVC before calling the flush to storage. To automate that there is change proposed in operators. To support the operator changes we need to make this change.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RaulGracia** [comment]
The Segment Store has a configuration flag to open the admin port. It is disabled by default for security reasons, but as soon as you enable it you will be able to send admin commands to Pravega. Please, review the admin gateway configuration before proposing changes to it, or describe more clearly the purpose of the change.
