### ISSUE TITLE
Readergroup.readerOffline requires reader's last known position which may not always be available

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#718]
**Problem description**
A readergroup, needs the readers last known position to mark it offline.
However, if a reader is created and crashes before it can read any event or before checkpointing any last known position, then there is no position available for application to notify to readergroup about reader being offline.

**Problem location**
readergroup.readerOffline()

**Suggestions for an improvement**
Either allow for null position or position with empty segment map or a special position flag which indicates that no progress had been made by the reader so the original assigned position should be used.

**Comment by shrids** [comment]
Closing this as a `null` position is allowed by the reader group.
