### ISSUE TITLE
Segmentstore default property 'single connection max outstanding bytes' not loaded

### ISSUE THREAD

**Issue by gfinol** [pravega/pravega#7325]
**Describe the bug**
The Segmentstore server does not load the  `DEFAULT_SINGLE_CONNECTION_MAX_OUTSTANDING_BYTES` property from the configuration file. Instead, it loads the value corresponding to `DEFAULT_ALL_CONNECTIONS_MAX_OUTSTANDING_BYTES`. (Notice the `SINGLE` vs `ALL` difference in the name).

**To Reproduce**
NA

**Screenshots**
NA

**Additional information**
In [ServiceConfig.java](https://github.com/pravega/pravega/blob/6422dbb5e2dd0b37e5ab600244aca1b5c25cfa59/segmentstore/server/src/main/java/io/pravega/segmentstore/server/store/ServiceConfig.java#L100C156-L100C156), the property is not loaded properly.

**Comment by RaulGracia** [comment]
Closed via #7326.
