### ISSUE TITLE
Revert zookeeper 3.7.2 upgrade in master

### ISSUE THREAD

**Issue by a6dulaleem** [pravega/pravega#7340]
**Describe the bug**
This version of zookeeper is having some performance issue.

**To Reproduce**
1. Run AppendTest integration test
2. It will fail the benchmark test

**Location of Integration Test**
https://github.com/pravega/pravega/blob/d145587152294716824f90f64430cace51e5c82c/test/integration/src/test/java/io/pravega/test/integration/AppendTest.java#L496

**Comment by anishakj** [comment]
Closing as it is not needed now.
