### ISSUE TITLE
Redeploy pravega

### ISSUE THREAD

**Issue by zzkww** [pravega/pravega#7353]
# Ask your question away
Now, I added some new functions to the source code of pravega. After the addition was completed, I repackaged the module into a jar package, and then I added it to the /opt/pravega/lib directory under the pod of the controller in k8s. Replaced it with the original jar package and restarted the segmentstore service, but the log showed that the original jar package was still read, so I wanted to know how to test my newly added functions in the k8s environment.

**Comment by RaulGracia** [comment]
@zzkww, thanks for the question. Let me share some comments: The procedure you mention is not the right way to "upgrade" Pravega and it is not going to work in Kubernetes. A Kubernetes pod uses a Docker image to get started, so even if you change locally the libraries of Pravega (or any other file in the Docker image), once the pod is restarted the original Docker image will be used, without your changes. That is, the local changes on Docker containers are not persistent (unless you use a storage volume).

If you want to upgrade Pravega with a custom version, please do the following:
1. In your local branch of Pravega with the changes, build the docker image with Gradle (note that depending on your user permissions you may need to use `sudo` to run that command):
```./gradlew buildPravegaImage```
2. The previous step generates a local Pravega image in your machine (see below). Push the generated image to your DockerHub account.
```
$ sudo docker image ls
REPOSITORY                                                                                       TAG                            IMAGE ID       CREATED              SIZE
pravega/pravega                                                                                  0.14.0-3262.99290c4-SNAPSHOT   9b86ca10422a   About a minute ago   434MB
pravega/pravega                                                                                  latest                         9b86ca10422a   About a minute ago   434MB
```
3. Then, if you have Pravega already running in Kubernetes, upgrade Pravega for example as follows:
```kubectl edit PravegaCluster```
And edit the `image` field of the configmap with the custom image you just pushed to DockerHub with your changes:
```
image:
      pullPolicy: IfNotPresent
      repository: YOUR_DOCKERHUB_USER/YOUR_IMAGE_NAME
```
This will make the Pravega Operator to upgrade the whole cluster with your new custom image.

For further discussion, I suggest you to join our Slack space (if you haven't already): https://join.slack.com/t/pravega-io/shared_invite/zt-245sgpw47-vbLBLiLfBdW9TlKemXkUnw

Thanks!
