### ISSUE TITLE
Fix flaky test "testFlushToStorageForEpochFileAlreadyExists"

### ISSUE THREAD

**Issue by abhinb** [pravega/pravega#7355]
**Describe the bug**
Fix flaky flush-to-storage tests

**To Reproduce**
Run Unit tests on a PR. testFlushToStorageForEpochFileAlreadyExists fails at times.

**Screenshots**
NA

**Additional information**
NA

**Comment by anishakj** [comment]
Fixed via https://github.com/pravega/pravega/pull/7356
