### ISSUE TITLE
Creating A Stream Or Scope With A '/' Returns A 500 Internal Server Error

### ISSUE THREAD

**Issue by jdmaguire** [pravega/pravega#809]
**Problem description**

With the rest API, I tried to create a stream called "stream/with/solidus" and the create operation returned a 500 Internal Server Error. Attempts to create a scope with the name "scope/with/solidus" fail with the same error.

**Suggestions for an improvement**

500 Internal Server error indicates a problem with the server. If the server isn't handling names with these characters correctly, it should be fixed. If there is an invalid character set or similar and therefore the client is at fault, instead of throwing a 5xx-style error indicating a server issue a 4xx-style error explaining the client's mistake should be returned.

**Comment by skrishnappa** [comment]
The current API returns 400 response as expected. Adding detailed description in the response body will be addressed as part of #1440
