### ISSUE TITLE
Find better default port numbers

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#829]
**Problem description**
In our configurations, we have various default port numbers which look like they belong in a unit test (i.e., '12345'). We should make a list of all these ports and thoughtfully choose some values that make sense for us.

**Comment by tkaitchuck** [comment]
This is also relevant for the case of 9090 which is the default port used by the standalone deployment for the controller, but ALSO the default local service port. Which makes the clients designed to work with the local service connect to the controller in the case that it is running the single host deployment, which of course causes them to fail.

**Comment by fpj** [comment]
@tkaitchuck I'm not sure what you are referring to. When I start standalone, I see this:

```
2017-12-21 10:25:11,312 688  [main] INFO  i.p.local.LocalPravegaEmulator - Starting Pravega Emulator with ports: ZK port 4000, controllerPort 9090, SegmentStorePort 6000 
```

there is no port conflict as far as I can tell. Could you explain in more detail the problem you are seeing?

**Comment by tkaitchuck** [comment]
9090 is also used here:
https://github.com/pravega/pravega/blob/83860e1cd187e91fd92d77aed2924fa09cbaa807/test/integration/src/main/java/io/pravega/test/integration/demo/StartLocalService.java#L21
As the port for the service. So in one case it is used for the controller and in another for the service, depending on which build target you run. So if you use the readers/writers meant for one of those deployments with the other, you get:
```
xception in thread "main" java.lang.RuntimeException: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Unknown wire command: 4612
        at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:180)
        at io.pravega.client.stream.mock.MockController.createSegment(MockController.java:213)
        at io.pravega.client.stream.mock.MockController.createStream(MockController.java:116)
        at io.pravega.client.stream.mock.MockStreamManager.createStream(MockStreamManager.java:74)
        at io.pravega.test.integration.demo.StartReader.main(StartReader.java:33)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: Unknown wire command: 4612
```

**Comment by fpj** [comment]
@andreipaduroiu @shiveshr  @tkaitchuck @arvindkandhare Let's get closure on this issue. My proposal is the following. 

The problem reported here is that we have not chosen and are not using sensible defaults. Based on the values that we are already using, I believe the following list makes sense:

1. Controller:
    a. RPC port: 9090
    b. REST server port: 9091
2. Segment store:
    a. Service port: 6000
    b. Reserved for future use: 6001

First, I'd like to get agreement on this list. Do you agree with it? If not, please provide some feedback.

Second, once we get agreement on the list, I'd like to ask each one of you to update if necessary the use of ports for the corresponding components across standalone and sample code. Standalone is Pravega standalone and sample code is what we have under `test/integration` and `pravega/pravega-samples`.
