### ISSUE TITLE
Read Bytes Counter is going down

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#886]
**Problem description**
We are seeing the total read bytes for our stream going up and down over time.  The expectation is that this value always goes up over time.

**Problem location**
Metrics

**Suggestions for an improvement**
Ensure that the read/write bytes always go up over time.

![screen shot 2017-03-29 at 9 40 31 am](https://cloud.githubusercontent.com/assets/9335655/24455103/c7fea7d0-1464-11e7-94d3-02ba7e9ba051.png)

**Comment by tkaitchuck** [comment]
From the discussion, it sounds like the best thing to do would be to simply replace this metric with a rate. As an absolute count is both hard to deal with on the receive side, and makes eviction hard on the server side.
