### ISSUE TITLE
REST API for create/update stream shouldn't require targetRate and scaleFactor for FIXED_NUM_SEGMENTS

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#914]
**Problem description**
Currently the REST api call will fail if we pick FIXED_NUM_SEGMENTS for the scaling policy and don't send the targetRate and scalingFactor properties.

**Problem location**
REST API

**Suggestions for an improvement**
The targetRate and scalingFactor properties should not be required when the scaling policy is set to FIXED_NUM_SEGMENTS.  Those values are not used for FIXED_NUM_SEGMENTS so it should not fail if they are not present.

**Comment by Abhijeet-Jadhav** [comment]
@glounder Can we close this ?

**Comment by glounder** [comment]
Yup, sure can.

**Comment by Abhijeet-Jadhav** [comment]
Fixed through #943
