### ISSUE TITLE
Move retryablity trait in exceptions to common and have pravegaExceptions implement the trait where relevant

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#936]
**Problem description**
Retriability trait in exceptions should be moved to common as we may want retriability trait implemented across pravega exceptions. 
For example ConnectionFailedException is an ideal candidate for retriability trait. 
**Problem location**

**Suggestions for an improvement**
Move retriabilityException trait to common and have several retryable exceptions implement the trait. 
Look at opportunities where Retry block can be broadened to cover more cases than specific exceptions as they do right now.

**Comment by tkaitchuck** [comment]
This sounds related to #1433

**Comment by fpj** [comment]
@shiveshr Is this the ability to retry like Kafka has in their code:

https://kafka.apache.org/21/javadoc/index.html?org/apache/kafka/common/errors/RetriableException.html

If not, then could you elaborate? Perhaps this is something we have already done even.
