### ISSUE TITLE
Enable getReaderGroup in EventProcessorGroupImpl

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#942]
**Problem description**
This method `createIfNotExists` has the following TODO and code commented out.
```
        // todo: getReaderGroup currently throws NotImplementedException
        //ReaderGroup readerGroup = streamManager.getReaderGroup(groupName);
        //if (readerGroup == null) {
        //    readerGroup = streamManager.createReaderGroup(groupName, groupConfig, streamNanes);
        //}
        //return  readerGroup;
```

`getReaderGroup` is implemented so we should revisit it.

**Problem location**
Controller.

**Suggestions for an improvement**
Bring back the commented code.

**Comment by bhargav-gulavani** [comment]
Fixed in #1108
