### ISSUE TITLE
Ping causes Txn to have "Aborted" Status

### ISSUE THREAD

**Issue by sggraham32** [pravega/pravega#971]
**Problem description**
When I use the ConsoleWriter (see below) to ping a Txn, and then check its status, it is in Aborted state.

**Problem location**
Using StandAlone Pravega.  Using ConsoleWriter CLI. ConsoleWriter is in pravega-samples repo (currently in the console-rw branch).  With ConsoleWriter, you can launch it on a scope/stream and use the DSL to enter commands like WRITE_EVENT etc.  It also does TXN management.  So to repeat the issue, launch the ConsoleWriter, enter BEGIN (starts a TXN) then PING then STATUS.

**Suggestions for an improvement**
Maybe it is a problem with standalone?  Maybe ConsoleWriter is doing something wrong?

**Comment by fpj** [comment]
We have used pings in system tests, and now we have removed explicit pings from the API, so I'm closing this issue.
